package com.baidu.tbadk.editortools.emotiontool;

import android.content.Context;
import com.baidu.tbadk.imageManager.a;
import com.baidu.tieba.R;
import java.util.ArrayList;
import java.util.HashMap;
/* loaded from: classes.dex */
public class b implements com.baidu.tbadk.imageManager.a {
    protected static final HashMap<String, Integer> dxH = new HashMap<>(200);
    public static final ArrayList<Integer> dxI = new ArrayList<>(180);
    public static final HashMap<String, Integer> dxJ = new HashMap<>(180);
    private static final HashMap<String, String> dxK = new HashMap<>(180);

    static {
        dxK.put("image_emoticon", "呵呵");
        dxK.put("image_emoticon2", "哈哈");
        dxK.put("image_emoticon3", "吐舌");
        dxK.put("image_emoticon4", "啊");
        dxK.put("image_emoticon5", "酷");
        dxK.put("image_emoticon6", "怒");
        dxK.put("image_emoticon7", "开心");
        dxK.put("image_emoticon8", "汗");
        dxK.put("image_emoticon9", "泪");
        dxK.put("image_emoticon10", "黑线");
        dxK.put("image_emoticon11", "鄙视");
        dxK.put("image_emoticon12", "不高兴");
        dxK.put("image_emoticon13", "真棒");
        dxK.put("image_emoticon14", "钱");
        dxK.put("image_emoticon15", "疑问");
        dxK.put("image_emoticon16", "阴险");
        dxK.put("image_emoticon17", "吐");
        dxK.put("image_emoticon18", "咦");
        dxK.put("image_emoticon19", "委屈");
        dxK.put("image_emoticon20", "花心");
        dxK.put("image_emoticon21", "呼~");
        dxK.put("image_emoticon22", "笑眼");
        dxK.put("image_emoticon23", "冷");
        dxK.put("image_emoticon24", "太开心");
        dxK.put("image_emoticon25", "滑稽");
        dxK.put("image_emoticon26", "勉强");
        dxK.put("image_emoticon27", "狂汗");
        dxK.put("image_emoticon28", "乖");
        dxK.put("image_emoticon29", "睡觉");
        dxK.put("image_emoticon30", "惊哭");
        dxK.put("image_emoticon31", "生气");
        dxK.put("image_emoticon32", "惊讶");
        dxK.put("image_emoticon33", "喷");
        dxK.put("image_emoticon34", "爱心");
        dxK.put("image_emoticon35", "心碎");
        dxK.put("image_emoticon36", "玫瑰");
        dxK.put("image_emoticon37", "礼物");
        dxK.put("image_emoticon38", "彩虹");
        dxK.put("image_emoticon39", "星星月亮");
        dxK.put("image_emoticon40", "太阳");
        dxK.put("image_emoticon41", "钱币");
        dxK.put("image_emoticon42", "灯泡");
        dxK.put("image_emoticon43", "茶杯");
        dxK.put("image_emoticon44", "蛋糕");
        dxK.put("image_emoticon45", "音乐");
        dxK.put("image_emoticon46", "haha");
        dxK.put("image_emoticon47", "胜利");
        dxK.put("image_emoticon48", "大拇指");
        dxK.put("image_emoticon49", "弱");
        dxK.put("image_emoticon50", "OK");
        dxK.put("image_emoticon61", "哼");
        dxK.put("image_emoticon62", "吃瓜");
        dxK.put("image_emoticon63", "扔便便");
        dxK.put("image_emoticon64", "惊恐");
        dxK.put("image_emoticon65", "哎呦");
        dxK.put("image_emoticon66", "小乖");
        dxK.put("image_emoticon67", "捂嘴笑");
        dxK.put("image_emoticon68", "你懂的");
        dxK.put("image_emoticon69", "what");
        dxK.put("image_emoticon70", "酸爽");
        dxK.put("image_emoticon71", "呀咩爹");
        dxK.put("image_emoticon72", "笑尿");
        dxK.put("image_emoticon73", "挖鼻");
        dxK.put("image_emoticon74", "犀利");
        dxK.put("image_emoticon75", "小红脸");
        dxK.put("image_emoticon76", "懒得理");
        dxK.put("image_emoticon77", "沙发");
        dxK.put("image_emoticon78", "手纸");
        dxK.put("image_emoticon79", "香蕉");
        dxK.put("image_emoticon80", "便便");
        dxK.put("image_emoticon81", "药丸");
        dxK.put("image_emoticon82", "红领巾");
        dxK.put("image_emoticon83", "蜡烛");
        dxK.put("image_emoticon84", "三道杠");
        dxK.put("image_emoticon85", "暗中观察");
        dxK.put("image_emoticon86", "吃瓜");
        dxK.put("image_emoticon87", "喝酒");
        dxK.put("image_emoticon88", "嘿嘿嘿");
        dxK.put("image_emoticon89", "噗");
        dxK.put("image_emoticon90", "困成狗");
        dxK.put("image_emoticon91", "微微一笑");
        dxK.put("image_emoticon92", "托腮");
        dxK.put("image_emoticon93", "摊手");
        dxK.put("image_emoticon94", "柯基暗中观察");
        dxK.put("image_emoticon95", "欢呼");
        dxK.put("image_emoticon96", "炸药");
        dxK.put("image_emoticon97", "突然兴奋");
        dxK.put("image_emoticon98", "紧张");
        dxK.put("image_emoticon99", "黑头瞪眼");
        dxK.put("image_emoticon100", "黑头高兴");
        dxK.put("image_emoticon101", "不跟丑人说话");
        dxK.put("image_emoticon102", "么么哒");
        dxK.put("image_emoticon103", "亲亲才能起来");
        dxK.put("image_emoticon104", "伦家只是宝宝");
        dxK.put("image_emoticon105", "你是我的人");
        dxK.put("image_emoticon106", "假装看不见");
        dxK.put("image_emoticon107", "单身等撩");
        dxK.put("image_emoticon108", "吓到宝宝了");
        dxK.put("image_emoticon109", "哈哈哈");
        dxK.put("image_emoticon110", "嗯嗯");
        dxK.put("image_emoticon111", "好幸福");
        dxK.put("image_emoticon112", "宝宝不开心");
        dxK.put("image_emoticon113", "小姐姐别走");
        dxK.put("image_emoticon114", "小姐姐在吗");
        dxK.put("image_emoticon115", "小姐姐来啦");
        dxK.put("image_emoticon116", "小姐姐来玩呀");
        dxK.put("image_emoticon117", "我养你");
        dxK.put("image_emoticon118", "我是不会骗你的");
        dxK.put("image_emoticon119", "扎心了");
        dxK.put("image_emoticon120", "无聊");
        dxK.put("image_emoticon121", "月亮代表我的心");
        dxK.put("image_emoticon122", "来追我呀");
        dxK.put("image_emoticon123", "爱你的形状");
        dxK.put("image_emoticon124", "白眼");
        dxK.put("ali_001", "赖皮");
        dxK.put("ali_002", "感动");
        dxK.put("ali_003", "十分惊讶");
        dxK.put("ali_004", "怒气");
        dxK.put("ali_005", "哭泣");
        dxK.put("ali_006", "吃惊");
        dxK.put("ali_007", "嘲弄");
        dxK.put("ali_008", "飘过");
        dxK.put("ali_009", "转圈哭");
        dxK.put("ali_010", "神经病");
        dxK.put("ali_011", "揪耳朵");
        dxK.put("ali_012", "惊汗");
        dxK.put("ali_013", "隐身");
        dxK.put("ali_014", "不要嘛");
        dxK.put("ali_015", "遁");
        dxK.put("ali_016", "不公平");
        dxK.put("ali_017", "爬来了");
        dxK.put("ali_018", "蛋花哭");
        dxK.put("ali_019", "温暖");
        dxK.put("ali_020", "点头");
        dxK.put("ali_021", "撒钱");
        dxK.put("ali_022", "献花");
        dxK.put("ali_023", "寒");
        dxK.put("ali_024", "傻笑");
        dxK.put("ali_025", "扭扭");
        dxK.put("ali_026", "疯");
        dxK.put("ali_027", "抓狂");
        dxK.put("ali_028", "抓");
        dxK.put("ali_029", "蜷");
        dxK.put("ali_030", "挠墙");
        dxK.put("ali_031", "狂笑");
        dxK.put("ali_032", "抱枕");
        dxK.put("ali_033", "吼叫");
        dxK.put("ali_034", "嚷");
        dxK.put("ali_035", "唠叨");
        dxK.put("ali_036", "捏脸");
        dxK.put("ali_037", "爆笑");
        dxK.put("ali_038", "郁闷");
        dxK.put("ali_039", "潜水");
        dxK.put("ali_040", "十分开心");
        dxK.put("ali_041", "冷笑话");
        dxK.put("ali_042", "顶！");
        dxK.put("ali_043", "潜");
        dxK.put("ali_044", "画圈圈");
        dxK.put("ali_045", "玩电脑");
        dxK.put("ali_046", "狂吐");
        dxK.put("ali_047", "哭着跑");
        dxK.put("ali_048", "阿狸侠");
        dxK.put("ali_049", "冷死了");
        dxK.put("ali_050", "惆怅~");
        dxK.put("ali_051", "摸头");
        dxK.put("ali_052", "蹭");
        dxK.put("ali_053", "打滚");
        dxK.put("ali_054", "叩拜");
        dxK.put("ali_055", "摸");
        dxK.put("ali_056", "数钱");
        dxK.put("ali_057", "拖走");
        dxK.put("ali_058", "热");
        dxK.put("ali_059", "加1");
        dxK.put("ali_060", "压力");
        dxK.put("ali_061", "表逼我");
        dxK.put("ali_062", "人呢");
        dxK.put("ali_063", "摇晃");
        dxK.put("ali_064", "打地鼠");
        dxK.put("ali_065", "这个屌");
        dxK.put("ali_066", "恐慌");
        dxK.put("ali_067", "晕乎乎");
        dxK.put("ali_068", "浮云");
        dxK.put("ali_069", "给力");
        dxK.put("ali_070", "杯具了");
        dxK.put("b01", "微笑");
        dxK.put("b02", "帅哥");
        dxK.put("b03", "美女");
        dxK.put("b04", "老大");
        dxK.put("b05", "哈哈哈");
        dxK.put("b06", "奸笑");
        dxK.put("b07", "傻乐");
        dxK.put("b08", "飞吻");
        dxK.put("b09", "害羞");
        dxK.put("b10", "花痴");
        dxK.put("b11", "憧憬");
        dxK.put("b12", "你牛");
        dxK.put("b13", "鼓掌");
        dxK.put("b14", "可爱");
        dxK.put("b15", "太委屈");
        dxK.put("b16", "大哭");
        dxK.put("b17", "泪奔");
        dxK.put("b18", "寻死");
        dxK.put("b19", "非常惊讶");
        dxK.put("b20", "表示疑问");
        dxK.put("yz_001", "焦糖舞");
        dxK.put("yz_002", "翻滚");
        dxK.put("yz_003", "拍屁股做鬼脸");
        dxK.put("yz_004", "不");
        dxK.put("yz_005", "河蟹掉啦");
        dxK.put("yz_006", "哦耶");
        dxK.put("yz_007", "我倒");
        dxK.put("yz_008", "投降");
        dxK.put("shoubai_emoji_face_01", "微笑");
        dxK.put("shoubai_emoji_face_02", "开心");
        dxK.put("shoubai_emoji_face_03", "期待");
        dxK.put("shoubai_emoji_face_04", "大笑");
        dxK.put("shoubai_emoji_face_05", "鼓掌");
        dxK.put("shoubai_emoji_face_06", "悠闲");
        dxK.put("shoubai_emoji_face_07", "笑哭");
        dxK.put("shoubai_emoji_face_08", "不要啊");
        dxK.put("shoubai_emoji_face_09", "啊");
        dxK.put("shoubai_emoji_face_10", "哟");
        dxK.put("shoubai_emoji_face_11", "汗");
        dxK.put("shoubai_emoji_face_12", "抠鼻");
        dxK.put("shoubai_emoji_face_13", "哼");
        dxK.put("shoubai_emoji_face_14", "发怒");
        dxK.put("shoubai_emoji_face_15", "委屈");
        dxK.put("shoubai_emoji_face_16", "不高兴");
        dxK.put("shoubai_emoji_face_17", "囧");
        dxK.put("shoubai_emoji_face_18", "惊哭");
        dxK.put("shoubai_emoji_face_19", "大哭");
        dxK.put("shoubai_emoji_face_20", "流泪");
        dxK.put("shoubai_emoji_face_21", "害羞");
        dxK.put("shoubai_emoji_face_22", "亲亲");
        dxK.put("shoubai_emoji_face_23", "色");
        dxK.put("shoubai_emoji_face_24", "舔屏");
        dxK.put("shoubai_emoji_face_25", "得意");
        dxK.put("shoubai_emoji_face_26", "疑问");
        dxK.put("shoubai_emoji_face_27", "晕");
        dxK.put("shoubai_emoji_face_28", "大哈");
        dxK.put("shoubai_emoji_face_29", "二哈");
        dxK.put("shoubai_emoji_face_30", "三哈");
        dxK.put("shoubai_emoji_face_31", "白眼");
        dxK.put("shoubai_emoji_face_32", "阴险");
        dxK.put("shoubai_emoji_face_33", "你懂的");
        dxK.put("shoubai_emoji_face_34", "偷笑");
        dxK.put("shoubai_emoji_face_35", "睡觉");
        dxK.put("shoubai_emoji_face_36", "哈欠");
        dxK.put("shoubai_emoji_face_37", "再见");
        dxK.put("shoubai_emoji_face_38", "鄙视");
        dxK.put("shoubai_emoji_face_39", "抓狂");
        dxK.put("shoubai_emoji_face_40", "咒骂");
        dxK.put("shoubai_emoji_face_41", "衰");
        dxK.put("shoubai_emoji_face_42", "骷髅");
        dxK.put("shoubai_emoji_face_43", "嘘");
        dxK.put("shoubai_emoji_face_44", "闭嘴");
        dxK.put("shoubai_emoji_face_45", "呆");
        dxK.put("shoubai_emoji_face_46", "什么鬼");
        dxK.put("shoubai_emoji_face_47", "吐");
        dxK.put("shoubai_emoji_face_48", "已阅");
        dxK.put("shoubai_emoji_face_49", "同上");
        dxK.put("shoubai_emoji_face_50", "友军");
        dxK.put("shoubai_emoji_face_51", "爱钱");
        dxK.put("shoubai_emoji_face_52", "Freestyle");
        dxK.put("shoubai_emoji_face_53", "国宝");
        dxK.put("shoubai_emoji_face_54", "羊驼");
        dxK.put("shoubai_emoji_face_55", "鲜花");
        dxK.put("shoubai_emoji_face_56", "中国加油");
        dxK.put("shoubai_emoji_face_57", "庆祝");
        dxK.put("shoubai_emoji_face_58", "生日蛋糕");
        dxK.put("shoubai_emoji_face_59", "MicDrop");
        dxK.put("shoubai_emoji_face_60", "赞同");
        dxK.put("shoubai_emoji_face_61", "药丸");
        dxK.put("shoubai_emoji_face_62", "蜡烛");
        dxK.put("shoubai_emoji_face_63", "鸡蛋");
        dxK.put("shoubai_emoji_face_64", "浪");
        dxK.put("shoubai_emoji_face_65", "打call");
        dxK.put("shoubai_emoji_face_66", "尬笑");
        dxK.put("shoubai_emoji_face_67", "坏笑");
        dxK.put("shoubai_emoji_face_68", "没眼看");
        dxK.put("shoubai_emoji_face_69", "嘿哈");
        dxK.put("shoubai_emoji_face_70", "前面的别走");
        dxK.put("shoubai_emoji_face_71", "滑稽");
        dxK.put("shoubai_emoji_face_72", "捂脸");
        dxK.put("shoubai_emoji_face_73", "左捂脸");
        dxK.put("shoubai_emoji_face_74", "666");
        dxK.put("shoubai_emoji_face_75", "2018");
        dxK.put("shoubai_emoji_face_76", "福");
        dxK.put("shoubai_emoji_face_77", "红包");
        dxK.put("shoubai_emoji_face_78", "鞭炮");
        dxK.put("shoubai_emoji_face_79", "财神");
        dxK.put("shoubai_emoji_face_80", "饺子");
        dxK.put("shoubai_emoji_face_81", "车票");
        dxK.put("shoubai_emoji_face_82", "火车");
        dxK.put("shoubai_emoji_face_83", "飞机");
        dxK.put("shoubai_emoji_face_84", "射门");
        dxK.put("shoubai_emoji_face_85", "红牌");
        dxK.put("shoubai_emoji_face_86", "黄牌");
        dxK.put("shoubai_emoji_face_87", "哨子");
        dxK.put("shoubai_emoji_face_88", "比分");
        dxK.put("shoubai_emoji_face_89", "啤酒");
        dxK.put("shoubai_emoji_face_90", "足球");
        dxK.put("shoubai_emoji_face_91", "大力神杯");
        dxK.put("shoubai_emoji_face_92", "锦鲤");
        dxK.put("shoubai_emoji_face_93", "2019");
        dxK.put("shoubai_emoji_face_94", "猪年");
        dxK.put("shoubai_emoji_face_95", "双手鼓掌");
        dxK.put("shoubai_emoji_face_96", "火焰");
        dxK.put("shoubai_emoji_face_97", "祈福");
        dxK.put("shoubai_emoji_face_98", "亲吻");
        dxK.put("shoubai_emoji_face_99", "天使");
        dxK.put("shoubai_emoji_face_100", "樱花");
        dxK.put("shoubai_emoji_face_101", "加油");
        dxK.put("shoubai_emoji_face_102", "泡泡枪");
        dxK.put("shoubai_emoji_face_103", "气球");
        dxK.put("shoubai_emoji_face_104", "棒棒糖");
        dxK.put("shoubai_emoji_face_105", "小黄鸭");
        dxK.put("shoubai_emoji_face_106", "粽子");
    }

    @Override // com.baidu.tbadk.imageManager.a
    public int vc(String str) {
        Integer num = dxH.get(str);
        if ("video_icon".equals(str)) {
            return Integer.valueOf((int) R.drawable.ico_link_video).intValue();
        }
        if (num != null) {
            return num.intValue();
        }
        return 0;
    }

    @Override // com.baidu.tbadk.imageManager.a
    public int vd(String str) {
        Integer num = dxJ.get(str);
        if (num != null) {
            return num.intValue();
        }
        return 0;
    }

    @Override // com.baidu.tbadk.imageManager.a
    public String ve(String str) {
        return dxK.get(str);
    }

    @Override // com.baidu.tbadk.imageManager.a
    public int aOH() {
        return dxI.size();
    }

    @Override // com.baidu.tbadk.imageManager.a
    public a.C0391a aA(Context context, String str) {
        return null;
    }
}
