package com.baidu.tieba.pb.pb.a;

import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.baidu.adp.lib.util.l;
import com.baidu.adp.widget.ListView.r;
import com.baidu.tbadk.TbConfig;
import com.baidu.tbadk.core.TbadkCoreApplication;
import com.baidu.tbadk.core.view.HeadImageView;
import com.baidu.tbadk.core.view.HeadPendantView;
import com.baidu.tbadk.core.view.UserIconBox;
import com.baidu.tbadk.widget.richText.TbRichTextView;
import com.baidu.tieba.d;
import com.baidu.tieba.pb.pb.main.view.TriangleShapeView;
import com.baidu.tieba.pb.pb.sub.SubPbLayout;
import com.baidu.tieba.pb.view.PbGiftListView;
import com.baidu.tieba.tbadkCore.FrsPraiseView;
/* loaded from: classes2.dex */
public class f extends r.a {
    UserIconBox bcN;
    public TextView cQi;
    public RelativeLayout cdM;
    public UserIconBox dUr;
    public View fFF;
    public View fFG;
    public View fFH;
    public HeadPendantView fFI;
    public HeadImageView fFJ;
    public ImageView fFK;
    public ImageView fFL;
    public TextView fFM;
    public TextView fFN;
    public TextView fFO;
    public TbRichTextView fFP;
    public FrsPraiseView fFQ;
    public ImageView fFR;
    public PbGiftListView fFS;
    public SubPbLayout fFT;
    public RelativeLayout fFU;
    public RelativeLayout fFV;
    public View fFW;
    public LinearLayout fFX;
    public TextView fFY;
    public LinearLayout fFZ;
    public Button fGa;
    public LinearLayout fGb;
    public TextView fGc;
    public View fGd;
    public View fGe;
    public RelativeLayout fGf;
    public TextView fGg;
    public TextView fGh;
    public TextView fGi;
    public TextView fGj;
    public TextView fGk;
    public TriangleShapeView fGl;
    public TextView fGm;
    public int mSkinType;

    public f(View view, boolean z, int i, boolean z2) {
        super(view);
        this.mSkinType = 3;
        this.fFH = view.findViewById(d.g.sub_pb_more);
        this.fFU = (RelativeLayout) view.findViewById(d.g.user_head_layout);
        this.fFV = (RelativeLayout) view.findViewById(d.g.pb_item_floor_layout);
        this.fFJ = (HeadImageView) view.findViewById(d.g.photo);
        this.fFI = (HeadPendantView) view.findViewById(d.g.pendant_photo);
        this.fFI.Dz();
        if (this.fFI.getHeadView() != null) {
            this.fFI.getHeadView().setIsRound(true);
            this.fFI.getHeadView().setDrawBorder(false);
        }
        if (this.fFI.getPendantView() != null) {
            this.fFI.getPendantView().setIsRound(true);
            this.fFI.getPendantView().setDrawBorder(false);
        }
        this.cQi = (TextView) view.findViewById(d.g.user_name);
        this.fFK = (ImageView) view.findViewById(d.g.user_rank);
        this.fFL = (ImageView) view.findViewById(d.g.user_bawu);
        this.fFP = (TbRichTextView) view.findViewById(d.g.richText);
        this.fFQ = (FrsPraiseView) view.findViewById(d.g.pb_item_praise_view);
        this.fFR = (ImageView) view.findViewById(d.g.pb_item_praise_bottomline);
        this.fFS = (PbGiftListView) view.findViewById(d.g.gift_list_view);
        this.fGf = (RelativeLayout) view.findViewById(d.g.pb_first_floor_location_container);
        this.fGg = (TextView) view.findViewById(d.g.pb_item_first_floor_name);
        this.fGh = (TextView) view.findViewById(d.g.pb_item_first_floor_reply_time);
        this.fGi = (TextView) view.findViewById(d.g.pb_item_first_floor_location_address);
        this.fGj = (TextView) view.findViewById(d.g.pb_reply_location_address);
        this.fFO = (TextView) view.findViewById(d.g.floor_owner);
        this.fFM = (TextView) view.findViewById(d.g.floor);
        this.fFN = (TextView) view.findViewById(d.g.time);
        this.cdM = (RelativeLayout) view.findViewById(d.g.pb_post_header_layout);
        this.fFT = (SubPbLayout) view.findViewById(d.g.pb_post_footer_layout);
        this.fFF = view;
        this.fFG = view.findViewById(d.g.new_pb_list_item_blank_top);
        this.fFW = view.findViewById(d.g.new_pb_list_item_line_full);
        this.fFP.getLayoutStrategy().QC();
        this.fFP.getLayoutStrategy().cI(true);
        int min = Math.min(((((l.ao(TbadkCoreApplication.getInst()) - view.getPaddingLeft()) - view.getPaddingRight()) - this.fFP.getPaddingLeft()) - this.fFP.getPaddingRight()) - ((int) TbadkCoreApplication.getInst().getResources().getDimension(d.e.ds60)), i);
        this.fFP.getLayoutStrategy().iO(min);
        this.fFP.getLayoutStrategy().iP((int) (min * 1.618f));
        this.fFP.setTextSize(TbConfig.getContentSize());
        ViewGroup.LayoutParams layoutParams = this.fFJ.getLayoutParams();
        layoutParams.width = (int) TbadkCoreApplication.getInst().getResources().getDimension(d.e.ds60);
        this.fFJ.setLayoutParams(layoutParams);
        this.fFJ.setVisibility(0);
        this.fFP.o(z, false);
        this.fFP.setVoiceViewRes(d.h.voice_play_btn);
        this.dUr = (UserIconBox) view.findViewById(d.g.user_icon_box);
        this.bcN = (UserIconBox) view.findViewById(d.g.user_tshow_icon_box);
        this.fFX = (LinearLayout) view.findViewById(d.g.add_post_footer_layout);
        if (z2) {
            this.cdM.setVisibility(8);
            this.fFP.setPadding(0, 0, 0, 0);
            LinearLayout.LayoutParams layoutParams2 = (LinearLayout.LayoutParams) this.fFP.getLayoutParams();
            layoutParams2.leftMargin = 0;
            layoutParams2.rightMargin = 0;
            layoutParams2.topMargin = 0;
            layoutParams2.bottomMargin = 0;
            this.fFP.setLayoutParams(layoutParams2);
            view.findViewById(d.g.pb_list_item_layout).setPadding(0, 0, 0, 0);
            this.fFZ = (LinearLayout) view.findViewById(d.g.add_time_container);
            this.fFY = (TextView) view.findViewById(d.g.add_time);
            this.fGa = (Button) view.findViewById(d.g.manage_btn);
            this.fFZ.setVisibility(0);
        }
        this.fGb = (LinearLayout) view.findViewById(d.g.addition_more_container);
        this.fGc = (TextView) this.fGb.findViewById(d.g.addition_more);
        this.fGd = this.fGb.findViewById(d.g.addition_divider1);
        this.fGe = this.fGb.findViewById(d.g.addition_divider2);
        this.fGk = (TextView) view.findViewById(d.g.pb_item_tail_content);
        this.fGl = (TriangleShapeView) view.findViewById(d.g.triangle_view);
        this.fGm = (TextView) view.findViewById(d.g.new_pb_recent_reply);
        this.fGm.setVisibility(8);
    }
}
