package com.baidu.tieba.pb.pb.a;

import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.baidu.adp.lib.util.l;
import com.baidu.adp.widget.ListView.r;
import com.baidu.tbadk.TbConfig;
import com.baidu.tbadk.core.TbadkCoreApplication;
import com.baidu.tbadk.core.view.HeadImageView;
import com.baidu.tbadk.core.view.HeadPendantView;
import com.baidu.tbadk.core.view.UserIconBox;
import com.baidu.tbadk.widget.richText.TbRichTextView;
import com.baidu.tieba.d;
import com.baidu.tieba.pb.pb.main.view.TriangleShapeView;
import com.baidu.tieba.pb.pb.sub.SubPbLayout;
import com.baidu.tieba.pb.view.PbGiftListView;
import com.baidu.tieba.tbadkCore.FrsPraiseView;
/* loaded from: classes2.dex */
public class f extends r.a {
    UserIconBox bcF;
    public TextView cPN;
    public RelativeLayout cdE;
    public UserIconBox dTW;
    public RelativeLayout fFA;
    public View fFB;
    public LinearLayout fFC;
    public TextView fFD;
    public LinearLayout fFE;
    public Button fFF;
    public LinearLayout fFG;
    public TextView fFH;
    public View fFI;
    public View fFJ;
    public RelativeLayout fFK;
    public TextView fFL;
    public TextView fFM;
    public TextView fFN;
    public TextView fFO;
    public TextView fFP;
    public TriangleShapeView fFQ;
    public TextView fFR;
    public View fFk;
    public View fFl;
    public View fFm;
    public HeadPendantView fFn;
    public HeadImageView fFo;
    public ImageView fFp;
    public ImageView fFq;
    public TextView fFr;
    public TextView fFs;
    public TextView fFt;
    public TbRichTextView fFu;
    public FrsPraiseView fFv;
    public ImageView fFw;
    public PbGiftListView fFx;
    public SubPbLayout fFy;
    public RelativeLayout fFz;
    public int mSkinType;

    public f(View view, boolean z, int i, boolean z2) {
        super(view);
        this.mSkinType = 3;
        this.fFm = view.findViewById(d.g.sub_pb_more);
        this.fFz = (RelativeLayout) view.findViewById(d.g.user_head_layout);
        this.fFA = (RelativeLayout) view.findViewById(d.g.pb_item_floor_layout);
        this.fFo = (HeadImageView) view.findViewById(d.g.photo);
        this.fFn = (HeadPendantView) view.findViewById(d.g.pendant_photo);
        this.fFn.Dx();
        if (this.fFn.getHeadView() != null) {
            this.fFn.getHeadView().setIsRound(true);
            this.fFn.getHeadView().setDrawBorder(false);
        }
        if (this.fFn.getPendantView() != null) {
            this.fFn.getPendantView().setIsRound(true);
            this.fFn.getPendantView().setDrawBorder(false);
        }
        this.cPN = (TextView) view.findViewById(d.g.user_name);
        this.fFp = (ImageView) view.findViewById(d.g.user_rank);
        this.fFq = (ImageView) view.findViewById(d.g.user_bawu);
        this.fFu = (TbRichTextView) view.findViewById(d.g.richText);
        this.fFv = (FrsPraiseView) view.findViewById(d.g.pb_item_praise_view);
        this.fFw = (ImageView) view.findViewById(d.g.pb_item_praise_bottomline);
        this.fFx = (PbGiftListView) view.findViewById(d.g.gift_list_view);
        this.fFK = (RelativeLayout) view.findViewById(d.g.pb_first_floor_location_container);
        this.fFL = (TextView) view.findViewById(d.g.pb_item_first_floor_name);
        this.fFM = (TextView) view.findViewById(d.g.pb_item_first_floor_reply_time);
        this.fFN = (TextView) view.findViewById(d.g.pb_item_first_floor_location_address);
        this.fFO = (TextView) view.findViewById(d.g.pb_reply_location_address);
        this.fFt = (TextView) view.findViewById(d.g.floor_owner);
        this.fFr = (TextView) view.findViewById(d.g.floor);
        this.fFs = (TextView) view.findViewById(d.g.time);
        this.cdE = (RelativeLayout) view.findViewById(d.g.pb_post_header_layout);
        this.fFy = (SubPbLayout) view.findViewById(d.g.pb_post_footer_layout);
        this.fFk = view;
        this.fFl = view.findViewById(d.g.new_pb_list_item_blank_top);
        this.fFB = view.findViewById(d.g.new_pb_list_item_line_full);
        this.fFu.getLayoutStrategy().QA();
        this.fFu.getLayoutStrategy().cH(true);
        int min = Math.min(((((l.ao(TbadkCoreApplication.getInst()) - view.getPaddingLeft()) - view.getPaddingRight()) - this.fFu.getPaddingLeft()) - this.fFu.getPaddingRight()) - ((int) TbadkCoreApplication.getInst().getResources().getDimension(d.e.ds60)), i);
        this.fFu.getLayoutStrategy().iO(min);
        this.fFu.getLayoutStrategy().iP((int) (min * 1.618f));
        this.fFu.setTextSize(TbConfig.getContentSize());
        ViewGroup.LayoutParams layoutParams = this.fFo.getLayoutParams();
        layoutParams.width = (int) TbadkCoreApplication.getInst().getResources().getDimension(d.e.ds60);
        this.fFo.setLayoutParams(layoutParams);
        this.fFo.setVisibility(0);
        this.fFu.o(z, false);
        this.fFu.setVoiceViewRes(d.h.voice_play_btn);
        this.dTW = (UserIconBox) view.findViewById(d.g.user_icon_box);
        this.bcF = (UserIconBox) view.findViewById(d.g.user_tshow_icon_box);
        this.fFC = (LinearLayout) view.findViewById(d.g.add_post_footer_layout);
        if (z2) {
            this.cdE.setVisibility(8);
            this.fFu.setPadding(0, 0, 0, 0);
            LinearLayout.LayoutParams layoutParams2 = (LinearLayout.LayoutParams) this.fFu.getLayoutParams();
            layoutParams2.leftMargin = 0;
            layoutParams2.rightMargin = 0;
            layoutParams2.topMargin = 0;
            layoutParams2.bottomMargin = 0;
            this.fFu.setLayoutParams(layoutParams2);
            view.findViewById(d.g.pb_list_item_layout).setPadding(0, 0, 0, 0);
            this.fFE = (LinearLayout) view.findViewById(d.g.add_time_container);
            this.fFD = (TextView) view.findViewById(d.g.add_time);
            this.fFF = (Button) view.findViewById(d.g.manage_btn);
            this.fFE.setVisibility(0);
        }
        this.fFG = (LinearLayout) view.findViewById(d.g.addition_more_container);
        this.fFH = (TextView) this.fFG.findViewById(d.g.addition_more);
        this.fFI = this.fFG.findViewById(d.g.addition_divider1);
        this.fFJ = this.fFG.findViewById(d.g.addition_divider2);
        this.fFP = (TextView) view.findViewById(d.g.pb_item_tail_content);
        this.fFQ = (TriangleShapeView) view.findViewById(d.g.triangle_view);
        this.fFR = (TextView) view.findViewById(d.g.new_pb_recent_reply);
        this.fFR.setVisibility(8);
    }
}
