package com.baidu.tieba.pb.pb.a;

import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.baidu.adp.lib.util.k;
import com.baidu.adp.widget.ListView.j;
import com.baidu.tbadk.TbConfig;
import com.baidu.tbadk.core.TbadkCoreApplication;
import com.baidu.tbadk.core.view.HeadImageView;
import com.baidu.tbadk.core.view.HeadPendantView;
import com.baidu.tbadk.core.view.UserIconBox;
import com.baidu.tbadk.widget.richText.TbRichTextView;
import com.baidu.tieba.d;
import com.baidu.tieba.pb.pb.main.view.TriangleShapeView;
import com.baidu.tieba.pb.pb.sub.SubPbLayout;
import com.baidu.tieba.pb.view.PbGiftListView;
import com.baidu.tieba.tbadkCore.FrsPraiseView;
/* loaded from: classes.dex */
public class g extends j.a {
    UserIconBox aoQ;
    public TextView bFC;
    public UserIconBox cIw;
    public View eGS;
    public View eGT;
    public View eGU;
    public HeadPendantView eGV;
    public HeadImageView eGW;
    public ImageView eGX;
    public ImageView eGY;
    public TextView eGZ;
    public TextView eHA;
    public TextView eHB;
    public TextView eHC;
    public TextView eHD;
    public LinearLayout eHE;
    public TextView eHF;
    public TextView eHa;
    public TextView eHb;
    public TbRichTextView eHc;
    public FrsPraiseView eHd;
    public ImageView eHe;
    public PbGiftListView eHf;
    public RelativeLayout eHg;
    public SubPbLayout eHh;
    public RelativeLayout eHi;
    public RelativeLayout eHj;
    public View eHk;
    public LinearLayout eHl;
    public TextView eHm;
    public LinearLayout eHn;
    public Button eHo;
    public LinearLayout eHp;
    public TextView eHq;
    public View eHr;
    public View eHs;
    public RelativeLayout eHt;
    public TextView eHu;
    public TextView eHv;
    public TextView eHw;
    public TextView eHx;
    public TextView eHy;
    public TriangleShapeView eHz;
    public int mSkinType;

    public g(View view, boolean z, int i, boolean z2) {
        super(view);
        this.mSkinType = 3;
        this.eHE = (LinearLayout) view.findViewById(d.h.belong_ba);
        this.eHA = (TextView) view.findViewById(d.h.belong_ba_btn1);
        this.eHB = (TextView) view.findViewById(d.h.belong_ba_btn2);
        this.eHC = (TextView) view.findViewById(d.h.belong_ba_btn3);
        this.eHD = (TextView) view.findViewById(d.h.belong_ba_btn4);
        this.eGU = view.findViewById(d.h.sub_pb_more);
        this.eHi = (RelativeLayout) view.findViewById(d.h.user_head_layout);
        this.eHj = (RelativeLayout) view.findViewById(d.h.pb_item_floor_layout);
        this.eGW = (HeadImageView) view.findViewById(d.h.photo);
        this.eGV = (HeadPendantView) view.findViewById(d.h.pendant_photo);
        this.eGV.wB();
        if (this.eGV.getHeadView() != null) {
            this.eGV.getHeadView().setIsRound(true);
            this.eGV.getHeadView().setDrawBorder(false);
        }
        if (this.eGV.getPendantView() != null) {
            this.eGV.getPendantView().setIsRound(true);
            this.eGV.getPendantView().setDrawBorder(false);
        }
        this.bFC = (TextView) view.findViewById(d.h.user_name);
        this.eGX = (ImageView) view.findViewById(d.h.user_rank);
        this.eGY = (ImageView) view.findViewById(d.h.user_bawu);
        this.eHc = (TbRichTextView) view.findViewById(d.h.richText);
        this.eHd = (FrsPraiseView) view.findViewById(d.h.pb_item_praise_view);
        this.eHe = (ImageView) view.findViewById(d.h.pb_item_praise_bottomline);
        this.eHf = (PbGiftListView) view.findViewById(d.h.gift_list_view);
        this.eHt = (RelativeLayout) view.findViewById(d.h.pb_first_floor_location_container);
        this.eHu = (TextView) view.findViewById(d.h.pb_item_first_floor_name);
        this.eHv = (TextView) view.findViewById(d.h.pb_item_first_floor_reply_time);
        this.eHw = (TextView) view.findViewById(d.h.pb_item_first_floor_location_address);
        this.eHx = (TextView) view.findViewById(d.h.pb_reply_location_address);
        this.eHb = (TextView) view.findViewById(d.h.floor_owner);
        this.eGZ = (TextView) view.findViewById(d.h.floor);
        this.eHa = (TextView) view.findViewById(d.h.time);
        this.eHg = (RelativeLayout) view.findViewById(d.h.pb_post_header_layout);
        this.eHh = (SubPbLayout) view.findViewById(d.h.pb_post_footer_layout);
        this.eGS = view;
        this.eGT = view.findViewById(d.h.new_pb_list_item_blank_top);
        this.eHk = view.findViewById(d.h.new_pb_list_item_line_full);
        this.eHc.Jk();
        this.eHc.setImageViewStretch(true);
        int min = Math.min(((((k.ae(TbadkCoreApplication.getInst()) - view.getPaddingLeft()) - view.getPaddingRight()) - this.eHc.getPaddingLeft()) - this.eHc.getPaddingRight()) - ((int) TbadkCoreApplication.getInst().getResources().getDimension(d.f.ds60)), i);
        this.eHc.setMaxImageWidth(min);
        this.eHc.setMaxImageHeight((int) (min * 1.618f));
        this.eHc.setTextSize(TbConfig.getContentSize());
        ViewGroup.LayoutParams layoutParams = this.eGW.getLayoutParams();
        layoutParams.width = (int) TbadkCoreApplication.getInst().getResources().getDimension(d.f.ds60);
        this.eGW.setLayoutParams(layoutParams);
        this.eGW.setVisibility(0);
        this.eHc.l(z, false);
        this.eHc.setVoiceViewRes(d.j.voice_play_btn);
        this.cIw = (UserIconBox) view.findViewById(d.h.user_icon_box);
        this.aoQ = (UserIconBox) view.findViewById(d.h.user_tshow_icon_box);
        this.eHl = (LinearLayout) view.findViewById(d.h.add_post_footer_layout);
        if (z2) {
            this.eHg.setVisibility(8);
            this.eHc.setPadding(0, 0, 0, 0);
            LinearLayout.LayoutParams layoutParams2 = (LinearLayout.LayoutParams) this.eHc.getLayoutParams();
            layoutParams2.leftMargin = 0;
            layoutParams2.rightMargin = 0;
            layoutParams2.topMargin = 0;
            layoutParams2.bottomMargin = 0;
            this.eHc.setLayoutParams(layoutParams2);
            view.findViewById(d.h.pb_list_item_layout).setPadding(0, 0, 0, 0);
            this.eHn = (LinearLayout) view.findViewById(d.h.add_time_container);
            this.eHm = (TextView) view.findViewById(d.h.add_time);
            this.eHo = (Button) view.findViewById(d.h.manage_btn);
            this.eHn.setVisibility(0);
        }
        this.eHp = (LinearLayout) view.findViewById(d.h.addition_more_container);
        this.eHq = (TextView) this.eHp.findViewById(d.h.addition_more);
        this.eHr = this.eHp.findViewById(d.h.addition_divider1);
        this.eHs = this.eHp.findViewById(d.h.addition_divider2);
        this.eHy = (TextView) view.findViewById(d.h.pb_item_tail_content);
        this.eHz = (TriangleShapeView) view.findViewById(d.h.triangle_view);
        this.eHF = (TextView) view.findViewById(d.h.new_pb_recent_reply);
        this.eHF.setVisibility(8);
    }
}
