package com.baidu.tieba.pb.pb.a;

import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.baidu.adp.widget.ListView.z;
import com.baidu.tbadk.TbConfig;
import com.baidu.tbadk.core.TbadkCoreApplication;
import com.baidu.tbadk.core.view.HeadImageView;
import com.baidu.tbadk.core.view.HeadPendantView;
import com.baidu.tbadk.core.view.UserIconBox;
import com.baidu.tbadk.widget.richText.TbRichTextView;
import com.baidu.tieba.pb.pb.main.view.TriangleShapeView;
import com.baidu.tieba.pb.pb.sub.SubPbLayout;
import com.baidu.tieba.pb.view.PbGiftListView;
import com.baidu.tieba.tbadkCore.FrsPraiseView;
import com.baidu.tieba.w;
/* loaded from: classes.dex */
public class l extends z.a {
    UserIconBox ani;
    public TextView bBa;
    public UserIconBox cqK;
    public ImageView etA;
    public PbGiftListView etB;
    public RelativeLayout etC;
    public SubPbLayout etD;
    public RelativeLayout etE;
    public RelativeLayout etF;
    public View etG;
    public LinearLayout etH;
    public TextView etI;
    public LinearLayout etJ;
    public Button etK;
    public LinearLayout etL;
    public TextView etM;
    public View etN;
    public View etO;
    public RelativeLayout etP;
    public TextView etQ;
    public TextView etR;
    public TextView etS;
    public TextView etT;
    public TextView etU;
    public TriangleShapeView etV;
    public TextView etW;
    public TextView etX;
    public TextView etY;
    public TextView etZ;
    public View eto;
    public View etp;
    public View etq;
    public HeadPendantView etr;
    public HeadImageView ets;
    public ImageView ett;
    public ImageView etu;
    public TextView etv;
    public TextView etw;
    public TextView etx;
    public TbRichTextView ety;
    public FrsPraiseView etz;
    public LinearLayout eua;
    public TextView eub;
    public int mSkinType;

    /* JADX DEBUG: Don't trust debug lines info. Repeating lines: [144=5] */
    public l(View view, boolean z, int i, boolean z2) {
        super(view);
        this.mSkinType = 3;
        this.eua = (LinearLayout) view.findViewById(w.h.belong_ba);
        this.etW = (TextView) view.findViewById(w.h.belong_ba_btn1);
        this.etX = (TextView) view.findViewById(w.h.belong_ba_btn2);
        this.etY = (TextView) view.findViewById(w.h.belong_ba_btn3);
        this.etZ = (TextView) view.findViewById(w.h.belong_ba_btn4);
        this.etq = view.findViewById(w.h.sub_pb_more);
        this.etE = (RelativeLayout) view.findViewById(w.h.user_head_layout);
        this.etF = (RelativeLayout) view.findViewById(w.h.pb_item_floor_layout);
        this.ets = (HeadImageView) view.findViewById(w.h.photo);
        this.etr = (HeadPendantView) view.findViewById(w.h.pendant_photo);
        this.etr.wm();
        if (this.etr.getHeadView() != null) {
            this.etr.getHeadView().setIsRound(true);
            this.etr.getHeadView().setDrawBorder(false);
        }
        if (this.etr.getPendantView() != null) {
            this.etr.getPendantView().setIsRound(true);
            this.etr.getPendantView().setDrawBorder(false);
        }
        this.bBa = (TextView) view.findViewById(w.h.user_name);
        this.ett = (ImageView) view.findViewById(w.h.user_rank);
        this.etu = (ImageView) view.findViewById(w.h.user_bawu);
        this.ety = (TbRichTextView) view.findViewById(w.h.richText);
        this.etz = (FrsPraiseView) view.findViewById(w.h.pb_item_praise_view);
        this.etA = (ImageView) view.findViewById(w.h.pb_item_praise_bottomline);
        this.etB = (PbGiftListView) view.findViewById(w.h.gift_list_view);
        this.etP = (RelativeLayout) view.findViewById(w.h.pb_first_floor_location_container);
        this.etQ = (TextView) view.findViewById(w.h.pb_item_first_floor_name);
        this.etR = (TextView) view.findViewById(w.h.pb_item_first_floor_reply_time);
        this.etS = (TextView) view.findViewById(w.h.pb_item_first_floor_location_address);
        this.etT = (TextView) view.findViewById(w.h.pb_reply_location_address);
        this.etx = (TextView) view.findViewById(w.h.floor_owner);
        this.etv = (TextView) view.findViewById(w.h.floor);
        this.etw = (TextView) view.findViewById(w.h.time);
        this.etC = (RelativeLayout) view.findViewById(w.h.pb_post_header_layout);
        this.etD = (SubPbLayout) view.findViewById(w.h.pb_post_footer_layout);
        this.eto = view;
        this.etp = view.findViewById(w.h.new_pb_list_item_blank_top);
        this.etG = view.findViewById(w.h.new_pb_list_item_line_full);
        this.ety.IJ();
        this.ety.setImageViewStretch(true);
        int min = Math.min(((((com.baidu.adp.lib.util.k.af(TbadkCoreApplication.m9getInst()) - view.getPaddingLeft()) - view.getPaddingRight()) - this.ety.getPaddingLeft()) - this.ety.getPaddingRight()) - ((int) TbadkCoreApplication.m9getInst().getResources().getDimension(w.f.ds60)), i);
        this.ety.setMaxImageWidth(min);
        this.ety.setMaxImageHeight((int) (min * 1.618f));
        this.ety.setTextSize(TbConfig.getContentSize());
        ViewGroup.LayoutParams layoutParams = this.ets.getLayoutParams();
        layoutParams.width = (int) TbadkCoreApplication.m9getInst().getResources().getDimension(w.f.ds60);
        this.ets.setLayoutParams(layoutParams);
        this.ets.setVisibility(0);
        this.ety.k(z, false);
        this.ety.setVoiceViewRes(w.j.voice_play_btn);
        this.cqK = (UserIconBox) view.findViewById(w.h.user_icon_box);
        this.ani = (UserIconBox) view.findViewById(w.h.user_tshow_icon_box);
        this.etH = (LinearLayout) view.findViewById(w.h.add_post_footer_layout);
        if (z2) {
            this.etC.setVisibility(8);
            this.ety.setPadding(0, 0, 0, 0);
            LinearLayout.LayoutParams layoutParams2 = (LinearLayout.LayoutParams) this.ety.getLayoutParams();
            layoutParams2.leftMargin = 0;
            layoutParams2.rightMargin = 0;
            layoutParams2.topMargin = 0;
            layoutParams2.bottomMargin = 0;
            this.ety.setLayoutParams(layoutParams2);
            view.findViewById(w.h.pb_list_item_layout).setPadding(0, 0, 0, 0);
            this.etJ = (LinearLayout) view.findViewById(w.h.add_time_container);
            this.etI = (TextView) view.findViewById(w.h.add_time);
            this.etK = (Button) view.findViewById(w.h.manage_btn);
            this.etJ.setVisibility(0);
        }
        this.etL = (LinearLayout) view.findViewById(w.h.addition_more_container);
        this.etM = (TextView) this.etL.findViewById(w.h.addition_more);
        this.etN = this.etL.findViewById(w.h.addition_divider1);
        this.etO = this.etL.findViewById(w.h.addition_divider2);
        this.etU = (TextView) view.findViewById(w.h.pb_item_tail_content);
        this.etV = (TriangleShapeView) view.findViewById(w.h.triangle_view);
        this.eub = (TextView) view.findViewById(w.h.new_pb_recent_reply);
        this.eub.setVisibility(8);
    }
}
