package com.baidu.webkit.sdk.performance;
/* loaded from: classes9.dex */
public class PagePerformanceTimingData {
    public long mConnectEnd;
    public long mConnectStart;
    public int mDocumentLoadState;
    public long mDomComplete;
    public long mDomContentLoadedEventEnd;
    public long mDomContentLoadedEventStart;
    public long mDomInteractive;
    public long mDomLoading;
    public long mDomainLookupEnd;
    public long mDomainLookupStart;
    public long mFetchStart;
    public long mFirstImagePaint;
    public long mFirstLayout;
    public long mFirstPaint;
    public long mFirstScreenDraw;
    public int mFirstScreenElementCnt;
    public long mFirstScreenLayout;
    public long mFirstScreenPaint;
    public int mFirstScreenPaintContentHeight;
    public long mFirstTextPaint;
    public long mLoadEventEnd;
    public long mLoadEventStart;
    public long mLoadUrlFinish;
    public long mLoadUrlStart;
    public long mNavigationStart;
    public long mParseBlockedOnScriptLoadDuration;
    public long mProxyEnd;
    public long mProxyStart;
    public int mRedirectCount;
    public long mRedirectEnd;
    public long mRedirectStart;
    public long mRequestStart;
    public long mResponseEnd;
    public long mResponseStart;
    public long mSslStart;
    public long mTagParseredClassAttributeWithResults;
}
