package com.baidu.tieba.person.b;

import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.baidu.adp.widget.ListView.x;
import com.baidu.tbadk.core.view.HeadImageView;
import com.baidu.tieba.n;
/* loaded from: classes.dex */
public class f extends x.a {
    public int afY;
    public TextView cOA;
    public TextView cOB;
    public TextView cOC;
    public TextView cOD;
    public RelativeLayout cOE;
    public RelativeLayout cOF;
    public HeadImageView cOG;
    public HeadImageView cOH;
    public TextView cOI;
    public TextView cOJ;
    public TextView cOK;
    public TextView cOL;
    public RelativeLayout cOM;
    public TextView cON;
    public TextView cOO;
    public ImageView cOP;
    public TextView cOQ;
    public View cOi;
    public View cOj;
    public LinearLayout cOl;
    public View cOr;
    public RelativeLayout cOs;
    public TextView cOt;
    public ImageView cOu;
    public TextView cOv;
    public RelativeLayout cOw;
    public RelativeLayout cOx;
    public HeadImageView cOy;
    public HeadImageView cOz;

    public f(View view) {
        super(view);
        this.cOr = null;
        this.cOs = null;
        this.cOt = null;
        this.cOu = null;
        this.cOv = null;
        this.cOi = null;
        this.cOw = null;
        this.cOx = null;
        this.cOy = null;
        this.cOz = null;
        this.cOA = null;
        this.cOB = null;
        this.cOC = null;
        this.cOD = null;
        this.cOj = null;
        this.cOE = null;
        this.cOF = null;
        this.cOG = null;
        this.cOH = null;
        this.cOI = null;
        this.cOJ = null;
        this.cOK = null;
        this.cOL = null;
        this.cOM = null;
        this.cON = null;
        this.cOO = null;
        this.cOP = null;
        this.cOl = null;
        this.cOQ = null;
        this.afY = 3;
        this.cOQ = (TextView) view.findViewById(n.f.gift_give_btn);
        this.cOr = view.findViewById(n.f.top_divider);
        this.cOi = view.findViewById(n.f.head_divider);
        this.cOs = (RelativeLayout) view.findViewById(n.f.group_head);
        this.cOt = (TextView) this.cOs.findViewById(n.f.group_head_title);
        this.cOu = (ImageView) this.cOs.findViewById(n.f.group_head_arrow);
        this.cOv = (TextView) this.cOs.findViewById(n.f.group_head_msg);
        this.cOw = (RelativeLayout) view.findViewById(n.f.first_group_line_item1);
        this.cOx = (RelativeLayout) view.findViewById(n.f.first_group_line_item2);
        this.cOy = (HeadImageView) this.cOw.findViewById(n.f.first_group_head_item1);
        this.cOA = (TextView) this.cOw.findViewById(n.f.first_group_name_item1);
        this.cOC = (TextView) this.cOw.findViewById(n.f.first_group_msg_item1);
        this.cOz = (HeadImageView) this.cOx.findViewById(n.f.first_group_head_item2);
        this.cOB = (TextView) this.cOx.findViewById(n.f.first_group_name_item2);
        this.cOD = (TextView) this.cOx.findViewById(n.f.first_group_msg_item2);
        this.cOj = view.findViewById(n.f.mid_divider);
        this.cOE = (RelativeLayout) view.findViewById(n.f.second_group_line_item1);
        this.cOF = (RelativeLayout) view.findViewById(n.f.second_group_line_item2);
        this.cOG = (HeadImageView) this.cOE.findViewById(n.f.second_group_head_item1);
        this.cOH = (HeadImageView) this.cOF.findViewById(n.f.second_group_head_item2);
        this.cOI = (TextView) this.cOE.findViewById(n.f.second_group_name_item1);
        this.cOJ = (TextView) this.cOF.findViewById(n.f.second_group_name_item2);
        this.cOK = (TextView) this.cOE.findViewById(n.f.second_group_msg_item1);
        this.cOL = (TextView) this.cOF.findViewById(n.f.second_group_msg_item2);
        this.cOM = (RelativeLayout) view.findViewById(n.f.group_none);
        this.cON = (TextView) this.cOM.findViewById(n.f.group_none_title);
        this.cOO = (TextView) this.cOM.findViewById(n.f.group_none_msg);
        this.cOP = (ImageView) this.cOM.findViewById(n.f.group_none_lock);
        this.cOl = (LinearLayout) view.findViewById(n.f.container);
    }
}
