package com.baidu.tieba.person.b;

import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.baidu.adp.widget.ListView.x;
import com.baidu.tbadk.core.view.HeadImageView;
import com.baidu.tieba.t;
/* loaded from: classes.dex */
public class i extends x.a {
    public int ahU;
    public TextView deA;
    public TextView deB;
    public RelativeLayout deC;
    public RelativeLayout deD;
    public HeadImageView deE;
    public HeadImageView deF;
    public TextView deG;
    public TextView deH;
    public TextView deI;
    public TextView deJ;
    public RelativeLayout deK;
    public TextView deL;
    public TextView deM;
    public ImageView deN;
    public TextView deO;
    public View deP;
    public View deQ;
    public ImageView deR;
    public TextView deS;
    public View def;
    public LinearLayout deh;
    public View deo;
    public RelativeLayout dep;
    public TextView deq;
    public ImageView der;
    public TextView des;
    public View det;
    public RelativeLayout deu;
    public RelativeLayout dev;
    public HeadImageView dew;
    public HeadImageView dex;
    public TextView dey;
    public TextView dez;

    public i(View view) {
        super(view);
        this.deo = null;
        this.dep = null;
        this.deq = null;
        this.der = null;
        this.des = null;
        this.det = null;
        this.deu = null;
        this.dev = null;
        this.dew = null;
        this.dex = null;
        this.dey = null;
        this.dez = null;
        this.deA = null;
        this.deB = null;
        this.def = null;
        this.deC = null;
        this.deD = null;
        this.deE = null;
        this.deF = null;
        this.deG = null;
        this.deH = null;
        this.deI = null;
        this.deJ = null;
        this.deK = null;
        this.deL = null;
        this.deM = null;
        this.deN = null;
        this.deh = null;
        this.deO = null;
        this.ahU = 3;
        this.deO = (TextView) view.findViewById(t.g.gift_give_btn);
        this.deo = view.findViewById(t.g.top_divider);
        this.det = view.findViewById(t.g.head_divider);
        this.dep = (RelativeLayout) view.findViewById(t.g.group_head);
        this.deq = (TextView) this.dep.findViewById(t.g.group_head_title);
        this.der = (ImageView) this.dep.findViewById(t.g.group_head_arrow);
        this.des = (TextView) this.dep.findViewById(t.g.group_head_msg);
        this.deu = (RelativeLayout) view.findViewById(t.g.first_group_line_item1);
        this.dev = (RelativeLayout) view.findViewById(t.g.first_group_line_item2);
        this.dew = (HeadImageView) this.deu.findViewById(t.g.first_group_head_item1);
        this.dey = (TextView) this.deu.findViewById(t.g.first_group_name_item1);
        this.deA = (TextView) this.deu.findViewById(t.g.first_group_msg_item1);
        this.dex = (HeadImageView) this.dev.findViewById(t.g.first_group_head_item2);
        this.dez = (TextView) this.dev.findViewById(t.g.first_group_name_item2);
        this.deB = (TextView) this.dev.findViewById(t.g.first_group_msg_item2);
        this.def = view.findViewById(t.g.mid_divider);
        this.deC = (RelativeLayout) view.findViewById(t.g.second_group_line_item1);
        this.deD = (RelativeLayout) view.findViewById(t.g.second_group_line_item2);
        this.deE = (HeadImageView) this.deC.findViewById(t.g.second_group_head_item1);
        this.deF = (HeadImageView) this.deD.findViewById(t.g.second_group_head_item2);
        this.deG = (TextView) this.deC.findViewById(t.g.second_group_name_item1);
        this.deH = (TextView) this.deD.findViewById(t.g.second_group_name_item2);
        this.deI = (TextView) this.deC.findViewById(t.g.second_group_msg_item1);
        this.deJ = (TextView) this.deD.findViewById(t.g.second_group_msg_item2);
        this.deK = (RelativeLayout) view.findViewById(t.g.group_none);
        this.deL = (TextView) this.deK.findViewById(t.g.group_none_title);
        this.deM = (TextView) this.deK.findViewById(t.g.group_none_msg);
        this.deN = (ImageView) this.deK.findViewById(t.g.group_none_lock);
        this.deh = (LinearLayout) view.findViewById(t.g.container);
        this.deP = view.findViewById(t.g.gift_give_god_layout_divider);
        this.deQ = view.findViewById(t.g.gift_give_god_layout);
        this.deR = (ImageView) view.findViewById(t.g.gift_give_god_icon);
        this.deS = (TextView) view.findViewById(t.g.gift_give_god_text);
    }
}
