package com.baidu.tieba.person.b;

import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.baidu.adp.widget.ListView.x;
import com.baidu.tbadk.core.view.HeadImageView;
import com.baidu.tieba.t;
/* loaded from: classes.dex */
public class i extends x.a {
    public int aik;
    public View dyF;
    public LinearLayout dyH;
    public View dyN;
    public RelativeLayout dyO;
    public TextView dyP;
    public ImageView dyQ;
    public TextView dyR;
    public View dyS;
    public RelativeLayout dyT;
    public RelativeLayout dyU;
    public HeadImageView dyV;
    public HeadImageView dyW;
    public TextView dyX;
    public TextView dyY;
    public TextView dyZ;
    public TextView dza;
    public RelativeLayout dzb;
    public RelativeLayout dzc;
    public HeadImageView dzd;
    public HeadImageView dze;
    public TextView dzf;
    public TextView dzg;
    public TextView dzh;
    public TextView dzi;
    public RelativeLayout dzj;
    public TextView dzk;
    public TextView dzl;
    public ImageView dzm;
    public TextView dzn;
    public View dzo;
    public View dzp;
    public ImageView dzq;
    public TextView dzr;

    public i(View view) {
        super(view);
        this.dyN = null;
        this.dyO = null;
        this.dyP = null;
        this.dyQ = null;
        this.dyR = null;
        this.dyS = null;
        this.dyT = null;
        this.dyU = null;
        this.dyV = null;
        this.dyW = null;
        this.dyX = null;
        this.dyY = null;
        this.dyZ = null;
        this.dza = null;
        this.dyF = null;
        this.dzb = null;
        this.dzc = null;
        this.dzd = null;
        this.dze = null;
        this.dzf = null;
        this.dzg = null;
        this.dzh = null;
        this.dzi = null;
        this.dzj = null;
        this.dzk = null;
        this.dzl = null;
        this.dzm = null;
        this.dyH = null;
        this.dzn = null;
        this.aik = 3;
        this.dzn = (TextView) view.findViewById(t.g.gift_give_btn);
        this.dyN = view.findViewById(t.g.top_divider);
        this.dyS = view.findViewById(t.g.head_divider);
        this.dyO = (RelativeLayout) view.findViewById(t.g.group_head);
        this.dyP = (TextView) this.dyO.findViewById(t.g.group_head_title);
        this.dyQ = (ImageView) this.dyO.findViewById(t.g.group_head_arrow);
        this.dyR = (TextView) this.dyO.findViewById(t.g.group_head_msg);
        this.dyT = (RelativeLayout) view.findViewById(t.g.first_group_line_item1);
        this.dyU = (RelativeLayout) view.findViewById(t.g.first_group_line_item2);
        this.dyV = (HeadImageView) this.dyT.findViewById(t.g.first_group_head_item1);
        this.dyX = (TextView) this.dyT.findViewById(t.g.first_group_name_item1);
        this.dyZ = (TextView) this.dyT.findViewById(t.g.first_group_msg_item1);
        this.dyW = (HeadImageView) this.dyU.findViewById(t.g.first_group_head_item2);
        this.dyY = (TextView) this.dyU.findViewById(t.g.first_group_name_item2);
        this.dza = (TextView) this.dyU.findViewById(t.g.first_group_msg_item2);
        this.dyF = view.findViewById(t.g.mid_divider);
        this.dzb = (RelativeLayout) view.findViewById(t.g.second_group_line_item1);
        this.dzc = (RelativeLayout) view.findViewById(t.g.second_group_line_item2);
        this.dzd = (HeadImageView) this.dzb.findViewById(t.g.second_group_head_item1);
        this.dze = (HeadImageView) this.dzc.findViewById(t.g.second_group_head_item2);
        this.dzf = (TextView) this.dzb.findViewById(t.g.second_group_name_item1);
        this.dzg = (TextView) this.dzc.findViewById(t.g.second_group_name_item2);
        this.dzh = (TextView) this.dzb.findViewById(t.g.second_group_msg_item1);
        this.dzi = (TextView) this.dzc.findViewById(t.g.second_group_msg_item2);
        this.dzj = (RelativeLayout) view.findViewById(t.g.group_none);
        this.dzk = (TextView) this.dzj.findViewById(t.g.group_none_title);
        this.dzl = (TextView) this.dzj.findViewById(t.g.group_none_msg);
        this.dzm = (ImageView) this.dzj.findViewById(t.g.group_none_lock);
        this.dyH = (LinearLayout) view.findViewById(t.g.container);
        this.dzo = view.findViewById(t.g.gift_give_god_layout_divider);
        this.dzp = view.findViewById(t.g.gift_give_god_layout);
        this.dzq = (ImageView) view.findViewById(t.g.gift_give_god_icon);
        this.dzr = (TextView) view.findViewById(t.g.gift_give_god_text);
    }
}
