package com.baidu.tieba.person.b;

import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.baidu.adp.widget.ListView.y;
import com.baidu.tbadk.core.view.HeadImageView;
import com.baidu.tieba.t;
/* loaded from: classes.dex */
public class j extends y.a {
    public int aej;
    public View dBN;
    public LinearLayout dBP;
    public View dBV;
    public RelativeLayout dBW;
    public TextView dBX;
    public ImageView dBY;
    public TextView dBZ;
    public View dCa;
    public RelativeLayout dCb;
    public RelativeLayout dCc;
    public HeadImageView dCd;
    public HeadImageView dCe;
    public TextView dCf;
    public TextView dCg;
    public TextView dCh;
    public TextView dCi;
    public RelativeLayout dCj;
    public RelativeLayout dCk;
    public HeadImageView dCl;
    public HeadImageView dCm;
    public TextView dCn;
    public TextView dCo;
    public TextView dCp;
    public TextView dCq;
    public RelativeLayout dCr;
    public TextView dCs;
    public TextView dCt;
    public ImageView dCu;
    public TextView dCv;
    public View dCw;
    public View dCx;
    public ImageView dCy;
    public TextView dCz;

    public j(View view) {
        super(view);
        this.dBV = null;
        this.dBW = null;
        this.dBX = null;
        this.dBY = null;
        this.dBZ = null;
        this.dCa = null;
        this.dCb = null;
        this.dCc = null;
        this.dCd = null;
        this.dCe = null;
        this.dCf = null;
        this.dCg = null;
        this.dCh = null;
        this.dCi = null;
        this.dBN = null;
        this.dCj = null;
        this.dCk = null;
        this.dCl = null;
        this.dCm = null;
        this.dCn = null;
        this.dCo = null;
        this.dCp = null;
        this.dCq = null;
        this.dCr = null;
        this.dCs = null;
        this.dCt = null;
        this.dCu = null;
        this.dBP = null;
        this.dCv = null;
        this.aej = 3;
        this.dCv = (TextView) view.findViewById(t.g.gift_give_btn);
        this.dBV = view.findViewById(t.g.top_divider);
        this.dCa = view.findViewById(t.g.head_divider);
        this.dBW = (RelativeLayout) view.findViewById(t.g.group_head);
        this.dBX = (TextView) this.dBW.findViewById(t.g.group_head_title);
        this.dBY = (ImageView) this.dBW.findViewById(t.g.group_head_arrow);
        this.dBZ = (TextView) this.dBW.findViewById(t.g.group_head_msg);
        this.dCb = (RelativeLayout) view.findViewById(t.g.first_group_line_item1);
        this.dCc = (RelativeLayout) view.findViewById(t.g.first_group_line_item2);
        this.dCd = (HeadImageView) this.dCb.findViewById(t.g.first_group_head_item1);
        this.dCf = (TextView) this.dCb.findViewById(t.g.first_group_name_item1);
        this.dCh = (TextView) this.dCb.findViewById(t.g.first_group_msg_item1);
        this.dCe = (HeadImageView) this.dCc.findViewById(t.g.first_group_head_item2);
        this.dCg = (TextView) this.dCc.findViewById(t.g.first_group_name_item2);
        this.dCi = (TextView) this.dCc.findViewById(t.g.first_group_msg_item2);
        this.dBN = view.findViewById(t.g.mid_divider);
        this.dCj = (RelativeLayout) view.findViewById(t.g.second_group_line_item1);
        this.dCk = (RelativeLayout) view.findViewById(t.g.second_group_line_item2);
        this.dCl = (HeadImageView) this.dCj.findViewById(t.g.second_group_head_item1);
        this.dCm = (HeadImageView) this.dCk.findViewById(t.g.second_group_head_item2);
        this.dCn = (TextView) this.dCj.findViewById(t.g.second_group_name_item1);
        this.dCo = (TextView) this.dCk.findViewById(t.g.second_group_name_item2);
        this.dCp = (TextView) this.dCj.findViewById(t.g.second_group_msg_item1);
        this.dCq = (TextView) this.dCk.findViewById(t.g.second_group_msg_item2);
        this.dCr = (RelativeLayout) view.findViewById(t.g.group_none);
        this.dCs = (TextView) this.dCr.findViewById(t.g.group_none_title);
        this.dCt = (TextView) this.dCr.findViewById(t.g.group_none_msg);
        this.dCu = (ImageView) this.dCr.findViewById(t.g.group_none_lock);
        this.dBP = (LinearLayout) view.findViewById(t.g.container);
        this.dCw = view.findViewById(t.g.gift_give_god_layout_divider);
        this.dCx = view.findViewById(t.g.gift_give_god_layout);
        this.dCy = (ImageView) view.findViewById(t.g.gift_give_god_icon);
        this.dCz = (TextView) view.findViewById(t.g.gift_give_god_text);
    }
}
