package com.baidu.tieba.person.b;

import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.baidu.adp.widget.ListView.x;
import com.baidu.tbadk.widget.TbImageView;
import com.baidu.tieba.t;
/* loaded from: classes.dex */
public class l extends x.a {
    public int aik;
    public TextView dAa;
    public TextView dAb;
    public TextView dAc;
    public RelativeLayout dAd;
    public TextView dAe;
    public TextView dAf;
    public TextView dAg;
    public RelativeLayout dAh;
    public TextView dAi;
    public TextView dAj;
    public TextView dAk;
    public TbImageView dAl;
    public TbImageView dAm;
    public TbImageView dAn;
    public TbImageView dAo;
    public TbImageView dAp;
    public TbImageView dAq;
    public View dyF;
    public LinearLayout dyH;
    public View dyN;
    public View dyS;
    public RelativeLayout dzL;
    public TextView dzM;
    public ImageView dzN;
    public TextView dzO;
    public RelativeLayout dzP;
    public TextView dzQ;
    public TextView dzR;
    public ImageView dzS;
    public RelativeLayout dzT;
    public TbImageView dzU;
    public TextView dzV;
    public TextView dzW;
    public TextView dzX;
    public RelativeLayout dzY;
    public TbImageView dzZ;

    public l(View view) {
        super(view);
        this.dyN = null;
        this.dzL = null;
        this.dzM = null;
        this.dzN = null;
        this.dzO = null;
        this.dyS = null;
        this.dyF = null;
        this.dzP = null;
        this.dzQ = null;
        this.dzR = null;
        this.dzS = null;
        this.dzT = null;
        this.dzU = null;
        this.dzV = null;
        this.dzW = null;
        this.dzX = null;
        this.dzY = null;
        this.dzZ = null;
        this.dAa = null;
        this.dAb = null;
        this.dAc = null;
        this.dAd = null;
        this.dAe = null;
        this.dAf = null;
        this.dAg = null;
        this.dAh = null;
        this.dAi = null;
        this.dAj = null;
        this.dAk = null;
        this.dAl = null;
        this.dAm = null;
        this.dAn = null;
        this.dAo = null;
        this.dAp = null;
        this.dAq = null;
        this.aik = 3;
        this.dyH = (LinearLayout) view.findViewById(t.g.container);
        this.dyN = view.findViewById(t.g.top_divider);
        this.dyS = view.findViewById(t.g.head_divider);
        this.dyF = view.findViewById(t.g.mid_divider);
        this.dzL = (RelativeLayout) view.findViewById(t.g.thread_head);
        this.dzM = (TextView) this.dzL.findViewById(t.g.thread_head_title);
        this.dzN = (ImageView) this.dzL.findViewById(t.g.thread_head_arrow);
        this.dzO = (TextView) this.dzL.findViewById(t.g.thread_head_msg);
        this.dzP = (RelativeLayout) view.findViewById(t.g.thread_none);
        this.dzQ = (TextView) this.dzP.findViewById(t.g.thread_none_title);
        this.dzR = (TextView) this.dzP.findViewById(t.g.thread_none_msg);
        this.dzS = (ImageView) this.dzP.findViewById(t.g.thread_none_lock);
        this.dzT = (RelativeLayout) view.findViewById(t.g.pic_thread_item);
        this.dzU = (TbImageView) this.dzT.findViewById(t.g.pic_thread_item_img);
        this.dzV = (TextView) this.dzT.findViewById(t.g.pic_thread_item_title);
        this.dzW = (TextView) this.dzT.findViewById(t.g.pic_thread_item_content);
        this.dzX = (TextView) this.dzT.findViewById(t.g.pic_thread_item_forum_name);
        this.dAl = (TbImageView) this.dzT.findViewById(t.g.pic_thread_item_play_video_icon);
        this.dAn = (TbImageView) this.dzT.findViewById(t.g.pic_thread_item_play_video_icon);
        this.dAn = (TbImageView) this.dzT.findViewById(t.g.pic_thread_item_zhibo_icon);
        this.dzY = (RelativeLayout) view.findViewById(t.g.pic_thread_item1);
        this.dzZ = (TbImageView) this.dzY.findViewById(t.g.pic_thread_item_img1);
        this.dAa = (TextView) this.dzY.findViewById(t.g.pic_thread_item_title1);
        this.dAb = (TextView) this.dzY.findViewById(t.g.pic_thread_item_content1);
        this.dAc = (TextView) this.dzY.findViewById(t.g.pic_thread_item_forum_name1);
        this.dAm = (TbImageView) this.dzY.findViewById(t.g.pic_thread_item_play_video_icon1);
        this.dAo = (TbImageView) this.dzY.findViewById(t.g.pic_thread_item_zhibo_icon1);
        this.dAd = (RelativeLayout) view.findViewById(t.g.text_thread_item1);
        this.dAe = (TextView) this.dAd.findViewById(t.g.text_thread_item_title1);
        this.dAf = (TextView) this.dAd.findViewById(t.g.text_thread_item_content1);
        this.dAg = (TextView) this.dAd.findViewById(t.g.text_thread_item_forum_name1);
        this.dAp = (TbImageView) this.dAd.findViewById(t.g.text_thread_item_zhibo_icon1);
        this.dAh = (RelativeLayout) view.findViewById(t.g.text_thread_item2);
        this.dAi = (TextView) this.dAh.findViewById(t.g.text_thread_item_title2);
        this.dAj = (TextView) this.dAh.findViewById(t.g.text_thread_item_content2);
        this.dAk = (TextView) this.dAh.findViewById(t.g.text_thread_item_forum_name2);
        this.dAq = (TbImageView) this.dAh.findViewById(t.g.text_thread_item_zhibo_icon2);
    }
}
