package com.baidu.tieba.person.b;

import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.baidu.adp.widget.ListView.x;
import com.baidu.tbadk.widget.TbImageView;
import com.baidu.tieba.t;
/* loaded from: classes.dex */
public class l extends x.a {
    public int ahU;
    public View def;
    public LinearLayout deh;
    public View deo;
    public View det;
    public TbImageView dfA;
    public TextView dfB;
    public TextView dfC;
    public TextView dfD;
    public RelativeLayout dfE;
    public TextView dfF;
    public TextView dfG;
    public TextView dfH;
    public RelativeLayout dfI;
    public TextView dfJ;
    public TextView dfK;
    public TextView dfL;
    public TbImageView dfM;
    public TbImageView dfN;
    public TbImageView dfO;
    public TbImageView dfP;
    public TbImageView dfQ;
    public TbImageView dfR;
    public RelativeLayout dfm;
    public TextView dfn;
    public ImageView dfo;
    public TextView dfp;
    public RelativeLayout dfq;
    public TextView dfr;
    public TextView dfs;
    public ImageView dft;
    public RelativeLayout dfu;
    public TbImageView dfv;
    public TextView dfw;
    public TextView dfx;
    public TextView dfy;
    public RelativeLayout dfz;

    public l(View view) {
        super(view);
        this.deo = null;
        this.dfm = null;
        this.dfn = null;
        this.dfo = null;
        this.dfp = null;
        this.det = null;
        this.def = null;
        this.dfq = null;
        this.dfr = null;
        this.dfs = null;
        this.dft = null;
        this.dfu = null;
        this.dfv = null;
        this.dfw = null;
        this.dfx = null;
        this.dfy = null;
        this.dfz = null;
        this.dfA = null;
        this.dfB = null;
        this.dfC = null;
        this.dfD = null;
        this.dfE = null;
        this.dfF = null;
        this.dfG = null;
        this.dfH = null;
        this.dfI = null;
        this.dfJ = null;
        this.dfK = null;
        this.dfL = null;
        this.dfM = null;
        this.dfN = null;
        this.dfO = null;
        this.dfP = null;
        this.dfQ = null;
        this.dfR = null;
        this.ahU = 3;
        this.deh = (LinearLayout) view.findViewById(t.g.container);
        this.deo = view.findViewById(t.g.top_divider);
        this.det = view.findViewById(t.g.head_divider);
        this.def = view.findViewById(t.g.mid_divider);
        this.dfm = (RelativeLayout) view.findViewById(t.g.thread_head);
        this.dfn = (TextView) this.dfm.findViewById(t.g.thread_head_title);
        this.dfo = (ImageView) this.dfm.findViewById(t.g.thread_head_arrow);
        this.dfp = (TextView) this.dfm.findViewById(t.g.thread_head_msg);
        this.dfq = (RelativeLayout) view.findViewById(t.g.thread_none);
        this.dfr = (TextView) this.dfq.findViewById(t.g.thread_none_title);
        this.dfs = (TextView) this.dfq.findViewById(t.g.thread_none_msg);
        this.dft = (ImageView) this.dfq.findViewById(t.g.thread_none_lock);
        this.dfu = (RelativeLayout) view.findViewById(t.g.pic_thread_item);
        this.dfv = (TbImageView) this.dfu.findViewById(t.g.pic_thread_item_img);
        this.dfw = (TextView) this.dfu.findViewById(t.g.pic_thread_item_title);
        this.dfx = (TextView) this.dfu.findViewById(t.g.pic_thread_item_content);
        this.dfy = (TextView) this.dfu.findViewById(t.g.pic_thread_item_forum_name);
        this.dfM = (TbImageView) this.dfu.findViewById(t.g.pic_thread_item_play_video_icon);
        this.dfO = (TbImageView) this.dfu.findViewById(t.g.pic_thread_item_play_video_icon);
        this.dfO = (TbImageView) this.dfu.findViewById(t.g.pic_thread_item_zhibo_icon);
        this.dfz = (RelativeLayout) view.findViewById(t.g.pic_thread_item1);
        this.dfA = (TbImageView) this.dfz.findViewById(t.g.pic_thread_item_img1);
        this.dfB = (TextView) this.dfz.findViewById(t.g.pic_thread_item_title1);
        this.dfC = (TextView) this.dfz.findViewById(t.g.pic_thread_item_content1);
        this.dfD = (TextView) this.dfz.findViewById(t.g.pic_thread_item_forum_name1);
        this.dfN = (TbImageView) this.dfz.findViewById(t.g.pic_thread_item_play_video_icon1);
        this.dfP = (TbImageView) this.dfz.findViewById(t.g.pic_thread_item_zhibo_icon1);
        this.dfE = (RelativeLayout) view.findViewById(t.g.text_thread_item1);
        this.dfF = (TextView) this.dfE.findViewById(t.g.text_thread_item_title1);
        this.dfG = (TextView) this.dfE.findViewById(t.g.text_thread_item_content1);
        this.dfH = (TextView) this.dfE.findViewById(t.g.text_thread_item_forum_name1);
        this.dfQ = (TbImageView) this.dfE.findViewById(t.g.text_thread_item_zhibo_icon1);
        this.dfI = (RelativeLayout) view.findViewById(t.g.text_thread_item2);
        this.dfJ = (TextView) this.dfI.findViewById(t.g.text_thread_item_title2);
        this.dfK = (TextView) this.dfI.findViewById(t.g.text_thread_item_content2);
        this.dfL = (TextView) this.dfI.findViewById(t.g.text_thread_item_forum_name2);
        this.dfR = (TbImageView) this.dfI.findViewById(t.g.text_thread_item_zhibo_icon2);
    }
}
