package com.kwad.sdk.core.b.kwai;

import com.baidu.titan.sdk.runtime.ClassClinitInterceptable;
import com.baidu.titan.sdk.runtime.ClassClinitInterceptorStorage;
import com.baidu.titan.sdk.runtime.FieldHolder;
import com.baidu.titan.sdk.runtime.InterceptResult;
import com.baidu.titan.sdk.runtime.Interceptable;
import com.kwad.sdk.collector.AppStatusRules;
import com.kwad.sdk.contentalliance.coupon.model.ActivityInfo;
import com.kwad.sdk.contentalliance.coupon.model.CouponStatus;
import com.kwad.sdk.contentalliance.coupon.model.CouponStatusInfo;
import com.kwad.sdk.core.config.item.AvatarGuiderConfigItem;
import com.kwad.sdk.core.config.item.InsertScreenConfigItem;
import com.kwad.sdk.core.config.item.InstallActivateReminderConfigItem;
import com.kwad.sdk.core.config.item.h;
import com.kwad.sdk.core.config.item.i;
import com.kwad.sdk.core.download.DownloadParams;
import com.kwad.sdk.core.preload.SplashPreloadManager;
import com.kwad.sdk.core.report.CommercialAction;
import com.kwad.sdk.core.report.ReportAction;
import com.kwad.sdk.core.report.a;
import com.kwad.sdk.core.report.p;
import com.kwad.sdk.core.request.model.TaskStat;
import com.kwad.sdk.core.request.model.g;
import com.kwad.sdk.core.response.model.ABParams;
import com.kwad.sdk.core.response.model.AdInfo;
import com.kwad.sdk.core.response.model.AdMatrixInfo;
import com.kwad.sdk.core.response.model.AdProductInfo;
import com.kwad.sdk.core.response.model.AdStyleInfo;
import com.kwad.sdk.core.response.model.AdTemplate;
import com.kwad.sdk.core.response.model.AggregatePageEntranceInfo;
import com.kwad.sdk.core.response.model.CouponInfo;
import com.kwad.sdk.core.response.model.HotspotInfo;
import com.kwad.sdk.core.response.model.HotspotListData;
import com.kwad.sdk.core.response.model.NewsInfo;
import com.kwad.sdk.core.response.model.PageInfo;
import com.kwad.sdk.core.response.model.PhotoAd;
import com.kwad.sdk.core.response.model.PhotoComment;
import com.kwad.sdk.core.response.model.PhotoInfo;
import com.kwad.sdk.core.response.model.PhotoShareInfo;
import com.kwad.sdk.core.response.model.PreloadData;
import com.kwad.sdk.core.response.model.ReportInfo;
import com.kwad.sdk.core.response.model.SdkConfigData;
import com.kwad.sdk.core.response.model.TabInfo;
import com.kwad.sdk.core.response.model.VideoPlayerStatus;
import com.kwad.sdk.core.scene.URLPackage;
import com.kwad.sdk.core.webview.jshandler.WebCardVideoPositionHandler;
import com.kwad.sdk.core.webview.jshandler.b;
import com.kwad.sdk.core.webview.jshandler.e;
import com.kwad.sdk.core.webview.jshandler.h;
import com.kwad.sdk.core.webview.jshandler.i;
import com.kwad.sdk.core.webview.jshandler.l;
import com.kwad.sdk.core.webview.jshandler.m;
import com.kwad.sdk.core.webview.jshandler.n;
import com.kwad.sdk.core.webview.jshandler.p;
import com.kwad.sdk.core.webview.jshandler.q;
import com.kwad.sdk.core.webview.jshandler.u;
import com.kwad.sdk.core.webview.jshandler.v;
import com.kwad.sdk.core.webview.jshandler.w;
import com.kwad.sdk.core.webview.jshandler.x;
import com.kwad.sdk.core.webview.jshandler.z;
import com.kwad.sdk.core.webview.kwai.h;
import com.kwad.sdk.home.download.HomeApkBannerData;
import com.kwad.sdk.internal.api.SceneImpl;
import com.kwad.sdk.live.mode.LiveInfo;
import com.kwad.sdk.reward.j;
import com.kwad.tachikoma.config.TKConfigResultData;
import java.util.HashMap;
import java.util.Map;
/* loaded from: classes3.dex */
public class cf {
    public static /* synthetic */ Interceptable $ic;
    public static Map<Class<? extends com.kwad.sdk.core.response.kwai.a>, com.kwad.sdk.core.d> a;
    public transient /* synthetic */ FieldHolder $fh;

    static {
        InterceptResult invokeClinit;
        ClassClinitInterceptable classClinitInterceptable = ClassClinitInterceptorStorage.$ic;
        if (classClinitInterceptable != null && (invokeClinit = classClinitInterceptable.invokeClinit(-2048576129, "Lcom/kwad/sdk/core/b/kwai/cf;")) != null) {
            Interceptable interceptable = invokeClinit.interceptor;
            if (interceptable != null) {
                $ic = interceptable;
            }
            if ((invokeClinit.flags & 1) != 0) {
                classClinitInterceptable.invokePostClinit(-2048576129, "Lcom/kwad/sdk/core/b/kwai/cf;");
                return;
            }
        }
        HashMap hashMap = new HashMap(150);
        a = hashMap;
        hashMap.put(AdInfo.AdSplashInfo.class, new s());
        a.put(j.a.class, new al());
        a.put(AdMatrixInfo.ActionBarInfoNew.class, new c());
        a.put(AdMatrixInfo.SplashInteractionInfo.class, new dw());
        a.put(ReportInfo.class, new dm());
        a.put(AdMatrixInfo.FullPageActionBarInfo.class, new bm());
        a.put(com.kwad.sdk.splashscreen.kwai.b.class, new dx());
        a.put(AdInfo.AdMaterialInfo.MaterialFeature.class, new cl());
        a.put(AdInfo.MaterialSize.class, new cm());
        a.put(AdStyleInfo.PlayEndInfo.EndTopToolBarInfo.class, new bf());
        a.put(com.kwad.sdk.core.request.model.d.class, new az());
        a.put(x.a.class, new ee());
        a.put(q.b.class, new aa());
        a.put(TaskStat.class, new ed());
        a.put(AdMatrixInfo.MatrixTemplate.class, new cn());
        a.put(HotspotListData.class, new bw());
        a.put(TabInfo.class, new ec());
        a.put(WebCardVideoPositionHandler.VideoPosition.class, new eq());
        a.put(com.kwad.sdk.core.report.m.class, new dl());
        a.put(com.kwad.sdk.core.webview.a.kwai.b.class, new co());
        a.put(LiveInfo.class, new cg());
        a.put(com.kwad.sdk.collector.kwai.e.class, new dp());
        a.put(q.a.class, new z());
        a.put(URLPackage.class, new ek());
        a.put(com.kwad.sdk.core.webview.a.kwai.f.class, new er());
        a.put(AdInfo.AdPreloadInfo.class, new p());
        a.put(e.a.class, new bp());
        a.put(m.b.class, new bo());
        a.put(AdStyleInfo.PlayDetailInfo.DetailTopToolBarInfo.class, new ax());
        a.put(AdStyleInfo.FeedAdInfo.class, new bl());
        a.put(com.kwad.sdk.internal.api.a.class, new m());
        a.put(h.a.class, new ba());
        a.put(PhotoInfo.AuthorInfo.class, new ac());
        a.put(PhotoInfo.WallpaperInfo.class, new et());
        a.put(NewsInfo.ImageInfo.class, new by());
        a.put(com.kwad.sdk.core.response.model.b.class, new de());
        a.put(i.a.class, new ca());
        a.put(CommercialAction.TKDownloadMsg.class, new ea());
        a.put(CouponStatus.class, new aq());
        a.put(AdProductInfo.class, new q());
        a.put(com.kwad.sdk.c.kwai.a.class, new br());
        a.put(SplashPreloadManager.PreLoadItem.class, new df());
        a.put(h.a.class, new bx());
        a.put(PhotoInfo.VideoInfo.class, new eo());
        a.put(AdStyleInfo.class, new t());
        a.put(com.kwad.sdk.collector.kwai.f.class, new dt());
        a.put(ReportAction.class, new dk());
        a.put(PhotoInfo.BaseInfo.class, new ae());
        a.put(AdInfo.AdMaterialInfo.class, new n());
        a.put(AdInfo.DownloadSafeInfo.class, new bc());
        a.put(AvatarGuiderConfigItem.AvatarGuiderConfig.class, new ad());
        a.put(AdStyleInfo.PlayDetailInfo.WidgetAdInfo.class, new eu());
        a.put(h.a.class, new em());
        a.put(SdkConfigData.CouponActiveConfig.class, new ao());
        a.put(NewsInfo.class, new cp());
        a.put(AdStyleInfo.PlayDetailInfo.PatchAdInfo.class, new cv());
        a.put(AdStyleInfo.PlayDetailInfo.DrawAdInfo.class, new be());
        a.put(ReportAction.a.class, new ai());
        a.put(i.a.class, new bs());
        a.put(AdStyleInfo.PlayEndInfo.AdWebCardInfo.class, new w());
        a.put(l.a.class, new as());
        a.put(AdInfo.AdInsertScreenInfo.class, new l());
        a.put(CouponInfo.class, new ap());
        a.put(AdInfo.ComplianceInfo.class, new am());
        a.put(PhotoInfo.ProductInfo.class, new dj());
        a.put(AdMatrixInfo.SplashInfo.class, new dv());
        a.put(AdInfo.H5Config.class, new bn());
        a.put(n.a.class, new cc());
        a.put(AdMatrixInfo.Styles.class, new dz());
        a.put(LiveInfo.LiveStreamPlayCDNNode.class, new ci());
        a.put(PageInfo.class, new ct());
        a.put(com.kwad.sdk.core.webview.a.kwai.a.class, new ak());
        a.put(n.b.class, new cd());
        a.put(com.kwad.sdk.collector.kwai.d.class, new bh());
        a.put(AdStyleInfo.PlayDetailInfo.ActionBarInfo.class, new b());
        a.put(AdInfo.AdAggregateInfo.class, new f());
        a.put(SdkConfigData.TemplateConfig.class, new ef());
        a.put(p.a.class, new aj());
        a.put(LiveInfo.CoverThumbnailUrl.class, new au());
        a.put(AdStyleInfo.PlayEndInfo.class, new dc());
        a.put(a.C2086a.class, new bi());
        a.put(PhotoInfo.ProductInfo.ProductDetail.class, new di());
        a.put(InsertScreenConfigItem.InsertScreenConfig.class, new bz());
        a.put(com.kwad.sdk.core.webview.a.kwai.e.class, new du());
        a.put(PhotoComment.class, new cy());
        a.put(v.a.class, new es());
        a.put(AdStyleInfo.ExposeTagInfo.class, new bj());
        a.put(AdMatrixInfo.TemplateData.class, new eh());
        a.put(AppStatusRules.UploadConfig.class, new el());
        a.put(AdStyleInfo.ExtraDisplayInfo.class, new bk());
        a.put(SceneImpl.class, new Cdo());
        a.put(PhotoInfo.class, new cz());
        a.put(AggregatePageEntranceInfo.class, new y());
        a.put(z.a.class, new ce());
        a.put(AdInfo.AdBaseInfo.class, new g());
        a.put(AdInfo.AdConversionInfo.class, new i());
        a.put(SdkConfigData.TemplateConfigMap.class, new eg());
        a.put(DownloadParams.class, new bb());
        a.put(LiveInfo.User.class, new en());
        a.put(com.kwad.sdk.core.request.model.c.class, new ag());
        a.put(com.kwad.sdk.core.webview.kwai.i.class, new cq());
        a.put(w.a.class, new dn());
        a.put(SplashPreloadManager.PreLoadPara.class, new dg());
        a.put(com.kwad.sdk.core.webview.a.kwai.d.class, new ds());
        a.put(ReportAction.LiveLogInfo.class, new ch());
        a.put(VideoPlayerStatus.class, new ep());
        a.put(AdStyleInfo.PlayDetailInfo.class, new da());
        a.put(com.kwad.sdk.c.kwai.d.class, new cs());
        a.put(AdMatrixInfo.AdDataV2.class, new j());
        a.put(ABParams.class, new a());
        a.put(PhotoShareInfo.ShareUrlInfo.class, new dr());
        a.put(AdInfo.AdRewardInfo.class, new r());
        a.put(AdStyleInfo.PlayDetailInfo.DetailCommonInfo.class, new aw());
        a.put(AdInfo.AdTrackInfo.class, new v());
        a.put(com.kwad.sdk.core.response.model.a.class, new bg());
        a.put(com.kwad.sdk.core.request.model.j.class, new dy());
        a.put(AdStyleInfo.AdBrowseInfo.class, new h());
        a.put(AdTemplate.class, new u());
        a.put(h.b.class, new bd());
        a.put(AdStyleInfo.PlayEndInfo.HorizontalPatchAdInfo.class, new bu());
        a.put(PreloadData.class, new dh());
        a.put(p.a.class, new cu());
        a.put(HotspotInfo.class, new bv());
        a.put(AdInfo.class, new k());
        a.put(AdStyleInfo.PlayDetailInfo.PatchEcInfo.class, new cw());
        a.put(com.kwad.sdk.c.kwai.b.class, new ck());
        a.put(b.a.class, new d());
        a.put(HomeApkBannerData.class, new bt());
        a.put(LiveInfo.CoverUrlCdn.class, new av());
        a.put(AdMatrixInfo.BaseMatrixTemplate.class, new af());
        a.put(CommercialAction.TKPerformMsg.class, new eb());
        a.put(TKConfigResultData.a.class, new an());
        a.put(PhotoInfo.CoverInfo.class, new at());
        a.put(com.kwad.sdk.core.webview.a.kwai.c.class, new db());
        a.put(ActivityInfo.class, new e());
        a.put(PhotoInfo.TubeEpisode.class, new ej());
        a.put(AdMatrixInfo.BottomBannerInfo.class, new ah());
        a.put(AdInfo.PlayableStyleInfo.class, new dd());
        a.put(AdStyleInfo.PlayDetailInfo.DetailWebCardInfo.class, new ay());
        a.put(g.a.class, new ab());
        a.put(com.kwad.sdk.c.kwai.c.class, new cr());
        a.put(AdMatrixInfo.ShakeInfo.class, new dq());
        a.put(b.C2093b.class, new cj());
        a.put(AdMatrixInfo.class, new o());
        a.put(InstallActivateReminderConfigItem.InstallActivateReminderConfig.class, new cb());
        a.put(LiveInfo.User.HeadUrl.class, new bq());
        a.put(CouponStatusInfo.class, new ar());
        a.put(u.a.class, new ei());
        a.put(AdInfo.AdvertiserInfo.class, new x());
        a.put(PhotoAd.class, new cx());
    }

    public static com.kwad.sdk.core.d a(Class<? extends com.kwad.sdk.core.response.kwai.a> cls) {
        InterceptResult invokeL;
        Interceptable interceptable = $ic;
        return (interceptable == null || (invokeL = interceptable.invokeL(65537, null, cls)) == null) ? a.get(cls) : (com.kwad.sdk.core.d) invokeL.objValue;
    }
}
