package com.baidu.searchbox.account.contants;

import com.baidu.titan.sdk.runtime.FieldHolder;
import com.baidu.titan.sdk.runtime.InitContext;
import com.baidu.titan.sdk.runtime.Interceptable;
import com.baidu.titan.sdk.runtime.TitanRuntime;
/* loaded from: classes11.dex */
public class AccountConstants {
    public static /* synthetic */ Interceptable $ic = null;
    public static final int FAILURE = 2;
    public static final int FEMALE_CODE = 0;
    public static final String FEMALE_TEXT = "女";
    public static final String INTENT_EXTRA_KEY_LOGIN_SRC = "intent_extra_key_login_src";
    public static final String LOGIN_TYPE_NATIVE_SRC_ACCOUNTRECORD = "account_record";
    public static final String LOGIN_TYPE_NATIVE_SRC_ACOUNT_MANAGEMENT = "personal_account_management";
    public static final String LOGIN_TYPE_NATIVE_SRC_ADD_BOOKMARK_MANAGER_SYNC_LOGIN = "personal_bookmark_add";
    public static final String LOGIN_TYPE_NATIVE_SRC_ALL_FUNC_ORDER_CENTER = "personal_order";
    public static final String LOGIN_TYPE_NATIVE_SRC_BINDEMAIL = "account_bindemail";
    public static final String LOGIN_TYPE_NATIVE_SRC_BINDPHONE = "account_bindphone";
    public static final String LOGIN_TYPE_NATIVE_SRC_BOOKMARK_MANAGER_SYNC_LOGIN = "hudong_bookmark";
    public static final String LOGIN_TYPE_NATIVE_SRC_CARD_MANAGER_SYNC_LOGIN = "card_manager_sync_login";
    public static final String LOGIN_TYPE_NATIVE_SRC_COMIC = "comic";
    public static final String LOGIN_TYPE_NATIVE_SRC_COMMENT = "hudong_comment";
    public static final String LOGIN_TYPE_NATIVE_SRC_COMMENT_REPORT = "hudong_report";
    public static final String LOGIN_TYPE_NATIVE_SRC_COOKIEDIFFSYNC = "cookie_diff_sync";
    public static final String LOGIN_TYPE_NATIVE_SRC_COOKIELOGINSYNC = "cookie_login_sync";
    public static final String LOGIN_TYPE_NATIVE_SRC_COOKIELOGOUTSYNC = "cookie_logout_sync";
    public static final String LOGIN_TYPE_NATIVE_SRC_CREATE_GROUP = "hudong_socialgroup";
    public static final String LOGIN_TYPE_NATIVE_SRC_DELIVERY = "delivery";
    public static final String LOGIN_TYPE_NATIVE_SRC_DISCOVERY_FAVORITE = "discovery_favorite";
    public static final String LOGIN_TYPE_NATIVE_SRC_FEED_DISLIKE = "feed_dislike";
    public static final String LOGIN_TYPE_NATIVE_SRC_FEED_HEADER = "feed_header";
    public static final String LOGIN_TYPE_NATIVE_SRC_FOLLOW_CREATE_GROUP = "hudong_subgroup";
    public static final String LOGIN_TYPE_NATIVE_SRC_FOLLOW_PERSONAL_PROFILE = "hudong_personalprofile";
    public static final String LOGIN_TYPE_NATIVE_SRC_HISYNC = "search_his";
    public static final String LOGIN_TYPE_NATIVE_SRC_HOME_ADDCARD_SYNC_LOGIN = "home_addcard_sync_login";
    public static final String LOGIN_TYPE_NATIVE_SRC_HOME_HUTONG = "yunying_hutonghint";
    public static final String LOGIN_TYPE_NATIVE_SRC_HOME_LOGIN = "baiduhome_login";
    public static final String LOGIN_TYPE_NATIVE_SRC_HOME_SYNC_LOGIN = "home_sync_login";
    public static final String LOGIN_TYPE_NATIVE_SRC_IMPORT_ADDRESSBOOK = "hudong_subaddress";
    public static final String LOGIN_TYPE_NATIVE_SRC_IM_SUBSCRIBE = "im_subscribe";
    public static final String LOGIN_TYPE_NATIVE_SRC_INVOICE = "setting_invoice";
    public static final String LOGIN_TYPE_NATIVE_SRC_LIGHTAPP_BAIDU = "lightapp_baidu_";
    public static final String LOGIN_TYPE_NATIVE_SRC_LIGHTAPP_THIRD = "lightapp_third";
    public static final String LOGIN_TYPE_NATIVE_SRC_LIGHTBROWSER = "light_browser";
    public static final String LOGIN_TYPE_NATIVE_SRC_LIVESHOW = "liveshow";
    public static final String LOGIN_TYPE_NATIVE_SRC_MANAGE_SPACE = "manage_space";
    public static final String LOGIN_TYPE_NATIVE_SRC_MENU_PHONE = "menu_phone";
    public static final String LOGIN_TYPE_NATIVE_SRC_MENU_QQ = "menu_qq";
    public static final String LOGIN_TYPE_NATIVE_SRC_MENU_UNLOGIN = "menu_unlogin";
    public static final String LOGIN_TYPE_NATIVE_SRC_MENU_WECHAT = "menu_wechat";
    public static final String LOGIN_TYPE_NATIVE_SRC_MINIGAME_ADD = "minigame_add";
    public static final String LOGIN_TYPE_NATIVE_SRC_MINIGAME_CHAT = "minigame_chat";
    public static final String LOGIN_TYPE_NATIVE_SRC_MINIGAME_PERSONAL = "minigame_personal";
    public static final String LOGIN_TYPE_NATIVE_SRC_MINIGAME_START = "minigame_start";
    public static final String LOGIN_TYPE_NATIVE_SRC_MODIFYPWD = "account_modifypwd";
    public static final String LOGIN_TYPE_NATIVE_SRC_NICKNAME_POPUP = "hudong_nickname";
    public static final String LOGIN_TYPE_NATIVE_SRC_NOVEL = "novel";
    public static final String LOGIN_TYPE_NATIVE_SRC_ORDER_CENTER = "order_center";
    public static final String LOGIN_TYPE_NATIVE_SRC_PERSONAL_CHENGZHANG = "personal_chengzhang";
    public static final String LOGIN_TYPE_NATIVE_SRC_PERSONAL_HEADER = "personal_header";
    public static final String LOGIN_TYPE_NATIVE_SRC_PERSONAL_HEADER_FANS = "personal_fensi";
    public static final String LOGIN_TYPE_NATIVE_SRC_PERSONAL_HEADER_PHONE = "personal_headerphone";
    public static final String LOGIN_TYPE_NATIVE_SRC_PERSONAL_HEADER_QQ = "personal_headerqq";
    public static final String LOGIN_TYPE_NATIVE_SRC_PERSONAL_HEADER_SIGN = "personal_sign";
    public static final String LOGIN_TYPE_NATIVE_SRC_PERSONAL_HEADER_SINA = "personal_headerweibo";
    public static final String LOGIN_TYPE_NATIVE_SRC_PERSONAL_HEADER_UGC = "personal_dongtai";
    public static final String LOGIN_TYPE_NATIVE_SRC_PERSONAL_HEADER_WECHAT = "personal_headerwechat";
    public static final String LOGIN_TYPE_NATIVE_SRC_PERSONAL_HUTONG = "personal_hutonghint";
    public static final String LOGIN_TYPE_NATIVE_SRC_PERSONAL_JIFEN = "personal_jifen";
    public static final String LOGIN_TYPE_NATIVE_SRC_PERSONAL_WANGPAN_PLUGIN = "plugin_name_unknown_wangpan_default";
    public static final String LOGIN_TYPE_NATIVE_SRC_PLUGIN = "plugin";
    public static final String LOGIN_TYPE_NATIVE_SRC_QRCODE = "qrcode";
    public static final String LOGIN_TYPE_NATIVE_SRC_REDPACKET = "hudong_subpacket";
    public static final String LOGIN_TYPE_NATIVE_SRC_REPLY = "hudong_commentreply";
    public static final String LOGIN_TYPE_NATIVE_SRC_RN = "rn_baidu_";
    public static final String LOGIN_TYPE_NATIVE_SRC_SAPI_ACCOUNT_CENTER = "multi_account";
    public static final String LOGIN_TYPE_NATIVE_SRC_SETPORTRAIT = "account_setportrait";
    public static final String LOGIN_TYPE_NATIVE_SRC_SETTINGS_SYNC_LOGIN = "settings_sync_login";
    public static final String LOGIN_TYPE_NATIVE_SRC_SKIN_CENTER_LOGIN = "personal_skin";
    public static final String LOGIN_TYPE_NATIVE_SRC_SMS_NALOGIN = "sms_nalogin";
    public static final String LOGIN_TYPE_NATIVE_SRC_SOCIALITY_ADDFRIEND = "social_addfriend";
    public static final String LOGIN_TYPE_NATIVE_SRC_SSO = "sso";
    public static final String LOGIN_TYPE_NATIVE_SRC_STAR = "star";
    public static final String LOGIN_TYPE_NATIVE_SRC_SWAN_APP = "aiapps";
    public static final String LOGIN_TYPE_NATIVE_SRC_TICKET_COUPON = "ticket_coupon";
    public static final String LOGIN_TYPE_NATIVE_SRC_UNKNOWN = "unknown";
    public static final String LOGIN_TYPE_NATIVE_SRC_USER_INFO = "hudong_personalpage";
    public static final String LOGIN_TYPE_NATIVE_SRC_VERIRYPHONENUMBER = "verify_phone_num";
    public static final String LOGIN_TYPE_NATIVE_SRC_VIDEO = "account_video";
    public static final String LOGIN_TYPE_NATIVE_SRC_VIDEO_BARRAGE = "hudong_videobarrage";
    public static final String LOGIN_TYPE_NATIVE_SRC_VOTE = "hudong_vote";
    public static final String LOGIN_TYPE_NATIVE_SRC_WALLET = "wallet";
    public static final String LOGIN_TYPE_NATIVE_SRC_WEB = "web_";
    public static final String LOGIN_TYPE_NATIVE_SRC_WEBVIEW = "webview_baidu_";
    public static final String LOGIN_TYPE_NATIVE_SRC_WEB_SSO_LOGIN = "web_sso_login";
    public static final String LOGIN_TYPE_NATIVE_SRC_WENDA_PAGE = "feed_wenda";
    public static final String LOGIN_TYPE_NATIVE_SRC_YUN_DOWNLOAD = "wangpan_download";
    public static final String LOGIN_TYPE_NATIVE_SRC_YUN_PICTURE = "wangpan_picture";
    public static final String LOGIN_TYPE_QRCODE = "qrcode";
    public static final String LOGOUT_TYPE_NATIVE_SRC_BDUSS_EXPIRED = "bduss_expired";
    public static final String LOGOUT_TYPE_NATIVE_SRC_BEARBAR = "hudong_sena";
    public static final String LOGOUT_TYPE_NATIVE_SRC_CHECK_BDUSS_EXPIRED = "check_bduss_expired";
    public static final String LOGOUT_TYPE_NATIVE_SRC_GET_BDUSS_EXPIRED = "get_bduss_expired";
    public static final String LOGOUT_TYPE_NATIVE_SRC_MODIFYPWD = "modify_pwd";
    public static final String LOGOUT_TYPE_NATIVE_SRC_OTHERS = "others";
    public static final String LOGOUT_TYPE_NATIVE_SRC_PASSGATE_BDUSS_EXPIRED = "passgate_bduss_expired";
    public static final String LOGOUT_TYPE_NATIVE_SRC_PASSPORT_BDUSS_EXPIRED = "passport_bduss_expired";
    public static final String LOGOUT_TYPE_NATIVE_SRC_PLUGIN = "plugin";
    public static final String LOGOUT_TYPE_NATIVE_SRC_SAVE_BDUSS_EXPIRED = "save_bduss_expired";
    public static final String LOGOUT_TYPE_NATIVE_SRC_SETTINGS = "settings";
    public static final String LOGOUT_TYPE_NATIVE_SRC_STATUS_BDUSS_EXPIRED = "status_bduss_expired";
    public static final String LOGOUT_TYPE_NATIVE_SRC_SYNC = "account_sync";
    public static final String LOGOUT_TYPE_NATIVE_SRC_WEBVIEW_BDUSS_EXPIRED = "web_bduss_expired";
    public static final int MALE_CODE = 1;
    public static final String MALE_TEXT = "男";
    public static final int NO_NEWWORK = 1;
    public static final int SUCCESS = 0;
    public static final String SWITCH_CLOSE = "0";
    public static final String SWITCH_OPEN = "1";
    public static final long TYPE_MODIFY_ADDRESSLIST_SWITCH = 16777216;
    public static final long TYPE_MODIFY_BIRTHDAY = 1;
    public static final long TYPE_MODIFY_CITY = 4096;
    public static final long TYPE_MODIFY_EXT_FIELDS = 4294967296L;
    public static final long TYPE_MODIFY_GENDER = 16;
    public static final long TYPE_MODIFY_INTEREST_SWITCH = 1048576;
    public static final long TYPE_MODIFY_NICKNAME = 268435456;
    public static final long TYPE_MODIFY_NONE = 0;
    public static final long TYPE_MODIFY_SIGN = 256;
    public static final long TYPE_MODIFY_TEL_SWITCH = 65536;
    public transient /* synthetic */ FieldHolder $fh;

    public AccountConstants() {
        Interceptable interceptable = $ic;
        if (interceptable != null) {
            InitContext newInitContext = TitanRuntime.newInitContext();
            interceptable.invokeUnInit(65536, newInitContext);
            int i2 = newInitContext.flag;
            if ((i2 & 1) != 0) {
                int i3 = i2 & 2;
                newInitContext.thisArg = this;
                interceptable.invokeInitBody(65536, newInitContext);
            }
        }
    }
}
