package com.baidu.tieba;

import com.baidu.titan.sdk.runtime.ClassClinitInterceptable;
import com.baidu.titan.sdk.runtime.ClassClinitInterceptorStorage;
import com.baidu.titan.sdk.runtime.FieldHolder;
import com.baidu.titan.sdk.runtime.InitContext;
import com.baidu.titan.sdk.runtime.InterceptResult;
import com.baidu.titan.sdk.runtime.Interceptable;
import com.baidu.titan.sdk.runtime.TitanRuntime;
import java.util.HashMap;
/* loaded from: classes3.dex */
public class am6 extends pd5 {
    public static /* synthetic */ Interceptable $ic;
    public transient /* synthetic */ FieldHolder $fh;

    static {
        InterceptResult invokeClinit;
        ClassClinitInterceptable classClinitInterceptable = ClassClinitInterceptorStorage.$ic;
        if (classClinitInterceptable != null && (invokeClinit = classClinitInterceptable.invokeClinit(1947620031, "Lcom/baidu/tieba/am6;")) != null) {
            Interceptable interceptable = invokeClinit.interceptor;
            if (interceptable != null) {
                $ic = interceptable;
            }
            if ((invokeClinit.flags & 1) != 0) {
                classClinitInterceptable.invokePostClinit(1947620031, "Lcom/baidu/tieba/am6;");
                return;
            }
        }
        pd5.a.put("video_icon", Integer.valueOf((int) R.drawable.ico_link_video));
        HashMap<String, Integer> hashMap = pd5.a;
        Integer valueOf = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bc8);
        hashMap.put("image_emoticon", valueOf);
        HashMap<String, Integer> hashMap2 = pd5.a;
        Integer valueOf2 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bf9);
        hashMap2.put("image_emoticon2", valueOf2);
        HashMap<String, Integer> hashMap3 = pd5.a;
        Integer valueOf3 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c04);
        hashMap3.put("image_emoticon3", valueOf3);
        HashMap<String, Integer> hashMap4 = pd5.a;
        Integer valueOf4 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c0f);
        hashMap4.put("image_emoticon4", valueOf4);
        HashMap<String, Integer> hashMap5 = pd5.a;
        Integer valueOf5 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c1a);
        hashMap5.put("image_emoticon5", valueOf5);
        HashMap<String, Integer> hashMap6 = pd5.a;
        Integer valueOf6 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c1c);
        hashMap6.put("image_emoticon6", valueOf6);
        HashMap<String, Integer> hashMap7 = pd5.a;
        Integer valueOf7 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c26);
        hashMap7.put("image_emoticon7", valueOf7);
        HashMap<String, Integer> hashMap8 = pd5.a;
        Integer valueOf8 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c31);
        hashMap8.put("image_emoticon8", valueOf8);
        HashMap<String, Integer> hashMap9 = pd5.a;
        Integer valueOf9 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c3c);
        hashMap9.put("image_emoticon9", valueOf9);
        HashMap<String, Integer> hashMap10 = pd5.a;
        Integer valueOf10 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bc9);
        hashMap10.put("image_emoticon10", valueOf10);
        HashMap<String, Integer> hashMap11 = pd5.a;
        Integer valueOf11 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bd4);
        hashMap11.put("image_emoticon11", valueOf11);
        HashMap<String, Integer> hashMap12 = pd5.a;
        Integer valueOf12 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bdf);
        hashMap12.put("image_emoticon12", valueOf12);
        HashMap<String, Integer> hashMap13 = pd5.a;
        Integer valueOf13 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bea);
        hashMap13.put("image_emoticon13", valueOf13);
        HashMap<String, Integer> hashMap14 = pd5.a;
        Integer valueOf14 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bf3);
        hashMap14.put("image_emoticon14", valueOf14);
        HashMap<String, Integer> hashMap15 = pd5.a;
        Integer valueOf15 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bf4);
        hashMap15.put("image_emoticon15", valueOf15);
        pd5.a.put("image_emoticon16", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bf5));
        pd5.a.put("image_emoticon17", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bf6));
        pd5.a.put("image_emoticon18", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bf7));
        pd5.a.put("image_emoticon19", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bf8));
        pd5.a.put("image_emoticon20", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bfa));
        pd5.a.put("image_emoticon21", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bfb));
        pd5.a.put("image_emoticon22", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bfc));
        pd5.a.put("image_emoticon23", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bfd));
        pd5.a.put("image_emoticon24", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bfe));
        pd5.a.put("image_emoticon25", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bff));
        pd5.a.put("image_emoticon26", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c00));
        pd5.a.put("image_emoticon27", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c01));
        pd5.a.put("image_emoticon28", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c02));
        pd5.a.put("image_emoticon29", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c03));
        pd5.a.put("image_emoticon30", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c05));
        pd5.a.put("image_emoticon31", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c06));
        pd5.a.put("image_emoticon32", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c07));
        pd5.a.put("image_emoticon33", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c08));
        pd5.a.put("image_emoticon61", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c1d));
        pd5.a.put("image_emoticon62", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c1e));
        pd5.a.put("image_emoticon63", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c1f));
        pd5.a.put("image_emoticon64", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c20));
        pd5.a.put("image_emoticon65", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c21));
        pd5.a.put("image_emoticon66", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c22));
        pd5.a.put("image_emoticon67", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c23));
        pd5.a.put("image_emoticon68", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c24));
        pd5.a.put("image_emoticon69", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c25));
        pd5.a.put("image_emoticon70", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c27));
        pd5.a.put("image_emoticon71", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c28));
        pd5.a.put("image_emoticon72", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c29));
        pd5.a.put("image_emoticon73", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c2a));
        pd5.a.put("image_emoticon74", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c2b));
        pd5.a.put("image_emoticon75", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c2c));
        pd5.a.put("image_emoticon76", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c2d));
        pd5.a.put("image_emoticon85", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c37));
        pd5.a.put("image_emoticon86", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c38));
        pd5.a.put("image_emoticon87", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c39));
        pd5.a.put("image_emoticon88", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c3a));
        pd5.a.put("image_emoticon89", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c3b));
        pd5.a.put("image_emoticon90", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c3d));
        pd5.a.put("image_emoticon91", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c3e));
        pd5.a.put("image_emoticon92", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c3f));
        pd5.a.put("image_emoticon93", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c40));
        pd5.a.put("image_emoticon94", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c41));
        pd5.a.put("image_emoticon95", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c42));
        pd5.a.put("image_emoticon96", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c43));
        pd5.a.put("image_emoticon97", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c44));
        pd5.a.put("image_emoticon98", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c45));
        pd5.a.put("image_emoticon99", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c46));
        pd5.a.put("image_emoticon100", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bca));
        pd5.a.put("image_emoticon125", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080be5));
        pd5.a.put("image_emoticon126", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080be6));
        pd5.a.put("image_emoticon127", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080be7));
        pd5.a.put("image_emoticon129", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080be9));
        pd5.a.put("image_emoticon130", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080beb));
        pd5.a.put("image_emoticon131", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bec));
        pd5.a.put("image_emoticon132", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bed));
        pd5.a.put("image_emoticon128", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080be8));
        pd5.a.put("image_emoticon133", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bee));
        pd5.a.put("image_emoticon134", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bef));
        pd5.a.put("image_emoticon135", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bf0));
        pd5.a.put("image_emoticon136", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bf1));
        pd5.a.put("image_emoticon137", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bf2));
        pd5.a.put("shoubai_emoji_face_01", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080515));
        pd5.a.put("shoubai_emoji_face_02", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080516));
        pd5.a.put("shoubai_emoji_face_03", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080517));
        pd5.a.put("shoubai_emoji_face_04", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080518));
        pd5.a.put("shoubai_emoji_face_05", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080519));
        pd5.a.put("shoubai_emoji_face_06", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08051a));
        pd5.a.put("shoubai_emoji_face_07", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08051b));
        pd5.a.put("shoubai_emoji_face_08", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08051c));
        pd5.a.put("shoubai_emoji_face_09", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08051d));
        pd5.a.put("shoubai_emoji_face_10", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08051e));
        pd5.a.put("shoubai_emoji_face_11", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080526));
        pd5.a.put("shoubai_emoji_face_12", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080527));
        pd5.a.put("shoubai_emoji_face_13", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080528));
        pd5.a.put("shoubai_emoji_face_14", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080529));
        pd5.a.put("shoubai_emoji_face_15", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08052a));
        pd5.a.put("shoubai_emoji_face_16", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08052b));
        pd5.a.put("shoubai_emoji_face_17", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08052c));
        pd5.a.put("shoubai_emoji_face_18", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08052d));
        pd5.a.put("shoubai_emoji_face_19", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08052e));
        pd5.a.put("shoubai_emoji_face_20", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08052f));
        pd5.a.put("shoubai_emoji_face_21", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080530));
        pd5.a.put("shoubai_emoji_face_22", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080531));
        pd5.a.put("shoubai_emoji_face_23", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080532));
        pd5.a.put("shoubai_emoji_face_24", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080533));
        pd5.a.put("shoubai_emoji_face_25", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080534));
        pd5.a.put("shoubai_emoji_face_26", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080535));
        pd5.a.put("shoubai_emoji_face_27", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080536));
        pd5.a.put("shoubai_emoji_face_28", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080537));
        pd5.a.put("shoubai_emoji_face_29", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080538));
        pd5.a.put("shoubai_emoji_face_30", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080539));
        pd5.a.put("shoubai_emoji_face_31", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08053a));
        pd5.a.put("shoubai_emoji_face_32", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08053b));
        pd5.a.put("shoubai_emoji_face_33", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08053c));
        pd5.a.put("shoubai_emoji_face_34", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08053d));
        pd5.a.put("shoubai_emoji_face_35", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08053e));
        pd5.a.put("shoubai_emoji_face_36", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08053f));
        pd5.a.put("shoubai_emoji_face_37", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080540));
        pd5.a.put("shoubai_emoji_face_38", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080541));
        pd5.a.put("shoubai_emoji_face_39", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080542));
        pd5.a.put("shoubai_emoji_face_40", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080543));
        pd5.a.put("shoubai_emoji_face_41", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080544));
        pd5.a.put("shoubai_emoji_face_42", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080545));
        pd5.a.put("shoubai_emoji_face_43", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080546));
        pd5.a.put("shoubai_emoji_face_44", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080547));
        pd5.a.put("shoubai_emoji_face_45", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080548));
        pd5.a.put("shoubai_emoji_face_46", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080549));
        pd5.a.put("shoubai_emoji_face_47", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08054a));
        pd5.a.put("shoubai_emoji_face_48", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08054b));
        pd5.a.put("shoubai_emoji_face_49", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08054c));
        pd5.a.put("shoubai_emoji_face_50", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08054d));
        pd5.a.put("shoubai_emoji_face_51", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08054e));
        pd5.a.put("shoubai_emoji_face_52", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08054f));
        pd5.a.put("shoubai_emoji_face_53", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080550));
        pd5.a.put("shoubai_emoji_face_54", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080551));
        pd5.a.put("shoubai_emoji_face_55", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080552));
        pd5.a.put("shoubai_emoji_face_56", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080553));
        pd5.a.put("shoubai_emoji_face_57", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080554));
        pd5.a.put("shoubai_emoji_face_58", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080555));
        pd5.a.put("shoubai_emoji_face_59", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080556));
        pd5.a.put("shoubai_emoji_face_60", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080557));
        pd5.a.put("shoubai_emoji_face_61", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080558));
        pd5.a.put("shoubai_emoji_face_62", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080559));
        pd5.a.put("shoubai_emoji_face_63", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08055a));
        pd5.a.put("shoubai_emoji_face_64", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08055b));
        pd5.a.put("shoubai_emoji_face_65", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08055c));
        pd5.a.put("shoubai_emoji_face_66", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08055d));
        pd5.a.put("shoubai_emoji_face_67", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08055e));
        pd5.a.put("shoubai_emoji_face_68", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08055f));
        pd5.a.put("shoubai_emoji_face_69", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080560));
        pd5.a.put("shoubai_emoji_face_70", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080561));
        pd5.a.put("shoubai_emoji_face_71", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080562));
        pd5.a.put("shoubai_emoji_face_72", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080563));
        pd5.a.put("shoubai_emoji_face_73", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080564));
        pd5.a.put("shoubai_emoji_face_74", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080565));
        pd5.a.put("shoubai_emoji_face_75", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080566));
        pd5.a.put("shoubai_emoji_face_76", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080567));
        pd5.a.put("shoubai_emoji_face_77", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080568));
        pd5.a.put("shoubai_emoji_face_78", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080569));
        pd5.a.put("shoubai_emoji_face_79", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08056a));
        pd5.a.put("shoubai_emoji_face_80", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08056b));
        pd5.a.put("shoubai_emoji_face_81", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08056c));
        pd5.a.put("shoubai_emoji_face_82", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08056d));
        pd5.a.put("shoubai_emoji_face_83", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08056e));
        pd5.a.put("shoubai_emoji_face_84", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08056f));
        pd5.a.put("shoubai_emoji_face_85", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080570));
        pd5.a.put("shoubai_emoji_face_86", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080571));
        pd5.a.put("shoubai_emoji_face_87", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080572));
        pd5.a.put("shoubai_emoji_face_88", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080573));
        pd5.a.put("shoubai_emoji_face_89", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080574));
        pd5.a.put("shoubai_emoji_face_90", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080575));
        pd5.a.put("shoubai_emoji_face_91", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080576));
        pd5.a.put("shoubai_emoji_face_92", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080577));
        pd5.a.put("shoubai_emoji_face_93", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080578));
        pd5.a.put("shoubai_emoji_face_94", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080579));
        pd5.a.put("shoubai_emoji_face_95", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08057a));
        pd5.a.put("shoubai_emoji_face_96", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08057b));
        pd5.a.put("shoubai_emoji_face_97", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08057c));
        pd5.a.put("shoubai_emoji_face_98", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08057d));
        pd5.a.put("shoubai_emoji_face_99", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08057e));
        pd5.a.put("shoubai_emoji_face_100", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08051f));
        pd5.a.put("shoubai_emoji_face_101", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080520));
        pd5.a.put("shoubai_emoji_face_102", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080521));
        pd5.a.put("shoubai_emoji_face_103", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080522));
        pd5.a.put("shoubai_emoji_face_104", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080523));
        pd5.a.put("shoubai_emoji_face_105", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080524));
        pd5.a.put("shoubai_emoji_face_106", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080525));
        pd5.a.put("bearchildren_01", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080226));
        pd5.a.put("bearchildren_02", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080227));
        pd5.a.put("bearchildren_03", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080228));
        pd5.a.put("bearchildren_04", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080229));
        pd5.a.put("bearchildren_05", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08022a));
        pd5.a.put("bearchildren_06", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08022b));
        pd5.a.put("bearchildren_07", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08022c));
        pd5.a.put("bearchildren_08", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08022d));
        pd5.a.put("bearchildren_09", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08022e));
        pd5.a.put("bearchildren_10", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08022f));
        pd5.a.put("bearchildren_11", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080230));
        pd5.a.put("bearchildren_12", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080231));
        pd5.a.put("bearchildren_13", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080232));
        pd5.a.put("bearchildren_14", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080233));
        pd5.a.put("bearchildren_15", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080234));
        pd5.a.put("bearchildren_16", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080235));
        pd5.a.put("bearchildren_17", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080236));
        pd5.a.put("bearchildren_18", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080237));
        pd5.a.put("bearchildren_19", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080238));
        pd5.a.put("bearchildren_20", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080239));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080be5));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080be9));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bed));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bf0));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bef));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bf2));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bf1));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bec));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080beb));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080be7));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080be6));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080be8));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c46));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bee));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c43));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c45));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c3b));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c39));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c41));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c37));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c3d));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c40));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c3f));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c38));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c3e));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c3a));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c42));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bca));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c44));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c06));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bfd));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bfb));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bf7));
        pd5.b.add(0, valueOf14);
        pd5.b.add(0, valueOf7);
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c00));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c2d));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c2c));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c2b));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bf6));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c2a));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c29));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c03));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c07));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bf8));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c28));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c27));
        pd5.b.add(0, valueOf15);
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c25));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c01));
        pd5.b.add(0, valueOf4);
        pd5.b.add(0, valueOf5);
        pd5.b.add(0, valueOf11);
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bf5));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c05));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c08));
        pd5.b.add(0, valueOf13);
        pd5.b.add(0, valueOf9);
        pd5.b.add(0, valueOf10);
        pd5.b.add(0, valueOf8);
        pd5.b.add(0, valueOf6);
        pd5.b.add(0, valueOf12);
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c24));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bff));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c23));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c02));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c22));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bfa));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bfc));
        pd5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bfe));
        pd5.b.add(0, valueOf3);
        pd5.b.add(0, valueOf2);
        pd5.b.add(0, valueOf);
        pd5.c.put("#(呵呵)", valueOf);
        pd5.c.put("#(哈哈)", valueOf2);
        pd5.c.put("#(吐舌)", valueOf3);
        pd5.c.put("#(啊)", valueOf4);
        pd5.c.put("#(酷)", valueOf5);
        pd5.c.put("#(怒)", valueOf6);
        pd5.c.put("#(开心)", valueOf7);
        pd5.c.put("#(汗)", valueOf8);
        pd5.c.put("#(泪)", valueOf9);
        pd5.c.put("#(黑线)", valueOf10);
        pd5.c.put("#(鄙视)", valueOf11);
        pd5.c.put("#(不高兴)", valueOf12);
        pd5.c.put("#(真棒)", valueOf13);
        pd5.c.put("#(钱)", valueOf14);
        pd5.c.put("#(疑问)", valueOf15);
        pd5.c.put("#(阴险)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bf5));
        pd5.c.put("#(吐)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bf6));
        pd5.c.put("#(咦)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bf7));
        pd5.c.put("#(委屈)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bf8));
        pd5.c.put("#(花心)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bfa));
        pd5.c.put("#(呼~)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bfb));
        pd5.c.put("#(笑眼)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bfc));
        pd5.c.put("#(冷)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bfd));
        pd5.c.put("#(太开心)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bfe));
        pd5.c.put("#(滑稽)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bff));
        pd5.c.put("#(勉强)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c00));
        pd5.c.put("#(狂汗)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c01));
        pd5.c.put("#(乖)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c02));
        pd5.c.put("#(睡觉)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c03));
        pd5.c.put("#(惊哭)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c05));
        pd5.c.put("#(升起)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c06));
        pd5.c.put("#(惊讶)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c07));
        pd5.c.put("#(喷)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c08));
        pd5.c.put("#(哼)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c1d));
        pd5.c.put("#(吃瓜)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c1e));
        pd5.c.put("#(扔便便)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c1f));
        pd5.c.put("#(惊恐)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c20));
        pd5.c.put("#(哎呦)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c21));
        pd5.c.put("#(小乖)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c22));
        pd5.c.put("#(捂嘴笑)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c23));
        pd5.c.put("#(你懂的)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c24));
        pd5.c.put("#(what)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c25));
        pd5.c.put("#(酸爽)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c27));
        pd5.c.put("#(呀咩爹)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c28));
        pd5.c.put("#(笑尿)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c29));
        pd5.c.put("#(挖鼻)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c2a));
        pd5.c.put("#(犀利)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c2b));
        pd5.c.put("#(小红脸)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c2c));
        pd5.c.put("#(懒得理)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c2d));
        pd5.c.put("#(暗中观察)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c37));
        pd5.c.put("#(吃瓜)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c38));
        pd5.c.put("#(喝酒)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c39));
        pd5.c.put("#(嘿嘿嘿)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c3a));
        pd5.c.put("#(噗)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c3b));
        pd5.c.put("#(困成狗)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c3d));
        pd5.c.put("#(微微一笑)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c3e));
        pd5.c.put("#(托腮)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c3f));
        pd5.c.put("#(摊手)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c40));
        pd5.c.put("#(柯基暗中观察)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c41));
        pd5.c.put("#(欢呼)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c42));
        pd5.c.put("#(炸药)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c43));
        pd5.c.put("#(香槟)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bee));
        pd5.c.put("#(突然兴奋)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c44));
        pd5.c.put("#(紧张)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c45));
        pd5.c.put("#(黑头瞪眼)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080c46));
        pd5.c.put("#(黑头高兴)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bca));
        pd5.c.put("#(奥特曼)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080be5));
        pd5.c.put("#(不听)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080be6));
        pd5.c.put("#(干饭)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080be7));
        pd5.c.put("#(菜狗)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080be9));
        pd5.c.put("#(老虎)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080beb));
        pd5.c.put("#(嗷呜)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bec));
        pd5.c.put("#(烟花)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bed));
        pd5.c.put("#(望远镜)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080be8));
        pd5.c.put("#(文字啊)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bef));
        pd5.c.put("#(文字对)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bf0));
        pd5.c.put("#(鼠1)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bf1));
        pd5.c.put("#(鼠2)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080bf2));
        pd5.c.put("[微笑]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080515));
        pd5.c.put("[开心]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080516));
        pd5.c.put("[期待]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080517));
        pd5.c.put("[大笑]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080518));
        pd5.c.put("[鼓掌]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080519));
        pd5.c.put("[悠闲]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08051a));
        pd5.c.put("[笑哭]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08051b));
        pd5.c.put("[不要啊]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08051c));
        pd5.c.put("[啊]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08051d));
        pd5.c.put("[哟]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08051e));
        pd5.c.put("[汗]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080526));
        pd5.c.put("[抠鼻]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080527));
        pd5.c.put("[哼]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080528));
        pd5.c.put("[发怒]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080529));
        pd5.c.put("[委屈]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08052a));
        pd5.c.put("[不高兴]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08052b));
        pd5.c.put("[囧]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08052c));
        pd5.c.put("[惊哭]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08052d));
        pd5.c.put("[大哭]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08052e));
        pd5.c.put("[流泪]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08052f));
        pd5.c.put("[害羞]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080530));
        pd5.c.put("[亲亲]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080531));
        pd5.c.put("[色]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080532));
        pd5.c.put("[舔屏]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080533));
        pd5.c.put("[得意]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080534));
        pd5.c.put("[疑问]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080535));
        pd5.c.put("[晕]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080536));
        pd5.c.put("[大哈]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080537));
        pd5.c.put("[二哈]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080538));
        pd5.c.put("[三哈]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080539));
        pd5.c.put("[白眼]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08053a));
        pd5.c.put("[阴险]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08053b));
        pd5.c.put("[你懂的]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08053c));
        pd5.c.put("[偷笑]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08053d));
        pd5.c.put("[睡觉]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08053e));
        pd5.c.put("[哈欠]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08053f));
        pd5.c.put("[再见]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080540));
        pd5.c.put("[鄙视]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080541));
        pd5.c.put("[抓狂]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080542));
        pd5.c.put("[咒骂]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080543));
        pd5.c.put("[衰]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080544));
        pd5.c.put("[骷髅]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080545));
        pd5.c.put("[嘘]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080546));
        pd5.c.put("[闭嘴]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080547));
        pd5.c.put("[呆]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080548));
        pd5.c.put("[什么鬼]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080549));
        pd5.c.put("[吐]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08054a));
        pd5.c.put("[已阅]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08054b));
        pd5.c.put("[同上]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08054c));
        pd5.c.put("[友军]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08054d));
        pd5.c.put("[爱钱]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08054e));
        pd5.c.put("[Freestyle]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08054f));
        pd5.c.put("[国宝]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080550));
        pd5.c.put("[羊驼]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080551));
        pd5.c.put("[鲜花]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080552));
        pd5.c.put("[中国加油]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080553));
        pd5.c.put("[庆祝]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080554));
        pd5.c.put("[生日蛋糕]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080555));
        pd5.c.put("[MicDrop]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080556));
        pd5.c.put("[赞同]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080557));
        pd5.c.put("[药丸]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080558));
        pd5.c.put("[蜡烛]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080559));
        pd5.c.put("[鸡蛋]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08055a));
        pd5.c.put("[浪]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08055b));
        pd5.c.put("[打call]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08055c));
        pd5.c.put("[尬笑]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08055d));
        pd5.c.put("[坏笑]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08055e));
        pd5.c.put("[没眼看]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08055f));
        pd5.c.put("[嘿哈]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080560));
        pd5.c.put("[前面的别走]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080561));
        pd5.c.put("[滑稽]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080562));
        pd5.c.put("[捂脸]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080563));
        pd5.c.put("[左捂脸]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080564));
        pd5.c.put("[666]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080565));
        pd5.c.put("[2018]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080566));
        pd5.c.put("[福]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080567));
        pd5.c.put("[红包]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080568));
        pd5.c.put("[鞭炮]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080569));
        pd5.c.put("[财神]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08056a));
        pd5.c.put("[饺子]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08056b));
        pd5.c.put("[车票]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08056c));
        pd5.c.put("[火车]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08056d));
        pd5.c.put("[飞机]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08056e));
        pd5.c.put("[射门]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08056f));
        pd5.c.put("[红牌]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080570));
        pd5.c.put("[黄牌]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080571));
        pd5.c.put("[哨子]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080572));
        pd5.c.put("[比分]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080573));
        pd5.c.put("[啤酒]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080574));
        pd5.c.put("[足球]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080575));
        pd5.c.put("[大力神杯]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080576));
        pd5.c.put("[锦鲤]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080577));
        pd5.c.put("[2019]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080578));
        pd5.c.put("[猪年]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080579));
        pd5.c.put("[双手鼓掌]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08057a));
        pd5.c.put("[火焰]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08057b));
        pd5.c.put("[祈福]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08057c));
        pd5.c.put("[亲吻]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08057d));
        pd5.c.put("[天使]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08057e));
        pd5.c.put("[樱花]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08051f));
        pd5.c.put("[加油]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080520));
        pd5.c.put("[泡泡枪]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080521));
        pd5.c.put("[气球]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080522));
        pd5.c.put("[棒棒糖]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080523));
        pd5.c.put("[小黄鸭]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080524));
        pd5.c.put("[粽子]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080525));
        pd5.c.put("#(熊-88)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080226));
        pd5.c.put("#(熊-HI)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080227));
        pd5.c.put("#(熊-人艰不拆)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080228));
        pd5.c.put("#(熊-啥)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080229));
        pd5.c.put("#(熊-大哭)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08022a));
        pd5.c.put("#(熊-失落)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08022b));
        pd5.c.put("#(熊-怒赞)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08022c));
        pd5.c.put("#(熊-惊呆了)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08022d));
        pd5.c.put("#(熊-李菊福)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08022e));
        pd5.c.put("#(熊-来信砍)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08022f));
        pd5.c.put("#(熊-欢迎入群)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080230));
        pd5.c.put("#(熊-牛闪闪)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080231));
        pd5.c.put("#(熊-生日快乐)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080232));
        pd5.c.put("#(熊-石化)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080233));
        pd5.c.put("#(熊-羞羞哒)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080234));
        pd5.c.put("#(熊-肥皂必杀)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080235));
        pd5.c.put("#(熊-谢谢你)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080236));
        pd5.c.put("#(熊-跳舞)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080237));
        pd5.c.put("#(熊-霹雳舞)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080238));
        pd5.c.put("#(熊-鼓掌)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080239));
    }

    public am6() {
        Interceptable interceptable = $ic;
        if (interceptable != null) {
            InitContext newInitContext = TitanRuntime.newInitContext();
            interceptable.invokeUnInit(65537, newInitContext);
            int i = newInitContext.flag;
            if ((i & 1) != 0) {
                int i2 = i & 2;
                newInitContext.thisArg = this;
                interceptable.invokeInitBody(65537, newInitContext);
            }
        }
    }
}
