package com.baidu.tieba;

import com.baidu.titan.sdk.runtime.ClassClinitInterceptable;
import com.baidu.titan.sdk.runtime.ClassClinitInterceptorStorage;
import com.baidu.titan.sdk.runtime.FieldHolder;
import com.baidu.titan.sdk.runtime.InitContext;
import com.baidu.titan.sdk.runtime.InterceptResult;
import com.baidu.titan.sdk.runtime.Interceptable;
import com.baidu.titan.sdk.runtime.TitanRuntime;
import java.util.HashMap;
/* loaded from: classes5.dex */
public class gs6 extends jf5 {
    public static /* synthetic */ Interceptable $ic;
    public transient /* synthetic */ FieldHolder $fh;

    static {
        InterceptResult invokeClinit;
        ClassClinitInterceptable classClinitInterceptable = ClassClinitInterceptorStorage.$ic;
        if (classClinitInterceptable != null && (invokeClinit = classClinitInterceptable.invokeClinit(1947804543, "Lcom/baidu/tieba/gs6;")) != null) {
            Interceptable interceptable = invokeClinit.interceptor;
            if (interceptable != null) {
                $ic = interceptable;
            }
            if ((invokeClinit.flags & 1) != 0) {
                classClinitInterceptable.invokePostClinit(1947804543, "Lcom/baidu/tieba/gs6;");
                return;
            }
        }
        jf5.a.put("video_icon", Integer.valueOf((int) R.drawable.ico_link_video));
        HashMap<String, Integer> hashMap = jf5.a;
        Integer valueOf = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d1f);
        hashMap.put("image_emoticon", valueOf);
        HashMap<String, Integer> hashMap2 = jf5.a;
        Integer valueOf2 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d50);
        hashMap2.put("image_emoticon2", valueOf2);
        HashMap<String, Integer> hashMap3 = jf5.a;
        Integer valueOf3 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d5b);
        hashMap3.put("image_emoticon3", valueOf3);
        HashMap<String, Integer> hashMap4 = jf5.a;
        Integer valueOf4 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d66);
        hashMap4.put("image_emoticon4", valueOf4);
        HashMap<String, Integer> hashMap5 = jf5.a;
        Integer valueOf5 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d71);
        hashMap5.put("image_emoticon5", valueOf5);
        HashMap<String, Integer> hashMap6 = jf5.a;
        Integer valueOf6 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d73);
        hashMap6.put("image_emoticon6", valueOf6);
        HashMap<String, Integer> hashMap7 = jf5.a;
        Integer valueOf7 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d7d);
        hashMap7.put("image_emoticon7", valueOf7);
        HashMap<String, Integer> hashMap8 = jf5.a;
        Integer valueOf8 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d88);
        hashMap8.put("image_emoticon8", valueOf8);
        HashMap<String, Integer> hashMap9 = jf5.a;
        Integer valueOf9 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d93);
        hashMap9.put("image_emoticon9", valueOf9);
        HashMap<String, Integer> hashMap10 = jf5.a;
        Integer valueOf10 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d20);
        hashMap10.put("image_emoticon10", valueOf10);
        HashMap<String, Integer> hashMap11 = jf5.a;
        Integer valueOf11 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d2b);
        hashMap11.put("image_emoticon11", valueOf11);
        HashMap<String, Integer> hashMap12 = jf5.a;
        Integer valueOf12 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d36);
        hashMap12.put("image_emoticon12", valueOf12);
        HashMap<String, Integer> hashMap13 = jf5.a;
        Integer valueOf13 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d41);
        hashMap13.put("image_emoticon13", valueOf13);
        HashMap<String, Integer> hashMap14 = jf5.a;
        Integer valueOf14 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d4a);
        hashMap14.put("image_emoticon14", valueOf14);
        HashMap<String, Integer> hashMap15 = jf5.a;
        Integer valueOf15 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d4b);
        hashMap15.put("image_emoticon15", valueOf15);
        jf5.a.put("image_emoticon16", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d4c));
        jf5.a.put("image_emoticon17", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d4d));
        jf5.a.put("image_emoticon18", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d4e));
        jf5.a.put("image_emoticon19", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d4f));
        jf5.a.put("image_emoticon20", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d51));
        jf5.a.put("image_emoticon21", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d52));
        jf5.a.put("image_emoticon22", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d53));
        jf5.a.put("image_emoticon23", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d54));
        jf5.a.put("image_emoticon24", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d55));
        jf5.a.put("image_emoticon25", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d56));
        jf5.a.put("image_emoticon26", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d57));
        jf5.a.put("image_emoticon27", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d58));
        jf5.a.put("image_emoticon28", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d59));
        jf5.a.put("image_emoticon29", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d5a));
        jf5.a.put("image_emoticon30", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d5c));
        jf5.a.put("image_emoticon31", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d5d));
        jf5.a.put("image_emoticon32", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d5e));
        jf5.a.put("image_emoticon33", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d5f));
        jf5.a.put("image_emoticon61", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d74));
        jf5.a.put("image_emoticon62", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d75));
        jf5.a.put("image_emoticon63", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d76));
        jf5.a.put("image_emoticon64", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d77));
        jf5.a.put("image_emoticon65", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d78));
        jf5.a.put("image_emoticon66", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d79));
        jf5.a.put("image_emoticon67", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d7a));
        jf5.a.put("image_emoticon68", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d7b));
        jf5.a.put("image_emoticon69", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d7c));
        jf5.a.put("image_emoticon70", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d7e));
        jf5.a.put("image_emoticon71", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d7f));
        jf5.a.put("image_emoticon72", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d80));
        jf5.a.put("image_emoticon73", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d81));
        jf5.a.put("image_emoticon74", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d82));
        jf5.a.put("image_emoticon75", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d83));
        jf5.a.put("image_emoticon76", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d84));
        jf5.a.put("image_emoticon85", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d8e));
        jf5.a.put("image_emoticon86", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d8f));
        jf5.a.put("image_emoticon87", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d90));
        jf5.a.put("image_emoticon88", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d91));
        jf5.a.put("image_emoticon89", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d92));
        jf5.a.put("image_emoticon90", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d94));
        jf5.a.put("image_emoticon91", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d95));
        jf5.a.put("image_emoticon92", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d96));
        jf5.a.put("image_emoticon93", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d97));
        jf5.a.put("image_emoticon94", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d98));
        jf5.a.put("image_emoticon95", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d99));
        jf5.a.put("image_emoticon96", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d9a));
        jf5.a.put("image_emoticon97", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d9b));
        jf5.a.put("image_emoticon98", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d9c));
        jf5.a.put("image_emoticon99", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d9d));
        jf5.a.put("image_emoticon100", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d21));
        jf5.a.put("image_emoticon125", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d3c));
        jf5.a.put("image_emoticon126", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d3d));
        jf5.a.put("image_emoticon127", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d3e));
        jf5.a.put("image_emoticon129", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d40));
        jf5.a.put("image_emoticon130", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d42));
        jf5.a.put("image_emoticon131", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d43));
        jf5.a.put("image_emoticon132", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d44));
        jf5.a.put("image_emoticon128", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d3f));
        jf5.a.put("image_emoticon133", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d45));
        jf5.a.put("image_emoticon134", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d46));
        jf5.a.put("image_emoticon135", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d47));
        jf5.a.put("image_emoticon136", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d48));
        jf5.a.put("image_emoticon137", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d49));
        jf5.a.put("shoubai_emoji_face_01", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f0805fd));
        jf5.a.put("shoubai_emoji_face_02", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f0805fe));
        jf5.a.put("shoubai_emoji_face_03", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f0805ff));
        jf5.a.put("shoubai_emoji_face_04", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080600));
        jf5.a.put("shoubai_emoji_face_05", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080601));
        jf5.a.put("shoubai_emoji_face_06", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080602));
        jf5.a.put("shoubai_emoji_face_07", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080603));
        jf5.a.put("shoubai_emoji_face_08", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080604));
        jf5.a.put("shoubai_emoji_face_09", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080605));
        jf5.a.put("shoubai_emoji_face_10", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080606));
        jf5.a.put("shoubai_emoji_face_11", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08060e));
        jf5.a.put("shoubai_emoji_face_12", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08060f));
        jf5.a.put("shoubai_emoji_face_13", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080610));
        jf5.a.put("shoubai_emoji_face_14", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080611));
        jf5.a.put("shoubai_emoji_face_15", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080612));
        jf5.a.put("shoubai_emoji_face_16", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080613));
        jf5.a.put("shoubai_emoji_face_17", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080614));
        jf5.a.put("shoubai_emoji_face_18", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080615));
        jf5.a.put("shoubai_emoji_face_19", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080616));
        jf5.a.put("shoubai_emoji_face_20", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080617));
        jf5.a.put("shoubai_emoji_face_21", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080618));
        jf5.a.put("shoubai_emoji_face_22", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080619));
        jf5.a.put("shoubai_emoji_face_23", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08061a));
        jf5.a.put("shoubai_emoji_face_24", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08061b));
        jf5.a.put("shoubai_emoji_face_25", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08061c));
        jf5.a.put("shoubai_emoji_face_26", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08061d));
        jf5.a.put("shoubai_emoji_face_27", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08061e));
        jf5.a.put("shoubai_emoji_face_28", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08061f));
        jf5.a.put("shoubai_emoji_face_29", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080620));
        jf5.a.put("shoubai_emoji_face_30", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080621));
        jf5.a.put("shoubai_emoji_face_31", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080622));
        jf5.a.put("shoubai_emoji_face_32", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080623));
        jf5.a.put("shoubai_emoji_face_33", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080624));
        jf5.a.put("shoubai_emoji_face_34", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080625));
        jf5.a.put("shoubai_emoji_face_35", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080626));
        jf5.a.put("shoubai_emoji_face_36", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080627));
        jf5.a.put("shoubai_emoji_face_37", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080628));
        jf5.a.put("shoubai_emoji_face_38", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080629));
        jf5.a.put("shoubai_emoji_face_39", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08062a));
        jf5.a.put("shoubai_emoji_face_40", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08062b));
        jf5.a.put("shoubai_emoji_face_41", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08062c));
        jf5.a.put("shoubai_emoji_face_42", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08062d));
        jf5.a.put("shoubai_emoji_face_43", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08062e));
        jf5.a.put("shoubai_emoji_face_44", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08062f));
        jf5.a.put("shoubai_emoji_face_45", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080630));
        jf5.a.put("shoubai_emoji_face_46", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080631));
        jf5.a.put("shoubai_emoji_face_47", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080632));
        jf5.a.put("shoubai_emoji_face_48", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080633));
        jf5.a.put("shoubai_emoji_face_49", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080634));
        jf5.a.put("shoubai_emoji_face_50", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080635));
        jf5.a.put("shoubai_emoji_face_51", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080636));
        jf5.a.put("shoubai_emoji_face_52", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080637));
        jf5.a.put("shoubai_emoji_face_53", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080638));
        jf5.a.put("shoubai_emoji_face_54", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080639));
        jf5.a.put("shoubai_emoji_face_55", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08063a));
        jf5.a.put("shoubai_emoji_face_56", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08063b));
        jf5.a.put("shoubai_emoji_face_57", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08063c));
        jf5.a.put("shoubai_emoji_face_58", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08063d));
        jf5.a.put("shoubai_emoji_face_59", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08063e));
        jf5.a.put("shoubai_emoji_face_60", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08063f));
        jf5.a.put("shoubai_emoji_face_61", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080640));
        jf5.a.put("shoubai_emoji_face_62", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080641));
        jf5.a.put("shoubai_emoji_face_63", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080642));
        jf5.a.put("shoubai_emoji_face_64", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080643));
        jf5.a.put("shoubai_emoji_face_65", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080644));
        jf5.a.put("shoubai_emoji_face_66", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080645));
        jf5.a.put("shoubai_emoji_face_67", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080646));
        jf5.a.put("shoubai_emoji_face_68", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080647));
        jf5.a.put("shoubai_emoji_face_69", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080648));
        jf5.a.put("shoubai_emoji_face_70", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080649));
        jf5.a.put("shoubai_emoji_face_71", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08064a));
        jf5.a.put("shoubai_emoji_face_72", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08064b));
        jf5.a.put("shoubai_emoji_face_73", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08064c));
        jf5.a.put("shoubai_emoji_face_74", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08064d));
        jf5.a.put("shoubai_emoji_face_75", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08064e));
        jf5.a.put("shoubai_emoji_face_76", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08064f));
        jf5.a.put("shoubai_emoji_face_77", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080650));
        jf5.a.put("shoubai_emoji_face_78", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080651));
        jf5.a.put("shoubai_emoji_face_79", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080652));
        jf5.a.put("shoubai_emoji_face_80", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080653));
        jf5.a.put("shoubai_emoji_face_81", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080654));
        jf5.a.put("shoubai_emoji_face_82", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080655));
        jf5.a.put("shoubai_emoji_face_83", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080656));
        jf5.a.put("shoubai_emoji_face_84", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080657));
        jf5.a.put("shoubai_emoji_face_85", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080658));
        jf5.a.put("shoubai_emoji_face_86", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080659));
        jf5.a.put("shoubai_emoji_face_87", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08065a));
        jf5.a.put("shoubai_emoji_face_88", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08065b));
        jf5.a.put("shoubai_emoji_face_89", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08065c));
        jf5.a.put("shoubai_emoji_face_90", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08065d));
        jf5.a.put("shoubai_emoji_face_91", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08065e));
        jf5.a.put("shoubai_emoji_face_92", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08065f));
        jf5.a.put("shoubai_emoji_face_93", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080660));
        jf5.a.put("shoubai_emoji_face_94", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080661));
        jf5.a.put("shoubai_emoji_face_95", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080662));
        jf5.a.put("shoubai_emoji_face_96", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080663));
        jf5.a.put("shoubai_emoji_face_97", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080664));
        jf5.a.put("shoubai_emoji_face_98", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080665));
        jf5.a.put("shoubai_emoji_face_99", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080666));
        jf5.a.put("shoubai_emoji_face_100", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080607));
        jf5.a.put("shoubai_emoji_face_101", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080608));
        jf5.a.put("shoubai_emoji_face_102", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080609));
        jf5.a.put("shoubai_emoji_face_103", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08060a));
        jf5.a.put("shoubai_emoji_face_104", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08060b));
        jf5.a.put("shoubai_emoji_face_105", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08060c));
        jf5.a.put("shoubai_emoji_face_106", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08060d));
        jf5.a.put("bearchildren_01", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080270));
        jf5.a.put("bearchildren_02", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080271));
        jf5.a.put("bearchildren_03", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080272));
        jf5.a.put("bearchildren_04", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080273));
        jf5.a.put("bearchildren_05", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080274));
        jf5.a.put("bearchildren_06", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080275));
        jf5.a.put("bearchildren_07", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080276));
        jf5.a.put("bearchildren_08", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080277));
        jf5.a.put("bearchildren_09", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080278));
        jf5.a.put("bearchildren_10", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080279));
        jf5.a.put("bearchildren_11", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08027a));
        jf5.a.put("bearchildren_12", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08027b));
        jf5.a.put("bearchildren_13", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08027c));
        jf5.a.put("bearchildren_14", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08027d));
        jf5.a.put("bearchildren_15", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08027e));
        jf5.a.put("bearchildren_16", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08027f));
        jf5.a.put("bearchildren_17", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080280));
        jf5.a.put("bearchildren_18", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080281));
        jf5.a.put("bearchildren_19", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080282));
        jf5.a.put("bearchildren_20", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080283));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d3c));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d40));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d44));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d47));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d46));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d49));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d48));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d43));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d42));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d3e));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d3d));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d3f));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d9d));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d45));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d9a));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d9c));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d92));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d90));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d98));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d8e));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d94));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d97));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d96));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d8f));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d95));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d91));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d99));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d21));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d9b));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d5d));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d54));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d52));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d4e));
        jf5.b.add(0, valueOf14);
        jf5.b.add(0, valueOf7);
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d57));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d84));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d83));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d82));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d4d));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d81));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d80));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d5a));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d5e));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d4f));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d7f));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d7e));
        jf5.b.add(0, valueOf15);
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d7c));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d58));
        jf5.b.add(0, valueOf4);
        jf5.b.add(0, valueOf5);
        jf5.b.add(0, valueOf11);
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d4c));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d5c));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d5f));
        jf5.b.add(0, valueOf13);
        jf5.b.add(0, valueOf9);
        jf5.b.add(0, valueOf10);
        jf5.b.add(0, valueOf8);
        jf5.b.add(0, valueOf6);
        jf5.b.add(0, valueOf12);
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d7b));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d56));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d7a));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d59));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d79));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d51));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d53));
        jf5.b.add(0, Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d55));
        jf5.b.add(0, valueOf3);
        jf5.b.add(0, valueOf2);
        jf5.b.add(0, valueOf);
        jf5.c.put("#(呵呵)", valueOf);
        jf5.c.put("#(哈哈)", valueOf2);
        jf5.c.put("#(吐舌)", valueOf3);
        jf5.c.put("#(啊)", valueOf4);
        jf5.c.put("#(酷)", valueOf5);
        jf5.c.put("#(怒)", valueOf6);
        jf5.c.put("#(开心)", valueOf7);
        jf5.c.put("#(汗)", valueOf8);
        jf5.c.put("#(泪)", valueOf9);
        jf5.c.put("#(黑线)", valueOf10);
        jf5.c.put("#(鄙视)", valueOf11);
        jf5.c.put("#(不高兴)", valueOf12);
        jf5.c.put("#(真棒)", valueOf13);
        jf5.c.put("#(钱)", valueOf14);
        jf5.c.put("#(疑问)", valueOf15);
        jf5.c.put("#(阴险)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d4c));
        jf5.c.put("#(吐)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d4d));
        jf5.c.put("#(咦)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d4e));
        jf5.c.put("#(委屈)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d4f));
        jf5.c.put("#(花心)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d51));
        jf5.c.put("#(呼~)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d52));
        jf5.c.put("#(笑眼)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d53));
        jf5.c.put("#(冷)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d54));
        jf5.c.put("#(太开心)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d55));
        jf5.c.put("#(滑稽)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d56));
        jf5.c.put("#(勉强)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d57));
        jf5.c.put("#(狂汗)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d58));
        jf5.c.put("#(乖)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d59));
        jf5.c.put("#(睡觉)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d5a));
        jf5.c.put("#(惊哭)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d5c));
        jf5.c.put("#(升起)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d5d));
        jf5.c.put("#(惊讶)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d5e));
        jf5.c.put("#(喷)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d5f));
        jf5.c.put("#(哼)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d74));
        jf5.c.put("#(吃瓜)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d75));
        jf5.c.put("#(扔便便)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d76));
        jf5.c.put("#(惊恐)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d77));
        jf5.c.put("#(哎呦)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d78));
        jf5.c.put("#(小乖)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d79));
        jf5.c.put("#(捂嘴笑)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d7a));
        jf5.c.put("#(你懂的)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d7b));
        jf5.c.put("#(what)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d7c));
        jf5.c.put("#(酸爽)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d7e));
        jf5.c.put("#(呀咩爹)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d7f));
        jf5.c.put("#(笑尿)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d80));
        jf5.c.put("#(挖鼻)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d81));
        jf5.c.put("#(犀利)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d82));
        jf5.c.put("#(小红脸)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d83));
        jf5.c.put("#(懒得理)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d84));
        jf5.c.put("#(暗中观察)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d8e));
        jf5.c.put("#(吃瓜)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d8f));
        jf5.c.put("#(喝酒)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d90));
        jf5.c.put("#(嘿嘿嘿)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d91));
        jf5.c.put("#(噗)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d92));
        jf5.c.put("#(困成狗)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d94));
        jf5.c.put("#(微微一笑)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d95));
        jf5.c.put("#(托腮)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d96));
        jf5.c.put("#(摊手)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d97));
        jf5.c.put("#(柯基暗中观察)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d98));
        jf5.c.put("#(欢呼)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d99));
        jf5.c.put("#(炸药)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d9a));
        jf5.c.put("#(香槟)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d45));
        jf5.c.put("#(突然兴奋)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d9b));
        jf5.c.put("#(紧张)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d9c));
        jf5.c.put("#(黑头瞪眼)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d9d));
        jf5.c.put("#(黑头高兴)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d21));
        jf5.c.put("#(奥特曼)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d3c));
        jf5.c.put("#(不听)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d3d));
        jf5.c.put("#(干饭)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d3e));
        jf5.c.put("#(菜狗)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d40));
        jf5.c.put("#(老虎)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d42));
        jf5.c.put("#(嗷呜)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d43));
        jf5.c.put("#(烟花)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d44));
        jf5.c.put("#(望远镜)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d3f));
        jf5.c.put("#(文字啊)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d46));
        jf5.c.put("#(文字对)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d47));
        jf5.c.put("#(鼠1)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d48));
        jf5.c.put("#(鼠2)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080d49));
        jf5.c.put("[微笑]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f0805fd));
        jf5.c.put("[开心]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f0805fe));
        jf5.c.put("[期待]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f0805ff));
        jf5.c.put("[大笑]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080600));
        jf5.c.put("[鼓掌]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080601));
        jf5.c.put("[悠闲]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080602));
        jf5.c.put("[笑哭]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080603));
        jf5.c.put("[不要啊]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080604));
        jf5.c.put("[啊]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080605));
        jf5.c.put("[哟]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080606));
        jf5.c.put("[汗]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08060e));
        jf5.c.put("[抠鼻]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08060f));
        jf5.c.put("[哼]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080610));
        jf5.c.put("[发怒]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080611));
        jf5.c.put("[委屈]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080612));
        jf5.c.put("[不高兴]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080613));
        jf5.c.put("[囧]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080614));
        jf5.c.put("[惊哭]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080615));
        jf5.c.put("[大哭]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080616));
        jf5.c.put("[流泪]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080617));
        jf5.c.put("[害羞]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080618));
        jf5.c.put("[亲亲]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080619));
        jf5.c.put("[色]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08061a));
        jf5.c.put("[舔屏]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08061b));
        jf5.c.put("[得意]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08061c));
        jf5.c.put("[疑问]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08061d));
        jf5.c.put("[晕]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08061e));
        jf5.c.put("[大哈]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08061f));
        jf5.c.put("[二哈]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080620));
        jf5.c.put("[三哈]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080621));
        jf5.c.put("[白眼]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080622));
        jf5.c.put("[阴险]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080623));
        jf5.c.put("[你懂的]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080624));
        jf5.c.put("[偷笑]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080625));
        jf5.c.put("[睡觉]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080626));
        jf5.c.put("[哈欠]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080627));
        jf5.c.put("[再见]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080628));
        jf5.c.put("[鄙视]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080629));
        jf5.c.put("[抓狂]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08062a));
        jf5.c.put("[咒骂]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08062b));
        jf5.c.put("[衰]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08062c));
        jf5.c.put("[骷髅]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08062d));
        jf5.c.put("[嘘]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08062e));
        jf5.c.put("[闭嘴]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08062f));
        jf5.c.put("[呆]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080630));
        jf5.c.put("[什么鬼]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080631));
        jf5.c.put("[吐]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080632));
        jf5.c.put("[已阅]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080633));
        jf5.c.put("[同上]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080634));
        jf5.c.put("[友军]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080635));
        jf5.c.put("[爱钱]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080636));
        jf5.c.put("[Freestyle]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080637));
        jf5.c.put("[国宝]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080638));
        jf5.c.put("[羊驼]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080639));
        jf5.c.put("[鲜花]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08063a));
        jf5.c.put("[中国加油]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08063b));
        jf5.c.put("[庆祝]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08063c));
        jf5.c.put("[生日蛋糕]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08063d));
        jf5.c.put("[MicDrop]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08063e));
        jf5.c.put("[赞同]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08063f));
        jf5.c.put("[药丸]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080640));
        jf5.c.put("[蜡烛]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080641));
        jf5.c.put("[鸡蛋]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080642));
        jf5.c.put("[浪]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080643));
        jf5.c.put("[打call]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080644));
        jf5.c.put("[尬笑]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080645));
        jf5.c.put("[坏笑]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080646));
        jf5.c.put("[没眼看]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080647));
        jf5.c.put("[嘿哈]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080648));
        jf5.c.put("[前面的别走]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080649));
        jf5.c.put("[滑稽]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08064a));
        jf5.c.put("[捂脸]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08064b));
        jf5.c.put("[左捂脸]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08064c));
        jf5.c.put("[666]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08064d));
        jf5.c.put("[2018]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08064e));
        jf5.c.put("[福]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08064f));
        jf5.c.put("[红包]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080650));
        jf5.c.put("[鞭炮]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080651));
        jf5.c.put("[财神]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080652));
        jf5.c.put("[饺子]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080653));
        jf5.c.put("[车票]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080654));
        jf5.c.put("[火车]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080655));
        jf5.c.put("[飞机]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080656));
        jf5.c.put("[射门]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080657));
        jf5.c.put("[红牌]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080658));
        jf5.c.put("[黄牌]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080659));
        jf5.c.put("[哨子]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08065a));
        jf5.c.put("[比分]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08065b));
        jf5.c.put("[啤酒]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08065c));
        jf5.c.put("[足球]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08065d));
        jf5.c.put("[大力神杯]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08065e));
        jf5.c.put("[锦鲤]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08065f));
        jf5.c.put("[2019]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080660));
        jf5.c.put("[猪年]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080661));
        jf5.c.put("[双手鼓掌]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080662));
        jf5.c.put("[火焰]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080663));
        jf5.c.put("[祈福]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080664));
        jf5.c.put("[亲吻]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080665));
        jf5.c.put("[天使]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080666));
        jf5.c.put("[樱花]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080607));
        jf5.c.put("[加油]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080608));
        jf5.c.put("[泡泡枪]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080609));
        jf5.c.put("[气球]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08060a));
        jf5.c.put("[棒棒糖]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08060b));
        jf5.c.put("[小黄鸭]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08060c));
        jf5.c.put("[粽子]", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08060d));
        jf5.c.put("#(熊-88)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080270));
        jf5.c.put("#(熊-HI)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080271));
        jf5.c.put("#(熊-人艰不拆)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080272));
        jf5.c.put("#(熊-啥)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080273));
        jf5.c.put("#(熊-大哭)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080274));
        jf5.c.put("#(熊-失落)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080275));
        jf5.c.put("#(熊-怒赞)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080276));
        jf5.c.put("#(熊-惊呆了)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080277));
        jf5.c.put("#(熊-李菊福)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080278));
        jf5.c.put("#(熊-来信砍)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080279));
        jf5.c.put("#(熊-欢迎入群)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08027a));
        jf5.c.put("#(熊-牛闪闪)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08027b));
        jf5.c.put("#(熊-生日快乐)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08027c));
        jf5.c.put("#(熊-石化)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08027d));
        jf5.c.put("#(熊-羞羞哒)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08027e));
        jf5.c.put("#(熊-肥皂必杀)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f08027f));
        jf5.c.put("#(熊-谢谢你)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080280));
        jf5.c.put("#(熊-跳舞)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080281));
        jf5.c.put("#(熊-霹雳舞)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080282));
        jf5.c.put("#(熊-鼓掌)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080283));
    }

    public gs6() {
        Interceptable interceptable = $ic;
        if (interceptable != null) {
            InitContext newInitContext = TitanRuntime.newInitContext();
            interceptable.invokeUnInit(65537, newInitContext);
            int i = newInitContext.flag;
            if ((i & 1) != 0) {
                int i2 = i & 2;
                newInitContext.thisArg = this;
                interceptable.invokeInitBody(65537, newInitContext);
            }
        }
    }
}
