package com.baidu.tbadk.coreExtra.live;
/* loaded from: classes.dex */
public class LiveStatusChangeDefinition {
    public static final String ERROR_PROMPT_CONNECTION_CLOSED = "Connection closed";
    public static final String ERROR_PROMPT_CONNECT_FAILED = "Connect failed";
    public static final String ERROR_PROMPT_CONNECT_PREPARE = "Init failed";
    public static final String ERROR_PROMPT_CREATE_ENGINE_FAILED = "Multimedia module failed";
    public static final String ERROR_PROMPT_EXIT_ACTIVITY_RETRY = "exit_activity_to_retry";
    public static final String ERROR_PROMPT_EXIT_APP_RETRY = "exit_app_to_retry";
    public static final String ERROR_PROMPT_EXIT_PHONE_RETRY = "restart_phone";
    public static final String ERROR_PROMPT_NOT_SUPPORT = "system_not_support";
    public static final String ERROR_PROMPT_PLAY_FILE_ERROR = "Play file error";
    public static final String ERROR_PROMPT_PLAY_INVALID_CODEC = "Play invalid codec";
    public static final String ERROR_PROMPT_PLAY_NET_ERROR = "Play network error";
    public static final String ERROR_PROMPT_PLUGIN_ERROR = "live Plugin not loaded";
    public static final String ERROR_PROMPT_SDK_RETRY_FAIL = "sdk_retry_fail";
    public static final String ERROR_PROMPT_SERVICE_CRASHED = "service_crashed_or_killed";
    public static final String ERROR_PROMPT_SERVICE_UNBIND = "service_unbind";
    public static final String ERROR_PROMPT_START_PUB = "publish_failed";
    public static final String ERROR_PROMPT_TOKEN_EXPIRED = "Token expired";
    public static final String ERROR_PROMPT_USER_NULL = "User Id is null";
    public static final String GROUP_FOR_RECORD_PLAY = "000000001";
    public static final int LIVE_IDLE = 0;
    public static final int LIVE_INVALID = -1;
    public static final int LIVE_PLAYING_LIVE = 2;
    public static final int LIVE_PLAYING_RECORD = 3;
    public static final int LIVE_PUBLISHING = 1;
    public static final int LIVE_RECORD_NOTREADY = 1;
    public static final int LIVE_RECORD_READY = 2;
    public static final int LIVE_RECORD_RECORDING = 3;
    public static final int RECORD_TIME_UPLIMIT = 14340;
    public static final int STATUS_IDLE = 0;
    public static final int STATUS_INVALID = -1;
    public static final int STATUS_PLAY_END = 17;
    public static final int STATUS_PLAY_PAUSED = 20;
    public static final int STATUS_PLAY_PLAYING = 19;
    public static final int STATUS_PLAY_PREPARING = 18;
    public static final int STATUS_PUBLISH_CONNECTED = 2;
    public static final int STATUS_PUBLISH_PAUSED = 4;
    public static final int STATUS_PUBLISH_PREPARING = 1;
    public static final int STATUS_PUBLISH_PUBLISHING = 3;
}
