package com.baidu.ufosdk;

import android.graphics.Bitmap;
import android.support.v4.view.ViewCompat;
import java.util.HashMap;
/* loaded from: classes21.dex */
public final class b {
    public static boolean a = false;
    public static String b = "";
    public static String c = "";
    public static String d = "";
    public static int e = 0;
    public static String f = "";
    public static Bitmap g = null;
    public static String h = "";
    public static String i = "";
    public static int j = 0;
    public static int k = 0;
    public static String l = "";
    public static String m = "";
    public static String n = "";
    public static int o = 1;
    public static String p = "";
    public static int q = 0;
    public static int r = ViewCompat.MEASURED_STATE_MASK;
    public static int s = ViewCompat.MEASURED_STATE_MASK;
    public static int t = -5262406;
    public static int u = -1;
    public static int v = -11821318;
    public static int w = -11821318;
    public static int x = ViewCompat.MEASURED_STATE_MASK;
    public static int y = -5262406;
    public static int z = -657673;
    public static int A = -1;
    public static int B = -460552;
    public static int C = -921103;
    public static int D = -1;
    public static int E = -6710887;
    public static int F = -6710887;
    public static int G = -1381654;
    public static int H = ViewCompat.MEASURED_STATE_MASK;
    public static int I = -855310;
    public static int J = -10066330;
    public static int K = -1293499;
    public static int L = -1;
    public static float M = 16.0f;
    public static float N = 20.0f;
    public static float O = 18.0f;
    public static float P = 16.0f;
    public static float Q = 12.0f;
    public static float R = 17.0f;
    public static float S = 19.0f;
    public static float T = 20.0f;
    public static float U = 16.0f;
    public static float V = 12.0f;
    public static float W = 19.0f;
    public static float X = 18.0f;
    public static float Y = 11.0f;
    public static float Z = 15.0f;
    public static int aa = 200;
    public static HashMap ab = null;
    public static ResumeCallBack ac = null;
    public static SubmitMessageCallBack ad = null;
    public static GetNoticeFlagCallBack ae = null;
    public static ReportCallback af = null;
    public static a ag = null;
    public static int ah = 10;
    public static int ai = 600;
}
