package d.a.i0.a.c2;

import com.baidu.searchbox.unitedscheme.UnitedSchemeMainDispatcher;
import d.a.i0.a.a0.a.g;
import d.a.i0.a.c2.f.l;
import d.a.i0.a.c2.f.m;
import d.a.i0.a.c2.f.n;
import d.a.i0.a.c2.f.p0.h;
import d.a.i0.a.c2.f.p0.i;
import d.a.i0.a.c2.f.r;
import d.a.i0.a.c2.f.s;
import d.a.i0.a.c2.f.v;
import d.a.i0.a.c2.f.z;
import d.a.i0.a.i1.g.d.f;
import d.a.i0.a.k;
/* loaded from: classes3.dex */
public final class a {

    /* renamed from: a  reason: collision with root package name */
    public static final boolean f40772a = k.f43025a;

    public static e a(UnitedSchemeMainDispatcher unitedSchemeMainDispatcher) {
        e eVar = new e();
        unitedSchemeMainDispatcher.setDynamicDispatcher("swanAPI", eVar);
        d.a.i0.a.c1.a.s().b(eVar);
        eVar.b(new d.a.i0.a.c2.f.p0.e(eVar));
        eVar.b(new d.a.i0.a.c2.f.p0.d(eVar));
        eVar.b(new d.a.i0.a.c2.f.p0.k(eVar));
        eVar.b(new i(eVar));
        eVar.b(new h(eVar));
        eVar.b(new d.a.i0.a.c2.f.p0.b(eVar));
        eVar.b(new d.a.i0.a.c2.f.m0.c(eVar));
        eVar.b(new d.a.i0.a.c2.f.m0.b(eVar));
        eVar.b(new d.a.i0.a.c2.f.m0.a(eVar));
        eVar.b(new d.a.i0.a.c2.f.m0.d(eVar));
        eVar.b(new d.a.i0.a.c2.f.o0.b(eVar));
        eVar.b(new d.a.i0.a.c2.f.o0.a(eVar));
        eVar.b(new d.a.i0.a.c2.f.r0.a(eVar));
        eVar.b(new d.a.i0.a.c2.f.r0.c(eVar));
        eVar.b(new d.a.i0.a.c2.f.r0.b(eVar));
        eVar.b(new d.a.i0.a.c2.f.h(eVar));
        eVar.b(new d.a.i0.a.c2.f.k0.a(eVar));
        eVar.b(new d.a.i0.a.a0.a.d(eVar));
        eVar.b(new g(eVar));
        eVar.b(new d.a.i0.a.a0.a.i(eVar));
        eVar.b(new d.a.i0.a.a0.a.b(eVar));
        eVar.b(new d.a.i0.a.a0.a.e(eVar));
        eVar.b(new d.a.i0.a.a0.a.h(eVar));
        eVar.b(new d.a.i0.a.i1.c.d.b(eVar));
        eVar.b(new d.a.i0.a.i1.c.d.a(eVar));
        eVar.b(new f(eVar));
        eVar.b(new d.a.i0.a.h0.e.a(eVar));
        eVar.b(new d.a.i0.a.e0.f.e.b(eVar));
        eVar.b(new d.a.i0.a.k2.e.k(eVar));
        eVar.b(new d.a.i0.a.k2.e.d(eVar));
        eVar.b(new d.a.i0.a.k2.e.e(eVar));
        eVar.b(new d.a.i0.a.k2.e.h(eVar));
        eVar.b(new d.a.i0.a.n1.g(eVar));
        eVar.b(new d.a.i0.a.z0.d(eVar));
        eVar.b(new d.a.i0.a.z0.a(eVar));
        eVar.b(new d.a.i0.a.z0.e(eVar));
        eVar.b(new d.a.i0.a.o2.a.b(eVar));
        eVar.b(new d.a.i0.a.o2.a.c(eVar));
        eVar.b(new d.a.i0.a.o2.a.d(eVar));
        eVar.b(new d.a.i0.a.o2.a.e(eVar));
        eVar.b(new d.a.i0.a.o2.a.f(eVar));
        eVar.b(new d.a.i0.a.o2.a.g(eVar));
        eVar.b(new d.a.i0.a.o2.a.h(eVar));
        eVar.b(new d.a.i0.a.o2.a.i(eVar));
        eVar.b(new d.a.i0.a.h1.a(eVar));
        eVar.b(new d.a.i0.a.z.b.b(eVar));
        eVar.b(new d.a.i0.a.z.b.g(eVar));
        eVar.b(new d.a.i0.a.z.b.c(eVar));
        eVar.b(new d.a.i0.a.z.b.f(eVar));
        eVar.b(new d.a.i0.a.z.b.d(eVar));
        eVar.b(new d.a.i0.a.z.b.e(eVar));
        eVar.b(new d.a.i0.a.c0.c.e.a.a(eVar));
        eVar.b(new d.a.i0.a.c0.c.e.a.b(eVar));
        eVar.b(new d.a.i0.a.s0.a(eVar));
        eVar.b(new d.a.i0.a.n.c.a(eVar));
        eVar.b(new d.a.i0.a.n.a.a(eVar));
        eVar.b(new d.a.i0.a.n2.l.a.a(eVar));
        eVar.b(new d.a.i0.a.n2.l.a.b(eVar));
        eVar.b(new d.a.i0.a.n2.e.a.a(eVar));
        eVar.b(new d.a.i0.a.w2.i.a(eVar));
        eVar.b(new d.a.i0.a.w.b(eVar));
        eVar.b(new d.a.i0.a.i1.d.a.b(eVar));
        eVar.b(new d.a.i0.a.i1.d.a.c(eVar));
        eVar.b(new d.a.i0.a.i1.d.a.a(eVar));
        eVar.b(new d.a.i0.a.k2.e.c(eVar));
        eVar.b(new d.a.i0.a.f0.b.b(eVar));
        eVar.b(new d.a.i0.a.p2.d.b(eVar));
        eVar.b(new d.a.i0.a.p2.d.a(eVar));
        eVar.b(new d.a.i0.a.p2.d.c(eVar));
        eVar.b(new d.a.i0.a.n2.h.f.a(eVar));
        eVar.b(new d.a.i0.a.c2.f.j0.d(eVar));
        eVar.b(new d.a.i0.a.c2.f.j0.a(eVar));
        eVar.b(new r(eVar));
        if (f40772a) {
            eVar.b(new d.a.i0.a.c2.f.q0.a(eVar));
            eVar.b(new d.a.i0.a.e0.g.c(eVar));
        }
        eVar.b(new v(eVar));
        eVar.b(new l(eVar));
        eVar.b(new d.a.i0.a.c2.f.c(eVar));
        eVar.b(new n(eVar));
        eVar.b(new d.a.i0.a.a0.a.c(eVar));
        eVar.b(new d.a.i0.a.a0.a.f(eVar));
        eVar.b(new d.a.i0.a.c0.c.b.b(eVar));
        eVar.b(new d.a.i0.a.c2.f.f0.a(eVar));
        eVar.b(new d.a.i0.a.c2.f.f0.d(eVar));
        eVar.b(new d.a.i0.a.c2.f.f0.e(eVar));
        eVar.b(new d.a.i0.a.c2.f.f0.c(eVar));
        eVar.b(new d.a.i0.a.c2.f.f0.f(eVar));
        eVar.b(new d.a.i0.a.c2.f.p0.f(eVar));
        eVar.b(new d.a.i0.a.q.b(eVar));
        eVar.b(new d.a.i0.a.p0.c.a(eVar));
        eVar.b(new d.a.i0.a.c2.f.e0.a(eVar));
        eVar.b(new d.a.i0.a.c2.f.e0.b(eVar));
        eVar.b(new d.a.i0.a.c2.f.l0.a(eVar));
        eVar.b(new d.a.i0.a.c2.f.f0.g(eVar));
        eVar.b(new z(eVar));
        eVar.b(new d.a.i0.a.c2.f.e(eVar));
        eVar.b(new d.a.i0.a.j1.c(eVar));
        eVar.b(new m(eVar));
        eVar.b(new d.a.i0.a.y0.h.a(eVar));
        eVar.b(new d.a.i0.a.y0.h.c(eVar));
        eVar.b(new d.a.i0.a.c2.f.h0.a(eVar));
        eVar.b(new d.a.i0.a.c2.f.h0.b(eVar));
        eVar.b(new d.a.i0.a.i1.h.d.b(eVar));
        eVar.b(new d.a.i0.a.o.d(eVar));
        eVar.b(new s(eVar));
        eVar.b(new d.a.i0.a.f0.b.a(eVar));
        eVar.b(new d.a.i0.a.p1.b.a(eVar));
        eVar.b(new d.a.i0.a.r.b(eVar));
        eVar.b(new d.a.i0.a.r.f(eVar));
        eVar.b(new d.a.i0.a.r.d(eVar));
        eVar.b(new d.a.i0.a.r.g(eVar));
        eVar.b(new d.a.i0.a.r.e(eVar));
        return eVar;
    }
}
