package com.kwad.sdk.core.b.a;

import com.ksad.annotation.invoker.InvokeBy;
import com.kwad.components.core.video.a.c;
import com.kwad.components.core.webview.a.a;
import com.kwad.components.core.webview.jshandler.WebCardRegisterLiveMessageListener;
import com.kwad.components.core.webview.jshandler.WebCardRegisterLiveShopListener;
import com.kwad.components.core.webview.jshandler.WebCardVideoPositionHandler;
import com.kwad.components.core.webview.jshandler.a;
import com.kwad.components.core.webview.jshandler.ae;
import com.kwad.components.core.webview.jshandler.af;
import com.kwad.components.core.webview.jshandler.ah;
import com.kwad.components.core.webview.jshandler.ai;
import com.kwad.components.core.webview.jshandler.al;
import com.kwad.components.core.webview.jshandler.am;
import com.kwad.components.core.webview.jshandler.an;
import com.kwad.components.core.webview.jshandler.aq;
import com.kwad.components.core.webview.jshandler.ar;
import com.kwad.components.core.webview.jshandler.as;
import com.kwad.components.core.webview.jshandler.at;
import com.kwad.components.core.webview.jshandler.av;
import com.kwad.components.core.webview.jshandler.ax;
import com.kwad.components.core.webview.jshandler.ba;
import com.kwad.components.core.webview.jshandler.bb;
import com.kwad.components.core.webview.jshandler.bc;
import com.kwad.components.core.webview.jshandler.be;
import com.kwad.components.core.webview.jshandler.c;
import com.kwad.components.core.webview.jshandler.d;
import com.kwad.components.core.webview.jshandler.e;
import com.kwad.components.core.webview.jshandler.f;
import com.kwad.components.core.webview.jshandler.g;
import com.kwad.components.core.webview.jshandler.h;
import com.kwad.components.core.webview.jshandler.j;
import com.kwad.components.core.webview.jshandler.k;
import com.kwad.components.core.webview.jshandler.o;
import com.kwad.components.core.webview.jshandler.s;
import com.kwad.components.core.webview.jshandler.t;
import com.kwad.components.core.webview.jshandler.w;
import com.kwad.components.core.webview.tachikoma.a.h;
import com.kwad.components.core.webview.tachikoma.a.u;
import com.kwad.components.core.webview.tachikoma.a.x;
import com.kwad.sdk.i.a;
import com.kwad.sdk.i.b;
import com.kwad.sdk.kgeo.KGeoInfo;
/* loaded from: classes10.dex */
public final class cl {
    @InvokeBy(invokerClass = fr.class, methodId = "registerHolder")
    public static void Cp() {
        fr.Cq().put(x.a.class, new be());
        fr.Cq().put(h.a.class, new ej());
        fr.Cq().put(b.a.class, new ij());
        fr.Cq().put(a.C0664a.class, new af());
        fr.Cq().put(k.b.class, new fd());
        fr.Cq().put(ah.a.class, new kh());
        fr.Cq().put(ax.a.class, new fz());
        fr.Cq().put(com.kwad.components.core.webview.tachikoma.b.e.class, new bs());
        fr.Cq().put(com.kwad.components.core.webview.tachikoma.b.o.class, new hd());
        fr.Cq().put(j.a.class, new el());
        fr.Cq().put(a.C0721a.class, new df());
        fr.Cq().put(b.C0722b.class, new ik());
        fr.Cq().put(ar.a.class, new ax());
        fr.Cq().put(h.b.class, new hn());
        fr.Cq().put(h.b.class, new ek());
        fr.Cq().put(com.kwad.components.core.webview.tachikoma.b.q.class, new in());
        fr.Cq().put(com.kwad.components.core.webview.tachikoma.b.u.class, new jd());
        fr.Cq().put(ae.a.class, new ho());
        fr.Cq().put(ai.a.class, new et());
        fr.Cq().put(am.b.class, new eo());
        fr.Cq().put(com.kwad.components.core.webview.tachikoma.b.w.class, new kj());
        fr.Cq().put(g.a.class, new ei());
        fr.Cq().put(com.kwad.components.core.page.b.a.class, new fw());
        fr.Cq().put(com.kwad.components.core.n.b.class, new gx());
        fr.Cq().put(ba.a.class, new kr());
        fr.Cq().put(w.a.class, new u());
        fr.Cq().put(com.kwad.components.core.webview.tachikoma.b.r.class, new ip());
        fr.Cq().put(com.kwad.sdk.a.a.a.a.class, new fe());
        fr.Cq().put(an.b.class, new fo());
        fr.Cq().put(al.a.class, new co());
        fr.Cq().put(bc.a.class, new er());
        fr.Cq().put(e.a.class, new eg());
        fr.Cq().put(com.kwad.components.core.webview.tachikoma.b.i.class, new em());
        fr.Cq().put(an.a.class, new fn());
        fr.Cq().put(com.kwad.components.core.webview.tachikoma.b.h.class, new cs());
        fr.Cq().put(av.a.class, new ks());
        fr.Cq().put(c.a.class, new kl());
        fr.Cq().put(com.kwad.components.core.webview.tachikoma.b.f.class, new bz());
        fr.Cq().put(com.kwad.components.core.webview.tachikoma.b.s.class, new iq());
        fr.Cq().put(aq.a.class, new hf());
        fr.Cq().put(com.kwad.components.core.webview.a.b.class, new gy());
        fr.Cq().put(WebCardRegisterLiveShopListener.AdLiveItemShopInfo.class, new z());
        fr.Cq().put(af.a.class, new hp());
        fr.Cq().put(f.a.class, new eh());
        fr.Cq().put(as.a.class, new ba());
        fr.Cq().put(com.kwad.components.core.webview.tachikoma.b.c.class, new bg());
        fr.Cq().put(bb.a.class, new ju());
        fr.Cq().put(com.kwad.components.core.webview.tachikoma.b.v.class, new kg());
        fr.Cq().put(WebCardRegisterLiveMessageListener.AdLiveMessageInfoList.AdLiveMessageItemInfo.class, new ab());
        fr.Cq().put(com.kwad.components.core.webview.tachikoma.b.b.class, new bc());
        fr.Cq().put(t.b.class, new jk());
        fr.Cq().put(c.b.class, new km());
        fr.Cq().put(com.kwad.components.core.webview.tachikoma.b.x.class, new kn());
        fr.Cq().put(com.kwad.components.core.webview.tachikoma.b.d.class, new bi());
        fr.Cq().put(s.a.class, new jo());
        fr.Cq().put(WebCardVideoPositionHandler.VideoPosition.class, new kp());
        fr.Cq().put(at.a.class, new bj());
        fr.Cq().put(be.a.class, new fq());
        fr.Cq().put(com.kwad.components.core.webview.tachikoma.b.t.class, new ir());
        fr.Cq().put(com.kwad.components.core.webview.a.c.class, new ha());
        fr.Cq().put(com.kwad.components.core.webview.tachikoma.b.m.class, new gl());
        fr.Cq().put(com.kwad.components.core.webview.tachikoma.b.n.class, new gz());
        fr.Cq().put(WebCardRegisterLiveMessageListener.AdLiveMessageInfoList.class, new aa());
        fr.Cq().put(as.b.class, new bb());
        fr.Cq().put(com.kwad.components.core.webview.tachikoma.b.g.class, new cc());
        fr.Cq().put(k.a.class, new fc());
        fr.Cq().put(o.a.class, new gj());
        fr.Cq().put(com.kwad.components.core.webview.tachikoma.b.a.class, new n());
        fr.Cq().put(a.C0663a.class, new cz());
        fr.Cq().put(u.b.class, new je());
        fr.Cq().put(com.kwad.components.core.webview.tachikoma.b.j.class, new fp());
        fr.Cq().put(c.b.class, new ew());
        fr.Cq().put(WebCardVideoPositionHandler.VideoPosition.KSAdJSCornerModel.class, new ft());
        fr.Cq().put(com.kwad.components.core.webview.tachikoma.b.p.class, new hl());
        fr.Cq().put(com.kwad.components.core.webview.tachikoma.b.y.class, new kq());
        fr.Cq().put(a.b.class, new dc());
        fr.Cq().put(com.kwad.components.core.webview.tachikoma.b.l.class, new fx());
        fr.Cq().put(a.b.class, new dg());
        fr.Cq().put(com.kwad.components.core.k.a.class, new s());
        fr.Cq().put(d.a.class, new ef());
        fr.Cq().put(KGeoInfo.class, new fs());
    }
}
