package com.baidu.searchbox.launch.stats;

import com.baidu.titan.sdk.runtime.FieldHolder;
import com.baidu.titan.sdk.runtime.InitContext;
import com.baidu.titan.sdk.runtime.Interceptable;
import com.baidu.titan.sdk.runtime.TitanRuntime;
/* loaded from: classes5.dex */
public final class SpeedStatsStampTable {
    public static /* synthetic */ Interceptable $ic = null;
    public static final int APP_CONFIG_INIT_END_STAMP_KEY = 1009;
    public static final int APP_CONFIG_INIT_STAMP_KEY = 2002;
    public static final int APP_CREATE_END_STAMP_KEY = 2006;
    public static final int APP_CREATE_START_STAMP_KEY = 2000;
    public static final int APP_START_TIMESTAMP_KEY = 1000;
    public static final int ATTACH_BASE_CONTEXT_END_STAMP_KEY = 1010;
    public static final int ATTACH_BASE_CONTEXT_START_STAMP_KEY = 1002;
    public static final int CHECK_AND_SEND_ACTIVE_CONFIG_END_STAMP_KEY = 3013;
    public static final int CHECK_AND_SEND_ACTIVE_CONFIG_START_STAMP_KEY = 3012;
    public static final int CHECK_CLIENT_CONFIG_END_STAMP_KEY = 3011;
    public static final int CHECK_CLIENT_CONFIG_START_STAMP_KEY = 3010;
    public static final int CHECK_PLUGIN_ENTRANCE_STATE_END_STAMP_KEY = 3007;
    public static final int CHECK_PLUGIN_ENTRANCE_STATE_START_STAMP_KEY = 3006;
    public static final int CHECK_REAL_NAME_END_STAMP_KEY = 3021;
    public static final int CHECK_REAL_NAME_START_STAMP_KEY = 3020;
    public static final int CLEAN_DIRECTORY_STAMP_KEY = 2010;
    public static final int CLEAR_CONCERN_CACHE_WHEN_VERSION_UPDATE_END_STAMP_KEY = 3023;
    public static final int CLEAR_CONCERN_CACHE_WHEN_VERSION_UPDATE_START_STAMP_KEY = 3022;
    public static final int CMDROUTER_INIT_STAMP_KEY = 2012;
    public static final int CUSTOM_VIEW_PAPER_INIT_START_STAMP_KEY = 4010;
    public static final int CUSTOM_VIEW_PAPER_VIEW_INIT_END_STAMP_KEY = 4011;
    public static final int ELAPSED_CPU_START_STAMP_KEY = 1001;
    public static final int HOME_FRAGMENT_CHECK_CONCERN_RED_TIP_END_STAMP_KEY = 4024;
    public static final int HOME_FRAGMENT_CHECK_CONCERN_RED_TIP_START_STAMP_KEY = 4023;
    public static final int HOME_FRAGMENT_FIRST_LOAD_END_STAMP_KEY = 4022;
    public static final int HOME_FRAGMENT_FIRST_LOAD_START_STAMP_KEY = 4021;
    public static final int HOME_FRAGMENT_INIT_MODEL_END_STAMP_KEY = 4016;
    public static final int HOME_FRAGMENT_INIT_MODEL_START_STAMP_KEY = 4015;
    public static final int HOME_FRAGMENT_INIT_TABLE_END_STAMP_KEY = 4018;
    public static final int HOME_FRAGMENT_INIT_TABLE_START_STAMP_KEY = 4017;
    public static final int HOME_FRAGMENT_INIT_VIEW_PAPER_END_STAMP_KEY = 4020;
    public static final int HOME_FRAGMENT_INIT_VIEW_PAPER_START_STAMP_KEY = 4019;
    public static final int HOME_FRAGMENT_ONRESUME_END_STAMP_KEY = 4029;
    public static final int HOME_FRAGMENT_ONRESUME_START_STAMP_KEY = 4028;
    public static final int HOME_FRAGMENT_ON_ACTIVITY_CREATED_END_STAMP_KEY = 4027;
    public static final int HOME_FRAGMENT_ON_ACTIVITY_CREATED_START_STAMP_KEY = 4014;
    public static final int HOME_FRAGMENT_ON_ATTACH_END_STAMP_KEY = 4001;
    public static final int HOME_FRAGMENT_ON_ATTACH_START_STAMP_KEY = 4000;
    public static final int HOME_FRAGMENT_ON_CREATE_END_STAMP_KEY = 4003;
    public static final int HOME_FRAGMENT_ON_CREATE_START_STAMP_KEY = 4002;
    public static final int HOME_FRAGMENT_ON_CREATE_VIEW_END_STAMP_KEY = 4005;
    public static final int HOME_FRAGMENT_ON_CREATE_VIEW_START_STAMP_KEY = 4004;
    public static final int HOME_FRAGMENT_SHOW_CONCERN_TAB_TIPS_END_STAMP_KEY = 4026;
    public static final int HOME_FRAGMENT_SHOW_CONCERN_TAB_TIPS_START_STAMP_KEY = 4025;
    public static final int HOME_TAB_BAR_VIEW_INIT_END_STAMP_KEY = 4009;
    public static final int HOME_TAB_BAR_VIEW_INIT_START_STAMP_KEY = 4008;
    public static final int HOME_TAB_BAR_VIEW_ON_LAYOUT_END_STAMP_KEY = 5012;
    public static final int HOME_TAB_BAR_VIEW_ON_LAYOUT_START_STAMP_KEY = 5011;
    public static final int HOME_TAB_BAR_VIEW_ON_MEASURE_END_STAMP_KEY = 5004;
    public static final int HOME_TAB_BAR_VIEW_ON_MEASURE_START_STAMP_KEY = 5003;
    public static final int HOME_VIEW_DISPATCH_DRAW_END_STAMP_KEY = 5017;
    public static final int HOME_VIEW_DISPATCH_DRAW_START_STAMP_KEY = 5016;
    public static final int HOME_VIEW_ON_LAYOUT_END_STAMP_KEY = 5015;
    public static final int HOME_VIEW_ON_LAYOUT_START_STAMP_KEY = 5008;
    public static final int INIT_ACCOUNT_CHANGE_STAMP_KEY = 2007;
    public static final int INIT_ACCOUNT_LOGIN_STAMP_KEY = 2020;
    public static final int INIT_ALL_STAMP_KEY = 2016;
    public static final int INIT_AR_STAMP_KEY = 2032;
    public static final int INIT_AXE_STAMP_KEY = 2031;
    public static final int INIT_BEAR_STAMP_KEY = 2025;
    public static final int INIT_CMD_STAMP_KEY = 2014;
    public static final int INIT_COOKIE_END_STAMP_KEY = 3017;
    public static final int INIT_COOKIE_START_STAMP_KEY = 3016;
    public static final int INIT_COUNT_STATS_STAMP_KEY = 2028;
    public static final int INIT_DIMON_ADAPT_STAMP_KEY = 2009;
    public static final int INIT_FACE_STAMP_KEY = 2017;
    public static final int INIT_GO_ACTION_STAMP_KEY = 2019;
    public static final int INIT_HOME_FRAGMENT_CONTROLLER_END_STAMP_KEY = 3005;
    public static final int INIT_HOME_FRAGMENT_CONTROLLER_START_STAMP_KEY = 3004;
    public static final int INIT_INTERRUPT_RULE_STAMP_KEY = 2021;
    public static final int INIT_LOKI_STAMP_KEY = 2027;
    public static final int INIT_MODULE_CONTEXT_END_STAMP_KEY = 2004;
    public static final int INIT_MSG_EIGHT_STAMP_KEY = 2040;
    public static final int INIT_MSG_EIGHT_START_STAMP_KEY = 2049;
    public static final int INIT_MSG_FIVE_STAMP_KEY = 2037;
    public static final int INIT_MSG_FIVE_START_STAMP_KEY = 2046;
    public static final int INIT_MSG_FOUR_STAMP_KEY = 2036;
    public static final int INIT_MSG_FOUR_START_STAMP_KEY = 2045;
    public static final int INIT_MSG_NINE_STAMP_KEY = 2041;
    public static final int INIT_MSG_NINE_START_STAMP_KEY = 2050;
    public static final int INIT_MSG_ONE_STAMP_KEY = 2033;
    public static final int INIT_MSG_ONE_START_STAMP_KEY = 2042;
    public static final int INIT_MSG_SEVEN_STAMP_KEY = 2039;
    public static final int INIT_MSG_SEVEN_START_STAMP_KEY = 2048;
    public static final int INIT_MSG_SIX_STAMP_KEY = 2038;
    public static final int INIT_MSG_SIX_START_STAMP_KEY = 2047;
    public static final int INIT_MSG_THREE_STAMP_KEY = 2035;
    public static final int INIT_MSG_THREE_START_STAMP_KEY = 2044;
    public static final int INIT_MSG_TWO_STAMP_KEY = 2034;
    public static final int INIT_MSG_TWO_START_STAMP_KEY = 2043;
    public static final int INIT_PLUGIN_STAMP_KEY = 2023;
    public static final int INIT_RUKA_STAMP_KEY = 2030;
    public static final int INIT_SAPI_STAMP_KEY = 2022;
    public static final int INIT_SWAN_DATA_STAMP_KEY = 2024;
    public static final int INIT_TABS_ON_ACTIVITY_CREATED_END_STAMP_KEY = 3015;
    public static final int INIT_TABS_ON_ACTIVITY_CREATED_START_STAMP_KEY = 3014;
    public static final int INIT_TASKS_STAMP_KEY = 2018;
    public static final int INIT_TO_LOGO_STAMP_KEY = 2026;
    public static final int INIT_UBC_STAMP_KEY = 2029;
    public static final int INIT_VERSION_STAMP_KEY = 2015;
    public static final int LAUNCH_TASK_INIT_END_STAMP_KEY = 2003;
    public static final int LOGGER_INIT_END_STAMP_KEY = 1006;
    public static final int LOKI_INIT_END_STAMP_KEY = 1007;
    public static final int MAINACTIVITY_CREATE_END_STAMP_KEY = 3028;
    public static final int MAINACTIVITY_CREATE_START_STAMP_KEY = 3002;
    public static final int MAINACTIVITY_ONRESUME_END_STAMP_KEY = 3032;
    public static final int MAINACTIVITY_ONRESUME_START_STAMP_KEY = 3031;
    public static final int MAINACTIVITY_ONSTART_END_STAMP_KEY = 3030;
    public static final int MAINACTIVITY_ONSTART_START_STAMP_KEY = 3029;
    public static final int MAINACTIVITY_SUPER_CREATE_END_STAMP_KEY = 3003;
    public static final int MAIN_PAGE_END_STAMP_KEY = 6000;
    public static final int MIGRATE_SP_END_STAMP_KEY = 1008;
    public static final int MULTI_DEX_INSTALL_END_STAMP_KEY = 1003;
    public static final int MULTI_DEX_TRICK_END_STAMP_KEY = 1005;
    public static final int NESTED_SCROLL_HEADER_INIT_END_STAMP_KEY = 4013;
    public static final int NESTED_SCROLL_HEADER_INIT_START_STAMP_KEY = 4012;
    public static final int NPS_INIT_END_STAMP_KEY = 1011;
    public static final int ON_APP_CREATE_END_STAMP_KEY = 2005;
    public static final int ON_FIRST_DISPATCH_DRAW_END_STAMP_KEY = 5019;
    public static final int ON_FIRST_DISPATCH_DRAW_START_STAMP_KEY = 5018;
    public static final int PERMMISSION_UTIL_STAMP_KEY = 2008;
    public static final int PROCESS_UPGRADE_STAMP_KEY = 2001;
    public static final int REG_RECEIVER_END_STAMP_KEY = 3009;
    public static final int REG_RECEIVER_START_STAMP_KEY = 3008;
    public static final int RUNTIME_INIT_END_STAMP_KEY = 1004;
    public static final int SCROLL_FRAGMENT_TAB_HOST_INIT_END_STAMP_KEY = 4007;
    public static final int SCROLL_FRAGMENT_TAB_HOST_INIT_START_STAMP_KEY = 4006;
    public static final int SCROLL_FRAGMENT_TAB_HOST_ON_MEASURE_END_STAMP_KEY = 5007;
    public static final int SCROLL_FRAGMENT_TAB_HOST_ON_MEASURE_START_STAMP_KEY = 5000;
    public static final int SEARCHBOX_VIEW_ON_LAYOUT_END_STAMP_KEY = 5010;
    public static final int SEARCHBOX_VIEW_ON_LAYOUT_START_STAMP_KEY = 5009;
    public static final int SEARCHBOX_VIEW_ON_MEASURE_END_STAMP_KEY = 5002;
    public static final int SEARCHBOX_VIEW_ON_MEASURE_START_STAMP_KEY = 5001;
    public static final int SHAREP_GET_STAMP_KEY = 2011;
    public static final int SPLASHACTIVITY_ADLOAD_END_STAMP_KEY = 3035;
    public static final int SPLASHACTIVITY_ADLOAD_START_STAMP_KEY = 3034;
    public static final int SPLASHACTIVITY_ADSHOW_END_STAMP_KEY = 3037;
    public static final int SPLASHACTIVITY_ADSHOW_START_STAMP_KEY = 3036;
    public static final int SPLASHACTIVITY_ONCREATE_END_STAMP_KEY = 3033;
    public static final int SPLASH_ACTIVITY_END_STAMP_KEY = 3001;
    public static final int SPLASH_ACTIVITY_START_STAMP_KEY = 3000;
    public static final int START_TRACK_CONFIG_REQUEST_END_STAMP_KEY = 3019;
    public static final int START_TRACK_CONFIG_REQUEST_START_STAMP_KEY = 3018;
    public static final int TAB_VIEW_PAGER_ON_LAYOUT_END_STAMP_KEY = 5014;
    public static final int TAB_VIEW_PAGER_ON_LAYOUT_START_STAMP_KEY = 5013;
    public static final int TAB_VIEW_PAGER_ON_MEASURE_END_STAMP_KEY = 5006;
    public static final int TAB_VIEW_PAGER_ON_MEASURE_START_STAMP_KEY = 5005;
    public static final int TITAN_INIT_END_STAMP_KEY = 1012;
    public static final int TRY_LOAD_NATIVE_FUN_END_STAMP_KEY = 3027;
    public static final int TRY_LOAD_NATIVE_FUN_START_STAMP_KEY = 3026;
    public static final int UPDATE_PROFILE_INFO_END_STAMP_KEY = 3025;
    public static final int UPDATE_PROFILE_INFO_START_STAMP_KEY = 3024;
    public static final int WEBVIEW_SUFFIX_STAMP_KEY = 2013;
    public transient /* synthetic */ FieldHolder $fh;

    public SpeedStatsStampTable() {
        Interceptable interceptable = $ic;
        if (interceptable != null) {
            InitContext newInitContext = TitanRuntime.newInitContext();
            interceptable.invokeUnInit(65536, newInitContext);
            int i2 = newInitContext.flag;
            if ((i2 & 1) != 0) {
                int i3 = i2 & 2;
                newInitContext.thisArg = this;
                interceptable.invokeInitBody(65536, newInitContext);
            }
        }
    }
}
