package com.baidu.tieba.frs;

import android.view.View;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.baidu.adp.widget.ListView.y;
import com.baidu.tbadk.core.view.HeadImageView;
import com.baidu.tbadk.core.view.UserIconBox;
import com.baidu.tbadk.widget.TbImageView;
import com.baidu.tieba.pb.ThreadSkinView;
import com.baidu.tieba.tbadkCore.FrsCommonImageLayout;
import com.baidu.tieba.tbadkCore.voice.PlayVoiceBnt;
import com.baidu.tieba.w;
/* loaded from: classes.dex */
public class bi extends y.a {
    public TextView alI;
    public TextView alL;
    public int amZ;
    public UserIconBox ams;
    public UserIconBox amt;
    public TextView bQs;
    public TextView bQt;
    public View bRA;
    public TbImageView bRB;
    public RelativeLayout bRC;
    public TbImageView bRD;
    public TextView bRE;
    public int bRk;
    public FrameLayout bRl;
    public LinearLayout bRm;
    public RelativeLayout bRn;
    public TbImageView bRo;
    public TextView bRp;
    public PlayVoiceBnt bRq;
    public FrsCommonImageLayout bRr;
    public TextView bRs;
    public HeadImageView bRt;
    public TextView bRu;
    public TextView bRv;
    public RelativeLayout bRw;
    public LinearLayout bRx;
    public LinearLayout bRy;
    public LinearLayout bRz;
    public ThreadSkinView bcb;
    public TextView mTitle;

    public bi(View view, int i) {
        super(view);
        this.amZ = 3;
        this.bRk = 0;
        this.bRk = i;
        this.bRl = (FrameLayout) view.findViewById(w.h.frs_list);
        this.bRw = (RelativeLayout) view.findViewById(w.h.frs_item_user_info_view);
        this.bRx = (LinearLayout) view.findViewById(w.h.frs_item_base_user_info);
        this.bRm = (LinearLayout) view.findViewById(w.h.frs_list_item_top_linear_layout);
        FrameLayout.LayoutParams layoutParams = (FrameLayout.LayoutParams) this.bRm.getLayoutParams();
        layoutParams.topMargin = i;
        this.bRm.setLayoutParams(layoutParams);
        this.bRn = (RelativeLayout) view.findViewById(w.h.frs_list_item_top_card);
        this.bRo = (TbImageView) view.findViewById(w.h.frs_normal_item_theme_card);
        this.bRt = (HeadImageView) view.findViewById(w.h.frs_photo);
        this.ams = (UserIconBox) view.findViewById(w.h.frs_user_tshow_icon_box);
        this.amt = (UserIconBox) view.findViewById(w.h.frs_user_icon_box);
        this.bRs = (TextView) view.findViewById(w.h.frs_lv_author);
        this.alI = (TextView) view.findViewById(w.h.frs_lv_reply_time);
        this.mTitle = (TextView) view.findViewById(w.h.frs_lv_title);
        this.bRp = (TextView) view.findViewById(w.h.abstract_text);
        this.bRq = (PlayVoiceBnt) view.findViewById(w.h.abstract_voice);
        this.bRr = (FrsCommonImageLayout) view.findViewById(w.h.abstract_img_layout);
        this.alL = (TextView) view.findViewById(w.h.frs_praise_num);
        this.bRu = (TextView) view.findViewById(w.h.action_button);
        this.bQt = (TextView) view.findViewById(w.h.frs_reply_num);
        this.bRv = (TextView) view.findViewById(w.h.frs_more_abstract);
        this.bRy = (LinearLayout) view.findViewById(w.h.frs_item_num);
        this.bRz = (LinearLayout) view.findViewById(w.h.frs_item_loc_view);
        this.bQs = (TextView) view.findViewById(w.h.frs_item_location_address);
        this.bRA = view.findViewById(w.h.frs_item_location_sep);
        this.bRB = (TbImageView) view.findViewById(w.h.game_activity_banner);
        this.bRD = (TbImageView) view.findViewById(w.h.app_code_banner);
        this.bRE = (TextView) view.findViewById(w.h.app_code_btn);
        this.bRC = (RelativeLayout) view.findViewById(w.h.app_code_wrapper);
        this.bcb = (ThreadSkinView) view.findViewById(w.h.frs_thread_skin);
    }
}
