package com.baidu.tieba.frs;

import android.view.View;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.baidu.adp.widget.ListView.j;
import com.baidu.tbadk.core.view.HeadImageView;
import com.baidu.tbadk.core.view.UserIconBox;
import com.baidu.tbadk.widget.TbImageView;
import com.baidu.tieba.d;
import com.baidu.tieba.pb.ThreadSkinView;
import com.baidu.tieba.tbadkCore.FrsCommonImageLayout;
import com.baidu.tieba.tbadkCore.voice.PlayVoiceBnt;
/* loaded from: classes.dex */
public class m extends j.a {
    public TextView amw;
    public TextView amz;
    public UserIconBox anO;
    public UserIconBox anP;
    public int aoN;
    public ThreadSkinView bna;
    public TextView crs;
    public TextView crt;
    public int cse;
    public FrameLayout csf;
    public LinearLayout csg;
    public RelativeLayout csh;
    public TbImageView csi;
    public TextView csj;
    public PlayVoiceBnt csk;
    public FrsCommonImageLayout csl;
    public TextView csm;
    public HeadImageView csn;
    public TextView cso;
    public TextView csp;
    public RelativeLayout csq;
    public LinearLayout csr;
    public LinearLayout css;
    public LinearLayout cst;
    public View csu;
    public TbImageView csv;
    public RelativeLayout csw;
    public TbImageView csx;
    public TextView csy;
    public TextView mTitle;

    public m(View view, int i) {
        super(view);
        this.aoN = 3;
        this.cse = 0;
        this.cse = i;
        this.csf = (FrameLayout) view.findViewById(d.h.frs_list);
        this.csq = (RelativeLayout) view.findViewById(d.h.frs_item_user_info_view);
        this.csr = (LinearLayout) view.findViewById(d.h.frs_item_base_user_info);
        this.csg = (LinearLayout) view.findViewById(d.h.frs_list_item_top_linear_layout);
        FrameLayout.LayoutParams layoutParams = (FrameLayout.LayoutParams) this.csg.getLayoutParams();
        layoutParams.topMargin = i;
        this.csg.setLayoutParams(layoutParams);
        this.csh = (RelativeLayout) view.findViewById(d.h.frs_list_item_top_card);
        this.csi = (TbImageView) view.findViewById(d.h.frs_normal_item_theme_card);
        this.csn = (HeadImageView) view.findViewById(d.h.frs_photo);
        this.anO = (UserIconBox) view.findViewById(d.h.frs_user_tshow_icon_box);
        this.anP = (UserIconBox) view.findViewById(d.h.frs_user_icon_box);
        this.csm = (TextView) view.findViewById(d.h.frs_lv_author);
        this.amw = (TextView) view.findViewById(d.h.frs_lv_reply_time);
        this.mTitle = (TextView) view.findViewById(d.h.frs_lv_title);
        this.csj = (TextView) view.findViewById(d.h.abstract_text);
        this.csk = (PlayVoiceBnt) view.findViewById(d.h.abstract_voice);
        this.csl = (FrsCommonImageLayout) view.findViewById(d.h.abstract_img_layout);
        this.amz = (TextView) view.findViewById(d.h.frs_praise_num);
        this.cso = (TextView) view.findViewById(d.h.action_button);
        this.crt = (TextView) view.findViewById(d.h.frs_reply_num);
        this.csp = (TextView) view.findViewById(d.h.frs_more_abstract);
        this.css = (LinearLayout) view.findViewById(d.h.frs_item_num);
        this.cst = (LinearLayout) view.findViewById(d.h.frs_item_loc_view);
        this.crs = (TextView) view.findViewById(d.h.frs_item_location_address);
        this.csu = view.findViewById(d.h.frs_item_location_sep);
        this.csv = (TbImageView) view.findViewById(d.h.game_activity_banner);
        this.csx = (TbImageView) view.findViewById(d.h.app_code_banner);
        this.csy = (TextView) view.findViewById(d.h.app_code_btn);
        this.csw = (RelativeLayout) view.findViewById(d.h.app_code_wrapper);
        this.bna = (ThreadSkinView) view.findViewById(d.h.frs_thread_skin);
    }
}
