package com.baidu.tieba.frs;

import android.view.View;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.baidu.adp.widget.ListView.j;
import com.baidu.tbadk.core.view.HeadImageView;
import com.baidu.tbadk.core.view.UserIconBox;
import com.baidu.tbadk.widget.TbImageView;
import com.baidu.tieba.d;
import com.baidu.tieba.pb.ThreadSkinView;
import com.baidu.tieba.tbadkCore.FrsCommonImageLayout;
import com.baidu.tieba.tbadkCore.voice.PlayVoiceBnt;
/* loaded from: classes.dex */
public class m extends j.a {
    public TextView amQ;
    public TextView amT;
    public UserIconBox aoi;
    public UserIconBox aoj;
    public int aph;
    public ThreadSkinView boR;
    public PlayVoiceBnt cAa;
    public FrsCommonImageLayout cAb;
    public TextView cAc;
    public HeadImageView cAd;
    public TextView cAe;
    public TextView cAf;
    public RelativeLayout cAg;
    public LinearLayout cAh;
    public LinearLayout cAi;
    public LinearLayout cAj;
    public View cAk;
    public TbImageView cAl;
    public RelativeLayout cAm;
    public TbImageView cAn;
    public TextView cAo;
    public int czU;
    public FrameLayout czV;
    public LinearLayout czW;
    public RelativeLayout czX;
    public TbImageView czY;
    public TextView czZ;
    public TextView czg;
    public TextView czh;
    public TextView mTitle;

    public m(View view, int i) {
        super(view);
        this.aph = 3;
        this.czU = 0;
        this.czU = i;
        this.czV = (FrameLayout) view.findViewById(d.g.frs_list);
        this.cAg = (RelativeLayout) view.findViewById(d.g.frs_item_user_info_view);
        this.cAh = (LinearLayout) view.findViewById(d.g.frs_item_base_user_info);
        this.czW = (LinearLayout) view.findViewById(d.g.frs_list_item_top_linear_layout);
        FrameLayout.LayoutParams layoutParams = (FrameLayout.LayoutParams) this.czW.getLayoutParams();
        layoutParams.topMargin = i;
        this.czW.setLayoutParams(layoutParams);
        this.czX = (RelativeLayout) view.findViewById(d.g.frs_list_item_top_card);
        this.czY = (TbImageView) view.findViewById(d.g.frs_normal_item_theme_card);
        this.cAd = (HeadImageView) view.findViewById(d.g.frs_photo);
        this.aoi = (UserIconBox) view.findViewById(d.g.frs_user_tshow_icon_box);
        this.aoj = (UserIconBox) view.findViewById(d.g.frs_user_icon_box);
        this.cAc = (TextView) view.findViewById(d.g.frs_lv_author);
        this.amQ = (TextView) view.findViewById(d.g.frs_lv_reply_time);
        this.mTitle = (TextView) view.findViewById(d.g.frs_lv_title);
        this.czZ = (TextView) view.findViewById(d.g.abstract_text);
        this.cAa = (PlayVoiceBnt) view.findViewById(d.g.abstract_voice);
        this.cAb = (FrsCommonImageLayout) view.findViewById(d.g.abstract_img_layout);
        this.amT = (TextView) view.findViewById(d.g.frs_praise_num);
        this.cAe = (TextView) view.findViewById(d.g.action_button);
        this.czh = (TextView) view.findViewById(d.g.frs_reply_num);
        this.cAf = (TextView) view.findViewById(d.g.frs_more_abstract);
        this.cAi = (LinearLayout) view.findViewById(d.g.frs_item_num);
        this.cAj = (LinearLayout) view.findViewById(d.g.frs_item_loc_view);
        this.czg = (TextView) view.findViewById(d.g.frs_item_location_address);
        this.cAk = view.findViewById(d.g.frs_item_location_sep);
        this.cAl = (TbImageView) view.findViewById(d.g.game_activity_banner);
        this.cAn = (TbImageView) view.findViewById(d.g.app_code_banner);
        this.cAo = (TextView) view.findViewById(d.g.app_code_btn);
        this.cAm = (RelativeLayout) view.findViewById(d.g.app_code_wrapper);
        this.boR = (ThreadSkinView) view.findViewById(d.g.frs_thread_skin);
    }
}
