package com.baidu.swan.apps.scheme;

import com.baidu.searchbox.unitedscheme.UnitedSchemeMainDispatcher;
import com.baidu.swan.apps.scheme.actions.l;
import com.baidu.swan.apps.scheme.actions.n;
import com.baidu.swan.apps.scheme.actions.r;
import com.baidu.swan.apps.scheme.actions.u;
import com.baidu.swan.apps.storage.a.k;
/* loaded from: classes2.dex */
public final class e {
    private static final boolean DEBUG = com.baidu.swan.apps.b.DEBUG;

    public static j a(UnitedSchemeMainDispatcher unitedSchemeMainDispatcher) {
        j jVar = new j();
        unitedSchemeMainDispatcher.setDynamicDispatcher("swan", jVar);
        com.baidu.swan.apps.u.a.CW().a(jVar);
        jVar.a(new com.baidu.swan.apps.scheme.actions.h.e(jVar));
        jVar.a(new com.baidu.swan.apps.scheme.actions.h.d(jVar));
        jVar.a(new com.baidu.swan.apps.scheme.actions.h.i(jVar));
        jVar.a(new com.baidu.swan.apps.scheme.actions.h.h(jVar));
        jVar.a(new com.baidu.swan.apps.scheme.actions.h.g(jVar));
        jVar.a(new com.baidu.swan.apps.scheme.actions.h.b(jVar));
        jVar.a(new com.baidu.swan.apps.scheme.actions.f.c(jVar));
        jVar.a(new com.baidu.swan.apps.scheme.actions.f.b(jVar));
        jVar.a(new com.baidu.swan.apps.scheme.actions.f.a(jVar));
        jVar.a(new com.baidu.swan.apps.scheme.actions.f.d(jVar));
        jVar.a(new com.baidu.swan.apps.scheme.actions.g.b(jVar));
        jVar.a(new com.baidu.swan.apps.scheme.actions.g.a(jVar));
        jVar.a(new com.baidu.swan.apps.scheme.actions.j.a(jVar));
        jVar.a(new com.baidu.swan.apps.scheme.actions.j.c(jVar));
        jVar.a(new com.baidu.swan.apps.scheme.actions.j.b(jVar));
        jVar.a(new com.baidu.swan.apps.scheme.actions.h(jVar));
        jVar.a(new com.baidu.swan.apps.scheme.actions.e.a(jVar));
        jVar.a(new com.baidu.swan.apps.canvas.a.d(jVar));
        jVar.a(new com.baidu.swan.apps.canvas.a.g(jVar));
        jVar.a(new com.baidu.swan.apps.canvas.a.i(jVar));
        jVar.a(new com.baidu.swan.apps.canvas.a.b(jVar));
        jVar.a(new com.baidu.swan.apps.canvas.a.e(jVar));
        jVar.a(new com.baidu.swan.apps.canvas.a.h(jVar));
        jVar.a(new com.baidu.swan.apps.media.audio.a.b(jVar));
        jVar.a(new com.baidu.swan.apps.media.audio.a.a(jVar));
        jVar.a(new com.baidu.swan.apps.media.b.a.a(jVar));
        jVar.a(new com.baidu.swan.apps.media.d.a.b(jVar));
        jVar.a(new com.baidu.swan.apps.core.b.a(jVar));
        jVar.a(new com.baidu.swan.apps.console.a.b(jVar));
        jVar.a(new k(jVar));
        jVar.a(new com.baidu.swan.apps.storage.a.d(jVar));
        jVar.a(new com.baidu.swan.apps.storage.a.e(jVar));
        jVar.a(new com.baidu.swan.apps.storage.a.h(jVar));
        jVar.a(new com.baidu.swan.apps.network.g(jVar));
        jVar.a(new com.baidu.swan.apps.r.f(jVar));
        jVar.a(new com.baidu.swan.apps.r.a(jVar));
        jVar.a(new com.baidu.swan.apps.r.g(jVar));
        jVar.a(new com.baidu.swan.apps.tabbar.a.a(jVar));
        jVar.a(new com.baidu.swan.apps.tabbar.a.b(jVar));
        jVar.a(new com.baidu.swan.apps.tabbar.a.c(jVar));
        jVar.a(new com.baidu.swan.apps.tabbar.a.d(jVar));
        jVar.a(new com.baidu.swan.apps.tabbar.a.e(jVar));
        jVar.a(new com.baidu.swan.apps.tabbar.a.f(jVar));
        jVar.a(new com.baidu.swan.apps.tabbar.a.g(jVar));
        jVar.a(new com.baidu.swan.apps.tabbar.a.h(jVar));
        jVar.a(new com.baidu.swan.apps.x.a(jVar));
        jVar.a(new com.baidu.swan.apps.camera.a.b(jVar));
        jVar.a(new com.baidu.swan.apps.camera.a.g(jVar));
        jVar.a(new com.baidu.swan.apps.camera.a.c(jVar));
        jVar.a(new com.baidu.swan.apps.camera.a.f(jVar));
        jVar.a(new com.baidu.swan.apps.camera.a.d(jVar));
        jVar.a(new com.baidu.swan.apps.camera.a.e(jVar));
        jVar.a(new com.baidu.swan.apps.view.coverview.a.b(jVar));
        jVar.a(new com.baidu.swan.apps.view.coverview.a.a(jVar));
        jVar.a(new com.baidu.swan.apps.n.a(jVar));
        jVar.a(new com.baidu.swan.apps.s.a(jVar));
        jVar.a(new com.baidu.swan.apps.c.a.a(jVar));
        jVar.a(new com.baidu.swan.apps.aj.f.a.a(jVar));
        jVar.a(new com.baidu.swan.apps.aj.f.a.b(jVar));
        jVar.a(new com.baidu.swan.apps.aj.c.a.a(jVar));
        jVar.a(new com.baidu.swan.apps.view.c.a(jVar));
        jVar.a(new com.baidu.swan.apps.g.b(jVar));
        jVar.a(new com.baidu.swan.apps.media.a.a.a(jVar));
        jVar.a(new com.baidu.swan.apps.storage.a.c(jVar));
        jVar.a(new com.baidu.swan.apps.i.a.a(jVar));
        jVar.a(new com.baidu.swan.apps.textarea.a.b(jVar));
        jVar.a(new com.baidu.swan.apps.textarea.a.a(jVar));
        jVar.a(new com.baidu.swan.apps.textarea.a.c(jVar));
        jVar.a(new com.baidu.swan.apps.aj.e.a.a(jVar));
        jVar.a(new com.baidu.swan.apps.scheme.actions.d.c(jVar));
        jVar.a(new com.baidu.swan.apps.scheme.actions.d.a(jVar));
        jVar.a(new r(jVar));
        if (DEBUG) {
            jVar.a(new com.baidu.swan.apps.scheme.actions.i.a(jVar));
            jVar.a(new com.baidu.swan.apps.console.property.c(jVar));
        }
        jVar.a(new u(jVar));
        jVar.a(new l(jVar));
        jVar.a(new com.baidu.swan.apps.scheme.actions.b(jVar));
        jVar.a(new n(jVar));
        jVar.a(new com.baidu.swan.apps.canvas.a.c(jVar));
        jVar.a(new com.baidu.swan.apps.canvas.a.f(jVar));
        jVar.a(new com.baidu.swan.apps.button.a.a(jVar));
        jVar.a(new com.baidu.swan.apps.scheme.actions.b.a(jVar));
        jVar.a(new com.baidu.swan.apps.scheme.actions.b.d(jVar));
        jVar.a(new com.baidu.swan.apps.scheme.actions.b.e(jVar));
        jVar.a(new com.baidu.swan.apps.scheme.actions.b.c(jVar));
        jVar.a(new com.baidu.swan.apps.scheme.actions.b.f(jVar));
        jVar.a(new com.baidu.swan.apps.d.a(jVar));
        jVar.a(new com.baidu.swan.apps.extcore.a.a(jVar));
        jVar.a(new com.baidu.swan.apps.scheme.actions.a.a(jVar));
        jVar.a(new com.baidu.swan.apps.scheme.actions.a.b(jVar));
        return jVar;
    }
}
