package com.baidu.tieba.emotion;

import com.baidu.tbadk.editortools.emotiontool.b;
import com.baidu.tieba.w;
/* loaded from: classes.dex */
public class PlugInFaceProviderStatic extends b {
    static {
        aAC.put("video_icon", Integer.valueOf(w.g.ico_link_video));
        aAC.put("image_emoticon34", Integer.valueOf(w.g.image_emoticon34));
        aAC.put("image_emoticon35", Integer.valueOf(w.g.image_emoticon35));
        aAC.put("image_emoticon36", Integer.valueOf(w.g.image_emoticon36));
        aAC.put("image_emoticon37", Integer.valueOf(w.g.image_emoticon37));
        aAC.put("image_emoticon38", Integer.valueOf(w.g.image_emoticon38));
        aAC.put("image_emoticon40", Integer.valueOf(w.g.image_emoticon40));
        aAC.put("image_emoticon39", Integer.valueOf(w.g.image_emoticon39));
        aAC.put("image_emoticon41", Integer.valueOf(w.g.image_emoticon41));
        aAC.put("image_emoticon42", Integer.valueOf(w.g.image_emoticon42));
        aAC.put("image_emoticon43", Integer.valueOf(w.g.image_emoticon43));
        aAC.put("image_emoticon44", Integer.valueOf(w.g.image_emoticon44));
        aAC.put("image_emoticon45", Integer.valueOf(w.g.image_emoticon45));
        aAC.put("image_emoticon46", Integer.valueOf(w.g.image_emoticon46));
        aAC.put("image_emoticon47", Integer.valueOf(w.g.image_emoticon47));
        aAC.put("image_emoticon48", Integer.valueOf(w.g.image_emoticon48));
        aAC.put("image_emoticon49", Integer.valueOf(w.g.image_emoticon49));
        aAC.put("image_emoticon50", Integer.valueOf(w.g.image_emoticon50));
        aAC.put("image_emoticon77", Integer.valueOf(w.g.image_emoticon77));
        aAC.put("image_emoticon78", Integer.valueOf(w.g.image_emoticon78));
        aAC.put("image_emoticon79", Integer.valueOf(w.g.image_emoticon79));
        aAC.put("image_emoticon80", Integer.valueOf(w.g.image_emoticon80));
        aAC.put("image_emoticon81", Integer.valueOf(w.g.image_emoticon81));
        aAC.put("image_emoticon82", Integer.valueOf(w.g.image_emoticon82));
        aAC.put("image_emoticon83", Integer.valueOf(w.g.image_emoticon83));
        aAC.put("image_emoticon84", Integer.valueOf(w.g.image_emoticon84));
        aAC.put("ali_001", Integer.valueOf(w.g.ali_001));
        aAC.put("ali_002", Integer.valueOf(w.g.ali_002));
        aAC.put("ali_003", Integer.valueOf(w.g.ali_003));
        aAC.put("ali_004", Integer.valueOf(w.g.ali_004));
        aAC.put("ali_005", Integer.valueOf(w.g.ali_005));
        aAC.put("ali_006", Integer.valueOf(w.g.ali_006));
        aAC.put("ali_007", Integer.valueOf(w.g.ali_007));
        aAC.put("ali_008", Integer.valueOf(w.g.ali_008));
        aAC.put("ali_009", Integer.valueOf(w.g.ali_009));
        aAC.put("ali_010", Integer.valueOf(w.g.ali_010));
        aAC.put("ali_011", Integer.valueOf(w.g.ali_011));
        aAC.put("ali_012", Integer.valueOf(w.g.ali_012));
        aAC.put("ali_013", Integer.valueOf(w.g.ali_013));
        aAC.put("ali_014", Integer.valueOf(w.g.ali_014));
        aAC.put("ali_015", Integer.valueOf(w.g.ali_015));
        aAC.put("ali_016", Integer.valueOf(w.g.ali_016));
        aAC.put("ali_017", Integer.valueOf(w.g.ali_017));
        aAC.put("ali_018", Integer.valueOf(w.g.ali_018));
        aAC.put("ali_019", Integer.valueOf(w.g.ali_019));
        aAC.put("ali_020", Integer.valueOf(w.g.ali_020));
        aAC.put("ali_021", Integer.valueOf(w.g.ali_021));
        aAC.put("ali_022", Integer.valueOf(w.g.ali_022));
        aAC.put("ali_023", Integer.valueOf(w.g.ali_023));
        aAC.put("ali_024", Integer.valueOf(w.g.ali_024));
        aAC.put("ali_025", Integer.valueOf(w.g.ali_025));
        aAC.put("ali_026", Integer.valueOf(w.g.ali_026));
        aAC.put("ali_027", Integer.valueOf(w.g.ali_027));
        aAC.put("ali_028", Integer.valueOf(w.g.ali_028));
        aAC.put("ali_029", Integer.valueOf(w.g.ali_029));
        aAC.put("ali_030", Integer.valueOf(w.g.ali_030));
        aAC.put("ali_031", Integer.valueOf(w.g.ali_031));
        aAC.put("ali_032", Integer.valueOf(w.g.ali_032));
        aAC.put("ali_033", Integer.valueOf(w.g.ali_033));
        aAC.put("ali_034", Integer.valueOf(w.g.ali_034));
        aAC.put("ali_035", Integer.valueOf(w.g.ali_035));
        aAC.put("ali_036", Integer.valueOf(w.g.ali_036));
        aAC.put("ali_037", Integer.valueOf(w.g.ali_037));
        aAC.put("ali_038", Integer.valueOf(w.g.ali_038));
        aAC.put("ali_039", Integer.valueOf(w.g.ali_039));
        aAC.put("ali_040", Integer.valueOf(w.g.ali_040));
        aAC.put("ali_041", Integer.valueOf(w.g.ali_041));
        aAC.put("ali_042", Integer.valueOf(w.g.ali_042));
        aAC.put("ali_043", Integer.valueOf(w.g.ali_043));
        aAC.put("ali_044", Integer.valueOf(w.g.ali_044));
        aAC.put("ali_045", Integer.valueOf(w.g.ali_045));
        aAC.put("ali_046", Integer.valueOf(w.g.ali_046));
        aAC.put("ali_047", Integer.valueOf(w.g.ali_047));
        aAC.put("ali_048", Integer.valueOf(w.g.ali_048));
        aAC.put("ali_049", Integer.valueOf(w.g.ali_049));
        aAC.put("ali_050", Integer.valueOf(w.g.ali_050));
        aAC.put("ali_051", Integer.valueOf(w.g.ali_051));
        aAC.put("ali_052", Integer.valueOf(w.g.ali_052));
        aAC.put("ali_053", Integer.valueOf(w.g.ali_053));
        aAC.put("ali_054", Integer.valueOf(w.g.ali_054));
        aAC.put("ali_055", Integer.valueOf(w.g.ali_055));
        aAC.put("ali_056", Integer.valueOf(w.g.ali_056));
        aAC.put("ali_057", Integer.valueOf(w.g.ali_057));
        aAC.put("ali_058", Integer.valueOf(w.g.ali_058));
        aAC.put("ali_059", Integer.valueOf(w.g.ali_059));
        aAC.put("ali_060", Integer.valueOf(w.g.ali_060));
        aAC.put("ali_061", Integer.valueOf(w.g.ali_061));
        aAC.put("ali_062", Integer.valueOf(w.g.ali_062));
        aAC.put("ali_063", Integer.valueOf(w.g.ali_063));
        aAC.put("ali_064", Integer.valueOf(w.g.ali_064));
        aAC.put("ali_065", Integer.valueOf(w.g.ali_065));
        aAC.put("ali_066", Integer.valueOf(w.g.ali_066));
        aAC.put("ali_067", Integer.valueOf(w.g.ali_067));
        aAC.put("ali_068", Integer.valueOf(w.g.ali_068));
        aAC.put("ali_069", Integer.valueOf(w.g.ali_069));
        aAC.put("ali_070", Integer.valueOf(w.g.ali_070));
        aAC.put("b01", Integer.valueOf(w.g.b01));
        aAC.put("b02", Integer.valueOf(w.g.b02));
        aAC.put("b03", Integer.valueOf(w.g.b03));
        aAC.put("b04", Integer.valueOf(w.g.b04));
        aAC.put("b05", Integer.valueOf(w.g.b05));
        aAC.put("b06", Integer.valueOf(w.g.b06));
        aAC.put("b07", Integer.valueOf(w.g.b07));
        aAC.put("b08", Integer.valueOf(w.g.b08));
        aAC.put("b09", Integer.valueOf(w.g.b09));
        aAC.put("b10", Integer.valueOf(w.g.b10));
        aAC.put("b11", Integer.valueOf(w.g.b11));
        aAC.put("b12", Integer.valueOf(w.g.b12));
        aAC.put("b13", Integer.valueOf(w.g.b13));
        aAC.put("b14", Integer.valueOf(w.g.b14));
        aAC.put("b15", Integer.valueOf(w.g.b15));
        aAC.put("b16", Integer.valueOf(w.g.b16));
        aAC.put("b17", Integer.valueOf(w.g.b17));
        aAC.put("b18", Integer.valueOf(w.g.b18));
        aAC.put("b19", Integer.valueOf(w.g.b19));
        aAC.put("b20", Integer.valueOf(w.g.b20));
        aAC.put("yz_001", Integer.valueOf(w.g.yz_001));
        aAC.put("yz_002", Integer.valueOf(w.g.yz_002));
        aAC.put("yz_003", Integer.valueOf(w.g.yz_003));
        aAC.put("yz_004", Integer.valueOf(w.g.yz_004));
        aAC.put("yz_005", Integer.valueOf(w.g.yz_005));
        aAC.put("yz_006", Integer.valueOf(w.g.yz_006));
        aAC.put("yz_007", Integer.valueOf(w.g.yz_007));
        aAC.put("yz_008", Integer.valueOf(w.g.yz_008));
        aAD.add(Integer.valueOf(w.g.image_emoticon34));
        aAD.add(Integer.valueOf(w.g.image_emoticon35));
        aAD.add(Integer.valueOf(w.g.image_emoticon36));
        aAD.add(Integer.valueOf(w.g.image_emoticon37));
        aAD.add(Integer.valueOf(w.g.image_emoticon38));
        aAD.add(Integer.valueOf(w.g.image_emoticon40));
        aAD.add(Integer.valueOf(w.g.image_emoticon39));
        aAD.add(Integer.valueOf(w.g.image_emoticon41));
        aAD.add(Integer.valueOf(w.g.image_emoticon43));
        aAD.add(Integer.valueOf(w.g.image_emoticon44));
        aAD.add(Integer.valueOf(w.g.image_emoticon48));
        aAD.add(Integer.valueOf(w.g.image_emoticon47));
        aAD.add(Integer.valueOf(w.g.image_emoticon46));
        aAD.add(Integer.valueOf(w.g.image_emoticon50));
        aAD.add(Integer.valueOf(w.g.image_emoticon77));
        aAD.add(Integer.valueOf(w.g.image_emoticon78));
        aAD.add(Integer.valueOf(w.g.image_emoticon79));
        aAD.add(Integer.valueOf(w.g.image_emoticon80));
        aAD.add(Integer.valueOf(w.g.image_emoticon81));
        aAD.add(Integer.valueOf(w.g.image_emoticon82));
        aAD.add(Integer.valueOf(w.g.image_emoticon83));
        aAD.add(Integer.valueOf(w.g.image_emoticon84));
        aAD.add(Integer.valueOf(w.g.image_emoticon45));
        aAD.add(Integer.valueOf(w.g.image_emoticon42));
        aAD.add(Integer.valueOf(w.g.ali_001));
        aAD.add(Integer.valueOf(w.g.ali_002));
        aAD.add(Integer.valueOf(w.g.ali_003));
        aAD.add(Integer.valueOf(w.g.ali_004));
        aAD.add(Integer.valueOf(w.g.ali_005));
        aAD.add(Integer.valueOf(w.g.ali_006));
        aAD.add(Integer.valueOf(w.g.ali_007));
        aAD.add(Integer.valueOf(w.g.ali_008));
        aAD.add(Integer.valueOf(w.g.ali_009));
        aAD.add(Integer.valueOf(w.g.ali_010));
        aAD.add(Integer.valueOf(w.g.ali_011));
        aAD.add(Integer.valueOf(w.g.ali_012));
        aAD.add(Integer.valueOf(w.g.ali_013));
        aAD.add(Integer.valueOf(w.g.ali_014));
        aAD.add(Integer.valueOf(w.g.ali_015));
        aAD.add(Integer.valueOf(w.g.ali_016));
        aAD.add(Integer.valueOf(w.g.ali_017));
        aAD.add(Integer.valueOf(w.g.ali_018));
        aAD.add(Integer.valueOf(w.g.ali_019));
        aAD.add(Integer.valueOf(w.g.ali_020));
        aAD.add(Integer.valueOf(w.g.ali_021));
        aAD.add(Integer.valueOf(w.g.ali_022));
        aAD.add(Integer.valueOf(w.g.ali_023));
        aAD.add(Integer.valueOf(w.g.ali_024));
        aAD.add(Integer.valueOf(w.g.ali_025));
        aAD.add(Integer.valueOf(w.g.ali_026));
        aAD.add(Integer.valueOf(w.g.ali_027));
        aAD.add(Integer.valueOf(w.g.ali_028));
        aAD.add(Integer.valueOf(w.g.ali_029));
        aAD.add(Integer.valueOf(w.g.ali_030));
        aAD.add(Integer.valueOf(w.g.ali_031));
        aAD.add(Integer.valueOf(w.g.ali_032));
        aAD.add(Integer.valueOf(w.g.ali_033));
        aAD.add(Integer.valueOf(w.g.ali_034));
        aAD.add(Integer.valueOf(w.g.ali_035));
        aAD.add(Integer.valueOf(w.g.ali_036));
        aAD.add(Integer.valueOf(w.g.ali_037));
        aAD.add(Integer.valueOf(w.g.ali_038));
        aAD.add(Integer.valueOf(w.g.ali_039));
        aAD.add(Integer.valueOf(w.g.ali_040));
        aAD.add(Integer.valueOf(w.g.ali_041));
        aAD.add(Integer.valueOf(w.g.ali_042));
        aAD.add(Integer.valueOf(w.g.ali_043));
        aAD.add(Integer.valueOf(w.g.ali_044));
        aAD.add(Integer.valueOf(w.g.ali_045));
        aAD.add(Integer.valueOf(w.g.ali_046));
        aAD.add(Integer.valueOf(w.g.ali_047));
        aAD.add(Integer.valueOf(w.g.ali_048));
        aAD.add(Integer.valueOf(w.g.ali_049));
        aAD.add(Integer.valueOf(w.g.ali_050));
        aAD.add(Integer.valueOf(w.g.ali_051));
        aAD.add(Integer.valueOf(w.g.ali_052));
        aAD.add(Integer.valueOf(w.g.ali_053));
        aAD.add(Integer.valueOf(w.g.ali_054));
        aAD.add(Integer.valueOf(w.g.ali_055));
        aAD.add(Integer.valueOf(w.g.ali_056));
        aAD.add(Integer.valueOf(w.g.ali_057));
        aAD.add(Integer.valueOf(w.g.ali_058));
        aAD.add(Integer.valueOf(w.g.ali_059));
        aAD.add(Integer.valueOf(w.g.ali_060));
        aAD.add(Integer.valueOf(w.g.ali_061));
        aAD.add(Integer.valueOf(w.g.ali_062));
        aAD.add(Integer.valueOf(w.g.ali_063));
        aAD.add(Integer.valueOf(w.g.ali_064));
        aAD.add(Integer.valueOf(w.g.ali_065));
        aAD.add(Integer.valueOf(w.g.ali_066));
        aAD.add(Integer.valueOf(w.g.ali_067));
        aAD.add(Integer.valueOf(w.g.ali_068));
        aAD.add(Integer.valueOf(w.g.ali_069));
        aAD.add(Integer.valueOf(w.g.ali_070));
        aAD.add(Integer.valueOf(w.g.yz_001));
        aAD.add(Integer.valueOf(w.g.yz_002));
        aAD.add(Integer.valueOf(w.g.yz_003));
        aAD.add(Integer.valueOf(w.g.yz_004));
        aAD.add(Integer.valueOf(w.g.yz_005));
        aAD.add(Integer.valueOf(w.g.yz_006));
        aAD.add(Integer.valueOf(w.g.yz_007));
        aAD.add(Integer.valueOf(w.g.yz_008));
        aAD.add(Integer.valueOf(w.g.b01));
        aAD.add(Integer.valueOf(w.g.b02));
        aAD.add(Integer.valueOf(w.g.b03));
        aAD.add(Integer.valueOf(w.g.b04));
        aAD.add(Integer.valueOf(w.g.b05));
        aAD.add(Integer.valueOf(w.g.b06));
        aAD.add(Integer.valueOf(w.g.b07));
        aAD.add(Integer.valueOf(w.g.b08));
        aAD.add(Integer.valueOf(w.g.b09));
        aAD.add(Integer.valueOf(w.g.b10));
        aAD.add(Integer.valueOf(w.g.b11));
        aAD.add(Integer.valueOf(w.g.b12));
        aAD.add(Integer.valueOf(w.g.b13));
        aAD.add(Integer.valueOf(w.g.b14));
        aAD.add(Integer.valueOf(w.g.b15));
        aAD.add(Integer.valueOf(w.g.b16));
        aAD.add(Integer.valueOf(w.g.b17));
        aAD.add(Integer.valueOf(w.g.b18));
        aAD.add(Integer.valueOf(w.g.b19));
        aAD.add(Integer.valueOf(w.g.b20));
        aAE.put("#(爱心)", Integer.valueOf(w.g.image_emoticon34));
        aAE.put("#(心碎)", Integer.valueOf(w.g.image_emoticon35));
        aAE.put("#(玫瑰)", Integer.valueOf(w.g.image_emoticon36));
        aAE.put("#(礼物)", Integer.valueOf(w.g.image_emoticon37));
        aAE.put("#(彩虹)", Integer.valueOf(w.g.image_emoticon38));
        aAE.put("#(星星月亮)", Integer.valueOf(w.g.image_emoticon39));
        aAE.put("#(太阳)", Integer.valueOf(w.g.image_emoticon40));
        aAE.put("#(钱币)", Integer.valueOf(w.g.image_emoticon41));
        aAE.put("#(灯泡)", Integer.valueOf(w.g.image_emoticon42));
        aAE.put("#(茶杯)", Integer.valueOf(w.g.image_emoticon43));
        aAE.put("#(蛋糕)", Integer.valueOf(w.g.image_emoticon44));
        aAE.put("#(音乐)", Integer.valueOf(w.g.image_emoticon45));
        aAE.put("#(haha)", Integer.valueOf(w.g.image_emoticon46));
        aAE.put("#(胜利)", Integer.valueOf(w.g.image_emoticon47));
        aAE.put("#(大拇指)", Integer.valueOf(w.g.image_emoticon48));
        aAE.put("#(弱)", Integer.valueOf(w.g.image_emoticon49));
        aAE.put("#(OK)", Integer.valueOf(w.g.image_emoticon50));
        aAE.put("#(沙发)", Integer.valueOf(w.g.image_emoticon77));
        aAE.put("#(手纸)", Integer.valueOf(w.g.image_emoticon78));
        aAE.put("#(香蕉)", Integer.valueOf(w.g.image_emoticon79));
        aAE.put("#(便便)", Integer.valueOf(w.g.image_emoticon80));
        aAE.put("#(药丸)", Integer.valueOf(w.g.image_emoticon81));
        aAE.put("#(红领巾)", Integer.valueOf(w.g.image_emoticon82));
        aAE.put("#(蜡烛)", Integer.valueOf(w.g.image_emoticon83));
        aAE.put("#(三道杠)", Integer.valueOf(w.g.image_emoticon84));
        aAE.put("#(赖皮)", Integer.valueOf(w.g.ali_001));
        aAE.put("#(感动)", Integer.valueOf(w.g.ali_002));
        aAE.put("#(十分惊讶)", Integer.valueOf(w.g.ali_003));
        aAE.put("#(怒气)", Integer.valueOf(w.g.ali_004));
        aAE.put("#(哭泣)", Integer.valueOf(w.g.ali_005));
        aAE.put("#(吃惊)", Integer.valueOf(w.g.ali_006));
        aAE.put("#(嘲弄)", Integer.valueOf(w.g.ali_007));
        aAE.put("#(飘过)", Integer.valueOf(w.g.ali_008));
        aAE.put("#(转圈哭)", Integer.valueOf(w.g.ali_009));
        aAE.put("#(神经病)", Integer.valueOf(w.g.ali_010));
        aAE.put("#(揪耳朵)", Integer.valueOf(w.g.ali_011));
        aAE.put("#(惊汗)", Integer.valueOf(w.g.ali_012));
        aAE.put("#(隐身)", Integer.valueOf(w.g.ali_013));
        aAE.put("#(不要嘛)", Integer.valueOf(w.g.ali_014));
        aAE.put("#(遁)", Integer.valueOf(w.g.ali_015));
        aAE.put("#(不公平)", Integer.valueOf(w.g.ali_016));
        aAE.put("#(爬来了)", Integer.valueOf(w.g.ali_017));
        aAE.put("#(蛋花哭)", Integer.valueOf(w.g.ali_018));
        aAE.put("#(温暖)", Integer.valueOf(w.g.ali_019));
        aAE.put("#(点头)", Integer.valueOf(w.g.ali_020));
        aAE.put("#(撒钱)", Integer.valueOf(w.g.ali_021));
        aAE.put("#(献花)", Integer.valueOf(w.g.ali_022));
        aAE.put("#(寒)", Integer.valueOf(w.g.ali_023));
        aAE.put("#(傻笑)", Integer.valueOf(w.g.ali_024));
        aAE.put("#(扭扭)", Integer.valueOf(w.g.ali_025));
        aAE.put("#(疯)", Integer.valueOf(w.g.ali_026));
        aAE.put("#(抓狂)", Integer.valueOf(w.g.ali_027));
        aAE.put("#(抓)", Integer.valueOf(w.g.ali_028));
        aAE.put("#(蜷)", Integer.valueOf(w.g.ali_029));
        aAE.put("#(挠墙)", Integer.valueOf(w.g.ali_030));
        aAE.put("#(狂笑)", Integer.valueOf(w.g.ali_031));
        aAE.put("#(抱枕)", Integer.valueOf(w.g.ali_032));
        aAE.put("#(吼叫)", Integer.valueOf(w.g.ali_033));
        aAE.put("#(嚷)", Integer.valueOf(w.g.ali_034));
        aAE.put("#(唠叨)", Integer.valueOf(w.g.ali_035));
        aAE.put("#(捏脸)", Integer.valueOf(w.g.ali_036));
        aAE.put("#(爆笑)", Integer.valueOf(w.g.ali_037));
        aAE.put("#(郁闷)", Integer.valueOf(w.g.ali_038));
        aAE.put("#(潜水)", Integer.valueOf(w.g.ali_039));
        aAE.put("#(十分开心)", Integer.valueOf(w.g.ali_040));
        aAE.put("#(冷笑话)", Integer.valueOf(w.g.ali_041));
        aAE.put("#(顶！)", Integer.valueOf(w.g.ali_042));
        aAE.put("#(潜)", Integer.valueOf(w.g.ali_043));
        aAE.put("#(画圈圈)", Integer.valueOf(w.g.ali_044));
        aAE.put("#(玩电脑)", Integer.valueOf(w.g.ali_045));
        aAE.put("#(狂吐)", Integer.valueOf(w.g.ali_046));
        aAE.put("#(哭着跑)", Integer.valueOf(w.g.ali_047));
        aAE.put("#(阿狸侠)", Integer.valueOf(w.g.ali_048));
        aAE.put("#(冷死了)", Integer.valueOf(w.g.ali_049));
        aAE.put("#(惆怅~)", Integer.valueOf(w.g.ali_050));
        aAE.put("#(摸头)", Integer.valueOf(w.g.ali_051));
        aAE.put("#(蹭)", Integer.valueOf(w.g.ali_052));
        aAE.put("#(打滚)", Integer.valueOf(w.g.ali_053));
        aAE.put("#(叩拜)", Integer.valueOf(w.g.ali_054));
        aAE.put("#(摸)", Integer.valueOf(w.g.ali_055));
        aAE.put("#(数钱)", Integer.valueOf(w.g.ali_056));
        aAE.put("#(拖走)", Integer.valueOf(w.g.ali_057));
        aAE.put("#(热)", Integer.valueOf(w.g.ali_058));
        aAE.put("#(加1)", Integer.valueOf(w.g.ali_059));
        aAE.put("#(压力)", Integer.valueOf(w.g.ali_060));
        aAE.put("#(表逼我)", Integer.valueOf(w.g.ali_061));
        aAE.put("#(人呢)", Integer.valueOf(w.g.ali_062));
        aAE.put("#(摇晃)", Integer.valueOf(w.g.ali_063));
        aAE.put("#(打地鼠)", Integer.valueOf(w.g.ali_064));
        aAE.put("#(这个屌)", Integer.valueOf(w.g.ali_065));
        aAE.put("#(恐慌)", Integer.valueOf(w.g.ali_066));
        aAE.put("#(晕乎乎)", Integer.valueOf(w.g.ali_067));
        aAE.put("#(浮云)", Integer.valueOf(w.g.ali_068));
        aAE.put("#(给力)", Integer.valueOf(w.g.ali_069));
        aAE.put("#(杯具了)", Integer.valueOf(w.g.ali_070));
        aAE.put("#(焦糖舞)", Integer.valueOf(w.g.yz_001));
        aAE.put("#(翻滚)", Integer.valueOf(w.g.yz_002));
        aAE.put("#(拍屁股做鬼脸)", Integer.valueOf(w.g.yz_003));
        aAE.put("#(不)", Integer.valueOf(w.g.yz_004));
        aAE.put("#(河蟹掉啦)", Integer.valueOf(w.g.yz_005));
        aAE.put("#(哦耶)", Integer.valueOf(w.g.yz_006));
        aAE.put("#(我倒)", Integer.valueOf(w.g.yz_007));
        aAE.put("#(投降)", Integer.valueOf(w.g.yz_008));
        aAE.put("#(微笑)", Integer.valueOf(w.g.b01));
        aAE.put("#(帅哥)", Integer.valueOf(w.g.b02));
        aAE.put("#(美女)", Integer.valueOf(w.g.b03));
        aAE.put("#(老大)", Integer.valueOf(w.g.b04));
        aAE.put("#(哈哈哈)", Integer.valueOf(w.g.b05));
        aAE.put("#(奸笑)", Integer.valueOf(w.g.b06));
        aAE.put("#(傻乐)", Integer.valueOf(w.g.b07));
        aAE.put("#(飞吻)", Integer.valueOf(w.g.b08));
        aAE.put("#(害羞)", Integer.valueOf(w.g.b09));
        aAE.put("#(花痴)", Integer.valueOf(w.g.b10));
        aAE.put("#(憧憬)", Integer.valueOf(w.g.b11));
        aAE.put("#(你牛)", Integer.valueOf(w.g.b12));
        aAE.put("#(鼓掌)", Integer.valueOf(w.g.b13));
        aAE.put("#(可爱)", Integer.valueOf(w.g.b14));
        aAE.put("#(太委屈)", Integer.valueOf(w.g.b15));
        aAE.put("#(大哭)", Integer.valueOf(w.g.b16));
        aAE.put("#(泪奔)", Integer.valueOf(w.g.b17));
        aAE.put("#(寻死)", Integer.valueOf(w.g.b18));
        aAE.put("#(非常惊讶)", Integer.valueOf(w.g.b19));
        aAE.put("#(表示疑问)", Integer.valueOf(w.g.b20));
    }
}
