package com.baidu.tieba.emotion;

import com.baidu.tbadk.editortools.emotiontool.b;
import com.baidu.tieba.R;
/* loaded from: classes13.dex */
public class PlugInFaceProviderStatic extends b {
    static {
        fvc.put("video_icon", Integer.valueOf(R.drawable.ico_link_video));
        fvc.put("image_emoticon34", Integer.valueOf(R.drawable.image_emoticon34));
        fvc.put("image_emoticon35", Integer.valueOf(R.drawable.image_emoticon35));
        fvc.put("image_emoticon36", Integer.valueOf(R.drawable.image_emoticon36));
        fvc.put("image_emoticon37", Integer.valueOf(R.drawable.image_emoticon37));
        fvc.put("image_emoticon38", Integer.valueOf(R.drawable.image_emoticon38));
        fvc.put("image_emoticon40", Integer.valueOf(R.drawable.image_emoticon40));
        fvc.put("image_emoticon39", Integer.valueOf(R.drawable.image_emoticon39));
        fvc.put("image_emoticon41", Integer.valueOf(R.drawable.image_emoticon41));
        fvc.put("image_emoticon42", Integer.valueOf(R.drawable.image_emoticon42));
        fvc.put("image_emoticon43", Integer.valueOf(R.drawable.image_emoticon43));
        fvc.put("image_emoticon44", Integer.valueOf(R.drawable.image_emoticon44));
        fvc.put("image_emoticon45", Integer.valueOf(R.drawable.image_emoticon45));
        fvc.put("image_emoticon46", Integer.valueOf(R.drawable.image_emoticon46));
        fvc.put("image_emoticon47", Integer.valueOf(R.drawable.image_emoticon47));
        fvc.put("image_emoticon48", Integer.valueOf(R.drawable.image_emoticon48));
        fvc.put("image_emoticon49", Integer.valueOf(R.drawable.image_emoticon49));
        fvc.put("image_emoticon50", Integer.valueOf(R.drawable.image_emoticon50));
        fvc.put("image_emoticon77", Integer.valueOf(R.drawable.image_emoticon77));
        fvc.put("image_emoticon78", Integer.valueOf(R.drawable.image_emoticon78));
        fvc.put("image_emoticon79", Integer.valueOf(R.drawable.image_emoticon79));
        fvc.put("image_emoticon80", Integer.valueOf(R.drawable.image_emoticon80));
        fvc.put("image_emoticon81", Integer.valueOf(R.drawable.image_emoticon81));
        fvc.put("image_emoticon82", Integer.valueOf(R.drawable.image_emoticon82));
        fvc.put("image_emoticon83", Integer.valueOf(R.drawable.image_emoticon83));
        fvc.put("image_emoticon84", Integer.valueOf(R.drawable.image_emoticon84));
        fvc.put("image_emoticon101", Integer.valueOf(R.drawable.image_emoticon101));
        fvc.put("image_emoticon102", Integer.valueOf(R.drawable.image_emoticon102));
        fvc.put("image_emoticon103", Integer.valueOf(R.drawable.image_emoticon103));
        fvc.put("image_emoticon104", Integer.valueOf(R.drawable.image_emoticon104));
        fvc.put("image_emoticon105", Integer.valueOf(R.drawable.image_emoticon105));
        fvc.put("image_emoticon106", Integer.valueOf(R.drawable.image_emoticon106));
        fvc.put("image_emoticon107", Integer.valueOf(R.drawable.image_emoticon107));
        fvc.put("image_emoticon108", Integer.valueOf(R.drawable.image_emoticon108));
        fvc.put("image_emoticon109", Integer.valueOf(R.drawable.image_emoticon109));
        fvc.put("image_emoticon110", Integer.valueOf(R.drawable.image_emoticon110));
        fvc.put("image_emoticon111", Integer.valueOf(R.drawable.image_emoticon111));
        fvc.put("image_emoticon112", Integer.valueOf(R.drawable.image_emoticon112));
        fvc.put("image_emoticon113", Integer.valueOf(R.drawable.image_emoticon113));
        fvc.put("image_emoticon114", Integer.valueOf(R.drawable.image_emoticon114));
        fvc.put("image_emoticon115", Integer.valueOf(R.drawable.image_emoticon115));
        fvc.put("image_emoticon116", Integer.valueOf(R.drawable.image_emoticon116));
        fvc.put("image_emoticon117", Integer.valueOf(R.drawable.image_emoticon117));
        fvc.put("image_emoticon118", Integer.valueOf(R.drawable.image_emoticon118));
        fvc.put("image_emoticon119", Integer.valueOf(R.drawable.image_emoticon119));
        fvc.put("image_emoticon120", Integer.valueOf(R.drawable.image_emoticon120));
        fvc.put("image_emoticon121", Integer.valueOf(R.drawable.image_emoticon121));
        fvc.put("image_emoticon122", Integer.valueOf(R.drawable.image_emoticon122));
        fvc.put("image_emoticon123", Integer.valueOf(R.drawable.image_emoticon123));
        fvc.put("image_emoticon124", Integer.valueOf(R.drawable.image_emoticon124));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon34));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon35));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon36));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon37));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon38));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon40));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon39));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon41));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon43));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon44));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon48));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon47));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon46));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon50));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon77));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon78));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon79));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon80));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon81));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon82));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon83));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon84));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon45));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon42));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon101));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon102));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon103));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon104));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon105));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon106));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon107));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon108));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon109));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon110));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon111));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon112));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon113));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon114));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon115));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon116));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon117));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon118));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon119));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon120));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon121));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon122));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon123));
        fvd.add(Integer.valueOf(R.drawable.image_emoticon124));
        fve.put("#(爱心)", Integer.valueOf(R.drawable.image_emoticon34));
        fve.put("#(心碎)", Integer.valueOf(R.drawable.image_emoticon35));
        fve.put("#(玫瑰)", Integer.valueOf(R.drawable.image_emoticon36));
        fve.put("#(礼物)", Integer.valueOf(R.drawable.image_emoticon37));
        fve.put("#(彩虹)", Integer.valueOf(R.drawable.image_emoticon38));
        fve.put("#(星星月亮)", Integer.valueOf(R.drawable.image_emoticon39));
        fve.put("#(太阳)", Integer.valueOf(R.drawable.image_emoticon40));
        fve.put("#(钱币)", Integer.valueOf(R.drawable.image_emoticon41));
        fve.put("#(灯泡)", Integer.valueOf(R.drawable.image_emoticon42));
        fve.put("#(茶杯)", Integer.valueOf(R.drawable.image_emoticon43));
        fve.put("#(蛋糕)", Integer.valueOf(R.drawable.image_emoticon44));
        fve.put("#(音乐)", Integer.valueOf(R.drawable.image_emoticon45));
        fve.put("#(haha)", Integer.valueOf(R.drawable.image_emoticon46));
        fve.put("#(胜利)", Integer.valueOf(R.drawable.image_emoticon47));
        fve.put("#(大拇指)", Integer.valueOf(R.drawable.image_emoticon48));
        fve.put("#(弱)", Integer.valueOf(R.drawable.image_emoticon49));
        fve.put("#(OK)", Integer.valueOf(R.drawable.image_emoticon50));
        fve.put("#(沙发)", Integer.valueOf(R.drawable.image_emoticon77));
        fve.put("#(手纸)", Integer.valueOf(R.drawable.image_emoticon78));
        fve.put("#(香蕉)", Integer.valueOf(R.drawable.image_emoticon79));
        fve.put("#(便便)", Integer.valueOf(R.drawable.image_emoticon80));
        fve.put("#(药丸)", Integer.valueOf(R.drawable.image_emoticon81));
        fve.put("#(红领巾)", Integer.valueOf(R.drawable.image_emoticon82));
        fve.put("#(蜡烛)", Integer.valueOf(R.drawable.image_emoticon83));
        fve.put("#(三道杠)", Integer.valueOf(R.drawable.image_emoticon84));
        fve.put("#(不跟丑人说话)", Integer.valueOf(R.drawable.image_emoticon101));
        fve.put("#(么么哒)", Integer.valueOf(R.drawable.image_emoticon102));
        fve.put("#(亲亲才能起来)", Integer.valueOf(R.drawable.image_emoticon103));
        fve.put("#(伦家只是宝宝)", Integer.valueOf(R.drawable.image_emoticon104));
        fve.put("#(你是我的人)", Integer.valueOf(R.drawable.image_emoticon105));
        fve.put("#(假装看不见)", Integer.valueOf(R.drawable.image_emoticon106));
        fve.put("#(单身等撩)", Integer.valueOf(R.drawable.image_emoticon107));
        fve.put("#(吓到宝宝了)", Integer.valueOf(R.drawable.image_emoticon108));
        fve.put("#(哈哈哈)", Integer.valueOf(R.drawable.image_emoticon109));
        fve.put("#(嗯嗯)", Integer.valueOf(R.drawable.image_emoticon110));
        fve.put("#(好幸福)", Integer.valueOf(R.drawable.image_emoticon111));
        fve.put("#(宝宝不开心)", Integer.valueOf(R.drawable.image_emoticon112));
        fve.put("#(小姐姐别走)", Integer.valueOf(R.drawable.image_emoticon113));
        fve.put("#(小姐姐在吗)", Integer.valueOf(R.drawable.image_emoticon114));
        fve.put("#(小姐姐来啦)", Integer.valueOf(R.drawable.image_emoticon115));
        fve.put("#(小姐姐来玩呀)", Integer.valueOf(R.drawable.image_emoticon116));
        fve.put("#(我养你)", Integer.valueOf(R.drawable.image_emoticon117));
        fve.put("#(我是不会骗你的)", Integer.valueOf(R.drawable.image_emoticon118));
        fve.put("#(扎心了)", Integer.valueOf(R.drawable.image_emoticon119));
        fve.put("#(无聊)", Integer.valueOf(R.drawable.image_emoticon120));
        fve.put("#(月亮代表我的心)", Integer.valueOf(R.drawable.image_emoticon121));
        fve.put("#(来追我呀)", Integer.valueOf(R.drawable.image_emoticon122));
        fve.put("#(爱你的形状)", Integer.valueOf(R.drawable.image_emoticon123));
        fve.put("#(白眼)", Integer.valueOf(R.drawable.image_emoticon124));
    }
}
