package com.baidu.tieba.util;

import android.content.Context;
import com.baidu.cloudsdk.social.core.util.SocialAPIErrorCodes;
import com.baidu.tieba.TiebaApplication;
import com.slidingmenu.lib.R;
import java.util.ArrayList;
import java.util.HashMap;
/* loaded from: classes.dex */
public class ad implements com.baidu.tbadk.imageManager.b {
    public static final ArrayList<Integer> a;
    public static final HashMap<String, Integer> b;
    private static final HashMap<String, Integer> c = new HashMap<>();
    private static final HashMap<String, String> d;

    static {
        c.put("video_icon", Integer.valueOf((int) R.drawable.ico_link_video));
        c.put("10th_001", Integer.valueOf((int) R.drawable.f10th_001));
        c.put("10th_002", Integer.valueOf((int) R.drawable.f10th_002));
        c.put("10th_003", Integer.valueOf((int) R.drawable.f10th_003));
        c.put("10th_004", Integer.valueOf((int) R.drawable.f10th_004));
        c.put("10th_005", Integer.valueOf((int) R.drawable.f10th_005));
        c.put("10th_006", Integer.valueOf((int) R.drawable.f10th_006));
        c.put("10th_007", Integer.valueOf((int) R.drawable.f10th_007));
        c.put("10th_008", Integer.valueOf((int) R.drawable.f10th_008));
        c.put("10th_009", Integer.valueOf((int) R.drawable.f10th_009));
        c.put("10th_010", Integer.valueOf((int) R.drawable.f10th_010));
        c.put("10th_011", Integer.valueOf((int) R.drawable.f10th_011));
        c.put("10th_012", Integer.valueOf((int) R.drawable.f10th_012));
        c.put("B_0001", Integer.valueOf((int) R.drawable.b_0001));
        c.put("B_0002", Integer.valueOf((int) R.drawable.b_0002));
        c.put("B_0003", Integer.valueOf((int) R.drawable.b_0003));
        c.put("B_0004", Integer.valueOf((int) R.drawable.b_0004));
        c.put("B_0005", Integer.valueOf((int) R.drawable.b_0005));
        c.put("B_0006", Integer.valueOf((int) R.drawable.b_0006));
        c.put("B_0007", Integer.valueOf((int) R.drawable.b_0007));
        c.put("B_0008", Integer.valueOf((int) R.drawable.b_0008));
        c.put("B_0009", Integer.valueOf((int) R.drawable.b_0009));
        c.put("B_0010", Integer.valueOf((int) R.drawable.b_0010));
        c.put("B_0011", Integer.valueOf((int) R.drawable.b_0011));
        c.put("B_0012", Integer.valueOf((int) R.drawable.b_0012));
        c.put("B_0013", Integer.valueOf((int) R.drawable.b_0013));
        c.put("B_0014", Integer.valueOf((int) R.drawable.b_0014));
        c.put("B_0015", Integer.valueOf((int) R.drawable.b_0015));
        c.put("B_0016", Integer.valueOf((int) R.drawable.b_0016));
        c.put("B_0017", Integer.valueOf((int) R.drawable.b_0017));
        c.put("B_0018", Integer.valueOf((int) R.drawable.b_0018));
        c.put("B_0019", Integer.valueOf((int) R.drawable.b_0019));
        c.put("B_0020", Integer.valueOf((int) R.drawable.b_0020));
        c.put("B_0021", Integer.valueOf((int) R.drawable.b_0021));
        c.put("B_0022", Integer.valueOf((int) R.drawable.b_0022));
        c.put("B_0023", Integer.valueOf((int) R.drawable.b_0023));
        c.put("B_0024", Integer.valueOf((int) R.drawable.b_0024));
        c.put("B_0025", Integer.valueOf((int) R.drawable.b_0025));
        c.put("B_0026", Integer.valueOf((int) R.drawable.b_0026));
        c.put("B_0027", Integer.valueOf((int) R.drawable.b_0027));
        c.put("B_0028", Integer.valueOf((int) R.drawable.b_0028));
        c.put("B_0029", Integer.valueOf((int) R.drawable.b_0029));
        c.put("B_0030", Integer.valueOf((int) R.drawable.b_0030));
        c.put("B_0031", Integer.valueOf((int) R.drawable.b_0031));
        c.put("B_0032", Integer.valueOf((int) R.drawable.b_0032));
        c.put("B_0033", Integer.valueOf((int) R.drawable.b_0033));
        c.put("B_0034", Integer.valueOf((int) R.drawable.b_0034));
        c.put("B_0035", Integer.valueOf((int) R.drawable.b_0035));
        c.put("B_0036", Integer.valueOf((int) R.drawable.b_0036));
        c.put("B_0037", Integer.valueOf((int) R.drawable.b_0037));
        c.put("B_0038", Integer.valueOf((int) R.drawable.b_0038));
        c.put("B_0039", Integer.valueOf((int) R.drawable.b_0039));
        c.put("B_0040", Integer.valueOf((int) R.drawable.b_0040));
        c.put("B_0041", Integer.valueOf((int) R.drawable.b_0041));
        c.put("B_0042", Integer.valueOf((int) R.drawable.b_0042));
        c.put("B_0043", Integer.valueOf((int) R.drawable.b_0043));
        c.put("B_0044", Integer.valueOf((int) R.drawable.b_0044));
        c.put("B_0045", Integer.valueOf((int) R.drawable.b_0045));
        c.put("B_0046", Integer.valueOf((int) R.drawable.b_0046));
        c.put("B_0047", Integer.valueOf((int) R.drawable.b_0047));
        c.put("B_0048", Integer.valueOf((int) R.drawable.b_0048));
        c.put("B_0049", Integer.valueOf((int) R.drawable.b_0049));
        c.put("B_0050", Integer.valueOf((int) R.drawable.b_0050));
        c.put("B_0051", Integer.valueOf((int) R.drawable.b_0051));
        c.put("B_0052", Integer.valueOf((int) R.drawable.b_0052));
        c.put("B_0053", Integer.valueOf((int) R.drawable.b_0053));
        c.put("B_0054", Integer.valueOf((int) R.drawable.b_0054));
        c.put("B_0055", Integer.valueOf((int) R.drawable.b_0055));
        c.put("B_0056", Integer.valueOf((int) R.drawable.b_0056));
        c.put("B_0057", Integer.valueOf((int) R.drawable.b_0057));
        c.put("B_0058", Integer.valueOf((int) R.drawable.b_0058));
        c.put("B_0059", Integer.valueOf((int) R.drawable.b_0059));
        c.put("B_0060", Integer.valueOf((int) R.drawable.b_0060));
        c.put("B_0061", Integer.valueOf((int) R.drawable.b_0061));
        c.put("B_0062", Integer.valueOf((int) R.drawable.b_0062));
        c.put("B_0063", Integer.valueOf((int) R.drawable.b_0063));
        c.put("i_f01", Integer.valueOf((int) R.drawable.image_emoticon));
        c.put("i_f02", Integer.valueOf((int) R.drawable.image_emoticon2));
        c.put("i_f03", Integer.valueOf((int) R.drawable.image_emoticon3));
        c.put("i_f04", Integer.valueOf((int) R.drawable.image_emoticon4));
        c.put("i_f05", Integer.valueOf((int) R.drawable.image_emoticon5));
        c.put("i_f06", Integer.valueOf((int) R.drawable.image_emoticon6));
        c.put("i_f07", Integer.valueOf((int) R.drawable.image_emoticon7));
        c.put("i_f08", Integer.valueOf((int) R.drawable.image_emoticon8));
        c.put("i_f09", Integer.valueOf((int) R.drawable.image_emoticon9));
        c.put("i_f10", Integer.valueOf((int) R.drawable.image_emoticon10));
        c.put("i_f11", Integer.valueOf((int) R.drawable.image_emoticon11));
        c.put("i_f12", Integer.valueOf((int) R.drawable.image_emoticon12));
        c.put("i_f13", Integer.valueOf((int) R.drawable.image_emoticon13));
        c.put("i_f14", Integer.valueOf((int) R.drawable.image_emoticon14));
        c.put("i_f15", Integer.valueOf((int) R.drawable.image_emoticon15));
        c.put("i_f16", Integer.valueOf((int) R.drawable.image_emoticon16));
        c.put("i_f17", Integer.valueOf((int) R.drawable.image_emoticon17));
        c.put("i_f18", Integer.valueOf((int) R.drawable.image_emoticon18));
        c.put("i_f19", Integer.valueOf((int) R.drawable.image_emoticon19));
        c.put("i_f20", Integer.valueOf((int) R.drawable.image_emoticon20));
        c.put("i_f21", Integer.valueOf((int) R.drawable.image_emoticon21));
        c.put("i_f22", Integer.valueOf((int) R.drawable.image_emoticon34));
        c.put("i_f23", Integer.valueOf((int) R.drawable.image_emoticon35));
        c.put("i_f24", Integer.valueOf((int) R.drawable.image_emoticon36));
        c.put("i_f25", Integer.valueOf((int) R.drawable.image_emoticon37));
        c.put("i_f26", Integer.valueOf((int) R.drawable.image_emoticon22));
        c.put("i_f27", Integer.valueOf((int) R.drawable.image_emoticon23));
        c.put("i_f28", Integer.valueOf((int) R.drawable.image_emoticon24));
        c.put("i_f29", Integer.valueOf((int) R.drawable.image_emoticon25));
        c.put("i_f30", Integer.valueOf((int) R.drawable.image_emoticon26));
        c.put("i_f31", Integer.valueOf((int) R.drawable.image_emoticon27));
        c.put("i_f32", Integer.valueOf((int) R.drawable.image_emoticon28));
        c.put("i_f33", Integer.valueOf((int) R.drawable.image_emoticon29));
        c.put("i_f34", Integer.valueOf((int) R.drawable.image_emoticon30));
        c.put("i_f35", Integer.valueOf((int) R.drawable.image_emoticon31));
        c.put("i_f36", Integer.valueOf((int) R.drawable.image_emoticon32));
        c.put("i_f37", Integer.valueOf((int) R.drawable.image_emoticon33));
        c.put("i_f38", Integer.valueOf((int) R.drawable.image_emoticon38));
        c.put("i_f39", Integer.valueOf((int) R.drawable.image_emoticon39));
        c.put("i_f40", Integer.valueOf((int) R.drawable.image_emoticon40));
        c.put("i_f41", Integer.valueOf((int) R.drawable.image_emoticon41));
        c.put("i_f42", Integer.valueOf((int) R.drawable.image_emoticon42));
        c.put("i_f43", Integer.valueOf((int) R.drawable.image_emoticon43));
        c.put("i_f44", Integer.valueOf((int) R.drawable.image_emoticon44));
        c.put("i_f45", Integer.valueOf((int) R.drawable.image_emoticon45));
        c.put("i_f46", Integer.valueOf((int) R.drawable.image_emoticon46));
        c.put("i_f47", Integer.valueOf((int) R.drawable.image_emoticon47));
        c.put("i_f48", Integer.valueOf((int) R.drawable.image_emoticon48));
        c.put("i_f49", Integer.valueOf((int) R.drawable.image_emoticon49));
        c.put("i_f50", Integer.valueOf((int) R.drawable.image_emoticon50));
        c.put("t_0001", Integer.valueOf((int) R.drawable.t_0001));
        c.put("t_0002", Integer.valueOf((int) R.drawable.t_0002));
        c.put("t_0003", Integer.valueOf((int) R.drawable.t_0003));
        c.put("t_0004", Integer.valueOf((int) R.drawable.t_0004));
        c.put("t_0005", Integer.valueOf((int) R.drawable.t_0005));
        c.put("t_0006", Integer.valueOf((int) R.drawable.t_0006));
        c.put("t_0007", Integer.valueOf((int) R.drawable.t_0007));
        c.put("t_0008", Integer.valueOf((int) R.drawable.t_0008));
        c.put("t_0009", Integer.valueOf((int) R.drawable.t_0009));
        c.put("t_0010", Integer.valueOf((int) R.drawable.t_0010));
        c.put("t_0011", Integer.valueOf((int) R.drawable.t_0011));
        c.put("t_0012", Integer.valueOf((int) R.drawable.t_0012));
        c.put("t_0013", Integer.valueOf((int) R.drawable.t_0013));
        c.put("t_0014", Integer.valueOf((int) R.drawable.t_0014));
        c.put("t_0015", Integer.valueOf((int) R.drawable.t_0015));
        c.put("t_0016", Integer.valueOf((int) R.drawable.t_0016));
        c.put("t_0017", Integer.valueOf((int) R.drawable.t_0017));
        c.put("t_0018", Integer.valueOf((int) R.drawable.t_0018));
        c.put("t_0019", Integer.valueOf((int) R.drawable.t_0019));
        c.put("t_0020", Integer.valueOf((int) R.drawable.t_0020));
        c.put("t_0021", Integer.valueOf((int) R.drawable.t_0021));
        c.put("t_0022", Integer.valueOf((int) R.drawable.t_0022));
        c.put("t_0023", Integer.valueOf((int) R.drawable.t_0023));
        c.put("t_0024", Integer.valueOf((int) R.drawable.t_0024));
        c.put("t_0025", Integer.valueOf((int) R.drawable.t_0025));
        c.put("t_0026", Integer.valueOf((int) R.drawable.t_0026));
        c.put("t_0027", Integer.valueOf((int) R.drawable.t_0027));
        c.put("t_0028", Integer.valueOf((int) R.drawable.t_0028));
        c.put("t_0029", Integer.valueOf((int) R.drawable.t_0029));
        c.put("t_0030", Integer.valueOf((int) R.drawable.t_0030));
        c.put("t_0031", Integer.valueOf((int) R.drawable.t_0031));
        c.put("t_0032", Integer.valueOf((int) R.drawable.t_0032));
        c.put("t_0033", Integer.valueOf((int) R.drawable.t_0033));
        c.put("t_0034", Integer.valueOf((int) R.drawable.t_0034));
        c.put("t_0035", Integer.valueOf((int) R.drawable.t_0035));
        c.put("t_0036", Integer.valueOf((int) R.drawable.t_0036));
        c.put("t_0037", Integer.valueOf((int) R.drawable.t_0037));
        c.put("t_0038", Integer.valueOf((int) R.drawable.t_0038));
        c.put("t_0039", Integer.valueOf((int) R.drawable.t_0039));
        c.put("t_0040", Integer.valueOf((int) R.drawable.t_0040));
        c.put("image_emoticon", Integer.valueOf((int) R.drawable.image_emoticon));
        c.put("image_emoticon2", Integer.valueOf((int) R.drawable.image_emoticon2));
        c.put("image_emoticon3", Integer.valueOf((int) R.drawable.image_emoticon3));
        c.put("image_emoticon4", Integer.valueOf((int) R.drawable.image_emoticon4));
        c.put("image_emoticon5", Integer.valueOf((int) R.drawable.image_emoticon5));
        c.put("image_emoticon6", Integer.valueOf((int) R.drawable.image_emoticon6));
        c.put("image_emoticon7", Integer.valueOf((int) R.drawable.image_emoticon7));
        c.put("image_emoticon8", Integer.valueOf((int) R.drawable.image_emoticon8));
        c.put("image_emoticon9", Integer.valueOf((int) R.drawable.image_emoticon9));
        c.put("image_emoticon10", Integer.valueOf((int) R.drawable.image_emoticon10));
        c.put("image_emoticon11", Integer.valueOf((int) R.drawable.image_emoticon11));
        c.put("image_emoticon12", Integer.valueOf((int) R.drawable.image_emoticon12));
        c.put("image_emoticon13", Integer.valueOf((int) R.drawable.image_emoticon13));
        c.put("image_emoticon14", Integer.valueOf((int) R.drawable.image_emoticon14));
        c.put("image_emoticon15", Integer.valueOf((int) R.drawable.image_emoticon15));
        c.put("image_emoticon16", Integer.valueOf((int) R.drawable.image_emoticon16));
        c.put("image_emoticon17", Integer.valueOf((int) R.drawable.image_emoticon17));
        c.put("image_emoticon18", Integer.valueOf((int) R.drawable.image_emoticon18));
        c.put("image_emoticon19", Integer.valueOf((int) R.drawable.image_emoticon19));
        c.put("image_emoticon20", Integer.valueOf((int) R.drawable.image_emoticon20));
        c.put("image_emoticon21", Integer.valueOf((int) R.drawable.image_emoticon21));
        c.put("image_emoticon22", Integer.valueOf((int) R.drawable.image_emoticon22));
        c.put("image_emoticon23", Integer.valueOf((int) R.drawable.image_emoticon23));
        c.put("image_emoticon24", Integer.valueOf((int) R.drawable.image_emoticon24));
        c.put("image_emoticon25", Integer.valueOf((int) R.drawable.image_emoticon25));
        c.put("image_emoticon26", Integer.valueOf((int) R.drawable.image_emoticon26));
        c.put("image_emoticon27", Integer.valueOf((int) R.drawable.image_emoticon27));
        c.put("image_emoticon28", Integer.valueOf((int) R.drawable.image_emoticon28));
        c.put("image_emoticon29", Integer.valueOf((int) R.drawable.image_emoticon29));
        c.put("image_emoticon30", Integer.valueOf((int) R.drawable.image_emoticon30));
        c.put("image_emoticon31", Integer.valueOf((int) R.drawable.image_emoticon31));
        c.put("image_emoticon32", Integer.valueOf((int) R.drawable.image_emoticon32));
        c.put("image_emoticon33", Integer.valueOf((int) R.drawable.image_emoticon33));
        c.put("image_emoticon34", Integer.valueOf((int) R.drawable.image_emoticon34));
        c.put("image_emoticon35", Integer.valueOf((int) R.drawable.image_emoticon35));
        c.put("image_emoticon36", Integer.valueOf((int) R.drawable.image_emoticon36));
        c.put("image_emoticon37", Integer.valueOf((int) R.drawable.image_emoticon37));
        c.put("image_emoticon38", Integer.valueOf((int) R.drawable.image_emoticon38));
        c.put("image_emoticon39", Integer.valueOf((int) R.drawable.image_emoticon39));
        c.put("image_emoticon40", Integer.valueOf((int) R.drawable.image_emoticon40));
        c.put("image_emoticon41", Integer.valueOf((int) R.drawable.image_emoticon41));
        c.put("image_emoticon42", Integer.valueOf((int) R.drawable.image_emoticon42));
        c.put("image_emoticon43", Integer.valueOf((int) R.drawable.image_emoticon43));
        c.put("image_emoticon44", Integer.valueOf((int) R.drawable.image_emoticon44));
        c.put("image_emoticon45", Integer.valueOf((int) R.drawable.image_emoticon45));
        c.put("image_emoticon46", Integer.valueOf((int) R.drawable.image_emoticon46));
        c.put("image_emoticon47", Integer.valueOf((int) R.drawable.image_emoticon47));
        c.put("image_emoticon48", Integer.valueOf((int) R.drawable.image_emoticon48));
        c.put("image_emoticon49", Integer.valueOf((int) R.drawable.image_emoticon49));
        c.put("image_emoticon50", Integer.valueOf((int) R.drawable.image_emoticon50));
        c.put("ali_001", Integer.valueOf((int) R.drawable.ali_001));
        c.put("ali_002", Integer.valueOf((int) R.drawable.ali_002));
        c.put("ali_003", Integer.valueOf((int) R.drawable.ali_003));
        c.put("ali_004", Integer.valueOf((int) R.drawable.ali_004));
        c.put("ali_005", Integer.valueOf((int) R.drawable.ali_005));
        c.put("ali_006", Integer.valueOf((int) R.drawable.ali_006));
        c.put("ali_007", Integer.valueOf((int) R.drawable.ali_007));
        c.put("ali_008", Integer.valueOf((int) R.drawable.ali_008));
        c.put("ali_009", Integer.valueOf((int) R.drawable.ali_009));
        c.put("ali_010", Integer.valueOf((int) R.drawable.ali_010));
        c.put("ali_011", Integer.valueOf((int) R.drawable.ali_011));
        c.put("ali_012", Integer.valueOf((int) R.drawable.ali_012));
        c.put("ali_013", Integer.valueOf((int) R.drawable.ali_013));
        c.put("ali_014", Integer.valueOf((int) R.drawable.ali_014));
        c.put("ali_015", Integer.valueOf((int) R.drawable.ali_015));
        c.put("ali_016", Integer.valueOf((int) R.drawable.ali_016));
        c.put("ali_017", Integer.valueOf((int) R.drawable.ali_017));
        c.put("ali_018", Integer.valueOf((int) R.drawable.ali_018));
        c.put("ali_019", Integer.valueOf((int) R.drawable.ali_019));
        c.put("ali_020", Integer.valueOf((int) R.drawable.ali_020));
        c.put("ali_021", Integer.valueOf((int) R.drawable.ali_021));
        c.put("ali_022", Integer.valueOf((int) R.drawable.ali_022));
        c.put("ali_023", Integer.valueOf((int) R.drawable.ali_023));
        c.put("ali_024", Integer.valueOf((int) R.drawable.ali_024));
        c.put("ali_025", Integer.valueOf((int) R.drawable.ali_025));
        c.put("ali_026", Integer.valueOf((int) R.drawable.ali_026));
        c.put("ali_027", Integer.valueOf((int) R.drawable.ali_027));
        c.put("ali_028", Integer.valueOf((int) R.drawable.ali_028));
        c.put("ali_029", Integer.valueOf((int) R.drawable.ali_029));
        c.put("ali_030", Integer.valueOf((int) R.drawable.ali_030));
        c.put("ali_031", Integer.valueOf((int) R.drawable.ali_031));
        c.put("ali_032", Integer.valueOf((int) R.drawable.ali_032));
        c.put("ali_033", Integer.valueOf((int) R.drawable.ali_033));
        c.put("ali_034", Integer.valueOf((int) R.drawable.ali_034));
        c.put("ali_035", Integer.valueOf((int) R.drawable.ali_035));
        c.put("ali_036", Integer.valueOf((int) R.drawable.ali_036));
        c.put("ali_037", Integer.valueOf((int) R.drawable.ali_037));
        c.put("ali_038", Integer.valueOf((int) R.drawable.ali_038));
        c.put("ali_039", Integer.valueOf((int) R.drawable.ali_039));
        c.put("ali_040", Integer.valueOf((int) R.drawable.ali_040));
        c.put("ali_041", Integer.valueOf((int) R.drawable.ali_041));
        c.put("ali_042", Integer.valueOf((int) R.drawable.ali_042));
        c.put("ali_043", Integer.valueOf((int) R.drawable.ali_043));
        c.put("ali_044", Integer.valueOf((int) R.drawable.ali_044));
        c.put("ali_045", Integer.valueOf((int) R.drawable.ali_045));
        c.put("ali_046", Integer.valueOf((int) R.drawable.ali_046));
        c.put("ali_047", Integer.valueOf((int) R.drawable.ali_047));
        c.put("ali_048", Integer.valueOf((int) R.drawable.ali_048));
        c.put("ali_049", Integer.valueOf((int) R.drawable.ali_049));
        c.put("ali_050", Integer.valueOf((int) R.drawable.ali_050));
        c.put("ali_051", Integer.valueOf((int) R.drawable.ali_051));
        c.put("ali_052", Integer.valueOf((int) R.drawable.ali_052));
        c.put("ali_053", Integer.valueOf((int) R.drawable.ali_053));
        c.put("ali_054", Integer.valueOf((int) R.drawable.ali_054));
        c.put("ali_055", Integer.valueOf((int) R.drawable.ali_055));
        c.put("ali_056", Integer.valueOf((int) R.drawable.ali_056));
        c.put("ali_057", Integer.valueOf((int) R.drawable.ali_057));
        c.put("ali_058", Integer.valueOf((int) R.drawable.ali_058));
        c.put("ali_059", Integer.valueOf((int) R.drawable.ali_059));
        c.put("ali_060", Integer.valueOf((int) R.drawable.ali_060));
        c.put("ali_061", Integer.valueOf((int) R.drawable.ali_061));
        c.put("ali_062", Integer.valueOf((int) R.drawable.ali_062));
        c.put("ali_063", Integer.valueOf((int) R.drawable.ali_063));
        c.put("ali_064", Integer.valueOf((int) R.drawable.ali_064));
        c.put("ali_065", Integer.valueOf((int) R.drawable.ali_065));
        c.put("ali_066", Integer.valueOf((int) R.drawable.ali_066));
        c.put("ali_067", Integer.valueOf((int) R.drawable.ali_067));
        c.put("ali_068", Integer.valueOf((int) R.drawable.ali_068));
        c.put("ali_069", Integer.valueOf((int) R.drawable.ali_069));
        c.put("ali_070", Integer.valueOf((int) R.drawable.ali_070));
        c.put("b01", Integer.valueOf((int) R.drawable.b01));
        c.put("b02", Integer.valueOf((int) R.drawable.b02));
        c.put("b03", Integer.valueOf((int) R.drawable.b03));
        c.put("b04", Integer.valueOf((int) R.drawable.b04));
        c.put("b05", Integer.valueOf((int) R.drawable.b05));
        c.put("b06", Integer.valueOf((int) R.drawable.b06));
        c.put("b07", Integer.valueOf((int) R.drawable.b07));
        c.put("b08", Integer.valueOf((int) R.drawable.b08));
        c.put("b09", Integer.valueOf((int) R.drawable.b09));
        c.put("b10", Integer.valueOf((int) R.drawable.b10));
        c.put("b11", Integer.valueOf((int) R.drawable.b11));
        c.put("b12", Integer.valueOf((int) R.drawable.b12));
        c.put("b13", Integer.valueOf((int) R.drawable.b13));
        c.put("b14", Integer.valueOf((int) R.drawable.b14));
        c.put("b15", Integer.valueOf((int) R.drawable.b15));
        c.put("b16", Integer.valueOf((int) R.drawable.b16));
        c.put("b17", Integer.valueOf((int) R.drawable.b17));
        c.put("b18", Integer.valueOf((int) R.drawable.b18));
        c.put("b19", Integer.valueOf((int) R.drawable.b19));
        c.put("b20", Integer.valueOf((int) R.drawable.b20));
        c.put("b21", Integer.valueOf((int) R.drawable.b21));
        c.put("b22", Integer.valueOf((int) R.drawable.b22));
        c.put("b23", Integer.valueOf((int) R.drawable.b23));
        c.put("b24", Integer.valueOf((int) R.drawable.b24));
        c.put("b25", Integer.valueOf((int) R.drawable.b25));
        c.put("b26", Integer.valueOf((int) R.drawable.b26));
        c.put("b27", Integer.valueOf((int) R.drawable.b27));
        c.put("b28", Integer.valueOf((int) R.drawable.b28));
        c.put("b29", Integer.valueOf((int) R.drawable.b29));
        c.put("b30", Integer.valueOf((int) R.drawable.b30));
        c.put("b31", Integer.valueOf((int) R.drawable.b31));
        c.put("b32", Integer.valueOf((int) R.drawable.b32));
        c.put("b33", Integer.valueOf((int) R.drawable.b33));
        c.put("b34", Integer.valueOf((int) R.drawable.b34));
        c.put("b35", Integer.valueOf((int) R.drawable.b35));
        c.put("b36", Integer.valueOf((int) R.drawable.b36));
        c.put("b37", Integer.valueOf((int) R.drawable.b37));
        c.put("b38", Integer.valueOf((int) R.drawable.b38));
        c.put("b39", Integer.valueOf((int) R.drawable.b39));
        c.put("b40", Integer.valueOf((int) R.drawable.b40));
        c.put("b41", Integer.valueOf((int) R.drawable.b41));
        c.put("b42", Integer.valueOf((int) R.drawable.b42));
        c.put("b43", Integer.valueOf((int) R.drawable.b43));
        c.put("b44", Integer.valueOf((int) R.drawable.b44));
        c.put("b45", Integer.valueOf((int) R.drawable.b45));
        c.put("b46", Integer.valueOf((int) R.drawable.b46));
        c.put("b47", Integer.valueOf((int) R.drawable.b47));
        c.put("b48", Integer.valueOf((int) R.drawable.b48));
        c.put("b49", Integer.valueOf((int) R.drawable.b49));
        c.put("b50", Integer.valueOf((int) R.drawable.b50));
        c.put("b51", Integer.valueOf((int) R.drawable.b51));
        c.put("b52", Integer.valueOf((int) R.drawable.b52));
        c.put("b53", Integer.valueOf((int) R.drawable.b53));
        c.put("b54", Integer.valueOf((int) R.drawable.b54));
        c.put("b55", Integer.valueOf((int) R.drawable.b55));
        c.put("b56", Integer.valueOf((int) R.drawable.b56));
        c.put("b57", Integer.valueOf((int) R.drawable.b57));
        c.put("b58", Integer.valueOf((int) R.drawable.b58));
        c.put("b59", Integer.valueOf((int) R.drawable.b59));
        c.put("b60", Integer.valueOf((int) R.drawable.b60));
        c.put("b61", Integer.valueOf((int) R.drawable.b61));
        c.put("b62", Integer.valueOf((int) R.drawable.b62));
        c.put("yz_001", Integer.valueOf((int) R.drawable.yz_001));
        c.put("yz_002", Integer.valueOf((int) R.drawable.yz_002));
        c.put("yz_003", Integer.valueOf((int) R.drawable.yz_003));
        c.put("yz_004", Integer.valueOf((int) R.drawable.yz_004));
        c.put("yz_005", Integer.valueOf((int) R.drawable.yz_005));
        c.put("yz_006", Integer.valueOf((int) R.drawable.yz_006));
        c.put("yz_007", Integer.valueOf((int) R.drawable.yz_007));
        c.put("yz_008", Integer.valueOf((int) R.drawable.yz_008));
        c.put("yz_009", Integer.valueOf((int) R.drawable.yz_009));
        c.put("yz_010", Integer.valueOf((int) R.drawable.yz_010));
        c.put("yz_011", Integer.valueOf((int) R.drawable.yz_011));
        c.put("yz_012", Integer.valueOf((int) R.drawable.yz_012));
        c.put("yz_013", Integer.valueOf((int) R.drawable.yz_013));
        c.put("yz_014", Integer.valueOf((int) R.drawable.yz_014));
        c.put("yz_015", Integer.valueOf((int) R.drawable.yz_015));
        c.put("yz_016", Integer.valueOf((int) R.drawable.yz_016));
        c.put("yz_017", Integer.valueOf((int) R.drawable.yz_017));
        c.put("yz_018", Integer.valueOf((int) R.drawable.yz_018));
        c.put("yz_019", Integer.valueOf((int) R.drawable.yz_019));
        c.put("yz_020", Integer.valueOf((int) R.drawable.yz_020));
        c.put("yz_021", Integer.valueOf((int) R.drawable.yz_021));
        c.put("yz_022", Integer.valueOf((int) R.drawable.yz_022));
        c.put("yz_023", Integer.valueOf((int) R.drawable.yz_023));
        c.put("yz_024", Integer.valueOf((int) R.drawable.yz_024));
        c.put("yz_025", Integer.valueOf((int) R.drawable.yz_025));
        c.put("yz_026", Integer.valueOf((int) R.drawable.yz_026));
        c.put("yz_027", Integer.valueOf((int) R.drawable.yz_027));
        c.put("yz_028", Integer.valueOf((int) R.drawable.yz_028));
        c.put("yz_029", Integer.valueOf((int) R.drawable.yz_029));
        c.put("yz_030", Integer.valueOf((int) R.drawable.yz_030));
        c.put("yz_031", Integer.valueOf((int) R.drawable.yz_031));
        c.put("yz_032", Integer.valueOf((int) R.drawable.yz_032));
        c.put("yz_033", Integer.valueOf((int) R.drawable.yz_033));
        c.put("yz_034", Integer.valueOf((int) R.drawable.yz_034));
        c.put("yz_035", Integer.valueOf((int) R.drawable.yz_035));
        c.put("yz_036", Integer.valueOf((int) R.drawable.yz_036));
        c.put("yz_037", Integer.valueOf((int) R.drawable.yz_037));
        c.put("yz_038", Integer.valueOf((int) R.drawable.yz_038));
        c.put("yz_039", Integer.valueOf((int) R.drawable.yz_039));
        c.put("yz_040", Integer.valueOf((int) R.drawable.yz_040));
        c.put("yz_041", Integer.valueOf((int) R.drawable.yz_041));
        c.put("yz_042", Integer.valueOf((int) R.drawable.yz_042));
        c.put("yz_043", Integer.valueOf((int) R.drawable.yz_043));
        c.put("yz_044", Integer.valueOf((int) R.drawable.yz_044));
        c.put("yz_045", Integer.valueOf((int) R.drawable.yz_045));
        c.put("yz_046", Integer.valueOf((int) R.drawable.yz_046));
        c.put("she_001", Integer.valueOf((int) R.drawable.she_001));
        c.put("she_002", Integer.valueOf((int) R.drawable.she_002));
        c.put("she_003", Integer.valueOf((int) R.drawable.she_003));
        c.put("she_004", Integer.valueOf((int) R.drawable.she_004));
        c.put("she_005", Integer.valueOf((int) R.drawable.she_005));
        c.put("she_006", Integer.valueOf((int) R.drawable.she_006));
        c.put("she_007", Integer.valueOf((int) R.drawable.she_007));
        c.put("she_008", Integer.valueOf((int) R.drawable.she_008));
        c.put("she_009", Integer.valueOf((int) R.drawable.she_009));
        c.put("she_010", Integer.valueOf((int) R.drawable.she_010));
        c.put("she_011", Integer.valueOf((int) R.drawable.she_011));
        c.put("she_012", Integer.valueOf((int) R.drawable.she_012));
        c.put("she_013", Integer.valueOf((int) R.drawable.she_013));
        c.put("she_014", Integer.valueOf((int) R.drawable.she_014));
        a = new ArrayList<>();
        a.add(Integer.valueOf((int) R.drawable.write_face_01));
        a.add(Integer.valueOf((int) R.drawable.write_face_02));
        a.add(Integer.valueOf((int) R.drawable.write_face_03));
        a.add(Integer.valueOf((int) R.drawable.write_face_04));
        a.add(Integer.valueOf((int) R.drawable.write_face_05));
        a.add(Integer.valueOf((int) R.drawable.write_face_06));
        a.add(Integer.valueOf((int) R.drawable.write_face_07));
        a.add(Integer.valueOf((int) R.drawable.write_face_08));
        a.add(Integer.valueOf((int) R.drawable.write_face_09));
        a.add(Integer.valueOf((int) R.drawable.write_face_10));
        a.add(Integer.valueOf((int) R.drawable.write_face_11));
        a.add(Integer.valueOf((int) R.drawable.write_face_12));
        a.add(Integer.valueOf((int) R.drawable.write_face_13));
        a.add(Integer.valueOf((int) R.drawable.write_face_14));
        a.add(Integer.valueOf((int) R.drawable.write_face_15));
        a.add(Integer.valueOf((int) R.drawable.write_face_16));
        a.add(Integer.valueOf((int) R.drawable.write_face_17));
        a.add(Integer.valueOf((int) R.drawable.write_face_18));
        a.add(Integer.valueOf((int) R.drawable.write_face_19));
        a.add(Integer.valueOf((int) R.drawable.write_face_20));
        a.add(Integer.valueOf((int) R.drawable.write_face_21));
        a.add(Integer.valueOf((int) R.drawable.write_face_22));
        a.add(Integer.valueOf((int) R.drawable.write_face_23));
        a.add(Integer.valueOf((int) R.drawable.write_face_24));
        a.add(Integer.valueOf((int) R.drawable.write_face_25));
        a.add(Integer.valueOf((int) R.drawable.write_face_26));
        a.add(Integer.valueOf((int) R.drawable.write_face_27));
        a.add(Integer.valueOf((int) R.drawable.write_face_28));
        a.add(Integer.valueOf((int) R.drawable.write_face_29));
        a.add(Integer.valueOf((int) R.drawable.write_face_30));
        a.add(Integer.valueOf((int) R.drawable.write_face_31));
        a.add(Integer.valueOf((int) R.drawable.write_face_32));
        a.add(Integer.valueOf((int) R.drawable.write_face_33));
        a.add(Integer.valueOf((int) R.drawable.write_face_34));
        a.add(Integer.valueOf((int) R.drawable.write_face_35));
        a.add(Integer.valueOf((int) R.drawable.write_face_36));
        a.add(Integer.valueOf((int) R.drawable.write_face_37));
        a.add(Integer.valueOf((int) R.drawable.write_face_38));
        a.add(Integer.valueOf((int) R.drawable.write_face_39));
        a.add(Integer.valueOf((int) R.drawable.write_face_40));
        a.add(Integer.valueOf((int) R.drawable.write_face_41));
        a.add(Integer.valueOf((int) R.drawable.write_face_42));
        a.add(Integer.valueOf((int) R.drawable.write_face_43));
        a.add(Integer.valueOf((int) R.drawable.write_face_44));
        a.add(Integer.valueOf((int) R.drawable.write_face_45));
        a.add(Integer.valueOf((int) R.drawable.write_face_46));
        a.add(Integer.valueOf((int) R.drawable.write_face_47));
        a.add(Integer.valueOf((int) R.drawable.write_face_48));
        a.add(Integer.valueOf((int) R.drawable.write_face_49));
        a.add(Integer.valueOf((int) R.drawable.write_face_50));
        a.add(Integer.valueOf((int) R.drawable.e_ali_047));
        a.add(Integer.valueOf((int) R.drawable.e_ali_050));
        a.add(Integer.valueOf((int) R.drawable.e_ali_051));
        a.add(Integer.valueOf((int) R.drawable.e_ali_052));
        a.add(Integer.valueOf((int) R.drawable.e_ali_053));
        a.add(Integer.valueOf((int) R.drawable.e_ali_054));
        a.add(Integer.valueOf((int) R.drawable.e_ali_055));
        a.add(Integer.valueOf((int) R.drawable.e_ali_056));
        a.add(Integer.valueOf((int) R.drawable.e_ali_059));
        a.add(Integer.valueOf((int) R.drawable.e_ali_060));
        a.add(Integer.valueOf((int) R.drawable.e_ali_061));
        a.add(Integer.valueOf((int) R.drawable.e_ali_062));
        a.add(Integer.valueOf((int) R.drawable.e_ali_063));
        a.add(Integer.valueOf((int) R.drawable.e_ali_064));
        a.add(Integer.valueOf((int) R.drawable.e_ali_065));
        a.add(Integer.valueOf((int) R.drawable.e_ali_066));
        a.add(Integer.valueOf((int) R.drawable.e_ali_067));
        a.add(Integer.valueOf((int) R.drawable.e_ali_068));
        a.add(Integer.valueOf((int) R.drawable.e_ali_069));
        a.add(Integer.valueOf((int) R.drawable.e_ali_070));
        a.add(Integer.valueOf((int) R.drawable.e_yz_001));
        a.add(Integer.valueOf((int) R.drawable.e_yz_002));
        a.add(Integer.valueOf((int) R.drawable.e_yz_003));
        a.add(Integer.valueOf((int) R.drawable.e_yz_004));
        a.add(Integer.valueOf((int) R.drawable.e_yz_005));
        a.add(Integer.valueOf((int) R.drawable.e_yz_006));
        a.add(Integer.valueOf((int) R.drawable.e_yz_007));
        a.add(Integer.valueOf((int) R.drawable.e_yz_008));
        a.add(Integer.valueOf((int) R.drawable.e_b01));
        a.add(Integer.valueOf((int) R.drawable.e_b02));
        a.add(Integer.valueOf((int) R.drawable.e_b03));
        a.add(Integer.valueOf((int) R.drawable.e_b04));
        a.add(Integer.valueOf((int) R.drawable.e_b05));
        a.add(Integer.valueOf((int) R.drawable.e_b06));
        a.add(Integer.valueOf((int) R.drawable.e_b07));
        a.add(Integer.valueOf((int) R.drawable.e_b08));
        a.add(Integer.valueOf((int) R.drawable.e_b09));
        a.add(Integer.valueOf((int) R.drawable.e_b10));
        a.add(Integer.valueOf((int) R.drawable.e_b11));
        a.add(Integer.valueOf((int) R.drawable.e_b12));
        a.add(Integer.valueOf((int) R.drawable.e_b13));
        a.add(Integer.valueOf((int) R.drawable.e_b14));
        a.add(Integer.valueOf((int) R.drawable.e_b15));
        a.add(Integer.valueOf((int) R.drawable.e_b16));
        a.add(Integer.valueOf((int) R.drawable.e_b17));
        a.add(Integer.valueOf((int) R.drawable.e_b18));
        a.add(Integer.valueOf((int) R.drawable.e_b19));
        a.add(Integer.valueOf((int) R.drawable.e_b20));
        a.add(Integer.valueOf((int) R.drawable.f10th_001));
        a.add(Integer.valueOf((int) R.drawable.f10th_002));
        a.add(Integer.valueOf((int) R.drawable.f10th_003));
        a.add(Integer.valueOf((int) R.drawable.f10th_004));
        a.add(Integer.valueOf((int) R.drawable.f10th_005));
        a.add(Integer.valueOf((int) R.drawable.f10th_006));
        a.add(Integer.valueOf((int) R.drawable.f10th_007));
        a.add(Integer.valueOf((int) R.drawable.f10th_008));
        a.add(Integer.valueOf((int) R.drawable.f10th_009));
        a.add(Integer.valueOf((int) R.drawable.f10th_010));
        a.add(Integer.valueOf((int) R.drawable.f10th_011));
        a.add(Integer.valueOf((int) R.drawable.f10th_012));
        b = new HashMap<>();
        b.put("#(呵呵)", a.get(0));
        b.put("#(哈哈)", a.get(1));
        b.put("#(吐舌)", a.get(2));
        b.put("#(啊)", a.get(3));
        b.put("#(酷)", a.get(4));
        b.put("#(怒)", a.get(5));
        b.put("#(开心)", a.get(6));
        b.put("#(汗)", a.get(7));
        b.put("#(泪)", a.get(8));
        b.put("#(黑线)", a.get(9));
        b.put("#(鄙视)", a.get(10));
        b.put("#(不高兴)", a.get(11));
        b.put("#(真棒)", a.get(12));
        b.put("#(钱)", a.get(13));
        b.put("#(疑问)", a.get(14));
        b.put("#(阴险)", a.get(15));
        b.put("#(吐)", a.get(16));
        b.put("#(咦)", a.get(17));
        b.put("#(委屈)", a.get(18));
        b.put("#(花心)", a.get(19));
        b.put("#(呼~)", a.get(20));
        b.put("#(笑眼)", a.get(21));
        b.put("#(冷)", a.get(22));
        b.put("#(太开心)", a.get(23));
        b.put("#(滑稽)", a.get(24));
        b.put("#(勉强)", a.get(25));
        b.put("#(狂汗)", a.get(26));
        b.put("#(乖)", a.get(27));
        b.put("#(睡觉)", a.get(28));
        b.put("#(惊哭)", a.get(29));
        b.put("#(升起)", a.get(30));
        b.put("#(惊讶)", a.get(31));
        b.put("#(喷)", a.get(32));
        b.put("#(爱心)", a.get(33));
        b.put("#(心碎)", a.get(34));
        b.put("#(玫瑰)", a.get(35));
        b.put("#(礼物)", a.get(36));
        b.put("#(彩虹)", a.get(37));
        b.put("#(星星月亮)", a.get(38));
        b.put("#(太阳)", a.get(39));
        b.put("#(钱币)", a.get(40));
        b.put("#(灯泡)", a.get(41));
        b.put("#(茶杯)", a.get(42));
        b.put("#(蛋糕)", a.get(43));
        b.put("#(音乐)", a.get(44));
        b.put("#(haha)", a.get(45));
        b.put("#(胜利)", a.get(46));
        b.put("#(大拇指)", a.get(47));
        b.put("#(弱)", a.get(48));
        b.put("#(OK)", a.get(49));
        b.put("#(哭着跑)", a.get(50));
        b.put("#(惆怅~)", a.get(51));
        b.put("#(摸头)", a.get(52));
        b.put("#(蹭)", a.get(53));
        b.put("#(打滚)", a.get(54));
        b.put("#(叩拜)", a.get(55));
        b.put("#(摸)", a.get(56));
        b.put("#(数钱)", a.get(57));
        b.put("#(加1)", a.get(58));
        b.put("#(压力)", a.get(59));
        b.put("#(表逼我)", a.get(60));
        b.put("#(人呢)", a.get(61));
        b.put("#(摇晃)", a.get(62));
        b.put("#(打地鼠)", a.get(63));
        b.put("#(这个屌)", a.get(64));
        b.put("#(恐慌)", a.get(65));
        b.put("#(晕乎乎)", a.get(66));
        b.put("#(浮云)", a.get(67));
        b.put("#(给力)", a.get(68));
        b.put("#(杯具了)", a.get(69));
        b.put("#(焦糖舞)", a.get(70));
        b.put("#(翻滚)", a.get(71));
        b.put("#(拍屁股做鬼脸)", a.get(72));
        b.put("#(不)", a.get(73));
        b.put("#(河蟹掉啦)", a.get(74));
        b.put("#(哦耶)", a.get(75));
        b.put("#(我倒)", a.get(76));
        b.put("#(投降)", a.get(77));
        b.put("#(微笑)", a.get(78));
        b.put("#(帅哥)", a.get(79));
        b.put("#(美女)", a.get(80));
        b.put("#(老大)", a.get(81));
        b.put("#(哈哈哈)", a.get(82));
        b.put("#(奸笑)", a.get(83));
        b.put("#(傻乐)", a.get(84));
        b.put("#(飞吻)", a.get(85));
        b.put("#(害羞)", a.get(86));
        b.put("#(花痴)", a.get(87));
        b.put("#(憧憬)", a.get(88));
        b.put("#(你牛)", a.get(89));
        b.put("#(鼓掌)", a.get(90));
        b.put("#(可爱)", a.get(91));
        b.put("#(太委屈)", a.get(92));
        b.put("#(大哭)", a.get(93));
        b.put("#(泪奔)", a.get(94));
        b.put("#(寻死)", a.get(95));
        b.put("#(非常惊讶)", a.get(96));
        b.put("#(表示疑问)", a.get(97));
        b.put("#(蹦蹦跳跳)", a.get(98));
        b.put("#(晃悠)", a.get(99));
        b.put("#(摇摇摆摆)", a.get(100));
        b.put("#(大撒花)", a.get(SocialAPIErrorCodes.ERROR_INVALID_CLIENT_ID));
        b.put("#(高高兴兴)", a.get(SocialAPIErrorCodes.ERROR_INVALID_SESSION_KEY));
        b.put("#(弹吉他)", a.get(103));
        b.put("#(魔法棒)", a.get(SocialAPIErrorCodes.ERROR_INVALID_SIGNATURE));
        b.put("#(扛大旗)", a.get(SocialAPIErrorCodes.ERROR_MANY_PARAMETER));
        b.put("#(点蜡烛)", a.get(SocialAPIErrorCodes.ERROR_INVALID_SIGNATURE_ALGORITHM));
        b.put("#(大秧歌)", a.get(SocialAPIErrorCodes.ERROR_INVALID_TIMESTAMP));
        b.put("#(贴吧十周年)", a.get(108));
        b.put("#(十周年)", a.get(109));
        d = new HashMap<>();
        d.put("B_0001", "HI");
        d.put("B_0002", "KISS");
        d.put("B_0003", "不说");
        d.put("B_0004", "不要");
        d.put("B_0005", "扯花");
        d.put("B_0006", "大心");
        d.put("B_0007", "顶");
        d.put("B_0008", "大惊");
        d.put("B_0009", "飞吻");
        d.put("B_0010", "鬼脸");
        d.put("B_0011", "害羞");
        d.put("B_0012", "口水");
        d.put("B_0013", "狂哭");
        d.put("B_0014", "来");
        d.put("B_0015", "泪眼");
        d.put("B_0016", "流泪");
        d.put("B_0017", "生气");
        d.put("B_0018", "吐舌");
        d.put("B_0019", "喜欢");
        d.put("B_0020", "旋转");
        d.put("B_0021", "再见");
        d.put("B_0022", "抓狂");
        d.put("B_0023", "汗");
        d.put("B_0024", "鄙视");
        d.put("B_0025", "拜");
        d.put("B_0026", "吐血");
        d.put("B_0027", "嘘");
        d.put("B_0028", "打人");
        d.put("B_0029", "蹦跳");
        d.put("B_0030", "变脸");
        d.put("B_0031", "扯肉");
        d.put("B_0032", "吃To");
        d.put("B_0033", "吃花");
        d.put("B_0034", "吹泡泡糖");
        d.put("B_0035", "大变身");
        d.put("B_0036", "飞天舞");
        d.put("B_0037", "回眸");
        d.put("B_0038", "可怜");
        d.put("B_0039", "猛抽");
        d.put("B_0040", "泡泡");
        d.put("B_0041", "苹果");
        d.put("B_0042", "亲");
        d.put("B_0043", "耍赖");
        d.put("B_0044", "骚舞");
        d.put("B_0045", "烧香");
        d.put("B_0046", "睡");
        d.put("B_0047", "套娃娃");
        d.put("B_0048", "捅捅");
        d.put("B_0049", "舞倒");
        d.put("B_0050", "西红柿");
        d.put("B_0051", "爱慕");
        d.put("B_0052", "摇");
        d.put("B_0053", "摇摆");
        d.put("B_0054", "杂耍");
        d.put("B_0055", "招财");
        d.put("B_0056", "被殴");
        d.put("B_0057", "被球闷");
        d.put("B_0058", "大惊");
        d.put("B_0059", "理想");
        d.put("B_0060", "殴打");
        d.put("B_0061", "呕吐");
        d.put("B_0062", "碎");
        d.put("B_0063", "吐痰");
        d.put("i_f01", "呵呵");
        d.put("i_f02", "哈哈");
        d.put("i_f03", "吐舌");
        d.put("i_f04", "啊?");
        d.put("i_f05", "酷");
        d.put("i_f06", "怒");
        d.put("i_f07", "开心");
        d.put("i_f08", "汗");
        d.put("i_f09", "泪");
        d.put("i_f10", "黑线");
        d.put("i_f11", "鄙视");
        d.put("i_f12", "不高兴");
        d.put("i_f13", "真棒");
        d.put("i_f14", "钱");
        d.put("i_f15", "疑问");
        d.put("i_f16", "阴险");
        d.put("i_f17", "吐");
        d.put("i_f18", "咦?");
        d.put("i_f19", "委屈");
        d.put("i_f20", "花心");
        d.put("i_f21", "呼~");
        d.put("i_f22", "笑眼");
        d.put("i_f23", "冷");
        d.put("i_f24", "太开心");
        d.put("i_f25", "滑稽");
        d.put("i_f26", "勉强");
        d.put("i_f27", "狂汗");
        d.put("i_f28", "乖");
        d.put("i_f29", "睡觉");
        d.put("i_f30", "惊哭");
        d.put("i_f31", "升起");
        d.put("i_f32", "惊讶");
        d.put("i_f33", "喷");
        d.put("i_f34", "爱心");
        d.put("i_f35", "心碎");
        d.put("i_f36", "玫瑰");
        d.put("i_f37", "礼物");
        d.put("i_f38", "彩虹");
        d.put("i_f39", "星星月亮");
        d.put("i_f40", "太阳");
        d.put("i_f41", "钱币");
        d.put("i_f42", "灯泡");
        d.put("i_f43", "茶杯");
        d.put("i_f44", "蛋糕");
        d.put("i_f45", "音乐");
        d.put("i_f46", "haha");
        d.put("i_f47", "胜利");
        d.put("i_f48", "大拇指");
        d.put("i_f49", "弱");
        d.put("i_f50", "OK");
        d.put("t_0001", "Kiss");
        d.put("t_0002", "Love");
        d.put("t_0003", "Yeah");
        d.put("t_0004", "啊!");
        d.put("t_0005", "背扭");
        d.put("t_0006", "顶");
        d.put("t_0007", "抖胸");
        d.put("t_0008", "88");
        d.put("t_0009", "汗");
        d.put("t_0010", "瞌睡");
        d.put("t_0011", "鲁拉");
        d.put("t_0012", "拍砖");
        d.put("t_0013", "揉脸");
        d.put("t_0014", "生日快乐");
        d.put("t_0015", "摊手");
        d.put("t_0016", "睡觉");
        d.put("t_0017", "瘫坐");
        d.put("t_0018", "无聊");
        d.put("t_0019", "星星闪");
        d.put("t_0020", "旋转");
        d.put("t_0021", "也不行");
        d.put("t_0022", "郁闷");
        d.put("t_0023", "正Music");
        d.put("t_0024", "抓墙");
        d.put("t_0025", "撞墙至死");
        d.put("t_0026", "歪头");
        d.put("t_0027", "戳眼");
        d.put("t_0028", "飘过");
        d.put("t_0029", "互相拍砖");
        d.put("t_0030", "砍死你");
        d.put("t_0031", "扔桌子");
        d.put("t_0032", "少林寺");
        d.put("t_0033", "什么?");
        d.put("t_0034", "转头");
        d.put("t_0035", "我爱牛奶");
        d.put("t_0036", "我踢");
        d.put("t_0037", "摇晃");
        d.put("t_0038", "晕厥");
        d.put("t_0039", "在笼子里");
        d.put("t_0040", "震荡");
        d.put("image_emoticon", "呵呵");
        d.put("image_emoticon2", "哈哈");
        d.put("image_emoticon3", "吐舌");
        d.put("image_emoticon4", "啊?");
        d.put("image_emoticon5", "酷");
        d.put("image_emoticon6", "怒");
        d.put("image_emoticon7", "开心");
        d.put("image_emoticon8", "汗");
        d.put("image_emoticon9", "泪");
        d.put("image_emoticon10", "黑线");
        d.put("image_emoticon11", "鄙视");
        d.put("image_emoticon12", "不高兴");
        d.put("image_emoticon13", "真棒");
        d.put("image_emoticon14", "钱");
        d.put("image_emoticon15", "疑问");
        d.put("image_emoticon16", "阴险");
        d.put("image_emoticon17", "吐");
        d.put("image_emoticon18", "咦?");
        d.put("image_emoticon19", "委屈");
        d.put("image_emoticon20", "花心");
        d.put("image_emoticon21", "呼~");
        d.put("image_emoticon22", "笑眼");
        d.put("image_emoticon23", "冷");
        d.put("image_emoticon24", "太开心");
        d.put("image_emoticon25", "滑稽");
        d.put("image_emoticon26", "勉强");
        d.put("image_emoticon27", "狂汗");
        d.put("image_emoticon28", "乖");
        d.put("image_emoticon29", "睡觉");
        d.put("image_emoticon30", "惊哭");
        d.put("image_emoticon31", "升起");
        d.put("image_emoticon32", "惊讶");
        d.put("image_emoticon33", "喷");
        d.put("image_emoticon34", "爱心");
        d.put("image_emoticon35", "心碎");
        d.put("image_emoticon36", "玫瑰");
        d.put("image_emoticon37", "礼物");
        d.put("image_emoticon38", "彩虹");
        d.put("image_emoticon39", "星星月亮");
        d.put("image_emoticon40", "太阳");
        d.put("image_emoticon41", "钱币");
        d.put("image_emoticon42", "灯泡");
        d.put("image_emoticon43", "茶杯");
        d.put("image_emoticon44", "蛋糕");
        d.put("image_emoticon45", "音乐");
        d.put("image_emoticon46", "haha");
        d.put("image_emoticon47", "胜利");
        d.put("image_emoticon48", "大拇指");
        d.put("image_emoticon49", "弱");
        d.put("image_emoticon50", "OK");
        d.put("ali_001", "赖皮");
        d.put("ali_002", "感动");
        d.put("ali_003", "十分惊讶");
        d.put("ali_004", "怒气");
        d.put("ali_005", "哭泣");
        d.put("ali_006", "吃惊");
        d.put("ali_007", "嘲弄");
        d.put("ali_008", "飘过");
        d.put("ali_009", "转圈哭");
        d.put("ali_010", "神经病");
        d.put("ali_011", "揪耳朵");
        d.put("ali_012", "惊汗");
        d.put("ali_013", "隐身");
        d.put("ali_014", "不要");
        d.put("ali_015", "遁");
        d.put("ali_016", "不公平");
        d.put("ali_017", "爬来了");
        d.put("ali_018", "蛋花哭");
        d.put("ali_019", "温暖");
        d.put("ali_020", "点头");
        d.put("ali_021", "撒钱");
        d.put("ali_022", "献花");
        d.put("ali_023", "寒");
        d.put("ali_024", "傻笑");
        d.put("ali_025", "扭扭");
        d.put("ali_026", "疯");
        d.put("ali_027", "抓狂");
        d.put("ali_028", "抓");
        d.put("ali_029", "蜷");
        d.put("ali_030", "挠墙");
        d.put("ali_031", "狂笑");
        d.put("ali_032", "抱枕");
        d.put("ali_033", "吼叫");
        d.put("ali_034", "嚷");
        d.put("ali_035", "唠叨");
        d.put("ali_036", "捏脸");
        d.put("ali_037", "爆笑");
        d.put("ali_038", "郁闷");
        d.put("ali_039", "潜水");
        d.put("ali_040", "十分开心");
        d.put("ali_041", "冷笑话");
        d.put("ali_042", "顶");
        d.put("ali_043", "潜");
        d.put("ali_044", "画圈圈");
        d.put("ali_045", "玩电脑");
        d.put("ali_046", "狂吐");
        d.put("ali_047", "哭着跑");
        d.put("ali_048", "阿狸侠");
        d.put("ali_049", "冷死了");
        d.put("ali_050", "惆怅~");
        d.put("ali_051", "摸头");
        d.put("ali_052", "蹭");
        d.put("ali_053", "打滚");
        d.put("ali_054", "叩拜");
        d.put("ali_055", "摸");
        d.put("ali_056", "数钱");
        d.put("ali_057", "拖走");
        d.put("ali_058", "热");
        d.put("ali_059", "加1");
        d.put("ali_060", "压力");
        d.put("ali_061", "表逼我");
        d.put("ali_062", "人呢");
        d.put("ali_063", "摇晃");
        d.put("ali_064", "打地鼠");
        d.put("ali_065", "这个屌");
        d.put("ali_066", "恐慌");
        d.put("ali_067", "晕乎乎");
        d.put("ali_068", "浮云");
        d.put("ali_069", "给力");
        d.put("ali_070", "杯具了");
        d.put("b01", "微笑");
        d.put("b02", "帅哥");
        d.put("b03", "美女");
        d.put("b04", "老大");
        d.put("b05", "哈哈哈");
        d.put("b06", "奸笑");
        d.put("b07", "傻乐");
        d.put("b08", "飞吻");
        d.put("b09", "害羞");
        d.put("b10", "花痴");
        d.put("b11", "憧憬");
        d.put("b12", "你牛");
        d.put("b13", "鼓掌");
        d.put("b14", "可爱");
        d.put("b15", "太委屈");
        d.put("b16", "大哭");
        d.put("b17", "泪奔");
        d.put("b18", "寻死");
        d.put("b19", "非常惊讶");
        d.put("b20", "表示疑问");
        d.put("b21", "鄙视你");
        d.put("b22", "大骂");
        d.put("b23", "狂怒");
        d.put("b24", "囧");
        d.put("b25", "晕");
        d.put("b26", "呕吐");
        d.put("b27", "财迷");
        d.put("b28", "睡了");
        d.put("b29", "思考");
        d.put("b30", "真汗");
        d.put("b31", "无语");
        d.put("b32", "拜");
        d.put("b33", "鞠躬");
        d.put("b34", "累了");
        d.put("b35", "病了");
        d.put("b36", "墙角");
        d.put("b37", "超人");
        d.put("b38", "戳");
        d.put("b39", "跳舞");
        d.put("b40", "鬼脸");
        d.put("b41", "无聊");
        d.put("b42", "撞墙");
        d.put("b43", "顶起");
        d.put("b44", "HI");
        d.put("b45", "饭");
        d.put("b46", "生日蛋糕");
        d.put("b47", "精美礼物");
        d.put("b48", "心");
        d.put("b49", "我心碎");
        d.put("b50", "玫瑰花");
        d.put("b51", "炸弹");
        d.put("b52", "集体舞");
        d.put("b53", "打人");
        d.put("b54", "拍拍");
        d.put("b55", "亲亲");
        d.put("b56", "握手");
        d.put("b57", "安慰");
        d.put("b58", "石头");
        d.put("b59", "剪子");
        d.put("b60", "布");
        d.put("b61", "恭喜啦");
        d.put("b62", "啵啵");
        d.put("yz_001", "焦糖舞");
        d.put("yz_002", "翻滚");
        d.put("yz_003", "拍屁股做鬼脸");
        d.put("yz_004", "不");
        d.put("yz_005", "河蟹掉啦");
        d.put("yz_006", "哦耶");
        d.put("yz_007", "我倒");
        d.put("yz_008", "投降");
        d.put("yz_009", "听音乐");
        d.put("yz_010", "被砸");
        d.put("yz_011", "吐舌头");
        d.put("yz_012", "太好啦");
        d.put("yz_013", "财源滚滚");
        d.put("yz_014", "人去哪了");
        d.put("yz_015", "挥手帕");
        d.put("yz_016", "偷笑");
        d.put("yz_017", "卷被");
        d.put("yz_018", "看楼上");
        d.put("yz_019", "我抽");
        d.put("yz_020", "有木有");
        d.put("yz_021", "哭");
        d.put("yz_022", "欢呼");
        d.put("yz_023", "傻兮兮");
        d.put("yz_024", "扇扇子");
        d.put("yz_025", "拍手");
        d.put("yz_026", "紧张");
        d.put("yz_027", "洗澡");
        d.put("yz_028", "耶");
        d.put("yz_029", "吃西瓜");
        d.put("yz_030", "纳尼");
        d.put("yz_031", "没有钱");
        d.put("yz_032", "拿玩偶");
        d.put("yz_033", "来看看");
        d.put("yz_034", "哇哇叫");
        d.put("yz_035", "招财猫");
        d.put("yz_036", "放屁");
        d.put("yz_037", "隆重介绍");
        d.put("yz_038", "求你了");
        d.put("yz_039", "撞玻璃");
        d.put("yz_040", "眺望");
        d.put("yz_041", "撒花");
        d.put("yz_042", "玩铃铛");
        d.put("yz_043", "思考者");
        d.put("yz_044", "抽风");
        d.put("yz_045", "吃苹果");
        d.put("yz_046", "光棍");
        d.put("she_001", "蛇年");
        d.put("she_002", "红包拿来");
        d.put("she_003", "美人鱼");
        d.put("she_004", "恭喜发财");
        d.put("she_005", "回家过年");
        d.put("she_006", "点灯笼");
        d.put("she_007", "招财兔");
        d.put("she_008", "喜庆鼓");
        d.put("she_009", "扭一扭");
        d.put("she_010", "又长一岁");
        d.put("she_011", "年年有鱼");
        d.put("she_012", "求红包");
        d.put("she_013", "压岁钱");
        d.put("she_014", "拜年");
        d.put("10th_001", "蹦蹦跳跳");
        d.put("10th_002", "晃悠");
        d.put("10th_003", "摇摇摆摆");
        d.put("10th_004", "大撒花");
        d.put("10th_005", "高高兴兴");
        d.put("10th_006", "弹吉他");
        d.put("10th_007", "魔法棒");
        d.put("10th_008", "扛大旗");
        d.put("10th_009", "点蜡烛");
        d.put("10th_010", "大秧歌");
        d.put("10th_011", "贴吧十周年");
        d.put("10th_012", "十周年");
    }

    @Override // com.baidu.tbadk.imageManager.b
    public int a(String str) {
        Integer num = c.get(str);
        if ("video_icon".equals(str)) {
            return Integer.valueOf(TiebaApplication.g().al() == 1 ? R.drawable.ico_link_video_1 : R.drawable.ico_link_video).intValue();
        } else if (num != null) {
            return num.intValue();
        } else {
            return 0;
        }
    }

    @Override // com.baidu.tbadk.imageManager.b
    public int b(String str) {
        Integer num = b.get(str);
        if (num != null) {
            return num.intValue();
        }
        return 0;
    }

    @Override // com.baidu.tbadk.imageManager.b
    public String c(String str) {
        return d.get(str);
    }

    @Override // com.baidu.tbadk.imageManager.b
    public com.baidu.tbadk.imageManager.c a(Context context, String str) {
        return null;
    }
}
