package com.baidu.tieba.util;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.drawable.BitmapDrawable;
import android.text.SpannableString;
import android.text.style.ImageSpan;
import com.baidu.tieba.R;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
/* loaded from: classes.dex */
public class FaceHelper {
    private static final HashMap<String, Integer> faces = new HashMap<>();
    private static final HashMap<String, String> file2str;
    private static final HashMap<String, Integer> write_faces;
    private static final ArrayList<Integer> write_faces_list;

    static {
        faces.put("B_0001", Integer.valueOf((int) R.drawable.b_0001));
        faces.put("B_0002", Integer.valueOf((int) R.drawable.b_0002));
        faces.put("B_0003", Integer.valueOf((int) R.drawable.b_0003));
        faces.put("B_0004", Integer.valueOf((int) R.drawable.b_0004));
        faces.put("B_0005", Integer.valueOf((int) R.drawable.b_0005));
        faces.put("B_0006", Integer.valueOf((int) R.drawable.b_0006));
        faces.put("B_0007", Integer.valueOf((int) R.drawable.b_0007));
        faces.put("B_0008", Integer.valueOf((int) R.drawable.b_0008));
        faces.put("B_0009", Integer.valueOf((int) R.drawable.b_0009));
        faces.put("B_0010", Integer.valueOf((int) R.drawable.b_0010));
        faces.put("B_0011", Integer.valueOf((int) R.drawable.b_0011));
        faces.put("B_0012", Integer.valueOf((int) R.drawable.b_0012));
        faces.put("B_0013", Integer.valueOf((int) R.drawable.b_0013));
        faces.put("B_0014", Integer.valueOf((int) R.drawable.b_0014));
        faces.put("B_0015", Integer.valueOf((int) R.drawable.b_0015));
        faces.put("B_0016", Integer.valueOf((int) R.drawable.b_0016));
        faces.put("B_0017", Integer.valueOf((int) R.drawable.b_0017));
        faces.put("B_0018", Integer.valueOf((int) R.drawable.b_0018));
        faces.put("B_0019", Integer.valueOf((int) R.drawable.b_0019));
        faces.put("B_0020", Integer.valueOf((int) R.drawable.b_0020));
        faces.put("B_0021", Integer.valueOf((int) R.drawable.b_0021));
        faces.put("B_0022", Integer.valueOf((int) R.drawable.b_0022));
        faces.put("B_0023", Integer.valueOf((int) R.drawable.b_0023));
        faces.put("B_0024", Integer.valueOf((int) R.drawable.b_0024));
        faces.put("B_0025", Integer.valueOf((int) R.drawable.b_0025));
        faces.put("B_0026", Integer.valueOf((int) R.drawable.b_0026));
        faces.put("B_0027", Integer.valueOf((int) R.drawable.b_0027));
        faces.put("B_0028", Integer.valueOf((int) R.drawable.b_0028));
        faces.put("B_0029", Integer.valueOf((int) R.drawable.b_0029));
        faces.put("B_0030", Integer.valueOf((int) R.drawable.b_0030));
        faces.put("B_0031", Integer.valueOf((int) R.drawable.b_0031));
        faces.put("B_0032", Integer.valueOf((int) R.drawable.b_0032));
        faces.put("B_0033", Integer.valueOf((int) R.drawable.b_0033));
        faces.put("B_0034", Integer.valueOf((int) R.drawable.b_0034));
        faces.put("B_0035", Integer.valueOf((int) R.drawable.b_0035));
        faces.put("B_0036", Integer.valueOf((int) R.drawable.b_0036));
        faces.put("B_0037", Integer.valueOf((int) R.drawable.b_0037));
        faces.put("B_0038", Integer.valueOf((int) R.drawable.b_0038));
        faces.put("B_0039", Integer.valueOf((int) R.drawable.b_0039));
        faces.put("B_0040", Integer.valueOf((int) R.drawable.b_0040));
        faces.put("B_0041", Integer.valueOf((int) R.drawable.b_0041));
        faces.put("B_0042", Integer.valueOf((int) R.drawable.b_0042));
        faces.put("B_0043", Integer.valueOf((int) R.drawable.b_0043));
        faces.put("B_0044", Integer.valueOf((int) R.drawable.b_0044));
        faces.put("B_0045", Integer.valueOf((int) R.drawable.b_0045));
        faces.put("B_0046", Integer.valueOf((int) R.drawable.b_0046));
        faces.put("B_0047", Integer.valueOf((int) R.drawable.b_0047));
        faces.put("B_0048", Integer.valueOf((int) R.drawable.b_0048));
        faces.put("B_0049", Integer.valueOf((int) R.drawable.b_0049));
        faces.put("B_0050", Integer.valueOf((int) R.drawable.b_0050));
        faces.put("B_0051", Integer.valueOf((int) R.drawable.b_0051));
        faces.put("B_0052", Integer.valueOf((int) R.drawable.b_0052));
        faces.put("B_0053", Integer.valueOf((int) R.drawable.b_0053));
        faces.put("B_0054", Integer.valueOf((int) R.drawable.b_0054));
        faces.put("B_0055", Integer.valueOf((int) R.drawable.b_0055));
        faces.put("B_0056", Integer.valueOf((int) R.drawable.b_0056));
        faces.put("B_0057", Integer.valueOf((int) R.drawable.b_0057));
        faces.put("B_0058", Integer.valueOf((int) R.drawable.b_0058));
        faces.put("B_0059", Integer.valueOf((int) R.drawable.b_0059));
        faces.put("B_0060", Integer.valueOf((int) R.drawable.b_0060));
        faces.put("B_0061", Integer.valueOf((int) R.drawable.b_0061));
        faces.put("B_0062", Integer.valueOf((int) R.drawable.b_0062));
        faces.put("B_0063", Integer.valueOf((int) R.drawable.b_0063));
        faces.put("i_f01", Integer.valueOf((int) R.drawable.image_emoticon));
        faces.put("i_f02", Integer.valueOf((int) R.drawable.image_emoticon2));
        faces.put("i_f03", Integer.valueOf((int) R.drawable.image_emoticon3));
        faces.put("i_f04", Integer.valueOf((int) R.drawable.image_emoticon4));
        faces.put("i_f05", Integer.valueOf((int) R.drawable.image_emoticon5));
        faces.put("i_f06", Integer.valueOf((int) R.drawable.image_emoticon6));
        faces.put("i_f07", Integer.valueOf((int) R.drawable.image_emoticon7));
        faces.put("i_f08", Integer.valueOf((int) R.drawable.image_emoticon8));
        faces.put("i_f09", Integer.valueOf((int) R.drawable.image_emoticon9));
        faces.put("i_f10", Integer.valueOf((int) R.drawable.image_emoticon10));
        faces.put("i_f11", Integer.valueOf((int) R.drawable.image_emoticon11));
        faces.put("i_f12", Integer.valueOf((int) R.drawable.image_emoticon12));
        faces.put("i_f13", Integer.valueOf((int) R.drawable.image_emoticon13));
        faces.put("i_f14", Integer.valueOf((int) R.drawable.image_emoticon14));
        faces.put("i_f15", Integer.valueOf((int) R.drawable.image_emoticon15));
        faces.put("i_f16", Integer.valueOf((int) R.drawable.image_emoticon16));
        faces.put("i_f17", Integer.valueOf((int) R.drawable.image_emoticon17));
        faces.put("i_f18", Integer.valueOf((int) R.drawable.image_emoticon18));
        faces.put("i_f19", Integer.valueOf((int) R.drawable.image_emoticon19));
        faces.put("i_f20", Integer.valueOf((int) R.drawable.image_emoticon20));
        faces.put("i_f21", Integer.valueOf((int) R.drawable.image_emoticon21));
        faces.put("i_f22", Integer.valueOf((int) R.drawable.image_emoticon34));
        faces.put("i_f23", Integer.valueOf((int) R.drawable.image_emoticon35));
        faces.put("i_f24", Integer.valueOf((int) R.drawable.image_emoticon36));
        faces.put("i_f25", Integer.valueOf((int) R.drawable.image_emoticon37));
        faces.put("i_f26", Integer.valueOf((int) R.drawable.image_emoticon22));
        faces.put("i_f27", Integer.valueOf((int) R.drawable.image_emoticon23));
        faces.put("i_f28", Integer.valueOf((int) R.drawable.image_emoticon24));
        faces.put("i_f29", Integer.valueOf((int) R.drawable.image_emoticon25));
        faces.put("i_f30", Integer.valueOf((int) R.drawable.image_emoticon26));
        faces.put("i_f31", Integer.valueOf((int) R.drawable.image_emoticon27));
        faces.put("i_f32", Integer.valueOf((int) R.drawable.image_emoticon28));
        faces.put("i_f33", Integer.valueOf((int) R.drawable.image_emoticon29));
        faces.put("i_f34", Integer.valueOf((int) R.drawable.image_emoticon30));
        faces.put("i_f35", Integer.valueOf((int) R.drawable.image_emoticon31));
        faces.put("i_f36", Integer.valueOf((int) R.drawable.image_emoticon32));
        faces.put("i_f37", Integer.valueOf((int) R.drawable.image_emoticon33));
        faces.put("i_f38", Integer.valueOf((int) R.drawable.image_emoticon38));
        faces.put("i_f39", Integer.valueOf((int) R.drawable.image_emoticon39));
        faces.put("i_f40", Integer.valueOf((int) R.drawable.image_emoticon40));
        faces.put("i_f41", Integer.valueOf((int) R.drawable.image_emoticon41));
        faces.put("i_f42", Integer.valueOf((int) R.drawable.image_emoticon42));
        faces.put("i_f43", Integer.valueOf((int) R.drawable.image_emoticon43));
        faces.put("i_f44", Integer.valueOf((int) R.drawable.image_emoticon44));
        faces.put("i_f45", Integer.valueOf((int) R.drawable.image_emoticon45));
        faces.put("i_f46", Integer.valueOf((int) R.drawable.image_emoticon46));
        faces.put("i_f47", Integer.valueOf((int) R.drawable.image_emoticon47));
        faces.put("i_f48", Integer.valueOf((int) R.drawable.image_emoticon48));
        faces.put("i_f49", Integer.valueOf((int) R.drawable.image_emoticon49));
        faces.put("i_f50", Integer.valueOf((int) R.drawable.image_emoticon50));
        faces.put("w_0001", Integer.valueOf((int) R.drawable.w_0001));
        faces.put("w_0002", Integer.valueOf((int) R.drawable.w_0002));
        faces.put("w_0003", Integer.valueOf((int) R.drawable.w_0003));
        faces.put("w_0004", Integer.valueOf((int) R.drawable.w_0004));
        faces.put("w_0005", Integer.valueOf((int) R.drawable.w_0005));
        faces.put("w_0006", Integer.valueOf((int) R.drawable.w_0006));
        faces.put("w_0007", Integer.valueOf((int) R.drawable.w_0007));
        faces.put("w_0008", Integer.valueOf((int) R.drawable.w_0008));
        faces.put("w_0009", Integer.valueOf((int) R.drawable.w_0009));
        faces.put("w_0010", Integer.valueOf((int) R.drawable.w_0010));
        faces.put("w_0011", Integer.valueOf((int) R.drawable.w_0011));
        faces.put("w_0012", Integer.valueOf((int) R.drawable.w_0012));
        faces.put("w_0013", Integer.valueOf((int) R.drawable.w_0013));
        faces.put("w_0014", Integer.valueOf((int) R.drawable.w_0014));
        faces.put("w_0015", Integer.valueOf((int) R.drawable.w_0015));
        faces.put("w_0016", Integer.valueOf((int) R.drawable.w_0016));
        faces.put("w_0017", Integer.valueOf((int) R.drawable.w_0017));
        faces.put("w_0018", Integer.valueOf((int) R.drawable.w_0018));
        faces.put("w_0019", Integer.valueOf((int) R.drawable.w_0019));
        faces.put("w_0020", Integer.valueOf((int) R.drawable.w_0020));
        faces.put("w_0021", Integer.valueOf((int) R.drawable.w_0021));
        faces.put("w_0022", Integer.valueOf((int) R.drawable.w_0022));
        faces.put("w_0023", Integer.valueOf((int) R.drawable.w_0023));
        faces.put("w_0024", Integer.valueOf((int) R.drawable.w_0024));
        faces.put("w_0025", Integer.valueOf((int) R.drawable.w_0025));
        faces.put("w_0026", Integer.valueOf((int) R.drawable.w_0026));
        faces.put("w_0027", Integer.valueOf((int) R.drawable.w_0027));
        faces.put("w_0028", Integer.valueOf((int) R.drawable.w_0028));
        faces.put("w_0029", Integer.valueOf((int) R.drawable.w_0029));
        faces.put("w_0030", Integer.valueOf((int) R.drawable.w_0030));
        faces.put("w_0031", Integer.valueOf((int) R.drawable.w_0031));
        faces.put("w_0032", Integer.valueOf((int) R.drawable.w_0032));
        faces.put("w_0033", Integer.valueOf((int) R.drawable.w_0033));
        faces.put("w_0034", Integer.valueOf((int) R.drawable.w_0034));
        faces.put("w_0035", Integer.valueOf((int) R.drawable.w_0035));
        faces.put("w_0036", Integer.valueOf((int) R.drawable.w_0036));
        faces.put("w_0037", Integer.valueOf((int) R.drawable.w_0037));
        faces.put("w_0038", Integer.valueOf((int) R.drawable.w_0038));
        faces.put("w_0039", Integer.valueOf((int) R.drawable.w_0039));
        faces.put("w_0040", Integer.valueOf((int) R.drawable.w_0040));
        faces.put("w_0041", Integer.valueOf((int) R.drawable.w_0041));
        faces.put("w_0042", Integer.valueOf((int) R.drawable.w_0042));
        faces.put("w_0043", Integer.valueOf((int) R.drawable.w_0043));
        faces.put("w_0044", Integer.valueOf((int) R.drawable.w_0044));
        faces.put("w_0045", Integer.valueOf((int) R.drawable.w_0045));
        faces.put("w_0046", Integer.valueOf((int) R.drawable.w_0046));
        faces.put("w_0047", Integer.valueOf((int) R.drawable.w_0047));
        faces.put("w_0048", Integer.valueOf((int) R.drawable.w_0048));
        faces.put("w_0049", Integer.valueOf((int) R.drawable.w_0049));
        faces.put("w_0050", Integer.valueOf((int) R.drawable.w_0050));
        faces.put("w_0051", Integer.valueOf((int) R.drawable.w_0051));
        faces.put("w_0052", Integer.valueOf((int) R.drawable.w_0052));
        faces.put("w_0053", Integer.valueOf((int) R.drawable.w_0053));
        faces.put("t_0001", Integer.valueOf((int) R.drawable.t_0001));
        faces.put("t_0002", Integer.valueOf((int) R.drawable.t_0002));
        faces.put("t_0003", Integer.valueOf((int) R.drawable.t_0003));
        faces.put("t_0004", Integer.valueOf((int) R.drawable.t_0004));
        faces.put("t_0005", Integer.valueOf((int) R.drawable.t_0005));
        faces.put("t_0006", Integer.valueOf((int) R.drawable.t_0006));
        faces.put("t_0007", Integer.valueOf((int) R.drawable.t_0007));
        faces.put("t_0008", Integer.valueOf((int) R.drawable.t_0008));
        faces.put("t_0009", Integer.valueOf((int) R.drawable.t_0009));
        faces.put("t_0010", Integer.valueOf((int) R.drawable.t_0010));
        faces.put("t_0011", Integer.valueOf((int) R.drawable.t_0011));
        faces.put("t_0012", Integer.valueOf((int) R.drawable.t_0012));
        faces.put("t_0013", Integer.valueOf((int) R.drawable.t_0013));
        faces.put("t_0014", Integer.valueOf((int) R.drawable.t_0014));
        faces.put("t_0015", Integer.valueOf((int) R.drawable.t_0015));
        faces.put("t_0016", Integer.valueOf((int) R.drawable.t_0016));
        faces.put("t_0017", Integer.valueOf((int) R.drawable.t_0017));
        faces.put("t_0018", Integer.valueOf((int) R.drawable.t_0018));
        faces.put("t_0019", Integer.valueOf((int) R.drawable.t_0019));
        faces.put("t_0020", Integer.valueOf((int) R.drawable.t_0020));
        faces.put("t_0021", Integer.valueOf((int) R.drawable.t_0021));
        faces.put("t_0022", Integer.valueOf((int) R.drawable.t_0022));
        faces.put("t_0023", Integer.valueOf((int) R.drawable.t_0023));
        faces.put("t_0024", Integer.valueOf((int) R.drawable.t_0024));
        faces.put("t_0025", Integer.valueOf((int) R.drawable.t_0025));
        faces.put("t_0026", Integer.valueOf((int) R.drawable.t_0026));
        faces.put("t_0027", Integer.valueOf((int) R.drawable.t_0027));
        faces.put("t_0028", Integer.valueOf((int) R.drawable.t_0028));
        faces.put("t_0029", Integer.valueOf((int) R.drawable.t_0029));
        faces.put("t_0030", Integer.valueOf((int) R.drawable.t_0030));
        faces.put("t_0031", Integer.valueOf((int) R.drawable.t_0031));
        faces.put("t_0032", Integer.valueOf((int) R.drawable.t_0032));
        faces.put("t_0033", Integer.valueOf((int) R.drawable.t_0033));
        faces.put("t_0034", Integer.valueOf((int) R.drawable.t_0034));
        faces.put("t_0035", Integer.valueOf((int) R.drawable.t_0035));
        faces.put("t_0036", Integer.valueOf((int) R.drawable.t_0036));
        faces.put("t_0037", Integer.valueOf((int) R.drawable.t_0037));
        faces.put("t_0038", Integer.valueOf((int) R.drawable.t_0038));
        faces.put("t_0039", Integer.valueOf((int) R.drawable.t_0039));
        faces.put("t_0040", Integer.valueOf((int) R.drawable.t_0040));
        faces.put("image_emoticon", Integer.valueOf((int) R.drawable.image_emoticon));
        faces.put("image_emoticon2", Integer.valueOf((int) R.drawable.image_emoticon2));
        faces.put("image_emoticon3", Integer.valueOf((int) R.drawable.image_emoticon3));
        faces.put("image_emoticon4", Integer.valueOf((int) R.drawable.image_emoticon4));
        faces.put("image_emoticon5", Integer.valueOf((int) R.drawable.image_emoticon5));
        faces.put("image_emoticon6", Integer.valueOf((int) R.drawable.image_emoticon6));
        faces.put("image_emoticon7", Integer.valueOf((int) R.drawable.image_emoticon7));
        faces.put("image_emoticon8", Integer.valueOf((int) R.drawable.image_emoticon8));
        faces.put("image_emoticon9", Integer.valueOf((int) R.drawable.image_emoticon9));
        faces.put("image_emoticon10", Integer.valueOf((int) R.drawable.image_emoticon10));
        faces.put("image_emoticon11", Integer.valueOf((int) R.drawable.image_emoticon11));
        faces.put("image_emoticon12", Integer.valueOf((int) R.drawable.image_emoticon12));
        faces.put("image_emoticon13", Integer.valueOf((int) R.drawable.image_emoticon13));
        faces.put("image_emoticon14", Integer.valueOf((int) R.drawable.image_emoticon14));
        faces.put("image_emoticon15", Integer.valueOf((int) R.drawable.image_emoticon15));
        faces.put("image_emoticon16", Integer.valueOf((int) R.drawable.image_emoticon16));
        faces.put("image_emoticon17", Integer.valueOf((int) R.drawable.image_emoticon17));
        faces.put("image_emoticon18", Integer.valueOf((int) R.drawable.image_emoticon18));
        faces.put("image_emoticon19", Integer.valueOf((int) R.drawable.image_emoticon19));
        faces.put("image_emoticon20", Integer.valueOf((int) R.drawable.image_emoticon20));
        faces.put("image_emoticon21", Integer.valueOf((int) R.drawable.image_emoticon21));
        faces.put("image_emoticon22", Integer.valueOf((int) R.drawable.image_emoticon22));
        faces.put("image_emoticon23", Integer.valueOf((int) R.drawable.image_emoticon23));
        faces.put("image_emoticon24", Integer.valueOf((int) R.drawable.image_emoticon24));
        faces.put("image_emoticon25", Integer.valueOf((int) R.drawable.image_emoticon25));
        faces.put("image_emoticon26", Integer.valueOf((int) R.drawable.image_emoticon26));
        faces.put("image_emoticon27", Integer.valueOf((int) R.drawable.image_emoticon27));
        faces.put("image_emoticon28", Integer.valueOf((int) R.drawable.image_emoticon28));
        faces.put("image_emoticon29", Integer.valueOf((int) R.drawable.image_emoticon29));
        faces.put("image_emoticon30", Integer.valueOf((int) R.drawable.image_emoticon30));
        faces.put("image_emoticon31", Integer.valueOf((int) R.drawable.image_emoticon31));
        faces.put("image_emoticon32", Integer.valueOf((int) R.drawable.image_emoticon32));
        faces.put("image_emoticon33", Integer.valueOf((int) R.drawable.image_emoticon33));
        faces.put("image_emoticon34", Integer.valueOf((int) R.drawable.image_emoticon34));
        faces.put("image_emoticon35", Integer.valueOf((int) R.drawable.image_emoticon35));
        faces.put("image_emoticon36", Integer.valueOf((int) R.drawable.image_emoticon36));
        faces.put("image_emoticon37", Integer.valueOf((int) R.drawable.image_emoticon37));
        faces.put("image_emoticon38", Integer.valueOf((int) R.drawable.image_emoticon38));
        faces.put("image_emoticon39", Integer.valueOf((int) R.drawable.image_emoticon39));
        faces.put("image_emoticon40", Integer.valueOf((int) R.drawable.image_emoticon40));
        faces.put("image_emoticon41", Integer.valueOf((int) R.drawable.image_emoticon41));
        faces.put("image_emoticon42", Integer.valueOf((int) R.drawable.image_emoticon42));
        faces.put("image_emoticon43", Integer.valueOf((int) R.drawable.image_emoticon43));
        faces.put("image_emoticon44", Integer.valueOf((int) R.drawable.image_emoticon44));
        faces.put("image_emoticon45", Integer.valueOf((int) R.drawable.image_emoticon45));
        faces.put("image_emoticon46", Integer.valueOf((int) R.drawable.image_emoticon46));
        faces.put("image_emoticon47", Integer.valueOf((int) R.drawable.image_emoticon47));
        faces.put("image_emoticon48", Integer.valueOf((int) R.drawable.image_emoticon48));
        faces.put("image_emoticon49", Integer.valueOf((int) R.drawable.image_emoticon49));
        faces.put("image_emoticon50", Integer.valueOf((int) R.drawable.image_emoticon50));
        faces.put("ali_001", Integer.valueOf((int) R.drawable.ali_001));
        faces.put("ali_002", Integer.valueOf((int) R.drawable.ali_002));
        faces.put("ali_003", Integer.valueOf((int) R.drawable.ali_003));
        faces.put("ali_004", Integer.valueOf((int) R.drawable.ali_004));
        faces.put("ali_005", Integer.valueOf((int) R.drawable.ali_005));
        faces.put("ali_006", Integer.valueOf((int) R.drawable.ali_006));
        faces.put("ali_007", Integer.valueOf((int) R.drawable.ali_007));
        faces.put("ali_008", Integer.valueOf((int) R.drawable.ali_008));
        faces.put("ali_009", Integer.valueOf((int) R.drawable.ali_009));
        faces.put("ali_010", Integer.valueOf((int) R.drawable.ali_010));
        faces.put("ali_011", Integer.valueOf((int) R.drawable.ali_011));
        faces.put("ali_012", Integer.valueOf((int) R.drawable.ali_012));
        faces.put("ali_013", Integer.valueOf((int) R.drawable.ali_013));
        faces.put("ali_014", Integer.valueOf((int) R.drawable.ali_014));
        faces.put("ali_015", Integer.valueOf((int) R.drawable.ali_015));
        faces.put("ali_016", Integer.valueOf((int) R.drawable.ali_016));
        faces.put("ali_017", Integer.valueOf((int) R.drawable.ali_017));
        faces.put("ali_018", Integer.valueOf((int) R.drawable.ali_018));
        faces.put("ali_019", Integer.valueOf((int) R.drawable.ali_019));
        faces.put("ali_020", Integer.valueOf((int) R.drawable.ali_020));
        faces.put("ali_021", Integer.valueOf((int) R.drawable.ali_021));
        faces.put("ali_022", Integer.valueOf((int) R.drawable.ali_022));
        faces.put("ali_023", Integer.valueOf((int) R.drawable.ali_023));
        faces.put("ali_024", Integer.valueOf((int) R.drawable.ali_024));
        faces.put("ali_025", Integer.valueOf((int) R.drawable.ali_025));
        faces.put("ali_026", Integer.valueOf((int) R.drawable.ali_026));
        faces.put("ali_027", Integer.valueOf((int) R.drawable.ali_027));
        faces.put("ali_028", Integer.valueOf((int) R.drawable.ali_028));
        faces.put("ali_029", Integer.valueOf((int) R.drawable.ali_029));
        faces.put("ali_030", Integer.valueOf((int) R.drawable.ali_030));
        faces.put("ali_031", Integer.valueOf((int) R.drawable.ali_031));
        faces.put("ali_032", Integer.valueOf((int) R.drawable.ali_032));
        faces.put("ali_033", Integer.valueOf((int) R.drawable.ali_033));
        faces.put("ali_034", Integer.valueOf((int) R.drawable.ali_034));
        faces.put("ali_035", Integer.valueOf((int) R.drawable.ali_035));
        faces.put("ali_036", Integer.valueOf((int) R.drawable.ali_036));
        faces.put("ali_037", Integer.valueOf((int) R.drawable.ali_037));
        faces.put("ali_038", Integer.valueOf((int) R.drawable.ali_038));
        faces.put("ali_039", Integer.valueOf((int) R.drawable.ali_039));
        faces.put("ali_040", Integer.valueOf((int) R.drawable.ali_040));
        faces.put("ali_041", Integer.valueOf((int) R.drawable.ali_041));
        faces.put("ali_042", Integer.valueOf((int) R.drawable.ali_042));
        faces.put("ali_043", Integer.valueOf((int) R.drawable.ali_043));
        faces.put("ali_044", Integer.valueOf((int) R.drawable.ali_044));
        faces.put("ali_045", Integer.valueOf((int) R.drawable.ali_045));
        faces.put("ali_046", Integer.valueOf((int) R.drawable.ali_046));
        faces.put("ali_047", Integer.valueOf((int) R.drawable.ali_047));
        faces.put("ali_048", Integer.valueOf((int) R.drawable.ali_048));
        faces.put("ali_049", Integer.valueOf((int) R.drawable.ali_049));
        faces.put("ali_050", Integer.valueOf((int) R.drawable.ali_050));
        faces.put("ali_051", Integer.valueOf((int) R.drawable.ali_051));
        faces.put("ali_052", Integer.valueOf((int) R.drawable.ali_052));
        faces.put("ali_053", Integer.valueOf((int) R.drawable.ali_053));
        faces.put("ali_054", Integer.valueOf((int) R.drawable.ali_054));
        faces.put("ali_055", Integer.valueOf((int) R.drawable.ali_055));
        faces.put("ali_056", Integer.valueOf((int) R.drawable.ali_056));
        faces.put("ali_057", Integer.valueOf((int) R.drawable.ali_057));
        faces.put("ali_058", Integer.valueOf((int) R.drawable.ali_058));
        faces.put("ali_059", Integer.valueOf((int) R.drawable.ali_059));
        faces.put("ali_060", Integer.valueOf((int) R.drawable.ali_060));
        faces.put("ali_061", Integer.valueOf((int) R.drawable.ali_061));
        faces.put("ali_062", Integer.valueOf((int) R.drawable.ali_062));
        faces.put("ali_063", Integer.valueOf((int) R.drawable.ali_063));
        faces.put("ali_064", Integer.valueOf((int) R.drawable.ali_064));
        faces.put("ali_065", Integer.valueOf((int) R.drawable.ali_065));
        faces.put("ali_066", Integer.valueOf((int) R.drawable.ali_066));
        faces.put("ali_067", Integer.valueOf((int) R.drawable.ali_067));
        faces.put("ali_068", Integer.valueOf((int) R.drawable.ali_068));
        faces.put("ali_069", Integer.valueOf((int) R.drawable.ali_069));
        faces.put("ali_070", Integer.valueOf((int) R.drawable.ali_070));
        faces.put("b01", Integer.valueOf((int) R.drawable.b01));
        faces.put("b02", Integer.valueOf((int) R.drawable.b02));
        faces.put("b03", Integer.valueOf((int) R.drawable.b03));
        faces.put("b04", Integer.valueOf((int) R.drawable.b04));
        faces.put("b05", Integer.valueOf((int) R.drawable.b05));
        faces.put("b06", Integer.valueOf((int) R.drawable.b06));
        faces.put("b07", Integer.valueOf((int) R.drawable.b07));
        faces.put("b08", Integer.valueOf((int) R.drawable.b08));
        faces.put("b09", Integer.valueOf((int) R.drawable.b09));
        faces.put("b10", Integer.valueOf((int) R.drawable.b10));
        faces.put("b11", Integer.valueOf((int) R.drawable.b11));
        faces.put("b12", Integer.valueOf((int) R.drawable.b12));
        faces.put("b13", Integer.valueOf((int) R.drawable.b13));
        faces.put("b14", Integer.valueOf((int) R.drawable.b14));
        faces.put("b15", Integer.valueOf((int) R.drawable.b15));
        faces.put("b16", Integer.valueOf((int) R.drawable.b16));
        faces.put("b17", Integer.valueOf((int) R.drawable.b17));
        faces.put("b18", Integer.valueOf((int) R.drawable.b18));
        faces.put("b19", Integer.valueOf((int) R.drawable.b19));
        faces.put("b20", Integer.valueOf((int) R.drawable.b20));
        faces.put("b21", Integer.valueOf((int) R.drawable.b21));
        faces.put("b22", Integer.valueOf((int) R.drawable.b22));
        faces.put("b23", Integer.valueOf((int) R.drawable.b23));
        faces.put("b24", Integer.valueOf((int) R.drawable.b24));
        faces.put("b25", Integer.valueOf((int) R.drawable.b25));
        faces.put("b26", Integer.valueOf((int) R.drawable.b26));
        faces.put("b27", Integer.valueOf((int) R.drawable.b27));
        faces.put("b28", Integer.valueOf((int) R.drawable.b28));
        faces.put("b29", Integer.valueOf((int) R.drawable.b29));
        faces.put("b30", Integer.valueOf((int) R.drawable.b30));
        faces.put("b31", Integer.valueOf((int) R.drawable.b31));
        faces.put("b32", Integer.valueOf((int) R.drawable.b32));
        faces.put("b33", Integer.valueOf((int) R.drawable.b33));
        faces.put("b34", Integer.valueOf((int) R.drawable.b34));
        faces.put("b35", Integer.valueOf((int) R.drawable.b35));
        faces.put("b36", Integer.valueOf((int) R.drawable.b36));
        faces.put("b37", Integer.valueOf((int) R.drawable.b37));
        faces.put("b38", Integer.valueOf((int) R.drawable.b38));
        faces.put("b39", Integer.valueOf((int) R.drawable.b39));
        faces.put("b40", Integer.valueOf((int) R.drawable.b40));
        faces.put("b41", Integer.valueOf((int) R.drawable.b41));
        faces.put("b42", Integer.valueOf((int) R.drawable.b42));
        faces.put("b43", Integer.valueOf((int) R.drawable.b43));
        faces.put("b44", Integer.valueOf((int) R.drawable.b44));
        faces.put("b45", Integer.valueOf((int) R.drawable.b45));
        faces.put("b46", Integer.valueOf((int) R.drawable.b46));
        faces.put("b47", Integer.valueOf((int) R.drawable.b47));
        faces.put("b48", Integer.valueOf((int) R.drawable.b48));
        faces.put("b49", Integer.valueOf((int) R.drawable.b49));
        faces.put("b50", Integer.valueOf((int) R.drawable.b50));
        faces.put("b51", Integer.valueOf((int) R.drawable.b51));
        faces.put("b52", Integer.valueOf((int) R.drawable.b52));
        faces.put("b53", Integer.valueOf((int) R.drawable.b53));
        faces.put("b54", Integer.valueOf((int) R.drawable.b54));
        faces.put("b55", Integer.valueOf((int) R.drawable.b55));
        faces.put("b56", Integer.valueOf((int) R.drawable.b56));
        faces.put("b57", Integer.valueOf((int) R.drawable.b57));
        faces.put("b58", Integer.valueOf((int) R.drawable.b58));
        faces.put("b59", Integer.valueOf((int) R.drawable.b59));
        faces.put("b60", Integer.valueOf((int) R.drawable.b60));
        faces.put("b61", Integer.valueOf((int) R.drawable.b61));
        faces.put("b62", Integer.valueOf((int) R.drawable.b62));
        faces.put("yz_001", Integer.valueOf((int) R.drawable.yz_001));
        faces.put("yz_002", Integer.valueOf((int) R.drawable.yz_002));
        faces.put("yz_003", Integer.valueOf((int) R.drawable.yz_003));
        faces.put("yz_004", Integer.valueOf((int) R.drawable.yz_004));
        faces.put("yz_005", Integer.valueOf((int) R.drawable.yz_005));
        faces.put("yz_006", Integer.valueOf((int) R.drawable.yz_006));
        faces.put("yz_007", Integer.valueOf((int) R.drawable.yz_007));
        faces.put("yz_008", Integer.valueOf((int) R.drawable.yz_008));
        faces.put("yz_009", Integer.valueOf((int) R.drawable.yz_009));
        faces.put("yz_010", Integer.valueOf((int) R.drawable.yz_010));
        faces.put("yz_011", Integer.valueOf((int) R.drawable.yz_011));
        faces.put("yz_012", Integer.valueOf((int) R.drawable.yz_012));
        faces.put("yz_013", Integer.valueOf((int) R.drawable.yz_013));
        faces.put("yz_014", Integer.valueOf((int) R.drawable.yz_014));
        faces.put("yz_015", Integer.valueOf((int) R.drawable.yz_015));
        faces.put("yz_016", Integer.valueOf((int) R.drawable.yz_016));
        faces.put("yz_017", Integer.valueOf((int) R.drawable.yz_017));
        faces.put("yz_018", Integer.valueOf((int) R.drawable.yz_018));
        faces.put("yz_019", Integer.valueOf((int) R.drawable.yz_019));
        faces.put("yz_020", Integer.valueOf((int) R.drawable.yz_020));
        faces.put("yz_021", Integer.valueOf((int) R.drawable.yz_021));
        faces.put("yz_022", Integer.valueOf((int) R.drawable.yz_022));
        faces.put("yz_023", Integer.valueOf((int) R.drawable.yz_023));
        faces.put("yz_024", Integer.valueOf((int) R.drawable.yz_024));
        faces.put("yz_025", Integer.valueOf((int) R.drawable.yz_025));
        faces.put("yz_026", Integer.valueOf((int) R.drawable.yz_026));
        faces.put("yz_027", Integer.valueOf((int) R.drawable.yz_027));
        faces.put("yz_028", Integer.valueOf((int) R.drawable.yz_028));
        faces.put("yz_029", Integer.valueOf((int) R.drawable.yz_029));
        faces.put("yz_030", Integer.valueOf((int) R.drawable.yz_030));
        faces.put("yz_031", Integer.valueOf((int) R.drawable.yz_031));
        faces.put("yz_032", Integer.valueOf((int) R.drawable.yz_032));
        faces.put("yz_033", Integer.valueOf((int) R.drawable.yz_033));
        faces.put("yz_034", Integer.valueOf((int) R.drawable.yz_034));
        faces.put("yz_035", Integer.valueOf((int) R.drawable.yz_035));
        faces.put("yz_036", Integer.valueOf((int) R.drawable.yz_036));
        faces.put("yz_037", Integer.valueOf((int) R.drawable.yz_037));
        faces.put("yz_038", Integer.valueOf((int) R.drawable.yz_038));
        faces.put("yz_039", Integer.valueOf((int) R.drawable.yz_039));
        faces.put("yz_040", Integer.valueOf((int) R.drawable.yz_040));
        faces.put("yz_041", Integer.valueOf((int) R.drawable.yz_041));
        faces.put("yz_042", Integer.valueOf((int) R.drawable.yz_042));
        faces.put("yz_043", Integer.valueOf((int) R.drawable.yz_043));
        faces.put("yz_044", Integer.valueOf((int) R.drawable.yz_044));
        faces.put("yz_045", Integer.valueOf((int) R.drawable.yz_045));
        faces.put("yz_046", Integer.valueOf((int) R.drawable.yz_046));
        write_faces_list = new ArrayList<>();
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_01));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_02));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_03));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_04));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_05));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_06));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_07));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_08));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_09));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_10));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_11));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_12));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_13));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_14));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_15));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_16));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_17));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_18));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_19));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_20));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_21));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_22));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_23));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_24));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_25));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_26));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_27));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_28));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_29));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_30));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_31));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_32));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_33));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_34));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_35));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_36));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_37));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_38));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_39));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_40));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_41));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_42));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_43));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_44));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_45));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_46));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_47));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_48));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_49));
        write_faces_list.add(Integer.valueOf((int) R.drawable.write_face_50));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_ali_047));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_ali_050));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_ali_051));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_ali_052));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_ali_053));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_ali_054));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_ali_055));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_ali_056));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_ali_059));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_ali_060));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_ali_061));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_ali_062));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_ali_063));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_ali_064));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_ali_065));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_ali_066));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_ali_067));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_ali_068));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_ali_069));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_ali_070));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_yz_001));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_yz_002));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_yz_003));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_yz_004));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_yz_005));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_yz_006));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_yz_007));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_yz_008));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_yz_009));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_yz_010));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_yz_011));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_yz_012));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_yz_013));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_yz_014));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_yz_016));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_yz_017));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_yz_018));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_yz_019));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_yz_020));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_yz_021));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_b01));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_b02));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_b03));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_b04));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_b05));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_b06));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_b07));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_b08));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_b09));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_b10));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_b11));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_b12));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_b13));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_b14));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_b15));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_b16));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_b17));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_b18));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_b19));
        write_faces_list.add(Integer.valueOf((int) R.drawable.e_b20));
        write_faces = new HashMap<>();
        write_faces.put("#(呵呵)", write_faces_list.get(0));
        write_faces.put("#(哈哈)", write_faces_list.get(1));
        write_faces.put("#(吐舌)", write_faces_list.get(2));
        write_faces.put("#(啊)", write_faces_list.get(3));
        write_faces.put("#(酷)", write_faces_list.get(4));
        write_faces.put("#(怒)", write_faces_list.get(5));
        write_faces.put("#(开心)", write_faces_list.get(6));
        write_faces.put("#(汗)", write_faces_list.get(7));
        write_faces.put("#(泪)", write_faces_list.get(8));
        write_faces.put("#(黑线)", write_faces_list.get(9));
        write_faces.put("#(鄙视)", write_faces_list.get(10));
        write_faces.put("#(不高兴)", write_faces_list.get(11));
        write_faces.put("#(真棒)", write_faces_list.get(12));
        write_faces.put("#(钱)", write_faces_list.get(13));
        write_faces.put("#(疑问)", write_faces_list.get(14));
        write_faces.put("#(阴险)", write_faces_list.get(15));
        write_faces.put("#(吐)", write_faces_list.get(16));
        write_faces.put("#(咦)", write_faces_list.get(17));
        write_faces.put("#(委屈)", write_faces_list.get(18));
        write_faces.put("#(花心)", write_faces_list.get(19));
        write_faces.put("#(呼~)", write_faces_list.get(20));
        write_faces.put("#(笑眼)", write_faces_list.get(21));
        write_faces.put("#(冷)", write_faces_list.get(22));
        write_faces.put("#(太开心)", write_faces_list.get(23));
        write_faces.put("#(滑稽)", write_faces_list.get(24));
        write_faces.put("#(勉强)", write_faces_list.get(25));
        write_faces.put("#(狂汗)", write_faces_list.get(26));
        write_faces.put("#(乖)", write_faces_list.get(27));
        write_faces.put("#(睡觉)", write_faces_list.get(28));
        write_faces.put("#(惊哭)", write_faces_list.get(29));
        write_faces.put("#(升起)", write_faces_list.get(30));
        write_faces.put("#(惊讶)", write_faces_list.get(31));
        write_faces.put("#(喷)", write_faces_list.get(32));
        write_faces.put("#(爱心)", write_faces_list.get(33));
        write_faces.put("#(心碎)", write_faces_list.get(34));
        write_faces.put("#(玫瑰)", write_faces_list.get(35));
        write_faces.put("#(礼物)", write_faces_list.get(36));
        write_faces.put("#(彩虹)", write_faces_list.get(37));
        write_faces.put("#(星星月亮)", write_faces_list.get(38));
        write_faces.put("#(太阳)", write_faces_list.get(39));
        write_faces.put("#(钱币)", write_faces_list.get(40));
        write_faces.put("#(灯泡)", write_faces_list.get(41));
        write_faces.put("#(茶杯)", write_faces_list.get(42));
        write_faces.put("#(蛋糕)", write_faces_list.get(43));
        write_faces.put("#(音乐)", write_faces_list.get(44));
        write_faces.put("#(haha)", write_faces_list.get(45));
        write_faces.put("#(胜利)", write_faces_list.get(46));
        write_faces.put("#(大拇指)", write_faces_list.get(47));
        write_faces.put("#(弱)", write_faces_list.get(48));
        write_faces.put("#(OK)", write_faces_list.get(49));
        write_faces.put("#(哭着跑)", write_faces_list.get(50));
        write_faces.put("#(惆怅~)", write_faces_list.get(51));
        write_faces.put("#(摸头)", write_faces_list.get(52));
        write_faces.put("#(蹭)", write_faces_list.get(53));
        write_faces.put("#(打滚)", write_faces_list.get(54));
        write_faces.put("#(叩拜)", write_faces_list.get(55));
        write_faces.put("#(摸)", write_faces_list.get(56));
        write_faces.put("#(数钱)", write_faces_list.get(57));
        write_faces.put("#(加1)", write_faces_list.get(58));
        write_faces.put("#(压力)", write_faces_list.get(59));
        write_faces.put("#(表逼我)", write_faces_list.get(60));
        write_faces.put("#(人呢)", write_faces_list.get(61));
        write_faces.put("#(摇晃)", write_faces_list.get(62));
        write_faces.put("#(打地鼠)", write_faces_list.get(63));
        write_faces.put("#(这个屌)", write_faces_list.get(64));
        write_faces.put("#(恐慌)", write_faces_list.get(65));
        write_faces.put("#(晕乎乎)", write_faces_list.get(66));
        write_faces.put("#(浮云)", write_faces_list.get(67));
        write_faces.put("#(给力)", write_faces_list.get(68));
        write_faces.put("#(杯具了)", write_faces_list.get(69));
        write_faces.put("#(焦糖舞)", write_faces_list.get(70));
        write_faces.put("#(翻滚)", write_faces_list.get(71));
        write_faces.put("#(拍屁股做鬼脸)", write_faces_list.get(72));
        write_faces.put("#(不)", write_faces_list.get(73));
        write_faces.put("#(河蟹掉啦)", write_faces_list.get(74));
        write_faces.put("#(哦耶)", write_faces_list.get(75));
        write_faces.put("#(我倒)", write_faces_list.get(76));
        write_faces.put("#(投降)", write_faces_list.get(77));
        write_faces.put("#(听音乐)", write_faces_list.get(78));
        write_faces.put("#(被砸)", write_faces_list.get(79));
        write_faces.put("#(吐舌头)", write_faces_list.get(80));
        write_faces.put("#(太好啦)", write_faces_list.get(81));
        write_faces.put("#(财源滚滚)", write_faces_list.get(82));
        write_faces.put("#(人去哪了)", write_faces_list.get(83));
        write_faces.put("#(偷笑)", write_faces_list.get(84));
        write_faces.put("#(卷被)", write_faces_list.get(85));
        write_faces.put("#(看楼上)", write_faces_list.get(86));
        write_faces.put("#(我抽)", write_faces_list.get(87));
        write_faces.put("#(有木有)", write_faces_list.get(88));
        write_faces.put("#(哭)", write_faces_list.get(89));
        write_faces.put("#(微笑)", write_faces_list.get(90));
        write_faces.put("#(帅哥)", write_faces_list.get(91));
        write_faces.put("#(美女)", write_faces_list.get(92));
        write_faces.put("#(老大)", write_faces_list.get(93));
        write_faces.put("#(哈哈哈)", write_faces_list.get(94));
        write_faces.put("#(奸笑)", write_faces_list.get(95));
        write_faces.put("#(傻乐)", write_faces_list.get(96));
        write_faces.put("#(飞吻)", write_faces_list.get(97));
        write_faces.put("#(害羞)", write_faces_list.get(98));
        write_faces.put("#(花痴)", write_faces_list.get(99));
        write_faces.put("#(憧憬)", write_faces_list.get(100));
        write_faces.put("#(你牛)", write_faces_list.get(101));
        write_faces.put("#(鼓掌)", write_faces_list.get(102));
        write_faces.put("#(可爱)", write_faces_list.get(103));
        write_faces.put("#(太委屈)", write_faces_list.get(104));
        write_faces.put("#(大哭)", write_faces_list.get(105));
        write_faces.put("#(泪奔)", write_faces_list.get(106));
        write_faces.put("#(寻死)", write_faces_list.get(107));
        write_faces.put("#(非常惊讶)", write_faces_list.get(108));
        write_faces.put("#(表示疑问)", write_faces_list.get(109));
        file2str = new HashMap<>();
        file2str.put("B_0001", "HI");
        file2str.put("B_0002", "KISS");
        file2str.put("B_0003", "不说");
        file2str.put("B_0004", "不要");
        file2str.put("B_0005", "扯花");
        file2str.put("B_0006", "大心");
        file2str.put("B_0007", "顶");
        file2str.put("B_0008", "大惊");
        file2str.put("B_0009", "飞吻");
        file2str.put("B_0010", "鬼脸");
        file2str.put("B_0011", "害羞");
        file2str.put("B_0012", "口水");
        file2str.put("B_0013", "狂哭");
        file2str.put("B_0014", "来");
        file2str.put("B_0015", "泪眼");
        file2str.put("B_0016", "流泪");
        file2str.put("B_0017", "生气");
        file2str.put("B_0018", "吐舌");
        file2str.put("B_0019", "喜欢");
        file2str.put("B_0020", "旋转");
        file2str.put("B_0021", "再见");
        file2str.put("B_0022", "抓狂");
        file2str.put("B_0023", "汗");
        file2str.put("B_0024", "鄙视");
        file2str.put("B_0025", "拜");
        file2str.put("B_0026", "吐血");
        file2str.put("B_0027", "嘘");
        file2str.put("B_0028", "打人");
        file2str.put("B_0029", "蹦跳");
        file2str.put("B_0030", "变脸");
        file2str.put("B_0031", "扯肉");
        file2str.put("B_0032", "吃To");
        file2str.put("B_0033", "吃花");
        file2str.put("B_0034", "吹泡泡糖");
        file2str.put("B_0035", "大变身");
        file2str.put("B_0036", "飞天舞");
        file2str.put("B_0037", "回眸");
        file2str.put("B_0038", "可怜");
        file2str.put("B_0039", "猛抽");
        file2str.put("B_0040", "泡泡");
        file2str.put("B_0041", "苹果");
        file2str.put("B_0042", "亲");
        file2str.put("B_0043", "耍赖");
        file2str.put("B_0044", "骚舞");
        file2str.put("B_0045", "烧香");
        file2str.put("B_0046", "睡");
        file2str.put("B_0047", "套娃娃");
        file2str.put("B_0048", "捅捅");
        file2str.put("B_0049", "舞倒");
        file2str.put("B_0050", "西红柿");
        file2str.put("B_0051", "爱慕");
        file2str.put("B_0052", "摇");
        file2str.put("B_0053", "摇摆");
        file2str.put("B_0054", "杂耍");
        file2str.put("B_0055", "招财");
        file2str.put("B_0056", "被殴");
        file2str.put("B_0057", "被球闷");
        file2str.put("B_0058", "大惊");
        file2str.put("B_0059", "理想");
        file2str.put("B_0060", "殴打");
        file2str.put("B_0061", "呕吐");
        file2str.put("B_0062", "碎");
        file2str.put("B_0063", "吐痰");
        file2str.put("i_f01", "呵呵");
        file2str.put("i_f02", "哈哈");
        file2str.put("i_f03", "吐舌");
        file2str.put("i_f04", "啊?");
        file2str.put("i_f05", "酷");
        file2str.put("i_f06", "怒");
        file2str.put("i_f07", "开心");
        file2str.put("i_f08", "汗");
        file2str.put("i_f09", "泪");
        file2str.put("i_f10", "黑线");
        file2str.put("i_f11", "鄙视");
        file2str.put("i_f12", "不高兴");
        file2str.put("i_f13", "真棒");
        file2str.put("i_f14", "钱");
        file2str.put("i_f15", "疑问");
        file2str.put("i_f16", "阴险");
        file2str.put("i_f17", "吐");
        file2str.put("i_f18", "咦?");
        file2str.put("i_f19", "委屈");
        file2str.put("i_f20", "花心");
        file2str.put("i_f21", "呼~");
        file2str.put("i_f22", "笑眼");
        file2str.put("i_f23", "冷");
        file2str.put("i_f24", "太开心");
        file2str.put("i_f25", "滑稽");
        file2str.put("i_f26", "勉强");
        file2str.put("i_f27", "狂汗");
        file2str.put("i_f28", "乖");
        file2str.put("i_f29", "睡觉");
        file2str.put("i_f30", "惊哭");
        file2str.put("i_f31", "升起");
        file2str.put("i_f32", "惊讶");
        file2str.put("i_f33", "喷");
        file2str.put("i_f34", "爱心");
        file2str.put("i_f35", "心碎");
        file2str.put("i_f36", "玫瑰");
        file2str.put("i_f37", "礼物");
        file2str.put("i_f38", "彩虹");
        file2str.put("i_f39", "星星月亮");
        file2str.put("i_f40", "太阳");
        file2str.put("i_f41", "钱币");
        file2str.put("i_f42", "灯泡");
        file2str.put("i_f43", "茶杯");
        file2str.put("i_f44", "蛋糕");
        file2str.put("i_f45", "音乐");
        file2str.put("i_f46", "haha");
        file2str.put("i_f47", "胜利");
        file2str.put("i_f48", "大拇指");
        file2str.put("i_f49", "弱");
        file2str.put("i_f50", "OK");
        file2str.put("w_0001", "一楼喂熊");
        file2str.put("w_0002", "俯卧撑");
        file2str.put("w_0003", "打酱油");
        file2str.put("w_0004", "囧");
        file2str.put("w_0005", "大笑");
        file2str.put("w_0006", "瀑布汗~");
        file2str.put("w_0007", "惊讶");
        file2str.put("w_0008", "臭美");
        file2str.put("w_0009", "傻笑");
        file2str.put("w_0010", "抛媚眼");
        file2str.put("w_0011", "发怒");
        file2str.put("w_0012", "我错了");
        file2str.put("w_0013", "money");
        file2str.put("w_0014", "气愤");
        file2str.put("w_0015", "挑逗");
        file2str.put("w_0016", "吻");
        file2str.put("w_0017", "怒");
        file2str.put("w_0018", "胜利");
        file2str.put("w_0019", "委屈");
        file2str.put("w_0020", "受伤");
        file2str.put("w_0021", "说啥呢?");
        file2str.put("w_0022", "闭嘴");
        file2str.put("w_0023", "不");
        file2str.put("w_0024", "逗你玩儿");
        file2str.put("w_0025", "飞吻");
        file2str.put("w_0026", "眩晕");
        file2str.put("w_0027", "魔法");
        file2str.put("w_0028", "我来了");
        file2str.put("w_0029", "睡了");
        file2str.put("w_0030", "我打");
        file2str.put("w_0031", "闭嘴");
        file2str.put("w_0032", "打");
        file2str.put("w_0033", "打晕了");
        file2str.put("w_0034", "刷牙");
        file2str.put("w_0035", "暴揍");
        file2str.put("w_0036", "炸弹");
        file2str.put("w_0037", "倒立");
        file2str.put("w_0038", "刮胡子");
        file2str.put("w_0039", "邪恶的笑");
        file2str.put("w_0040", "不要不要");
        file2str.put("w_0041", "爱恋中");
        file2str.put("w_0042", "放大仔细看");
        file2str.put("w_0043", "偷窥");
        file2str.put("w_0044", "超高兴");
        file2str.put("w_0045", "晕");
        file2str.put("w_0046", "松口气");
        file2str.put("w_0047", "我跑");
        file2str.put("w_0048", "享受");
        file2str.put("w_0049", "休养");
        file2str.put("w_0050", "哭");
        file2str.put("w_0051", "汗");
        file2str.put("w_0052", "啊~");
        file2str.put("w_0053", "热烈欢迎");
        file2str.put("t_0001", "Kiss");
        file2str.put("t_0002", "Love");
        file2str.put("t_0003", "Yeah");
        file2str.put("t_0004", "啊!");
        file2str.put("t_0005", "背扭");
        file2str.put("t_0006", "顶");
        file2str.put("t_0007", "抖胸");
        file2str.put("t_0008", "88");
        file2str.put("t_0009", "汗");
        file2str.put("t_0010", "瞌睡");
        file2str.put("t_0011", "鲁拉");
        file2str.put("t_0012", "拍砖");
        file2str.put("t_0013", "揉脸");
        file2str.put("t_0014", "生日快乐");
        file2str.put("t_0015", "摊手");
        file2str.put("t_0016", "睡觉");
        file2str.put("t_0017", "瘫坐");
        file2str.put("t_0018", "无聊");
        file2str.put("t_0019", "星星闪");
        file2str.put("t_0020", "旋转");
        file2str.put("t_0021", "也不行");
        file2str.put("t_0022", "郁闷");
        file2str.put("t_0023", "正Music");
        file2str.put("t_0024", "抓墙");
        file2str.put("t_0025", "撞墙至死");
        file2str.put("t_0026", "歪头");
        file2str.put("t_0027", "戳眼");
        file2str.put("t_0028", "飘过");
        file2str.put("t_0029", "互相拍砖");
        file2str.put("t_0030", "砍死你");
        file2str.put("t_0031", "扔桌子");
        file2str.put("t_0032", "少林寺");
        file2str.put("t_0033", "什么?");
        file2str.put("t_0034", "转头");
        file2str.put("t_0035", "我爱牛奶");
        file2str.put("t_0036", "我踢");
        file2str.put("t_0037", "摇晃");
        file2str.put("t_0038", "晕厥");
        file2str.put("t_0039", "在笼子里");
        file2str.put("t_0040", "震荡");
        file2str.put("image_emoticon", "呵呵");
        file2str.put("image_emoticon2", "哈哈");
        file2str.put("image_emoticon3", "吐舌");
        file2str.put("image_emoticon4", "啊?");
        file2str.put("image_emoticon5", "酷");
        file2str.put("image_emoticon6", "怒");
        file2str.put("image_emoticon7", "开心");
        file2str.put("image_emoticon8", "汗");
        file2str.put("image_emoticon9", "泪");
        file2str.put("image_emoticon10", "黑线");
        file2str.put("image_emoticon11", "鄙视");
        file2str.put("image_emoticon12", "不高兴");
        file2str.put("image_emoticon13", "真棒");
        file2str.put("image_emoticon14", "钱");
        file2str.put("image_emoticon15", "疑问");
        file2str.put("image_emoticon16", "阴险");
        file2str.put("image_emoticon17", "吐");
        file2str.put("image_emoticon18", "咦?");
        file2str.put("image_emoticon19", "委屈");
        file2str.put("image_emoticon20", "花心");
        file2str.put("image_emoticon21", "呼~");
        file2str.put("image_emoticon22", "笑眼");
        file2str.put("image_emoticon23", "冷");
        file2str.put("image_emoticon24", "太开心");
        file2str.put("image_emoticon25", "滑稽");
        file2str.put("image_emoticon26", "勉强");
        file2str.put("image_emoticon27", "狂汗");
        file2str.put("image_emoticon28", "乖");
        file2str.put("image_emoticon29", "睡觉");
        file2str.put("image_emoticon30", "惊哭");
        file2str.put("image_emoticon31", "升起");
        file2str.put("image_emoticon32", "惊讶");
        file2str.put("image_emoticon33", "喷");
        file2str.put("image_emoticon34", "爱心");
        file2str.put("image_emoticon35", "心碎");
        file2str.put("image_emoticon36", "玫瑰");
        file2str.put("image_emoticon37", "礼物");
        file2str.put("image_emoticon38", "彩虹");
        file2str.put("image_emoticon39", "星星月亮");
        file2str.put("image_emoticon40", "太阳");
        file2str.put("image_emoticon41", "钱币");
        file2str.put("image_emoticon42", "灯泡");
        file2str.put("image_emoticon43", "茶杯");
        file2str.put("image_emoticon44", "蛋糕");
        file2str.put("image_emoticon45", "音乐");
        file2str.put("image_emoticon46", "haha");
        file2str.put("image_emoticon47", "胜利");
        file2str.put("image_emoticon48", "大拇指");
        file2str.put("image_emoticon49", "弱");
        file2str.put("image_emoticon50", "OK");
        file2str.put("ali_001", "赖皮");
        file2str.put("ali_002", "感动");
        file2str.put("ali_003", "十分惊讶");
        file2str.put("ali_004", "怒气");
        file2str.put("ali_005", "哭泣");
        file2str.put("ali_006", "吃惊");
        file2str.put("ali_007", "嘲弄");
        file2str.put("ali_008", "飘过");
        file2str.put("ali_009", "转圈哭");
        file2str.put("ali_010", "神经病");
        file2str.put("ali_011", "揪耳朵");
        file2str.put("ali_012", "惊汗");
        file2str.put("ali_013", "隐身");
        file2str.put("ali_014", "不要");
        file2str.put("ali_015", "遁");
        file2str.put("ali_016", "不公平");
        file2str.put("ali_017", "爬来了");
        file2str.put("ali_018", "蛋花哭");
        file2str.put("ali_019", "温暖");
        file2str.put("ali_020", "点头");
        file2str.put("ali_021", "撒钱");
        file2str.put("ali_022", "献花");
        file2str.put("ali_023", "寒");
        file2str.put("ali_024", "傻笑");
        file2str.put("ali_025", "扭扭");
        file2str.put("ali_026", "疯");
        file2str.put("ali_027", "抓狂");
        file2str.put("ali_028", "抓");
        file2str.put("ali_029", "蜷");
        file2str.put("ali_030", "挠墙");
        file2str.put("ali_031", "狂笑");
        file2str.put("ali_032", "抱枕");
        file2str.put("ali_033", "吼叫");
        file2str.put("ali_034", "嚷");
        file2str.put("ali_035", "唠叨");
        file2str.put("ali_036", "捏脸");
        file2str.put("ali_037", "爆笑");
        file2str.put("ali_038", "郁闷");
        file2str.put("ali_039", "潜水");
        file2str.put("ali_040", "十分开心");
        file2str.put("ali_041", "冷笑话");
        file2str.put("ali_042", "顶");
        file2str.put("ali_043", "潜");
        file2str.put("ali_044", "画圈圈");
        file2str.put("ali_045", "玩电脑");
        file2str.put("ali_046", "狂吐");
        file2str.put("ali_047", "哭着跑");
        file2str.put("ali_048", "阿狸侠");
        file2str.put("ali_049", "冷死了");
        file2str.put("ali_050", "惆怅~");
        file2str.put("ali_051", "摸头");
        file2str.put("ali_052", "蹭");
        file2str.put("ali_053", "打滚");
        file2str.put("ali_054", "叩拜");
        file2str.put("ali_055", "摸");
        file2str.put("ali_056", "数钱");
        file2str.put("ali_057", "拖走");
        file2str.put("ali_058", "热");
        file2str.put("ali_059", "加1");
        file2str.put("ali_060", "压力");
        file2str.put("ali_061", "表逼我");
        file2str.put("ali_062", "人呢");
        file2str.put("ali_063", "摇晃");
        file2str.put("ali_064", "打地鼠");
        file2str.put("ali_065", "这个屌");
        file2str.put("ali_066", "恐慌");
        file2str.put("ali_067", "晕乎乎");
        file2str.put("ali_068", "浮云");
        file2str.put("ali_069", "给力");
        file2str.put("ali_070", "杯具了");
        file2str.put("b01", "微笑");
        file2str.put("b02", "帅哥");
        file2str.put("b03", "美女");
        file2str.put("b04", "老大");
        file2str.put("b05", "哈哈哈");
        file2str.put("b06", "奸笑");
        file2str.put("b07", "傻乐");
        file2str.put("b08", "飞吻");
        file2str.put("b09", "害羞");
        file2str.put("b10", "花痴");
        file2str.put("b11", "憧憬");
        file2str.put("b12", "你牛");
        file2str.put("b13", "鼓掌");
        file2str.put("b14", "可爱");
        file2str.put("b15", "太委屈");
        file2str.put("b16", "大哭");
        file2str.put("b17", "泪奔");
        file2str.put("b18", "寻死");
        file2str.put("b19", "非常惊讶");
        file2str.put("b20", "表示疑问");
        file2str.put("b21", "鄙视你");
        file2str.put("b22", "大骂");
        file2str.put("b23", "狂怒");
        file2str.put("b24", "囧");
        file2str.put("b25", "晕");
        file2str.put("b26", "呕吐");
        file2str.put("b27", "财迷");
        file2str.put("b28", "睡了");
        file2str.put("b29", "思考");
        file2str.put("b30", "真汗");
        file2str.put("b31", "无语");
        file2str.put("b32", "拜");
        file2str.put("b33", "鞠躬");
        file2str.put("b34", "累了");
        file2str.put("b35", "病了");
        file2str.put("b36", "墙角");
        file2str.put("b37", "超人");
        file2str.put("b38", "戳");
        file2str.put("b39", "跳舞");
        file2str.put("b40", "鬼脸");
        file2str.put("b41", "无聊");
        file2str.put("b42", "撞墙");
        file2str.put("b43", "顶起");
        file2str.put("b44", "HI");
        file2str.put("b45", "饭");
        file2str.put("b46", "生日蛋糕");
        file2str.put("b47", "精美礼物");
        file2str.put("b48", "心");
        file2str.put("b49", "我心碎");
        file2str.put("b50", "玫瑰花");
        file2str.put("b51", "炸弹");
        file2str.put("b52", "集体舞");
        file2str.put("b53", "打人");
        file2str.put("b54", "拍拍");
        file2str.put("b55", "亲亲");
        file2str.put("b56", "握手");
        file2str.put("b57", "安慰");
        file2str.put("b58", "石头");
        file2str.put("b59", "剪子");
        file2str.put("b60", "布");
        file2str.put("b61", "恭喜啦");
        file2str.put("b62", "啵啵");
        file2str.put("yz_001", "焦糖舞");
        file2str.put("yz_002", "翻滚");
        file2str.put("yz_003", "拍屁股做鬼脸");
        file2str.put("yz_004", "不");
        file2str.put("yz_005", "河蟹掉啦");
        file2str.put("yz_006", "哦耶");
        file2str.put("yz_007", "我倒");
        file2str.put("yz_008", "投降");
        file2str.put("yz_009", "听音乐");
        file2str.put("yz_010", "被砸");
        file2str.put("yz_011", "吐舌头");
        file2str.put("yz_012", "太好啦");
        file2str.put("yz_013", "财源滚滚");
        file2str.put("yz_014", "人去哪了");
        file2str.put("yz_015", "挥手帕");
        file2str.put("yz_016", "偷笑");
        file2str.put("yz_017", "卷被");
        file2str.put("yz_018", "看楼上");
        file2str.put("yz_019", "我抽");
        file2str.put("yz_020", "有木有");
        file2str.put("yz_021", "哭");
        file2str.put("yz_022", "欢呼");
        file2str.put("yz_023", "傻兮兮");
        file2str.put("yz_024", "扇扇子");
        file2str.put("yz_025", "拍手");
        file2str.put("yz_026", "紧张");
        file2str.put("yz_027", "洗澡");
        file2str.put("yz_028", "耶");
        file2str.put("yz_029", "吃西瓜");
        file2str.put("yz_030", "纳尼");
        file2str.put("yz_031", "没有钱");
        file2str.put("yz_032", "拿玩偶");
        file2str.put("yz_033", "来看看");
        file2str.put("yz_034", "哇哇叫");
        file2str.put("yz_035", "招财猫");
        file2str.put("yz_036", "放屁");
        file2str.put("yz_037", "隆重介绍");
        file2str.put("yz_038", "求你了");
        file2str.put("yz_039", "撞玻璃");
        file2str.put("yz_040", "眺望");
        file2str.put("yz_041", "撒花");
        file2str.put("yz_042", "玩铃铛");
        file2str.put("yz_043", "思考者");
        file2str.put("yz_044", "抽风");
        file2str.put("yz_045", "吃苹果");
        file2str.put("yz_046", "光棍");
    }

    public static String getFaceStrByFile(String file) {
        return file2str.get(file);
    }

    public static HashMap<String, Integer> getWriteFace() {
        return write_faces;
    }

    public static ArrayList<Integer> getWriteFaceList() {
        return write_faces_list;
    }

    public static Bitmap getBitmap(Context context, String key) {
        Integer bmId = faces.get(key);
        if (bmId != null) {
            return BitmapHelper.getResBitmap(context, bmId.intValue());
        }
        return null;
    }

    public static SpannableString parserFace(Context context, String str) {
        Bitmap bm;
        if (str == null) {
            return null;
        }
        SpannableString spanStr = new SpannableString(str);
        Pattern pattern = Pattern.compile("#[\\(][\\w?]+[\\)]");
        Matcher matcher = pattern.matcher(str);
        while (matcher.find()) {
            String face_name = matcher.group();
            Integer face_id = write_faces.get(face_name);
            if (face_id != null && (bm = BitmapHelper.getResBitmap(context, face_id.intValue())) != null) {
                int len = face_name.length();
                int start = matcher.start();
                BitmapDrawable dr = new BitmapDrawable(bm);
                dr.setBounds(0, 0, bm.getWidth(), bm.getHeight());
                ImageSpan span = new ImageSpan(dr, 0);
                spanStr.setSpan(span, start, start + len, 33);
            }
        }
        return spanStr;
    }
}
