package com.baidu.tieba.util;
/* loaded from: classes.dex */
public class NetWorkErr {
    public static final int CONTENT_BUHEXIE = 12;
    public static final int FILE_UPLOAD_NET_ERROR = 103;
    public static final int FILE_UPLOAD_SIZE_ERROR = 15;
    public static final int FORUM_NOT_EXIST = 3;
    public static final int HAVE_DING = 14;
    public static final int HAVE_SIGNED = 160002;
    public static final int INSERT_TO_MANY_SMILE = 13;
    public static final int INTERNAL_ERROR = 500;
    public static final int INVALID_SIGN = 102;
    public static final int METHOD_MUST_POST = 100;
    public static final int NEED_VCODE = 5;
    public static final int NETWORK_ERR = -1;
    public static final int NETWORK_IGNORE = -2;
    public static final int NETWORK_OK = 0;
    public static final int OP_TOO_FAST = 7;
    public static final int PARAM_NOT_ENOUGH = 101;
    public static final int PASSWD_IS_INVALID = 19;
    public static final int PASSWD_IS_TOO_SIMPLE = 20;
    public static final int POST_NEED_AUDIT = 8;
    public static final int POST_NOT_EXIST = 29;
    public static final int POST_REPEAT = 11;
    public static final int REGIST_NAME_ERROR = 27;
    public static final int REGIST_PHONE_ERROR = 28;
    public static final int REGIST_PSW_ERROR = 29;
    public static final int REGIST_SMSCODE_ERROR = 26;
    public static final int THREAD_NOT_EXIST = 4;
    public static final int THREAD_NOT_EXIST_1 = 28;
    public static final int UID_PRISON = 9;
    public static final int UIP_PRISON = 10;
    public static final int USERNAME_BU_HEXIE = 18;
    public static final int USERNAME_CANT_USE = 36;
    public static final int USERNAME_HAS_REGED = 16;
    public static final int USERNAME_HAVE_INPUT = 35;
    public static final int USERNAME_IS_INVALID = 17;
    public static final int USERNAME_OR_PASSWD_ERROR = 2;
    public static final int USER_CANNOT_LOGIN = 21;
    public static final int USER_HAS_LIKE_FORUM = 22;
    public static final int USER_NOT_LOGIN = 1;
    public static final int VCODE_INPUT_ERROR = 6;
}
