package com.kwad.sdk.core.config;

import com.kwad.sdk.core.config.item.InstallActivateReminderConfigItem;
import com.kwad.sdk.core.config.item.TipsConfigItem;
import com.kwad.sdk.core.config.item.e;
import com.kwad.sdk.core.config.item.f;
import com.kwad.sdk.core.config.item.g;
import com.kwad.sdk.core.config.item.h;
import com.kwad.sdk.core.config.item.i;
import com.kwad.sdk.core.config.item.j;
import com.kwad.sdk.core.config.item.k;
import com.kwad.sdk.core.config.item.l;
import com.kwad.sdk.core.config.item.m;
import com.kwad.sdk.core.config.item.n;
import com.kwad.sdk.core.config.item.o;
import com.kwad.sdk.core.config.item.p;
import java.util.ArrayList;
/* loaded from: classes10.dex */
public final class c {
    public static e TO;
    public static e TP;
    public static f TQ;
    public static f TR;
    public static f TS;
    public static f TT;
    public static f TU;
    public static f TV;
    public static f TW;
    public static o TX;
    public static o TY;
    public static o TZ;
    public static o UA;
    public static o UB;
    public static o UC;
    public static j UD;
    public static com.kwad.sdk.core.config.item.d UE;
    public static g UF;
    public static com.kwad.sdk.core.config.item.d UG;
    public static com.kwad.sdk.core.config.item.d UH;
    public static com.kwad.sdk.core.config.item.d UI;
    public static j UJ;
    public static j UK;
    public static com.kwad.sdk.core.config.item.d UL;
    public static j UM;
    public static j UN;
    public static o UO;
    public static o UP;
    public static j UQ;
    public static o UR;
    public static j US;
    public static j UT;
    public static j UU;
    public static j UV;
    public static com.kwad.sdk.core.config.item.d UW;
    public static f UX;
    public static f UY;
    public static com.kwad.sdk.core.config.item.d UZ;
    public static o Ua;
    public static com.kwad.sdk.core.config.item.d Ub;
    public static k Uc;
    public static p Ud;
    public static p Ue;
    public static TipsConfigItem Uf;
    public static com.kwad.sdk.core.config.item.c Ug;
    public static InstallActivateReminderConfigItem Uh;
    public static m Ui;
    public static n Uj;
    public static j Uk;
    public static j Ul;
    public static j Um;
    public static j Un;
    public static j Uo;
    public static j Up;
    public static j Uq;
    public static i Ur;
    public static j Us;
    public static j Ut;
    public static j Uu;
    public static j Uv;
    public static j Uw;
    public static j Ux;
    public static j Uy;
    public static j Uz;
    public static com.kwad.sdk.core.config.item.d Va;
    public static j Vb;
    public static com.kwad.sdk.core.config.item.d Vc;
    public static com.kwad.sdk.core.config.item.d Vd;
    public static com.kwad.sdk.core.config.item.d Ve;
    public static l Vf;
    public static k Vg;
    public static l Vh;
    public static j Vi;
    public static j Vj;
    public static f Vk;
    public static f Vl;
    public static com.kwad.sdk.core.config.item.d Vm;
    public static com.kwad.sdk.core.config.item.d Vn;
    public static j Vo;
    public static j Vp;
    public static f Vq;
    public static h Vr;
    public static l Vs;
    public static com.kwad.sdk.core.config.item.d Vt;
    public static j Vu;
    public static f Vv;
    public static j Vw;
    public static j Vx;
    public static j Tq = new j("batchReportCatchLimit", 20);
    public static j Tr = new j("exceptionCollectorSwitch", 1);
    public static j Ts = new j("mediaPlayerLogReport", 0);
    public static j Tt = new j("didCopySwitch", 1);
    public static j Tu = new j("enableHodor", 0);
    public static j Tv = new j("speedLimitSwitch", 1);
    public static j Tw = new j("speedLimitThreshold", 200);
    public static j Tx = new j("ksNativeAdCustomSwitch", 0);
    public static j Ty = new j("forceActivateAfterInstalled", 0);
    public static j Tz = new j("formAdExitInterceptSwitch", 0);
    public static j TA = new j("adLeaveConfirmSwitch", 0);
    public static j TB = new j("viewLandingPageTaskDuration", 15);
    public static j TC = new j("rewardAdVideoPreCacheSize", 800);
    public static com.kwad.sdk.core.config.item.d TD = new com.kwad.sdk.core.config.item.d("dataFlowAutoStartSwitch", false);
    public static l TE = new l("deviceInfoDisableConfig", 0L);
    public static com.kwad.sdk.core.config.item.d TF = new com.kwad.sdk.core.config.item.d("playerEnable", false);
    public static com.kwad.sdk.core.config.item.d TG = new com.kwad.sdk.core.config.item.d("dynamicEnable", false);
    public static f TH = new f("commercialLogReportRate", 1.0f);
    public static f TI = new f("apmToRELogReportRate", 0.0f);
    public static f TJ = new f("sdkInitLogReportRate", 1.0f);
    public static j TL = new j("commercialLoggerSwitch", 0);
    public static f TM = new f("sdkSplashReportRate", 1.0f);
    public static e TN = new e("sdkInterstitialLoadReportRate", Double.valueOf(0.01d));

    static {
        Double valueOf = Double.valueOf(1.0d);
        TO = new e("sdkInterstitialDownloadErrorReportRate", valueOf);
        TP = new e("sdkInterstitialPlayErrorReportRate", valueOf);
        TQ = new f("sdkRewardReportRate", 1.0f);
        TR = new f("sdkWebHybridReportRate", 1.0f);
        TS = new f("sdkDynamicReportRate", 1.0f);
        TT = new f("sdkAdWebviewReportRate", 1.0f);
        TU = new f("sdkFullScreenReportRate", 1.0f);
        TV = new f("sdkRewardErrorReportRate", 1.0f);
        TW = new f("sdkFullScreenErrorReportRate", 1.0f);
        TX = new o("webpSoUrlV7a", "");
        TY = new o("webpSoUrlV8a", "");
        TZ = new o("tkSoUrlV7a", "");
        Ua = new o("tkSoUrlV8a", "");
        Ub = new com.kwad.sdk.core.config.item.d("disableTkLite", false);
        Uc = new k("playerConfig", null);
        Ud = new p("pkgNameList", new ArrayList(0));
        Ue = new p("hostList", new ArrayList(0));
        Uf = new TipsConfigItem();
        Ug = new com.kwad.sdk.core.config.item.c();
        Uh = new InstallActivateReminderConfigItem();
        Ui = new m("realtimeReportActions", "");
        Uj = new n();
        Uk = new j("appInstallNoticeSecond", 0);
        Ul = new j("installFloatingLayerPostion", 0);
        Um = new j("remindInstallStyle", 0);
        Un = new j("remindInstallTime", 60);
        Uo = new j("watermarkKwaiIdSwitch", 0);
        Up = new j("insertScreenV2Switch", 0);
        Uq = new j("insertScreenAutoPlaySwitch", 0);
        Ur = new i("insertScreenV2ShowConfig");
        Us = new j("environmentDetectEnable", 0);
        Ut = new j("simCardInfoEnable", 0);
        Uu = new j("baseStationEnable", 0);
        Uv = new j("sensorEventEnable2", 0);
        Uw = new j("lpAutoDownloadApkSwitch", 1);
        Ux = new j("autoDownloadUrlSwitch", 0);
        Uy = new j("insertScreenAdType", 0);
        Uz = new j("mediaControlPlaySwitch", 1);
        UA = new o("appStatusSoUrlV7a", "");
        UB = new o("appStatusSoUrlV8a", "");
        UC = new o("appStatusSoVersion", "");
        UD = new j("deeplinkCheckSwitch", -3);
        UE = new com.kwad.sdk.core.config.item.d("deeplinkWindowSwitch", false);
        UF = new g();
        UG = new com.kwad.sdk.core.config.item.d("TKSwitch", true);
        UH = new com.kwad.sdk.core.config.item.d("reduceDeviceSigSwitch", true);
        UI = new com.kwad.sdk.core.config.item.d("personalRecommend", false);
        UJ = new j("forceActivate", 0);
        UK = new j("remindOpen", -1);
        UL = new com.kwad.sdk.core.config.item.d("viewVisibleCheckLegacy", false);
        UM = new j("enableAnrReportReal", 0);
        UN = new j("enableNativeCrashReport", 0);
        UO = new o("exceptionSoUrlV7a", "");
        UP = new o("exceptionSoUrlV8a", "");
        UQ = new j("kwaiAppVersionSwitch", 1);
        UR = new o("userAgent", com.kwad.sdk.core.network.o.getDefaultUserAgent());
        US = new j("biddingLogSwitch", 0);
        UT = new j("forceActiveThreshold", 5);
        UU = new j("forceActiveInterval", 3);
        UV = new j("hybridEnable", 1);
        UW = new com.kwad.sdk.core.config.item.d("wifiResumeDownload", false);
        UX = new f("adExposureAreaPercent", 0.3f);
        UY = new f("adExposureTime", -1.0f);
        UZ = new com.kwad.sdk.core.config.item.d("appInAdExposureBlacklist", false);
        Va = new com.kwad.sdk.core.config.item.d("soDownloadBreakpointContinuation", true);
        Vb = new j("soLoadMaxRetryCount", 1);
        Vc = new com.kwad.sdk.core.config.item.d("feedAdForceGetAudioFocus", false);
        Vd = new com.kwad.sdk.core.config.item.d("logCommandSwitch", false);
        Ve = new com.kwad.sdk.core.config.item.d("logRecordAllSwitch", false);
        Vf = new l("obiwanLogFilesDiskQuota", 52428800L);
        Vg = new k("logCommandResult", "", false);
        Vh = new l("validClickConvertTime", 1000L);
        Vi = new j("playableAutoPlayEnable", 1);
        Vj = new j("netMonitorSwitch", 0);
        Vk = new f("netMonitorReportSuccessRate", 0.01f);
        Vl = new f("netMonitorReportErrorRate", 0.1f);
        Vm = new com.kwad.sdk.core.config.item.d("ipDirectEnable", false);
        Vn = new com.kwad.sdk.core.config.item.d("ipPreferEnable", false);
        Vo = new j("weaponSwitch", 1);
        Vp = new j("kvMode", 0);
        Vq = new f("kvFailed", 0.01f);
        Vr = new h();
        Vs = new l("currentServerTimeMs");
        Vt = new com.kwad.sdk.core.config.item.d("clientProofreadTimeSwitch", false);
        Vu = new j("clientProofreadTimeErrorRangeHours", 100);
        Vv = new f("adTraceReportRate", 1.0f);
        Vw = new j("adTraceRepeatEnable", 0);
        Vx = new j("adCacheCode", 0);
    }

    public static void init() {
    }
}
