package com.kwad.sdk.core.c.a;

import com.baidu.android.imsdk.internal.Constants;
import com.baidu.mobads.container.adrequest.IAdRequestParam;
import com.baidu.titan.sdk.runtime.FieldHolder;
import com.baidu.titan.sdk.runtime.InitContext;
import com.baidu.titan.sdk.runtime.InterceptResult;
import com.baidu.titan.sdk.runtime.Interceptable;
import com.baidu.titan.sdk.runtime.TitanRuntime;
import com.baidu.walletfacesdk.LightInvokerImpl;
import com.kwad.sdk.core.report.ReportAction;
import com.kwad.sdk.core.scene.URLPackage;
import com.meizu.cloud.pushsdk.constants.PushConstants;
import org.json.JSONObject;
/* loaded from: classes10.dex */
public class bz implements com.kwad.sdk.core.d<ReportAction> {
    public static /* synthetic */ Interceptable $ic;
    public transient /* synthetic */ FieldHolder $fh;

    public bz() {
        Interceptable interceptable = $ic;
        if (interceptable != null) {
            InitContext newInitContext = TitanRuntime.newInitContext();
            interceptable.invokeUnInit(65536, newInitContext);
            int i2 = newInitContext.flag;
            if ((i2 & 1) != 0) {
                int i3 = i2 & 2;
                newInitContext.thisArg = this;
                interceptable.invokeInitBody(65536, newInitContext);
            }
        }
    }

    /* JADX DEBUG: Method merged with bridge method */
    @Override // com.kwad.sdk.core.d
    public void a(ReportAction reportAction, JSONObject jSONObject) {
        Interceptable interceptable = $ic;
        if (!(interceptable == null || interceptable.invokeLL(1048576, this, reportAction, jSONObject) == null) || jSONObject == null) {
            return;
        }
        reportAction.f72469d = jSONObject.optLong("timestamp");
        reportAction.f72470e = jSONObject.optString("sessionId");
        reportAction.f72471f = jSONObject.optLong(IAdRequestParam.SEQ);
        reportAction.f72473h = jSONObject.optLong("listId");
        reportAction.f72474i = jSONObject.optLong(LightInvokerImpl.VOICE_ACTIONTYPE);
        reportAction.f72475j = jSONObject.optLong("llsid");
        reportAction.k = jSONObject.optJSONObject("extra");
        reportAction.l = jSONObject.optJSONObject("impAdExtra");
        reportAction.m = jSONObject.optLong("posId");
        reportAction.n = jSONObject.optInt("contentType");
        reportAction.o = jSONObject.optInt("realShowType");
        reportAction.p = jSONObject.optLong("photoId");
        reportAction.q = jSONObject.optLong("position");
        reportAction.r = jSONObject.optLong("serverPosition");
        reportAction.s = jSONObject.optLong("photoDuration");
        reportAction.t = jSONObject.optLong("effectivePlayDuration");
        reportAction.u = jSONObject.optLong("playDuration");
        reportAction.v = jSONObject.optLong("startDuration");
        reportAction.w = jSONObject.optLong("stayDuration");
        reportAction.x = jSONObject.optLong("stayLength");
        reportAction.y = jSONObject.optLong("blockDuration");
        reportAction.z = jSONObject.optLong("intervalDuration");
        reportAction.A = jSONObject.optLong("allIntervalDuration");
        reportAction.B = jSONObject.optLong("flowSdk");
        reportAction.C = jSONObject.optLong("blockTimes");
        reportAction.D = jSONObject.optString("tabName");
        reportAction.E = jSONObject.optInt("nextPageType");
        reportAction.F = jSONObject.optInt("contentSourceType");
        reportAction.G = jSONObject.optInt("enterType");
        reportAction.H = jSONObject.optInt("leaveType");
        reportAction.J = jSONObject.optInt("adAggPageSource");
        reportAction.K = jSONObject.optString("entryPageSource");
        URLPackage uRLPackage = new URLPackage();
        reportAction.L = uRLPackage;
        uRLPackage.parseJson(jSONObject.optJSONObject("urlPackage"));
        URLPackage uRLPackage2 = new URLPackage();
        reportAction.M = uRLPackage2;
        uRLPackage2.parseJson(jSONObject.optJSONObject("referURLPackage"));
        reportAction.N = jSONObject.optLong(URLPackage.KEY_AUTHOR_ID);
        reportAction.O = jSONObject.optInt("likeStatus");
        reportAction.P = jSONObject.optString("photoSize");
        reportAction.Q = jSONObject.optInt("playEnd");
        reportAction.R = jSONObject.optInt("dragProgressType");
        reportAction.S = jSONObject.optLong("dragProgressPhotoDuration");
        reportAction.T = jSONObject.optLong("dragProgressVideoTime");
        reportAction.U = jSONObject.optInt("likeType");
        reportAction.W = jSONObject.optInt("shareResult");
        reportAction.X = jSONObject.optJSONArray("appInstalled");
        reportAction.Y = jSONObject.optJSONArray("appUninstalled");
        reportAction.Z = jSONObject.optString("coverUrl");
        reportAction.aa = jSONObject.optString("videoCurrentUrl");
        reportAction.ab = jSONObject.optString("entryId");
        reportAction.ac = jSONObject.optString("pushUrl");
        reportAction.ad = jSONObject.optLong("commentId");
        reportAction.ae = jSONObject.optLong("seenCount");
        reportAction.af = jSONObject.optInt(PushConstants.CLICK_TYPE);
        reportAction.ag = jSONObject.optInt("buttonPictureClick");
        reportAction.ah = jSONObject.optString("recoExt");
        ReportAction.a aVar = new ReportAction.a();
        reportAction.ai = aVar;
        aVar.parseJson(jSONObject.optJSONObject("clientExt"));
        reportAction.aj = jSONObject.optInt("playerType");
        reportAction.ak = jSONObject.optInt("uiType");
        reportAction.al = jSONObject.optString("tubeName");
        reportAction.am = jSONObject.optLong(URLPackage.KEY_TUBE_ID);
        reportAction.an = jSONObject.optString("episodeName");
        reportAction.ao = jSONObject.optString("trendName");
        reportAction.ap = jSONObject.optLong(URLPackage.KEY_TREND_ID);
        reportAction.ar = jSONObject.optLong("relatedContentSourceType");
        reportAction.at = jSONObject.optInt("closeType");
        reportAction.au = jSONObject.optInt("isLeftSlipStatus");
        reportAction.av = jSONObject.optInt("preloadType");
        reportAction.aw = jSONObject.optJSONArray("preloadPhotoList");
        reportAction.ax = jSONObject.optInt("refreshType");
        reportAction.ay = jSONObject.optInt("photoResponseType");
        reportAction.az = jSONObject.optString("failUrl");
        reportAction.aA = jSONObject.optString("errorMsg");
        reportAction.aB = jSONObject.optInt("errorCode");
        reportAction.aC = jSONObject.optLong("creativeId");
        ReportAction.LiveLogInfo liveLogInfo = new ReportAction.LiveLogInfo();
        reportAction.aD = liveLogInfo;
        liveLogInfo.parseJson(jSONObject.optJSONObject("liveLogInfo"));
        reportAction.aE = jSONObject.optString("moduleName");
        reportAction.aH = jSONObject.optString("cacheFailedReason");
        reportAction.aI = jSONObject.optString("componentPosition");
        reportAction.aJ = jSONObject.optJSONObject("appExt");
        reportAction.aK = jSONObject.optJSONArray("appRunningInfoList");
        reportAction.aL = jSONObject.optLong(com.kwad.sdk.api.loader.ReportAction.KEY_DOWNLOAD_DURATION);
        reportAction.aM = jSONObject.optInt("pageType");
        reportAction.aN = jSONObject.optInt("guideTimes");
        reportAction.aO = jSONObject.optInt("speedLimitStatus");
        reportAction.aP = jSONObject.optInt("speedLimitThreshold");
        reportAction.aQ = jSONObject.optInt("currentRealDownloadSpeed");
        reportAction.aS = jSONObject.optJSONArray("sdkPlatform");
        reportAction.aT = jSONObject.optBoolean("isKsUnion");
        reportAction.aU = jSONObject.optString("trackMethodName");
        reportAction.aV = jSONObject.optInt("viewModeType");
        reportAction.aX = jSONObject.optInt("playAgainControlledType");
        reportAction.aY = jSONObject.optString("mediaShareStr");
        reportAction.aZ = jSONObject.optLong("clickTime");
        reportAction.ba = jSONObject.optLong("frameRenderTime");
        reportAction.bb = jSONObject.optInt("playerEnterAction");
        reportAction.bc = jSONObject.optString("requestUrl");
        reportAction.bd = jSONObject.optLong("requestTotalTime");
        reportAction.be = jSONObject.optLong("requestResponseTime");
        reportAction.bf = jSONObject.optLong("requestParseDataTime");
        reportAction.bg = jSONObject.optLong("requestCallbackTime");
        reportAction.bh = jSONObject.optString("requestFailReason");
        reportAction.bi = jSONObject.optString("pageName");
        reportAction.bj = jSONObject.optLong("pageCreateTime");
        reportAction.bk = jSONObject.optLong("pageResumeTime");
        reportAction.bl = jSONObject.optJSONArray("trackUrlList");
        reportAction.bm = jSONObject.optLong("pageLaunchTime");
        reportAction.bp = jSONObject.optJSONArray("appAuthorityInfoList");
        reportAction.bq = jSONObject.optInt("entryRealRefresh");
        reportAction.br = jSONObject.optString("tkVersion");
        reportAction.bs = jSONObject.optString("jsVersion");
        reportAction.bt = jSONObject.optString("jsFileName");
        reportAction.bu = jSONObject.optString("jsErrorMsg");
        reportAction.bv = jSONObject.optString("jsConfig");
        reportAction.bw = jSONObject.optInt("couponStatus");
        reportAction.bx = jSONObject.optDouble("readPct");
        reportAction.by = jSONObject.optString("lostReason");
        reportAction.bz = jSONObject.optInt("photoType");
    }

    /* JADX DEBUG: Method merged with bridge method */
    @Override // com.kwad.sdk.core.d
    public JSONObject b(ReportAction reportAction, JSONObject jSONObject) {
        InterceptResult invokeLL;
        Interceptable interceptable = $ic;
        if (interceptable == null || (invokeLL = interceptable.invokeLL(Constants.METHOD_SEND_USER_MSG, this, reportAction, jSONObject)) == null) {
            if (jSONObject == null) {
                jSONObject = new JSONObject();
            }
            com.kwad.sdk.utils.q.a(jSONObject, "timestamp", reportAction.f72469d);
            com.kwad.sdk.utils.q.a(jSONObject, "sessionId", reportAction.f72470e);
            com.kwad.sdk.utils.q.a(jSONObject, IAdRequestParam.SEQ, reportAction.f72471f);
            com.kwad.sdk.utils.q.a(jSONObject, "listId", reportAction.f72473h);
            com.kwad.sdk.utils.q.a(jSONObject, LightInvokerImpl.VOICE_ACTIONTYPE, reportAction.f72474i);
            com.kwad.sdk.utils.q.a(jSONObject, "llsid", reportAction.f72475j);
            com.kwad.sdk.utils.q.a(jSONObject, "extra", reportAction.k);
            com.kwad.sdk.utils.q.a(jSONObject, "impAdExtra", reportAction.l);
            com.kwad.sdk.utils.q.a(jSONObject, "posId", reportAction.m);
            com.kwad.sdk.utils.q.a(jSONObject, "contentType", reportAction.n);
            com.kwad.sdk.utils.q.a(jSONObject, "realShowType", reportAction.o);
            com.kwad.sdk.utils.q.a(jSONObject, "photoId", reportAction.p);
            com.kwad.sdk.utils.q.a(jSONObject, "position", reportAction.q);
            com.kwad.sdk.utils.q.a(jSONObject, "serverPosition", reportAction.r);
            com.kwad.sdk.utils.q.a(jSONObject, "photoDuration", reportAction.s);
            com.kwad.sdk.utils.q.a(jSONObject, "effectivePlayDuration", reportAction.t);
            com.kwad.sdk.utils.q.a(jSONObject, "playDuration", reportAction.u);
            com.kwad.sdk.utils.q.a(jSONObject, "startDuration", reportAction.v);
            com.kwad.sdk.utils.q.a(jSONObject, "stayDuration", reportAction.w);
            com.kwad.sdk.utils.q.a(jSONObject, "stayLength", reportAction.x);
            com.kwad.sdk.utils.q.a(jSONObject, "blockDuration", reportAction.y);
            com.kwad.sdk.utils.q.a(jSONObject, "intervalDuration", reportAction.z);
            com.kwad.sdk.utils.q.a(jSONObject, "allIntervalDuration", reportAction.A);
            com.kwad.sdk.utils.q.a(jSONObject, "flowSdk", reportAction.B);
            com.kwad.sdk.utils.q.a(jSONObject, "blockTimes", reportAction.C);
            com.kwad.sdk.utils.q.a(jSONObject, "tabName", reportAction.D);
            com.kwad.sdk.utils.q.a(jSONObject, "nextPageType", reportAction.E);
            com.kwad.sdk.utils.q.a(jSONObject, "contentSourceType", reportAction.F);
            com.kwad.sdk.utils.q.a(jSONObject, "enterType", reportAction.G);
            com.kwad.sdk.utils.q.a(jSONObject, "leaveType", reportAction.H);
            com.kwad.sdk.utils.q.a(jSONObject, "adAggPageSource", reportAction.J);
            com.kwad.sdk.utils.q.a(jSONObject, "entryPageSource", reportAction.K);
            com.kwad.sdk.utils.q.a(jSONObject, "urlPackage", reportAction.L);
            com.kwad.sdk.utils.q.a(jSONObject, "referURLPackage", reportAction.M);
            com.kwad.sdk.utils.q.a(jSONObject, URLPackage.KEY_AUTHOR_ID, reportAction.N);
            com.kwad.sdk.utils.q.a(jSONObject, "likeStatus", reportAction.O);
            com.kwad.sdk.utils.q.a(jSONObject, "photoSize", reportAction.P);
            com.kwad.sdk.utils.q.a(jSONObject, "playEnd", reportAction.Q);
            com.kwad.sdk.utils.q.a(jSONObject, "dragProgressType", reportAction.R);
            com.kwad.sdk.utils.q.a(jSONObject, "dragProgressPhotoDuration", reportAction.S);
            com.kwad.sdk.utils.q.a(jSONObject, "dragProgressVideoTime", reportAction.T);
            com.kwad.sdk.utils.q.a(jSONObject, "likeType", reportAction.U);
            com.kwad.sdk.utils.q.a(jSONObject, "shareResult", reportAction.W);
            com.kwad.sdk.utils.q.a(jSONObject, "appInstalled", reportAction.X);
            com.kwad.sdk.utils.q.a(jSONObject, "appUninstalled", reportAction.Y);
            com.kwad.sdk.utils.q.a(jSONObject, "coverUrl", reportAction.Z);
            com.kwad.sdk.utils.q.a(jSONObject, "videoCurrentUrl", reportAction.aa);
            com.kwad.sdk.utils.q.a(jSONObject, "entryId", reportAction.ab);
            com.kwad.sdk.utils.q.a(jSONObject, "pushUrl", reportAction.ac);
            com.kwad.sdk.utils.q.a(jSONObject, "commentId", reportAction.ad);
            com.kwad.sdk.utils.q.a(jSONObject, "seenCount", reportAction.ae);
            com.kwad.sdk.utils.q.a(jSONObject, PushConstants.CLICK_TYPE, reportAction.af);
            com.kwad.sdk.utils.q.a(jSONObject, "buttonPictureClick", reportAction.ag);
            com.kwad.sdk.utils.q.a(jSONObject, "recoExt", reportAction.ah);
            com.kwad.sdk.utils.q.a(jSONObject, "clientExt", reportAction.ai);
            com.kwad.sdk.utils.q.a(jSONObject, "playerType", reportAction.aj);
            com.kwad.sdk.utils.q.a(jSONObject, "uiType", reportAction.ak);
            com.kwad.sdk.utils.q.a(jSONObject, "tubeName", reportAction.al);
            com.kwad.sdk.utils.q.a(jSONObject, URLPackage.KEY_TUBE_ID, reportAction.am);
            com.kwad.sdk.utils.q.a(jSONObject, "episodeName", reportAction.an);
            com.kwad.sdk.utils.q.a(jSONObject, "trendName", reportAction.ao);
            com.kwad.sdk.utils.q.a(jSONObject, URLPackage.KEY_TREND_ID, reportAction.ap);
            com.kwad.sdk.utils.q.a(jSONObject, "relatedContentSourceType", reportAction.ar);
            com.kwad.sdk.utils.q.a(jSONObject, "closeType", reportAction.at);
            com.kwad.sdk.utils.q.a(jSONObject, "isLeftSlipStatus", reportAction.au);
            com.kwad.sdk.utils.q.a(jSONObject, "preloadType", reportAction.av);
            com.kwad.sdk.utils.q.a(jSONObject, "preloadPhotoList", reportAction.aw);
            com.kwad.sdk.utils.q.a(jSONObject, "refreshType", reportAction.ax);
            com.kwad.sdk.utils.q.a(jSONObject, "photoResponseType", reportAction.ay);
            com.kwad.sdk.utils.q.a(jSONObject, "failUrl", reportAction.az);
            com.kwad.sdk.utils.q.a(jSONObject, "errorMsg", reportAction.aA);
            com.kwad.sdk.utils.q.a(jSONObject, "errorCode", reportAction.aB);
            com.kwad.sdk.utils.q.a(jSONObject, "creativeId", reportAction.aC);
            com.kwad.sdk.utils.q.a(jSONObject, "liveLogInfo", reportAction.aD);
            com.kwad.sdk.utils.q.a(jSONObject, "moduleName", reportAction.aE);
            com.kwad.sdk.utils.q.a(jSONObject, "cacheFailedReason", reportAction.aH);
            com.kwad.sdk.utils.q.a(jSONObject, "componentPosition", reportAction.aI);
            com.kwad.sdk.utils.q.a(jSONObject, "appExt", reportAction.aJ);
            com.kwad.sdk.utils.q.a(jSONObject, "appRunningInfoList", reportAction.aK);
            com.kwad.sdk.utils.q.a(jSONObject, com.kwad.sdk.api.loader.ReportAction.KEY_DOWNLOAD_DURATION, reportAction.aL);
            com.kwad.sdk.utils.q.a(jSONObject, "pageType", reportAction.aM);
            com.kwad.sdk.utils.q.a(jSONObject, "guideTimes", reportAction.aN);
            com.kwad.sdk.utils.q.a(jSONObject, "speedLimitStatus", reportAction.aO);
            com.kwad.sdk.utils.q.a(jSONObject, "speedLimitThreshold", reportAction.aP);
            com.kwad.sdk.utils.q.a(jSONObject, "currentRealDownloadSpeed", reportAction.aQ);
            com.kwad.sdk.utils.q.a(jSONObject, "sdkPlatform", reportAction.aS);
            com.kwad.sdk.utils.q.a(jSONObject, "isKsUnion", reportAction.aT);
            com.kwad.sdk.utils.q.a(jSONObject, "trackMethodName", reportAction.aU);
            com.kwad.sdk.utils.q.a(jSONObject, "viewModeType", reportAction.aV);
            com.kwad.sdk.utils.q.a(jSONObject, "playAgainControlledType", reportAction.aX);
            com.kwad.sdk.utils.q.a(jSONObject, "mediaShareStr", reportAction.aY);
            com.kwad.sdk.utils.q.a(jSONObject, "clickTime", reportAction.aZ);
            com.kwad.sdk.utils.q.a(jSONObject, "frameRenderTime", reportAction.ba);
            com.kwad.sdk.utils.q.a(jSONObject, "playerEnterAction", reportAction.bb);
            com.kwad.sdk.utils.q.a(jSONObject, "requestUrl", reportAction.bc);
            com.kwad.sdk.utils.q.a(jSONObject, "requestTotalTime", reportAction.bd);
            com.kwad.sdk.utils.q.a(jSONObject, "requestResponseTime", reportAction.be);
            com.kwad.sdk.utils.q.a(jSONObject, "requestParseDataTime", reportAction.bf);
            com.kwad.sdk.utils.q.a(jSONObject, "requestCallbackTime", reportAction.bg);
            com.kwad.sdk.utils.q.a(jSONObject, "requestFailReason", reportAction.bh);
            com.kwad.sdk.utils.q.a(jSONObject, "pageName", reportAction.bi);
            com.kwad.sdk.utils.q.a(jSONObject, "pageCreateTime", reportAction.bj);
            com.kwad.sdk.utils.q.a(jSONObject, "pageResumeTime", reportAction.bk);
            com.kwad.sdk.utils.q.a(jSONObject, "trackUrlList", reportAction.bl);
            com.kwad.sdk.utils.q.a(jSONObject, "pageLaunchTime", reportAction.bm);
            com.kwad.sdk.utils.q.a(jSONObject, "appAuthorityInfoList", reportAction.bp);
            com.kwad.sdk.utils.q.a(jSONObject, "entryRealRefresh", reportAction.bq);
            com.kwad.sdk.utils.q.a(jSONObject, "tkVersion", reportAction.br);
            com.kwad.sdk.utils.q.a(jSONObject, "jsVersion", reportAction.bs);
            com.kwad.sdk.utils.q.a(jSONObject, "jsFileName", reportAction.bt);
            com.kwad.sdk.utils.q.a(jSONObject, "jsErrorMsg", reportAction.bu);
            com.kwad.sdk.utils.q.a(jSONObject, "jsConfig", reportAction.bv);
            com.kwad.sdk.utils.q.a(jSONObject, "couponStatus", reportAction.bw);
            com.kwad.sdk.utils.q.a(jSONObject, "readPct", reportAction.bx);
            com.kwad.sdk.utils.q.a(jSONObject, "lostReason", reportAction.by);
            com.kwad.sdk.utils.q.a(jSONObject, "photoType", reportAction.bz);
            return jSONObject;
        }
        return (JSONObject) invokeLL.objValue;
    }
}
