package c.a.p0.v0;

import c.a.o0.w.p.c;
import com.baidu.tieba.R;
import com.baidu.titan.sdk.runtime.ClassClinitInterceptable;
import com.baidu.titan.sdk.runtime.ClassClinitInterceptorStorage;
import com.baidu.titan.sdk.runtime.FieldHolder;
import com.baidu.titan.sdk.runtime.InitContext;
import com.baidu.titan.sdk.runtime.InterceptResult;
import com.baidu.titan.sdk.runtime.Interceptable;
import com.baidu.titan.sdk.runtime.TitanRuntime;
import java.util.HashMap;
/* loaded from: classes2.dex */
public class b extends c {
    public static /* synthetic */ Interceptable $ic;
    public transient /* synthetic */ FieldHolder $fh;

    static {
        InterceptResult invokeClinit;
        ClassClinitInterceptable classClinitInterceptable = ClassClinitInterceptorStorage.$ic;
        if (classClinitInterceptable != null && (invokeClinit = classClinitInterceptable.invokeClinit(-1687037915, "Lc/a/p0/v0/b;")) != null) {
            Interceptable interceptable = invokeClinit.interceptor;
            if (interceptable != null) {
                $ic = interceptable;
            }
            if ((invokeClinit.flags & 1) != 0) {
                classClinitInterceptable.invokePostClinit(-1687037915, "Lc/a/p0/v0/b;");
                return;
            }
        }
        c.a.put("video_icon", Integer.valueOf((int) R.drawable.ico_link_video));
        HashMap<String, Integer> hashMap = c.a;
        Integer valueOf = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b2d);
        hashMap.put("image_emoticon34", valueOf);
        HashMap<String, Integer> hashMap2 = c.a;
        Integer valueOf2 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b2e);
        hashMap2.put("image_emoticon35", valueOf2);
        HashMap<String, Integer> hashMap3 = c.a;
        Integer valueOf3 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b2f);
        hashMap3.put("image_emoticon36", valueOf3);
        HashMap<String, Integer> hashMap4 = c.a;
        Integer valueOf4 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b30);
        hashMap4.put("image_emoticon37", valueOf4);
        HashMap<String, Integer> hashMap5 = c.a;
        Integer valueOf5 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b31);
        hashMap5.put("image_emoticon38", valueOf5);
        HashMap<String, Integer> hashMap6 = c.a;
        Integer valueOf6 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b34);
        hashMap6.put("image_emoticon40", valueOf6);
        HashMap<String, Integer> hashMap7 = c.a;
        Integer valueOf7 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b32);
        hashMap7.put("image_emoticon39", valueOf7);
        HashMap<String, Integer> hashMap8 = c.a;
        Integer valueOf8 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b35);
        hashMap8.put("image_emoticon41", valueOf8);
        HashMap<String, Integer> hashMap9 = c.a;
        Integer valueOf9 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b36);
        hashMap9.put("image_emoticon42", valueOf9);
        HashMap<String, Integer> hashMap10 = c.a;
        Integer valueOf10 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b37);
        hashMap10.put("image_emoticon43", valueOf10);
        HashMap<String, Integer> hashMap11 = c.a;
        Integer valueOf11 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b38);
        hashMap11.put("image_emoticon44", valueOf11);
        HashMap<String, Integer> hashMap12 = c.a;
        Integer valueOf12 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b39);
        hashMap12.put("image_emoticon45", valueOf12);
        HashMap<String, Integer> hashMap13 = c.a;
        Integer valueOf13 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b3a);
        hashMap13.put("image_emoticon46", valueOf13);
        HashMap<String, Integer> hashMap14 = c.a;
        Integer valueOf14 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b3b);
        hashMap14.put("image_emoticon47", valueOf14);
        HashMap<String, Integer> hashMap15 = c.a;
        Integer valueOf15 = Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b3c);
        hashMap15.put("image_emoticon48", valueOf15);
        c.a.put("image_emoticon49", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b3d));
        c.a.put("image_emoticon50", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b3f));
        c.a.put("image_emoticon77", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b52));
        c.a.put("image_emoticon78", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b53));
        c.a.put("image_emoticon79", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b54));
        c.a.put("image_emoticon80", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b56));
        c.a.put("image_emoticon81", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b57));
        c.a.put("image_emoticon82", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b58));
        c.a.put("image_emoticon83", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b59));
        c.a.put("image_emoticon84", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b5a));
        c.a.put("image_emoticon101", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080af4));
        c.a.put("image_emoticon102", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080af5));
        c.a.put("image_emoticon103", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080af6));
        c.a.put("image_emoticon104", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080af7));
        c.a.put("image_emoticon105", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080af8));
        c.a.put("image_emoticon106", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080af9));
        c.a.put("image_emoticon107", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080afa));
        c.a.put("image_emoticon108", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080afb));
        c.a.put("image_emoticon109", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080afc));
        c.a.put("image_emoticon110", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080afe));
        c.a.put("image_emoticon111", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080aff));
        c.a.put("image_emoticon112", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b00));
        c.a.put("image_emoticon113", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b01));
        c.a.put("image_emoticon114", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b02));
        c.a.put("image_emoticon115", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b03));
        c.a.put("image_emoticon116", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b04));
        c.a.put("image_emoticon117", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b05));
        c.a.put("image_emoticon118", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b06));
        c.a.put("image_emoticon119", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b07));
        c.a.put("image_emoticon120", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b09));
        c.a.put("image_emoticon121", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b0a));
        c.a.put("image_emoticon122", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b0b));
        c.a.put("image_emoticon123", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b0c));
        c.a.put("image_emoticon124", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b0d));
        c.f11515b.add(valueOf);
        c.f11515b.add(valueOf2);
        c.f11515b.add(valueOf3);
        c.f11515b.add(valueOf4);
        c.f11515b.add(valueOf5);
        c.f11515b.add(valueOf6);
        c.f11515b.add(valueOf7);
        c.f11515b.add(valueOf8);
        c.f11515b.add(valueOf10);
        c.f11515b.add(valueOf11);
        c.f11515b.add(valueOf15);
        c.f11515b.add(valueOf14);
        c.f11515b.add(valueOf13);
        c.f11515b.add(Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b3f));
        c.f11515b.add(Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b52));
        c.f11515b.add(Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b53));
        c.f11515b.add(Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b54));
        c.f11515b.add(Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b56));
        c.f11515b.add(Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b57));
        c.f11515b.add(Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b58));
        c.f11515b.add(Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b59));
        c.f11515b.add(Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b5a));
        c.f11515b.add(valueOf12);
        c.f11515b.add(valueOf9);
        c.f11515b.add(Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080af4));
        c.f11515b.add(Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080af5));
        c.f11515b.add(Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080af6));
        c.f11515b.add(Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080af7));
        c.f11515b.add(Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080af8));
        c.f11515b.add(Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080af9));
        c.f11515b.add(Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080afa));
        c.f11515b.add(Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080afb));
        c.f11515b.add(Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080afc));
        c.f11515b.add(Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080afe));
        c.f11515b.add(Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080aff));
        c.f11515b.add(Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b00));
        c.f11515b.add(Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b01));
        c.f11515b.add(Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b02));
        c.f11515b.add(Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b03));
        c.f11515b.add(Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b04));
        c.f11515b.add(Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b05));
        c.f11515b.add(Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b06));
        c.f11515b.add(Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b07));
        c.f11515b.add(Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b09));
        c.f11515b.add(Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b0a));
        c.f11515b.add(Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b0b));
        c.f11515b.add(Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b0c));
        c.f11515b.add(Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b0d));
        c.f11516c.put("#(爱心)", valueOf);
        c.f11516c.put("#(心碎)", valueOf2);
        c.f11516c.put("#(玫瑰)", valueOf3);
        c.f11516c.put("#(礼物)", valueOf4);
        c.f11516c.put("#(彩虹)", valueOf5);
        c.f11516c.put("#(星星月亮)", valueOf7);
        c.f11516c.put("#(太阳)", valueOf6);
        c.f11516c.put("#(钱币)", valueOf8);
        c.f11516c.put("#(灯泡)", valueOf9);
        c.f11516c.put("#(茶杯)", valueOf10);
        c.f11516c.put("#(蛋糕)", valueOf11);
        c.f11516c.put("#(音乐)", valueOf12);
        c.f11516c.put("#(haha)", valueOf13);
        c.f11516c.put("#(胜利)", valueOf14);
        c.f11516c.put("#(大拇指)", valueOf15);
        c.f11516c.put("#(弱)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b3d));
        c.f11516c.put("#(OK)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b3f));
        c.f11516c.put("#(沙发)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b52));
        c.f11516c.put("#(手纸)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b53));
        c.f11516c.put("#(香蕉)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b54));
        c.f11516c.put("#(便便)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b56));
        c.f11516c.put("#(药丸)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b57));
        c.f11516c.put("#(红领巾)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b58));
        c.f11516c.put("#(蜡烛)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b59));
        c.f11516c.put("#(三道杠)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b5a));
        c.f11516c.put("#(不跟丑人说话)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080af4));
        c.f11516c.put("#(么么哒)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080af5));
        c.f11516c.put("#(亲亲才能起来)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080af6));
        c.f11516c.put("#(伦家只是宝宝)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080af7));
        c.f11516c.put("#(你是我的人)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080af8));
        c.f11516c.put("#(假装看不见)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080af9));
        c.f11516c.put("#(单身等撩)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080afa));
        c.f11516c.put("#(吓到宝宝了)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080afb));
        c.f11516c.put("#(哈哈哈)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080afc));
        c.f11516c.put("#(嗯嗯)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080afe));
        c.f11516c.put("#(好幸福)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080aff));
        c.f11516c.put("#(宝宝不开心)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b00));
        c.f11516c.put("#(小姐姐别走)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b01));
        c.f11516c.put("#(小姐姐在吗)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b02));
        c.f11516c.put("#(小姐姐来啦)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b03));
        c.f11516c.put("#(小姐姐来玩呀)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b04));
        c.f11516c.put("#(我养你)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b05));
        c.f11516c.put("#(我是不会骗你的)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b06));
        c.f11516c.put("#(扎心了)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b07));
        c.f11516c.put("#(无聊)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b09));
        c.f11516c.put("#(月亮代表我的心)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b0a));
        c.f11516c.put("#(来追我呀)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b0b));
        c.f11516c.put("#(爱你的形状)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b0c));
        c.f11516c.put("#(白眼)", Integer.valueOf((int) R.drawable.obfuscated_res_0x7f080b0d));
    }

    public b() {
        Interceptable interceptable = $ic;
        if (interceptable != null) {
            InitContext newInitContext = TitanRuntime.newInitContext();
            interceptable.invokeUnInit(65537, newInitContext);
            int i = newInitContext.flag;
            if ((i & 1) != 0) {
                int i2 = i & 2;
                newInitContext.thisArg = this;
                interceptable.invokeInitBody(65537, newInitContext);
            }
        }
    }
}
