package com.baidu.tieba.person.holder;

import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.baidu.adp.widget.ListView.y;
import com.baidu.tbadk.core.view.HeadImageView;
import com.baidu.tieba.u;
/* loaded from: classes.dex */
public class j extends y.a {
    public int afy;
    public View euN;
    public LinearLayout euP;
    public View euV;
    public RelativeLayout euW;
    public TextView euX;
    public ImageView euY;
    public TextView euZ;
    public View eva;
    public RelativeLayout evb;
    public RelativeLayout evc;
    public HeadImageView evd;
    public HeadImageView eve;
    public TextView evf;
    public TextView evg;
    public TextView evh;
    public TextView evi;
    public RelativeLayout evj;
    public RelativeLayout evk;
    public HeadImageView evl;
    public HeadImageView evm;
    public TextView evn;
    public TextView evo;
    public TextView evp;
    public TextView evq;
    public RelativeLayout evr;
    public TextView evs;
    public TextView evt;
    public ImageView evu;
    public TextView evv;
    public View evw;
    public View evx;
    public ImageView evy;
    public TextView evz;

    public j(View view) {
        super(view);
        this.euV = null;
        this.euW = null;
        this.euX = null;
        this.euY = null;
        this.euZ = null;
        this.eva = null;
        this.evb = null;
        this.evc = null;
        this.evd = null;
        this.eve = null;
        this.evf = null;
        this.evg = null;
        this.evh = null;
        this.evi = null;
        this.euN = null;
        this.evj = null;
        this.evk = null;
        this.evl = null;
        this.evm = null;
        this.evn = null;
        this.evo = null;
        this.evp = null;
        this.evq = null;
        this.evr = null;
        this.evs = null;
        this.evt = null;
        this.evu = null;
        this.euP = null;
        this.evv = null;
        this.afy = 3;
        this.evv = (TextView) view.findViewById(u.g.gift_give_btn);
        this.euV = view.findViewById(u.g.top_divider);
        this.eva = view.findViewById(u.g.head_divider);
        this.euW = (RelativeLayout) view.findViewById(u.g.group_head);
        this.euX = (TextView) this.euW.findViewById(u.g.group_head_title);
        this.euY = (ImageView) this.euW.findViewById(u.g.group_head_arrow);
        this.euZ = (TextView) this.euW.findViewById(u.g.group_head_msg);
        this.evb = (RelativeLayout) view.findViewById(u.g.first_group_line_item1);
        this.evc = (RelativeLayout) view.findViewById(u.g.first_group_line_item2);
        this.evd = (HeadImageView) this.evb.findViewById(u.g.first_group_head_item1);
        this.evf = (TextView) this.evb.findViewById(u.g.first_group_name_item1);
        this.evh = (TextView) this.evb.findViewById(u.g.first_group_msg_item1);
        this.eve = (HeadImageView) this.evc.findViewById(u.g.first_group_head_item2);
        this.evg = (TextView) this.evc.findViewById(u.g.first_group_name_item2);
        this.evi = (TextView) this.evc.findViewById(u.g.first_group_msg_item2);
        this.euN = view.findViewById(u.g.mid_divider);
        this.evj = (RelativeLayout) view.findViewById(u.g.second_group_line_item1);
        this.evk = (RelativeLayout) view.findViewById(u.g.second_group_line_item2);
        this.evl = (HeadImageView) this.evj.findViewById(u.g.second_group_head_item1);
        this.evm = (HeadImageView) this.evk.findViewById(u.g.second_group_head_item2);
        this.evn = (TextView) this.evj.findViewById(u.g.second_group_name_item1);
        this.evo = (TextView) this.evk.findViewById(u.g.second_group_name_item2);
        this.evp = (TextView) this.evj.findViewById(u.g.second_group_msg_item1);
        this.evq = (TextView) this.evk.findViewById(u.g.second_group_msg_item2);
        this.evr = (RelativeLayout) view.findViewById(u.g.group_none);
        this.evs = (TextView) this.evr.findViewById(u.g.group_none_title);
        this.evt = (TextView) this.evr.findViewById(u.g.group_none_msg);
        this.evu = (ImageView) this.evr.findViewById(u.g.group_none_lock);
        this.euP = (LinearLayout) view.findViewById(u.g.container);
        this.evw = view.findViewById(u.g.gift_give_god_layout_divider);
        this.evx = view.findViewById(u.g.gift_give_god_layout);
        this.evy = (ImageView) view.findViewById(u.g.gift_give_god_icon);
        this.evz = (TextView) view.findViewById(u.g.gift_give_god_text);
    }
}
